Feature/e structure
elementor/elementor pull request #10066
Opened 2020-01-05 13:00 UTC by iNewLegend

2020-01-05 14:14 UTC, matipojo requested changes

2020-01-05 14:14 UTC, matipojo commented on assets/dev/js/editor/document/hooks/data/create/section-columns-limit.js
> +import DataDependency from 'elementor-api/modules/hooks/data-base/dependency';
```suggestion
import DataDependency from 'elementor-api/modules/hooks/data/dependency-base';
```

2020-01-05 14:14 UTC, matipojo commented on assets/dev/js/editor/document/hooks/data/index.js
> -export * from './paste-style/';
Where is it?

2020-01-05 14:14 UTC, matipojo commented on assets/dev/js/editor/document/hooks/ui/create/column-is-populated.js
> +import UIAfter from 'elementor-api/modules/hooks/ui-base/after';
```suggestion
import UIAfter from 'elementor-api/modules/hooks/ui/after-base';
```

2020-01-05 14:14 UTC, matipojo commented on assets/dev/js/editor/elements/views/section.js
> +	toggleSectionIsFull: function() {
BC

2020-01-05 14:14 UTC, matipojo commented on core/common/assets/js/api/api/commands.js
> +	 * @notice List of command available [here](method---ecommands-get-all.md)
Currently remove any reference to md docs.

2020-01-05 14:14 UTC, matipojo commented on core/common/assets/js/api/api/hooks.js
> +import DataHooks from './hooks/data.js';
Rename

2020-01-05 14:14 UTC, matipojo commented on core/common/assets/js/api/api/hooks/base.js
>  			elType = containers[ 0 ] ? containers[ 0 ].type : false;
elType => containerType

2020-01-05 14:14 UTC, matipojo commented on core/common/assets/js/api/api/hooks/base.js
> +			throw new Error( `invalid instance, please use: 'elementor-api/modules/callable-base'. ` );
`callable`?

2020-01-06 08:41 UTC, iNewLegend commented on assets/dev/js/editor/document/hooks/data/index.js
> -export * from './paste-style/';
Not needed.

2020-01-06 09:12 UTC, matipojo requested changes

2020-01-06 09:12 UTC, matipojo commented on core/common/assets/js/api/api/commands.js
> +	/**
Rename api/api

2020-01-06 09:12 UTC, matipojo commented on core/common/assets/js/modules.js
> +import ComponentModal from './api/modules/component-modal';
```suggestion
import ComponentModal from './api/modules/component-modal-base';
```

2020-01-06 09:12 UTC, matipojo commented on core/common/assets/js/modules.js
> +	Component: Component, // TODO: remove use `$e.modules.ComponentBase`.
Add deprecated notice. for example:
https://github.com/elementor/elementor/blob/5ee95138703488fd7c82a4a0939c801d1718cbc1/assets/dev/js/editor/editor-base.js#L1079
But use `get()` instehad of `defineProperty`.

2020-01-06 09:12 UTC, matipojo commented on tests/qunit/core/editor/document/ui/commands/copy.spec.js
> +import CommonHelper from '../../../../common/helper';
Use an alias

2020-01-06 09:12 UTC, matipojo commented on tests/qunit/core/editor/document/ui/commands/delete.spec.js
> +import CommonHelper from '../../../../common/helper';
Use an alias, here and every `../../`

2020-01-07 13:52 UTC, matipojo submitted a review, later dismissed

2020-01-12 11:41 UTC, merged