Refactor and move System Info to elementor\modules
elementor/elementor pull request #10102
Opened 2020-01-09 09:31 UTC by udidol

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [X] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Description
An explanation of what is done in this PR

* Moved Elementor's `System Info` report module into `elementor\modules` and refactored it as a module

## Quality assurance

- [X] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

2020-01-09 09:47 UTC, kobizz requested changes

2020-01-09 09:47 UTC, kobizz commented on modules/system-info/module.php
> + * managing Elementor system info modules.
```suggestion
 * managing Elementor system info reports.
```

2020-01-09 09:47 UTC, kobizz commented on modules/system-info/module.php
> +		$settings['namespaces'] = [
Are we still need these settings?

2020-01-09 09:47 UTC, kobizz commented on modules/system-info/module.php
> +	/*final public function get_settings( $setting = null, array $container = null ) {
Remove this method

2020-01-09 10:05 UTC, udidol commented on modules/system-info/module.php
> +		$settings['namespaces'] = [
No, will delete

2020-01-12 13:32 UTC, kobizz approved these changes

2020-01-12 16:20 UTC, merged