Feature/settings usage
elementor/elementor pull request #10250
Opened 2020-01-22 09:30 UTC by iNewLegend

2020-01-22 11:21 UTC, matipojo requested changes

2020-01-22 11:21 UTC, matipojo commented on modules/usage/module.php
> +			$label = strtolower( $tab['label'] );
Don't use label, find a key or something else.

2020-01-22 11:21 UTC, matipojo commented on modules/usage/module.php
> +					if ( ! strstr( $field_name, 'elementor_' ) ) {
Always add `elementor_`

2020-01-22 13:17 UTC, matipojo approved these changes

2020-01-23 09:48 UTC, matipojo requested changes

2020-01-23 09:48 UTC, matipojo commented on modules/usage/module.php
> +		$params['usages']['settings'] = $this->get_settings_usage();
```suggestion
		$params['usages']['elementor_settings'] = $this->get_settings_usage();
```

2020-01-23 10:05 UTC, matipojo submitted a review, later dismissed

2020-01-23 17:03 UTC, KingYes requested changes
Use with whitelist && Defaults only.

2020-02-05 13:44 UTC, closed without merging