JS API: Change - History module to 'document/history'.
elementor/elementor pull request #10306
Opened 2020-01-27 14:44 UTC by iNewLegend

2020-02-16 10:00 UTC, matipojo requested changes

2020-02-16 10:00 UTC, matipojo commented on assets/dev/js/editor/document.js
> -class Editor {
Move to a separated PR

2020-04-06 08:33 UTC, iNewLegend commented
@matipojo what the status of this PR?

2020-12-13 13:04 UTC, matipojo commented
It will be merged in the future.

2020-12-13 13:04 UTC, closed without merging