Editor/Behaviors: Fix - Inline-Editing on leave does not rendered fro…
elementor/elementor pull request #10594
Opened 2020-02-18 09:50 UTC by iNewLegend

2020-02-20 17:41 UTC, matipojo approved these changes

2020-02-23 10:12 UTC, kobizz requested changes

2020-02-23 10:12 UTC, kobizz commented on assets/dev/js/editor/elements/views/behaviors/inline-editing.js
> +		this.view.getEditModel().renderRemoteServer();
We need to discuss it

2020-02-23 13:44 UTC, matipojo approved these changes

2020-02-23 13:44 UTC, merged