Added new parameter to Swiper wrapper to limit breakpoint intervention
elementor/elementor pull request #10642
Opened 2020-02-24 10:43 UTC by udidol

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

* Added new parameter `handleElementorBreakpoints` to Elementor's Swiper wrapper to limit its breakpoint intervention

## Quality assurance

- [X] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

2020-02-24 14:01 UTC, shilo-ey commented
fixes #10525

2020-02-26 15:57 UTC, mackyangeles commented
How’s the bug? Is it near fixing?

2020-02-27 12:22 UTC, udidol commented
The issue will be addressed in an upcoming release

2020-02-28 08:47 UTC, mackyangeles commented
> The issue will be addressed in an upcoming release

Still not fix on version 2.9.3 (just did the update) :(

2020-02-28 10:15 UTC, udidol commented
> > The issue will be addressed in an upcoming release
> 
> Still not fix on version 2.9.3 (just did the update) :(

Upcoming, but not this one. We will update the ticket once the change is implemented.

2020-03-04 14:15 UTC, vollyimnetz commented
Hi @KingYes, hi @kobizz,
it would be really great to get this change into elementor **fast**. 
Every plugin- or theme-developer who used the swiper library for a custom functionality, tearing there hair because elementor destroyed the breakpoint settings.

Please merge the request to keep the code clean from custom overrides.

The problems are also described here: https://github.com/elementor/elementor/issues/10525

2020-03-05 16:29 UTC, kobizz requested changes

2020-03-05 16:29 UTC, kobizz commented on assets/lib/swiper/swiper.js
> + * Swiper 5.3.6
Update version inside related files

2020-03-05 16:53 UTC, udidol commented on assets/lib/swiper/swiper.js
> + * Swiper 5.3.6
Version numbers are already updated...

2020-03-08 08:41 UTC, kobizz approved these changes

2020-03-08 15:44 UTC, mackyangeles commented
Any update on this? With 2.9.4 not yet fix... we need a fix ASAP

2020-03-08 15:48 UTC, KingYes approved these changes

2020-03-08 15:48 UTC, merged

2020-03-09 07:28 UTC, shilo-ey commented
We released Pro v2.8.5 to support this fix and will soon release a patch to this issue.