Elements/View: Fix - Don't allow drag and drop for documents which ar…
elementor/elementor pull request #10714
Opened 2020-03-01 15:05 UTC by iNewLegend

2020-03-03 08:44 UTC, matipojo submitted a review, later dismissed

2020-03-04 15:48 UTC, kobizz approved these changes
It needs further discussion

2020-03-04 15:48 UTC, kobizz requested changes

2020-03-04 15:48 UTC, kobizz commented on assets/dev/js/editor/elements/views/column.js
> +				// Dont allow dragging items to document which is not edit able.
Move it to `onDroppingAllowed` method

2020-03-04 16:03 UTC, matipojo approved these changes

2020-03-04 16:14 UTC, kobizz approved these changes

2020-03-04 16:15 UTC, merged