Disable dynamic capabilities from all COLOR controls in Theme Style
elementor/elementor pull request #10735
Opened 2020-03-04 09:59 UTC by udidol

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [X] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

* Disabled Dynamic Capabilities for all Color controls in Theme Style - Theme Style does not support dynamic values at this time.

## Quality assurance

- [X] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

2020-03-05 08:13 UTC, kobizz requested changes

2020-03-05 08:13 UTC, kobizz commented on core/kits/documents/kit.php
> +				'dynamic' => false,
Change all occurrences to `'dynamic' => [],`

2020-03-05 08:54 UTC, kobizz approved these changes

2020-03-08 09:00 UTC, matipojo approved these changes

2020-03-08 12:44 UTC, merged