Feature/editor theme
elementor/elementor pull request #10857
Opened 2020-03-16 09:30 UTC by joshmarom

A css variable based color theme system for the editor

2020-03-16 11:05 UTC, matipojo requested changes

2020-03-16 11:05 UTC, matipojo commented on core/editor/editor.php
>  		if ( Responsive::has_custom_breakpoints() ) {
Remove the `elementor.zip` file. (push force)

2020-03-16 11:05 UTC, matipojo commented on core/editor/editor.php
> +		$ui_theme = SettingsManager::get_settings_managers( 'editorPreferences' )->get_model()->get_settings( 'ui_theme' );
Too complicated.

2020-04-06 16:09 UTC, joshmarom commented on core/editor/editor.php
> +		$ui_theme = SettingsManager::get_settings_managers( 'editorPreferences' )->get_model()->get_settings( 'ui_theme' );
Would that make it better?
```php
$editor_preferences_model = SettingsManager::get_settings_managers( 'editorPreferences' )->get_model();
		$ui_theme = $editor_preferences_model->get_settings( 'ui_theme' );
```

2020-04-06 16:14 UTC, joshmarom commented on assets/dev/scss/editor/navigator/navigator.scss
> -		background-color: $editor-background;
It was not required

2020-04-06 16:16 UTC, joshmarom commented on assets/dev/scss/editor/_global.scss
> +			//background-color: lighten($editor-accent, 10%);
It's WIP.
We have a technical problem using SCSS color manipulation functions because of the css variables

2022-03-14 17:30 UTC, closed without merging