JS API/Core/Hooks: Fix - Support Async hooks.
elementor/elementor pull request #10981
Opened 2020-03-26 16:03 UTC by iNewLegend

2020-03-26 16:12 UTC, matipojo submitted a review, later dismissed

2020-04-05 14:56 UTC, kobizz requested changes

2020-04-05 14:56 UTC, kobizz commented on core/common/assets/js/api/core/hooks/data.js
Remove the default and return false at the end of this method

2020-04-06 18:01 UTC, matipojo submitted a review, later dismissed

2020-04-07 10:11 UTC, kobizz submitted a review, later dismissed

2020-04-30 09:49 UTC, KingYes approved these changes

2020-04-30 09:49 UTC, merged