Added a 'columns' option to the Social Icons widget
elementor/elementor pull request #11003
Opened 2020-03-29 15:42 UTC by udidol

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

* Added a 'columns' option to the Social Icons widget

## Quality assurance

- [X] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

2020-03-30 11:39 UTC, kobizz requested changes

2020-03-30 11:39 UTC, kobizz commented on includes/widgets/social-icons.php
> +					'{{WRAPPER}}:not(.elementor-grid-0) .elementor-grid' => 'grid-column-gap: {{SIZE}}{{UNIT}}',
Extract this grid system to use variables

2020-04-19 08:01 UTC, kobizz requested changes

2020-04-19 08:01 UTC, kobizz commented on includes/widgets/social-icons.php
> +					'{{WRAPPER}}:not(.elementor-grid-0) .elementor-grid' => 'display: inline-grid; grid-template-columns: repeat({{VALUE}}, auto);',
Print only the variable here

2020-04-23 06:51 UTC, kobizz requested changes

2020-04-23 06:51 UTC, kobizz commented on includes/utils.php
> +	public static function is_control_responsive_generated( $control ) {
Until we find a better place, do this check inline and don't create a new method

2020-04-23 13:57 UTC, kobizz approved these changes

2020-04-27 10:32 UTC, matipojo approved these changes

2020-04-30 09:47 UTC, KingYes approved these changes

2020-04-30 09:47 UTC, merged