Added 'Learn More' link to URL Custom Attributes Description
elementor/elementor pull request #11143
Opened 2020-04-16 08:02 UTC by udidol

2020-04-16 09:31 UTC, kobizz requested changes

2020-04-16 09:31 UTC, kobizz commented on includes/controls/url.php
> +		$learn_more_link = ! Utils::has_pro() ? ' <a href="https://go.elementor.com/panel-link-custom-attributes/" target="_blank">' . __( 'Learn More', 'elementor' ) . '</a>' : '';
I think that Learn More should also appear if the user has pro

2020-04-19 07:50 UTC, kobizz submitted a review, later dismissed

2020-04-28 15:52 UTC, KingYes requested changes

2020-04-28 15:52 UTC, KingYes commented on includes/controls/url.php
> +			from values using the | (pipe) character. Separate key-value pairs with a comma.', 'elementor' )
@udidol Do not use new line in gettext string.

2020-05-03 13:49 UTC, KingYes approved these changes

2020-05-03 13:49 UTC, merged