Media upload files ui.
elementor/elementor pull request #11263
Opened 2020-04-30 15:23 UTC by rotemee

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2020-04-30 15:45 UTC, kobizz requested changes

2020-04-30 15:45 UTC, kobizz commented on assets/dev/js/editor/controls/media.js
> +			fileName: '',
We can't insert the filename inside the widget value. You can extract it from the file URL

2020-04-30 15:45 UTC, kobizz commented on assets/dev/scss/editor/panel/controls/_media.scss
> +	&-upload-label {
remove it

2020-04-30 15:45 UTC, kobizz commented on assets/dev/scss/editor/panel/controls/_media.scss
> +	&__file .elementor-control-upload-content {
Nest all nested selectors

2020-04-30 15:45 UTC, kobizz commented on assets/dev/scss/editor/panel/controls/_media.scss
> +		color: #A4AFB7;
Use our system colors

2020-04-30 15:45 UTC, kobizz commented on assets/dev/scss/editor/panel/controls/_media.scss
> +		font-family: Roboto;
This value should be inherited from the panel

2020-04-30 15:45 UTC, kobizz commented on assets/dev/scss/editor/panel/controls/_media.scss
> +		font-weight: normal;
Same as above

2020-04-30 15:45 UTC, kobizz commented on assets/dev/scss/editor/panel/controls/_media.scss
> +	&:not(.elementor-media-empty) &__file &__upload-label {
We need to discuss together the rest of this file

2020-05-03 10:51 UTC, kobizz requested changes

2020-05-03 10:51 UTC, kobizz commented on assets/dev/js/editor/controls/media.js
> +				id: attachment.id
Bring back the comma. We always put a comma even in the last object property

2020-05-03 12:37 UTC, kobizz requested changes

2020-05-03 12:37 UTC, kobizz commented on assets/dev/scss/editor/panel/controls/_media.scss
> +	&__file .elementor-control-file-area {
Remvoe it

2020-05-03 12:37 UTC, kobizz commented on assets/dev/scss/editor/panel/controls/_media.scss
> +	&__file .elementor-control-upload-controls {
Remove it

2020-05-03 12:37 UTC, kobizz commented on assets/dev/scss/editor/panel/controls/_media.scss
> +	&__file &__remove {
Check for duplications

2020-05-03 12:37 UTC, kobizz commented on assets/dev/scss/editor/panel/controls/_media.scss
> +	&__file &__remove {
Separate remove buttons style

2020-05-03 12:37 UTC, kobizz commented on assets/dev/scss/editor/panel/controls/_media.scss
> +		height: 27px;
Use `$control-unit` variable

2020-05-03 12:37 UTC, kobizz commented on assets/dev/scss/editor/panel/controls/_media.scss
> +		font-style: normal;
Should be inherited

2020-05-03 12:37 UTC, kobizz commented on assets/dev/scss/editor/panel/controls/_media.scss
> +		background-color: initial;
Apply on media mode only

2020-05-03 12:37 UTC, kobizz commented on assets/dev/scss/editor/panel/controls/_media.scss
> +		background-image: none;
Apply on media mode only

2020-05-04 12:37 UTC, kobizz requested changes

2020-05-04 12:37 UTC, kobizz commented on assets/dev/scss/editor/panel/controls/_media.scss
> +				&__name {
Instead of that, add these properties to their shared parent

2020-05-04 12:38 UTC, kobizz commented
Always use direction functions

2020-05-04 13:08 UTC, kobizz approved these changes

2020-05-04 17:37 UTC, KingYes approved these changes

2020-05-04 17:37 UTC, merged