WIP: JS API/Core: POC - Globals  $e.data.
elementor/elementor pull request #11281
Opened 2020-05-03 09:32 UTC by iNewLegend

2020-05-06 15:37 UTC, matipojo requested changes

2020-05-06 15:37 UTC, matipojo commented on data/editor/document/processors/add-default-globals.php
> +					// Add default globals only when __globals__ does not exist.
Explain that if the `__globals__`  is exist but empty, it's means that the globals is disabled even though the default is global. 

2020-05-14 15:06 UTC, iNewLegend commented on core/common/assets/js/api/core/data/cache.js
> +			} else if ( endpointKey.includes( endpoint + '/' ) ) {
Use '/*' to determine that next parts need to be deleted.

2020-05-14 15:08 UTC, iNewLegend commented on data/base/controller.php
> +	public function register_endpoint_format( $command, $format ) {
Add PHPDOC.

2020-06-14 15:06 UTC, closed without merging