Tweak/app ui changes
elementor/elementor pull request #11520
Opened 2020-06-02 06:26 UTC by rotemee

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2020-06-02 07:49 UTC, matipojo requested changes

2020-06-02 07:49 UTC, matipojo commented on assets/dev/scss/global/e-app.scss
> +	&__view {
Remove.

2020-06-02 07:49 UTC, matipojo commented on assets/dev/scss/global/e-app.scss
> +@import '../helpers/variables.scss';
Move to `core/app/assets/...` and split per each component.

2020-08-25 19:35 UTC, shilo-ey commented
@kobizz @matipojo 

Status of this PR? please move to develop/next major release branch

2020-08-26 07:21 UTC, closed without merging