Feature/kit migrations
elementor/elementor pull request #11540
Opened 2020-06-04 17:48 UTC by matipojo

2020-06-04 17:51 UTC, rodolphebertozzo approved these changes

2020-06-04 17:56 UTC, KingYes approved these changes

2020-06-08 12:25 UTC, kobizz requested changes

2020-06-08 13:23 UTC, matipojo commented on core/base/document.php
> +	public function add_repeater_row( $control_id, $item ) {
No. it's already exist in the globals-data PR.

2020-06-11 07:01 UTC, kobizz approved these changes

2020-06-15 13:23 UTC, merged