Make admin_menu permission filterable
elementor/elementor pull request #11568
Opened 2020-06-08 22:32 UTC by paulschreiber

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

* Adds a filter to which controls access to the Elementor menu

Fixes #11567

You'll probably want to rename the filter. I guessed at your house style.

2020-06-08 22:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/elementor/elementor?pullRequest=11568) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/elementor/elementor?pullRequest=11568) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/elementor/elementor?pullRequest=11568) it.</sub>

2021-08-17 08:28 UTC, ramiy requested changes

2021-08-17 08:28 UTC, ramiy commented on includes/settings/settings.php
> +		if ( ! current_user_can( apply_filters( 'elementor/admin/edit_settings', 'manage_options' ) ) ) {
```suggestion
		$edit_settings_capability = 'manage_options';

		/**
		 * Edit Elementor Settings Capability.
		 *
		 * Filters the user capability required to edit Elementor settings.
		 *
		 * @param $edit_settings_capability User capability required to edit Elementor
		 *                                  settings. Default is `manage_options`.
		 */
		$edit_settingss_capability = apply_filters( 'elementor/admin/edit_settings', $edit_settings_capability );

		if ( ! current_user_can( $edit_settings_capability ) ) {
```

2024-05-21 16:06 UTC, yotamselementor commented
Hi @paulschreiber ,
This PR was unintentionally closed - I removed the obsolete master branch which caused a chain effect of auto-closing all PRs directed at that branch.
I am looking for a way to reopen these PRs against main.

Thanks for your understanding!

2026-06-03 06:41 UTC, closed without merging