Feature/app design system and basic components
elementor/elementor pull request #11649
Opened 2020-06-16 17:45 UTC by joshmarom

2020-06-16 17:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/elementor/elementor?pullRequest=11649) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/elementor/elementor?pullRequest=11649) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: joshmarom<br/>:x: yonatanelm<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/elementor/elementor?pullRequest=11649) it.</sub>

2020-06-16 18:04 UTC, rodolphebertozzo commented
What is exactly?

2020-06-17 11:26 UTC, matipojo requested changes
Partial review (42/97)

2020-06-18 08:19 UTC, kobizz requested changes

2020-06-18 08:19 UTC, kobizz commented on core/app/assets/styles/mixins/_text-truncate.scss
> +// Utilities: Text truncate
What is it used for?

2020-06-18 08:19 UTC, kobizz commented on core/app/assets/styles/themes/dark/tokens/_dark-theme.scss
> +$eps-dark-theme-info: null;
Why do you use null variables?

2020-06-18 08:19 UTC, kobizz commented on core/app/assets/styles/tokens/_font.scss
> +//$eps-font-weight-light: 300;
Don't keep commented-out code. Decide whether to include them or not

2020-06-18 08:19 UTC, kobizz commented on core/app/assets/styles/tokens/_ratio.scss
> +						),
Mind the indentation

2020-06-18 08:19 UTC, kobizz commented on core/app/assets/styles/tokens/_utilities.scss
> +$user-selects: all, auto, none !default;
Why do you need to re-map all these properties?

2020-06-18 08:19 UTC, kobizz commented on core/app/assets/styles/tokens/maps/_colors-map.scss
> +);
I don't think we need this depth

2020-06-18 08:19 UTC, kobizz commented on core/app/assets/styles/utilities/_align.scss
> +.u-align-text-top    { vertical-align: text-top !important; }
These are old-fashioned rules. We are not supposed to use them

2020-06-18 08:19 UTC, kobizz commented on core/app/assets/styles/utilities/_background.scss
> +}
What is it used for?

2020-06-18 08:19 UTC, kobizz commented on core/app/assets/styles/utilities/_borders.scss
> +// stylelint-disable property-blacklist, declaration-no-important
I don't think we suppose to use all these rules. It's should be consumed as a variable wherever it's needed

2020-06-18 08:19 UTC, kobizz commented on core/app/assets/styles/utilities/_clearfix.scss
> +}
Used?

2020-06-18 08:19 UTC, kobizz commented on core/app/assets/styles/utilities/_display.scss
> +
Do we really need this method?

2020-06-18 08:19 UTC, kobizz commented on core/app/assets/styles/utilities/_embed.scss
> +// Credit: Nicolas Gallagher and SUIT CSS.
What is it used for?

2020-06-18 08:19 UTC, kobizz commented on core/app/assets/styles/utilities/_flex.scss
> +// Flex variation
I can't see the advantage of using these classes

2020-06-18 08:19 UTC, kobizz commented on core/app/assets/styles/utilities/_float.scss
> +// Utilities: float
We should discuss all of these utility classes

2020-06-18 14:02 UTC, matipojo commented on .grunt-config/loaders/app-imports.js
> +	const importsFile = dir + '/core/app/assets/styles/app-imports.scss',
We can change the convention - but for all modules.

2020-06-19 01:09 UTC, joshmarom commented on core/app/assets/js/app.scss
> +$app-sidebar-box-shadow: 0 2px 30px var(--box-shadow-color);
Box shadow tokens and functions are still WIP

2020-06-19 01:10 UTC, joshmarom commented on core/app/assets/js/app.scss
> +
This is temporary, just to get the view normalized, until further discussion.

2020-06-30 13:20 UTC, merged