Feature/global panel
elementor/elementor pull request #11665
Opened 2020-06-17 16:43 UTC by matipojo

2020-06-22 08:03 UTC, kobizz requested changes

2020-06-22 08:03 UTC, kobizz commented on core/kits/assets/js/commands/open-site-editor.js
> +	apply() {
?

2020-06-22 08:22 UTC, kobizz approved these changes

2020-06-23 10:31 UTC, KingYes approved these changes

2020-06-23 10:31 UTC, merged