Editor/Screenshots: New - capture screenshot on publish
elementor/elementor pull request #11751
Opened 2020-06-28 14:19 UTC by Nevoss

## PR Checklist

- [x] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Description
An explanation of what is done in this PR

* On publish it creates a screenshot of the current view of the post

## Test instructions
This PR can be tested by following these steps:

* Open a post with the editor
* Make some changes as you wish
* Publish the post
* Make sure that screenshot is created at the upload directory
* Make sure that the screenshot look the same as the preview of the post.

## Quality assurance

- [x] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2020-06-28 14:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/elementor/elementor?pullRequest=11751) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/elementor/elementor?pullRequest=11751) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: matipojo<br/>:x: Nevoss<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/elementor/elementor?pullRequest=11751) it.</sub>

2020-06-28 15:22 UTC, matipojo requested changes

2020-06-28 15:22 UTC, matipojo commented on modules/screenshots/assets/js/frontend/screenshot.js
> +			.then( this.handleIFrames.bind( this ) )
Try remove the promise if not needed.

2020-06-28 15:22 UTC, matipojo commented on modules/screenshots/assets/js/frontend/screenshot.js
> +	 * The html-to-image library can not snapshot the iframes.
```suggestion
	 * Html-to-image libraries can not snapshot the iframes.
```

2020-06-28 15:22 UTC, matipojo commented on modules/screenshots/assets/js/frontend/screenshot.js
> +		this.$elementor.find( 'iframe' ).each( function () {
Try use arrow function + remove the $self.

2020-06-28 15:22 UTC, matipojo commented on modules/screenshots/assets/js/frontend/screenshot.js
> +	 * css from another server cannot be loaded.
```suggestion
	 * CSS from another server cannot be loaded.
```

2020-06-28 15:22 UTC, matipojo commented on modules/screenshots/assets/js/frontend/screenshot.js
> +	 * that is why we fetch the content of the css and set it as an inline css.
```suggestion
	 * that is why it needed to be fetch the content of the css and set it as an inline css.
```

2020-06-28 15:22 UTC, matipojo commented on modules/screenshots/assets/js/frontend/screenshot.js
> +		const $self = this;
Try remove.

2020-06-28 15:22 UTC, matipojo commented on modules/screenshots/assets/js/frontend/screenshot.js
> +				domtoimage.toPng( this.$elementor.parents( 'body' ).get( 0 ), {} )
`document.body`.

2020-06-28 15:22 UTC, matipojo commented on modules/screenshots/module.php
> +		if ( ! isset( $_REQUEST['elementor-screenshot'] ) || ! User::is_current_user_can_edit() ) { // WPCS: CSRF ok.
```suggestion
		if ( ! isset( $_REQUEST['elementor-screenshot'] ) || ! User::is_current_user_can_edit() ) {
```

2020-06-30 10:25 UTC, matipojo requested changes

2020-06-30 10:25 UTC, matipojo commented on modules/screenshots/assets/js/editor/component.js
> +	isCapturingScreenshot() {
It's a public property, so it don't needs a getter.

2020-06-30 10:25 UTC, matipojo commented on modules/screenshots/assets/js/preview/screenshot.js
> +		const selector = this.config.allowedCssUrls.map( ( allowedCssUrl ) => {
What about adding a proxy URL to the original external link?

2020-06-30 10:25 UTC, matipojo commented on modules/screenshots/assets/js/preview/screenshot.js
> +				// This is a specific use case when we need
We :)

2020-06-30 10:25 UTC, matipojo commented on modules/screenshots/module.php
> +		if ( ! wp_verify_nonce( $_GET['nonce'], 'screenshot_proxy' ) ) {
Do we have a pattern for allowed URLs? (like `/(png|jpg|css)/`)

2020-06-30 10:25 UTC, matipojo commented on modules/screenshots/module.php
> +		$file_name = 'Elementor Post Screenshot ' . $post_id . '.png';
I think your preview fix was good:
```suggestion
		$file_name = 'Elementor-post-screenshot-' . $post_id . '.png';
```

2020-06-30 10:25 UTC, matipojo commented on modules/screenshots/module.php
> +		$upload = wp_upload_bits(
Try move all screenshots to a new folder `/wp-content/uploads/elementor/screenshots`. (create if not exist with `wp_mkdir_p`)

2020-06-30 10:25 UTC, matipojo commented on modules/screenshots/module.php
> +		if ( ! $this->is_in_screenshot_mode() || ! User::is_current_user_can_edit() ) {
```suggestion
		if ( ! $this->is_screenshot_mode() || ! User::is_current_user_can_edit() ) {
```

2020-06-30 13:37 UTC, matipojo requested changes

2020-06-30 13:37 UTC, matipojo commented on modules/screenshots/assets/js/preview/screenshot.js
> +			return;
Run `screenshotFailed` in order to clear the timer.

2020-06-30 13:37 UTC, matipojo commented on modules/screenshots/assets/js/editor/commands/internal/capture.js
> +			this.component.isCapturingScreenshot = false;
Remove the iframe element.

2020-07-12 15:52 UTC, matipojo requested changes

2020-07-12 15:52 UTC, matipojo commented on modules/screenshots/assets/js/preview/screenshot.js
> +			timerLabel: null,
Keep all config keys with `snake_case` format.

2020-07-12 15:52 UTC, matipojo commented on modules/screenshots/screenshot.php
> +
Remove all top empty lines.

2020-07-12 15:52 UTC, matipojo commented on modules/screenshots/screenshot.php
> +			$now = ( new \DateTime() )->format( 'Y-m-dTH:i:s' );
Use valid file name characters.
```suggestion
			$now = ( new \DateTime() )->format( 'Y-m-d-H-i-s' );
```

2020-07-12 15:52 UTC, matipojo commented on tests/phpunit/elementor/modules/screenshots/module/test-ajax-action.php
> +		$response = $this->module->ajax_save( [ 'screenshot' => 'adsasd' ] );
```suggestion
		$response = $this->module->ajax_save( [ 'screenshot' => 'invalid-id' ] );
```

2020-07-13 11:00 UTC, matipojo submitted a review, later dismissed

2020-07-14 11:00 UTC, matipojo submitted a review, later dismissed

2020-07-21 10:08 UTC, matipojo requested changes

2020-07-21 10:08 UTC, matipojo commented on tests/phpunit/elementor/modules/screenshots/module/test-ajax-action.php
> +
Remove all top empty lines.

2020-07-21 12:19 UTC, kobizz requested changes

2020-07-21 13:00 UTC, matipojo commented on modules/screenshots/assets/js/editor/commands/internal/capture.js
> +}
It's not needed here.

2020-07-21 13:04 UTC, matipojo commented on modules/screenshots/assets/js/preview/screenshot.js
> +class Screenshot {
It's not a part of the editor environment. it's more like a "frontend handle" bu the handlers system is not available on static render.

2020-07-21 14:51 UTC, Nevoss commented on modules/screenshots/assets/js/preview/screenshot.js
> +		const matches = regex.exec( $iframe.attr( 'src' ) );
Function removed from the code (not needed any more).

2020-07-21 14:51 UTC, Nevoss commented on modules/screenshots/assets/js/preview/screenshot.js
> +			$this.find( '> *' ).not( $this.find( '> :first-child' ) ).each( ( childIndex, childEl ) => {
Function removed from the code (not needed any more).

2020-07-21 14:51 UTC, Nevoss commented on modules/screenshots/assets/js/preview/screenshot.js
> +
Function removed from the code (not needed any more).

2020-07-21 16:42 UTC, matipojo requested changes

2020-07-21 16:42 UTC, matipojo commented on modules/screenshots/assets/js/preview/screenshot.js
> -	handleIFrames() {
We still need it for custom iframes.

2020-07-21 16:42 UTC, matipojo commented on modules/screenshots/assets/js/preview/screenshot.js
> +		const selector = this.config.include_images_urls
```suggestion
		const selector = this.config.external_images_urls
```

2020-07-23 13:35 UTC, kobizz commented on modules/screenshots/assets/js/editor/commands/internal/capture.js
> +}
Our standard is to use jQuery for dom manipulations and queries

2020-07-23 13:36 UTC, kobizz commented on modules/screenshots/assets/js/preview/screenshot.js
> +class Screenshot {
Our standard is to handle all our views modules the same way. There is a ViewModule base available on both ends and you should use it.

2020-07-26 15:22 UTC, kobizz requested changes

2020-07-26 15:22 UTC, kobizz commented on assets/lib/html2canvas/js/html2canvas.min.js
> +/*!
This library weights 120k in its minified version. I don't think it worths it.

2020-07-26 15:22 UTC, kobizz commented on modules/screenshots/assets/js/editor/commands/internal/capture.js
> +		jQuery( 'body' ).append( this.$iframe );
```suggestion
		elementorCommon.elements.$body.append( this.$iframe );
```

2020-07-26 15:22 UTC, kobizz commented on modules/screenshots/assets/js/editor/commands/internal/capture.js
> +		$iframe.attr( 'src', this.getIframeUrl() );
You can simplify it:

```suggestion
		const $iframe = jQuery( '<iframe>', { src: this.getIframeUrl() } );
```

2020-07-26 15:22 UTC, kobizz commented on modules/screenshots/assets/js/preview/screenshot.js
> +		jQuery( 'body' ).prepend(
```suggestion
		elementorCommon.elements.$body.prepend(
```

2020-07-26 15:22 UTC, kobizz commented on modules/screenshots/assets/js/preview/screenshot.js
> +		jQuery( 'body > *' ).not( this.elements.$elementor ).css( 'display', 'none' );
Consider caching `jQuery( 'body > *' ).not( this.elements.$elementor )` inside `getDefaultElements`

2020-07-26 15:22 UTC, kobizz commented on modules/screenshots/assets/js/preview/screenshot.js
> +			jQuery( 'head' ).append( $newLink );
cache `jQuery( 'head' )` inside `getDefaultElements`

2020-07-26 15:22 UTC, kobizz commented on modules/screenshots/assets/js/preview/screenshot.js
> +			.find( ' .elementor-section-wrap > .elementor-section' )
Consider caching it inside `getDefaultElements`

2020-07-26 15:22 UTC, kobizz commented on modules/screenshots/screenshot.php
> +	public function upload() {
Add a TODO to use the planned Uploads Manager here

2020-07-27 10:39 UTC, matipojo requested changes

2020-07-27 10:39 UTC, matipojo commented on modules/screenshots/module.php
> +		$css->enqueue();
Try remove.

2020-07-27 14:44 UTC, matipojo submitted a review, later dismissed

2020-07-28 11:56 UTC, kobizz approved these changes

2020-07-28 12:21 UTC, matipojo approved these changes

2020-07-28 12:25 UTC, KingYes approved these changes

2020-07-28 12:25 UTC, merged