Feature/devtools/tests/in editor compatibility
elementor/elementor pull request #11778
Opened 2020-07-02 13:37 UTC by iNewLegend

Depended on https://github.com/elementor/elementor/pull/11762

2020-07-05 13:15 UTC, matipojo requested changes

2020-07-05 13:15 UTC, matipojo commented on tests/qunit/core/common/assets/js/api/core/components.spec.js
> +			$e.routes.clearCurrent( namespace );
`hooks.afterEach`?

2020-07-05 13:15 UTC, matipojo commented on tests/qunit/tests.js
> -function initialize() {
Please commit a `rename` action (`tests => main`) before changing the content.

2020-07-13 13:21 UTC, matipojo approved these changes

2020-07-13 15:48 UTC, kobizz approved these changes

2020-07-16 13:18 UTC, KingYes approved these changes

2020-07-16 13:18 UTC, merged