Helpers: Move `getUniqueID` to `elementorCommon.helpers.getUniqueId`.
elementor/elementor pull request #11870
Opened 2020-07-14 13:49 UTC by matipojo

2020-07-15 06:27 UTC, kobizz requested changes

2020-07-15 06:27 UTC, kobizz commented on assets/dev/js/editor/utils/helpers.js
> +		elementorCommon.helpers.softDeprecated( 'elementor.helpers.getUniqueID()', '3.0.0', 'elementorCommon.helpers.getUniqueId()' );
Did you update the deprecation sheet?

2020-07-15 06:51 UTC, kobizz approved these changes

2020-07-16 13:11 UTC, KingYes approved these changes

2020-07-16 13:11 UTC, merged