Data/Manager: New - Simple cache, data API can called  multiple times.
elementor/elementor pull request #11876
Opened 2020-07-15 11:09 UTC by iNewLegend

2020-07-15 11:16 UTC, matipojo submitted a review, later dismissed

2020-07-16 07:59 UTC, kobizz requested changes

2020-07-16 07:59 UTC, kobizz commented on data/manager.php
> +		return $result;
```suggestion
		return self::get_items( $this->cache, $key );
```

2020-07-16 09:16 UTC, matipojo approved these changes

2020-07-16 14:03 UTC, kobizz approved these changes

2020-07-16 16:24 UTC, merged