E-Icons: Added 6 new icons: custom-css, global-colors, globe, typogra…
elementor/elementor pull request #11896
Opened 2020-07-19 12:50 UTC by udidol

The New Icons:
* `eicon-custom-css`
* `eicon-global-colors`
* `eicon-globe`
* `eicon-typography`
* `eicon-background`

+ changed `eicon-elementor-square` to `eicon-elementor-circle`

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [X] Other... Please describe: Update External E-Icons Library

## Summary

This PR can be summarized in the following changelog entry:

* Updated the E-Icons library: Added 6 new icons + changed `eicon-elementor-square` to `eicon-elementor-circle`

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [X] Docs have been added / updated (for bug fixes / features)

2020-07-19 15:48 UTC, kobizz submitted a review, later dismissed

2020-07-20 11:21 UTC, matipojo requested changes

2020-07-20 11:21 UTC, matipojo commented on assets/lib/eicons/css/elementor-icons.css
> +.eicon-elementor-square {
`:before`?

2020-07-20 11:25 UTC, udidol commented on assets/lib/eicons/css/elementor-icons.css
> +.eicon-elementor-square {
!!!

2020-07-21 08:14 UTC, kobizz approved these changes

2020-07-21 08:40 UTC, matipojo approved these changes

2020-07-21 10:12 UTC, KingYes approved these changes

2020-07-21 10:12 UTC, merged