Globals: Convert the Global Control Select Box into a Toggle Button with Icon
elementor/elementor pull request #11898
Opened 2020-07-19 16:26 UTC by udidol

2020-07-21 10:06 UTC, kobizz requested changes

2020-07-21 10:06 UTC, kobizz commented on assets/dev/scss/editor/panel/controls/_globals.scss
> +		padding: 4px;
You don't need the padding

2020-07-21 10:06 UTC, kobizz commented on assets/dev/scss/editor/panel/controls/_globals.scss
> +		width: $control-unit;
Use the `control-unit-1` class instead

2020-07-21 10:06 UTC, kobizz commented on assets/dev/scss/editor/panel/controls/_globals.scss
>  		border-radius: getValueByDirection(3px 0 0 3px, 0 3px 3px 0);
Use another terminology that "select box" everywhere

2020-07-21 12:04 UTC, kobizz approved these changes

2020-07-21 12:56 UTC, matipojo approved these changes

2020-07-22 12:02 UTC, KingYes approved these changes

2020-07-22 12:02 UTC, merged