Globals: Global Colors Popover - Added checkmark to selected global color
elementor/elementor pull request #11953
Opened 2020-07-26 15:11 UTC by udidol

2020-07-27 12:02 UTC, kobizz requested changes

2020-07-27 12:02 UTC, kobizz commented on assets/dev/scss/frontend/widgets/heading.scss
> +// The double selector here is for specificity reasons - to avoid being overridden by default Globals CSS.
Check what happens in theme style typography

2020-07-28 07:25 UTC, kobizz requested changes

2020-07-28 07:25 UTC, kobizz commented on assets/dev/js/editor/controls/color.js
> +		this.globalValue = null;
@udidol What about this?

2020-07-28 10:17 UTC, udidol commented on assets/dev/js/editor/controls/color.js
> +		this.globalValue = null;
I am in favor of leaving it. The error which caused me to add it was not actually caused by the absence of it. But - when I added it, the clear action worked as it should even despite the error. What do you think?

2020-07-28 11:07 UTC, kobizz requested changes

2020-07-28 11:07 UTC, kobizz commented on core/kits/manager.php
> +				'font_cannot_be_deleted' => __( 'System Font can\'t be deleted', 'elementor' ),
Where is this key implemented?

2020-07-28 11:09 UTC, udidol commented on core/kits/manager.php
> +				'font_cannot_be_deleted' => __( 'System Font can\'t be deleted', 'elementor' ),
kit repeater-row.js

2020-07-28 11:13 UTC, kobizz approved these changes

2020-07-28 11:42 UTC, matipojo approved these changes

2020-07-28 11:42 UTC, merged