Fix/dynamic optimization
elementor/elementor pull request #11957
Opened 2020-07-27 11:22 UTC by kobizz

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2020-07-27 13:40 UTC, matipojo requested changes

2020-07-27 13:40 UTC, matipojo commented on core/dynamic-tags/dynamic-css.php
> +		$post_css_file = Post_CSS::create( $post_id_for_data );
Receive the CSS file itself.

2020-07-27 13:40 UTC, matipojo commented on core/files/base.php
> +	 * for files that doesn't support sync
```suggestion
	 * For files that don't support sync.
```

2020-07-27 13:40 UTC, matipojo commented on core/files/base.php
> +		if ( $this->is_sync_enabled() ){
Move to BaseCache.

2020-07-28 11:27 UTC, matipojo approved these changes

2020-07-28 11:31 UTC, KingYes approved these changes

2020-07-28 11:31 UTC, merged