Global Colors: New Global Color Modal - Made the color name duplication notice dynamic.
elementor/elementor pull request #11969
Opened 2020-07-28 13:13 UTC by udidol

2020-07-28 13:19 UTC, matipojo submitted a review, later dismissed

2020-07-29 13:41 UTC, kobizz requested changes

2020-07-29 13:41 UTC, kobizz commented on core/kits/assets/js/globals/global-select-behavior.js
> +				this.ui.confirmMessageText = this.confirmNewGlobalModal.getElements( 'widget' ).find( '.e-global__confirm-message-text' );
Insert `this.confirmNewGlobalModal.getElements( 'widget' )` into a local variable

2020-07-29 13:41 UTC, kobizz commented on core/kits/assets/js/globals/global-select-behavior.js
> +				this.ui.globalNameInput.on( 'change paste keyup', () => this.onAddGlobalConfirmInputChange() );
```suggestion
				this.ui.globalNameInput.on( 'input', () => this.onAddGlobalConfirmInputChange() );
```

2020-07-29 13:41 UTC, kobizz commented on core/kits/assets/js/globals/global-select-behavior.js
> +		for ( const globalColor of Object.values( this.view.globalsList ) ) {
```suggestion
		for ( const globalValue of Object.values( this.view.globalsList ) ) {
```

2020-07-29 13:41 UTC, kobizz commented on core/kits/assets/js/globals/global-select-behavior.js
> +				messageContent = elementor.translate( 'global_color_confirm_text' );
Use view functions

2020-08-02 10:54 UTC, kobizz approved these changes

2020-08-02 17:42 UTC, matipojo approved these changes

2020-08-03 06:25 UTC, KingYes approved these changes

2020-08-03 06:25 UTC, merged