Global Control Popover: Moved the Manage Globals button to the popover header
elementor/elementor pull request #11970
Opened 2020-07-28 15:14 UTC by udidol

2020-07-29 12:51 UTC, kobizz requested changes

2020-07-29 12:51 UTC, kobizz commented on assets/dev/scss/editor/panel/controls/_globals.scss
> +			span {
Add a class

2020-07-29 14:03 UTC, kobizz approved these changes

2020-07-29 14:52 UTC, matipojo approved these changes

2020-08-02 10:56 UTC, KingYes approved these changes

2020-08-02 10:56 UTC, merged