Site Settings: Panel Menu - Add "Dashboard Settings" link.
elementor/elementor pull request #12040
Opened 2020-08-05 14:23 UTC by udidol

2020-08-05 15:09 UTC, kobizz requested changes

2020-08-05 15:09 UTC, kobizz commented on core/kits/assets/js/panel-menu.js
> +		if ( 'additional-settings' === key ) {
Instead of doing it inside the general `createGroupItems` method, do it where you create the "settings" group

2020-08-06 08:06 UTC, kobizz requested changes

2020-08-06 08:06 UTC, kobizz commented on core/kits/assets/js/panel-menu.js
> +		if ( ! 'additional-settings' === key ) {
Remove the 'additional-settings' key from the items array, and you won't need to handle it here

2020-08-06 17:54 UTC, matipojo approved these changes

2020-08-06 17:56 UTC, kobizz approved these changes

2020-08-06 18:45 UTC, merged