Site Editor - Error modal.
elementor/elementor pull request #12045
Opened 2020-08-06 08:48 UTC by Nevoss

2020-08-06 13:10 UTC, matipojo requested changes

2020-08-06 13:10 UTC, matipojo commented on core/app/modules/site-editor/assets/js/ui/dialog/dialog.js
> +		...'form' === props.wrapperTag && { onSubmit: props.onSubmit },
Simplify.

2020-08-06 13:49 UTC, matipojo requested changes

2020-08-06 13:49 UTC, matipojo commented on core/app/modules/site-editor/assets/js/organisms/error-dialog.js
> +	backButtonText: PropTypes.string,
Reorder here and on defaultProps.

```suggestion
	learnButtonText: PropTypes.string,
	learnButtonUrl: PropTypes.string,
	backButtonText: PropTypes.string,
	backButtonHandler: PropTypes.func,
```

2020-08-09 08:53 UTC, matipojo submitted a review, later dismissed

2020-08-13 17:00 UTC, joshmarom requested changes

2020-08-17 14:28 UTC, joshmarom submitted a review, later dismissed

2020-08-17 14:36 UTC, kobizz requested changes

2020-08-17 14:36 UTC, kobizz commented on core/app/assets/js/ui/molecules/buttons-api.scss
> +	// cta
It looks like a wrong indentation

2020-08-17 14:36 UTC, kobizz commented on core/app/assets/js/ui/dialog/dialog.scss
> +		&:last-child:not(:first-child) {
Insert an empty line between rules and an internal selector

2020-08-17 15:01 UTC, kobizz approved these changes

2020-08-17 19:03 UTC, matipojo approved these changes

2020-08-18 05:46 UTC, merged