Dialogs Manager: Updated The Dialog library to v4.8.0 - new close button accessibility options
elementor/elementor pull request #12115
Opened 2020-08-13 16:09 UTC by udidol

2020-08-13 16:20 UTC, kobizz submitted a review, later dismissed

2020-08-13 17:14 UTC, matipojo requested changes

2020-08-13 17:14 UTC, matipojo commented on assets/lib/dialog/dialog.js
> +				const $button = $('<div>', settings.closeButtonOptions.attributes),
Needs backwards compatibility for `closeButtonClass`.

2020-08-17 16:16 UTC, kobizz approved these changes

2020-08-17 19:09 UTC, matipojo approved these changes

2020-08-18 05:45 UTC, merged