Icon List Widget: Fix -  Theme style overrides Icon List items typography when list items are links
elementor/elementor pull request #12116
Opened 2020-08-13 16:34 UTC by udidol

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

* Icon List Widget: Fix -  Theme style overrides Icon List items typography when list items are links

## Quality assurance

- [X] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

2020-08-13 16:45 UTC, rodolphebertozzo requested changes
And for icon box.

2020-08-17 13:04 UTC, kobizz submitted a review, later dismissed

2020-08-17 14:49 UTC, kobizz approved these changes

2020-08-17 20:53 UTC, rodolphebertozzo commented
Hi @udidol, Can you take a look at my improvement request, I'm sure it's something that doesn't take a lot of time to do and could give a nice dynamic look to the sites, why not add it to milestone 3.1 https://github.com/elementor/elementor/issues/12058

2020-08-18 05:44 UTC, merged