Global Settings: Global Fonts screen - Fix: Global typography popover glitch in RTL mode
elementor/elementor pull request #12164
Opened 2020-08-19 13:13 UTC by udidol

2020-08-19 13:14 UTC, rodolphebertozzo approved these changes, later dismissed

2020-08-20 07:00 UTC, kobizz requested changes

2020-08-20 07:00 UTC, kobizz commented on core/kits/assets/css/panel.scss
> +				#{$end}: 5px;
```suggestion
				@include end(5px);
```

2020-08-23 12:00 UTC, kobizz approved these changes

2020-08-23 12:09 UTC, matipojo approved these changes

2020-08-24 10:44 UTC, merged