Kits/Manager: Fix - Show Globals dropdown to all of the user.
elementor/elementor pull request #12261
Opened 2020-08-26 13:24 UTC by iNewLegend

2020-08-26 16:22 UTC, matipojo requested changes

2020-08-26 16:22 UTC, matipojo commented on core/kits/assets/js/manager.js
> +			if ( ! elementor.config.user.can_edit_kit && ! elementor.config.user.is_administrator ) {
```suggestion
			if ( ! elementor.config.user.can_edit_kit ) {
```

2020-08-27 04:53 UTC, iNewLegend commented on core/kits/assets/js/manager.js
> +			if ( ! elementor.config.user.can_edit_kit && ! elementor.config.user.is_administrator ) {
Handled, force-pushed.

2020-08-27 07:14 UTC, matipojo approved these changes

2020-08-27 11:57 UTC, kobizz approved these changes

2020-08-27 11:57 UTC, merged

2020-12-01 13:42 UTC, iNewLegend commented on core/kits/assets/js/manager.js
> +			$e.components.register( new Component( { manager: this } ) );
test

2020-12-01 13:42 UTC, iNewLegend commented on core/kits/assets/js/component.js
> +
test