Fix: Elementor overrides Gutenberg's CSS for rounded images.
elementor/elementor pull request #12278
Opened 2020-08-27 07:42 UTC by udidol

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

* Fix: Elementor overrides Gutenberg's CSS for rounded images.

## Quality assurance

- [X] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

2020-09-22 17:10 UTC, arielk requested changes
Please move it to compatibility file

2020-10-02 17:30 UTC, luisalpaba commented
It is possible to temporarily fix this by pasting the CSS code below within the Additional CSS tab of the theme. 
.is-style-rounded img {
    border-radius: 9999px !important;
}
For reference: https://www.loom.com/share/a14c09045cd54be7bd6ea17b168e8c12

2020-12-21 23:14 UTC, borayeris commented
How can this issue cannot be fixed since August?

**This overrides:**
.elementor img {
	height: auto;
	max-width: 100%;
	border: none;
	-webkit-border-radius: 0;
	border-radius: 0;
	-webkit-box-shadow: none;
	box-shadow: none;
}

**This:**
.is-style-circle-mask img, .is-style-rounded img {
	border-radius: 9999px;
}

2020-12-22 07:22 UTC, arielk submitted a review, later dismissed

2022-03-14 17:30 UTC, closed without merging