Fix/install version detection
elementor/elementor pull request #12292
Opened 2020-08-27 15:10 UTC by kobizz

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2020-10-25 09:55 UTC, matipojo requested changes
Please add tests.

2020-12-18 11:50 UTC, matipojo approved these changes

2020-12-18 11:51 UTC, matipojo requested changes
Error: Elementor\Tests\Phpunit\Elementor\Core\Upgrades\Test_Manager::test_start_run
uksort() expects parameter 1 to be array, null given

2020-12-28 08:12 UTC, matipojo approved these changes

2020-12-28 17:09 UTC, KingYes requested changes

2020-12-28 17:09 UTC, KingYes commented on core/upgrade/manager.php
> +			$installs_history[ $old_version ] = $installs_history[ ELEMENTOR_VERSION ] - 1;
@kobizz Please explain why you remove one millisecond from this value.

2020-12-29 10:17 UTC, merged