Editor/Navigator: Fix - Resizeable destroy was called unnecessary (Fi…
elementor/elementor pull request #12321
Opened 2020-08-30 07:50 UTC by iNewLegend

2020-08-30 09:22 UTC, matipojo approved these changes, later dismissed

2020-08-30 13:19 UTC, kobizz requested changes

2020-08-30 13:19 UTC, kobizz commented on assets/dev/js/editor/regions/navigator/navigator.js
> +		if ( this.$el.resizable( 'instance' ) ) {
What about line 179?

2020-08-30 16:30 UTC, shilo-ey commented
Change base to develop @iNewLegend

2020-08-31 07:46 UTC, matipojo approved these changes

2020-08-31 10:31 UTC, kobizz approved these changes

2020-08-31 10:31 UTC, merged