Data: Fix - Sending incorrect url when permalinks on 'plain' mode.
elementor/elementor pull request #12390
Opened 2020-09-02 14:53 UTC by Nevoss

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2020-09-03 15:41 UTC, matipojo requested changes

2020-09-03 15:41 UTC, matipojo commented on core/common/assets/js/api/core/data.js
> +			const separator = -1 === url.search( /\?/ ) ? '?' : '&';
Use `includes`.

2020-09-03 15:41 UTC, matipojo commented on tests/qunit/core/common/assets/js/api/core/data.spec.js
> +		QUnit.test( 'prepareEndpoint(): permalinks in plain mod ', ( assert ) => {
```suggestion
		QUnit.test( 'prepareEndpoint(): permalinks in plain mode', ( assert ) => {
```

2020-09-06 09:12 UTC, matipojo requested changes

2020-09-06 09:12 UTC, matipojo commented on core/common/assets/js/api/core/data.js
> +			const separator = -1 === url.includes( '?' ) ? '?' : '&';
```suggestion
			const separator = url.includes( '?' ) ? '?' : '&';
```

2020-09-06 17:03 UTC, matipojo approved these changes

2020-09-07 06:58 UTC, kobizz approved these changes

2020-09-08 11:48 UTC, merged