Templates: Fix - duplicate Single in new template modal.
elementor/elementor pull request #12423
Opened 2020-09-06 12:18 UTC by Nevoss

2020-09-06 13:27 UTC, matipojo approved these changes, later dismissed

2020-09-07 06:56 UTC, kobizz requested changes

2020-09-07 06:56 UTC, kobizz commented on includes/admin-templates/new-template.php
> +use ElementorPro\Modules\ThemeBuilder\Documents\Single;
You can't explicitly filter pro classes here

2020-09-08 08:11 UTC, matipojo approved these changes

2020-09-08 08:32 UTC, closed without merging