Globals: Fix - Fetch id that does not exists returns false response (empty object).
elementor/elementor pull request #12459
Opened 2020-09-09 12:44 UTC by Nevoss

2020-09-09 16:09 UTC, matipojo requested changes

2020-09-09 16:09 UTC, matipojo commented on core/editor/data/globals/endpoints/base.php
> +				__( 'Global setting was not founded.', 'elementor' ),
```suggestion
				__( 'Global value was not found.', 'elementor' ),
```

2020-09-09 16:09 UTC, matipojo commented on core/editor/data/globals/endpoints/base.php
> +				'global_not_founded',
```suggestion
				'global_not_found',
```

2020-09-10 06:38 UTC, matipojo approved these changes

2020-09-10 07:04 UTC, matipojo approved these changes

2020-09-10 09:24 UTC, kobizz approved these changes

2020-09-11 07:06 UTC, merged