Feature/new app components
elementor/elementor pull request #12505
Opened 2020-09-14 07:30 UTC by rotemee

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2020-09-14 07:57 UTC, kobizz requested changes

2020-09-14 07:57 UTC, kobizz commented on core/app/assets/js/ui/molecules/notice.scss
> +	box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
It should use one of predefined values

2020-09-14 07:57 UTC, kobizz commented on core/app/assets/js/ui/molecules/notice.scss
> +		border-left: 2px solid theme-colors(warning);
Check with @joshmarom about border mixins and values

2020-09-15 15:33 UTC, rodolphebertozzo commented
Close this :https://github.com/elementor/elementor/pull/12401

2020-09-17 11:05 UTC, kobizz approved these changes

2020-11-04 12:34 UTC, matipojo approved these changes

2020-11-04 12:34 UTC, merged