Kits/Site Identity: Fix - Cannot upload svg logo.
elementor/elementor pull request #12529
Opened 2020-09-15 10:33 UTC by Nevoss

2020-09-24 08:51 UTC, matipojo requested changes

2020-09-24 08:51 UTC, matipojo commented on core/kits/documents/tabs/settings-site-identity.php
> +		$can_upload_unfiltered_images = Files_Upload_Handler::is_enabled();
```suggestion
		$include_svg_inline_option = ! Files_Upload_Handler::is_enabled();
```

2020-10-14 15:49 UTC, matipojo requested changes

2020-10-14 15:49 UTC, matipojo commented on core/kits/documents/tabs/settings-site-identity.php
> +				'include_svg_inline_option' => ! $include_svg_inline_option,
```suggestion
				'include_svg_inline_option' => $include_svg_inline_option,
```

2020-10-14 15:49 UTC, matipojo commented on core/kits/documents/tabs/settings-site-identity.php
> +		$include_svg_inline_option = Files_Upload_Handler::is_enabled();
```suggestion
		$include_svg_inline_option = ! Files_Upload_Handler::is_enabled();
```

2020-10-14 15:49 UTC, matipojo commented on core/kits/documents/tabs/settings-site-identity.php
> +				'include_svg_inline_option' => ! $include_svg_inline_option,
```suggestion
				'include_svg_inline_option' => $include_svg_inline_option,
```

2020-10-15 09:44 UTC, rodolphebertozzo submitted a review, later dismissed

2020-10-15 14:57 UTC, matipojo requested changes

2020-10-15 14:57 UTC, matipojo commented on core/kits/documents/tabs/settings-site-identity.php
> +				'include_svg_inline_option' => $should_include_svg_inline_option,
```suggestion
				'should_include_svg_inline_option' => $should_include_svg_inline_option,
```

2020-10-15 15:36 UTC, matipojo approved these changes, later dismissed

2020-10-18 08:20 UTC, kobizz requested changes

2020-10-18 08:20 UTC, kobizz commented on assets/dev/js/editor/controls/media.js
> +		const mediaType = e?.target?.dataset?.value || this.getMediaType();
It's better to call the parameter something like `media-type` rather than `value`

2020-10-18 09:03 UTC, matipojo approved these changes

2020-10-18 09:50 UTC, kobizz approved these changes

2020-10-19 14:51 UTC, KingYes approved these changes

2020-10-19 14:52 UTC, merged