Document/Elements/Paste-Style: Fix - When paste styling with globals,…
elementor/elementor pull request #12561
Opened 2020-09-16 16:23 UTC by iNewLegend

2020-09-16 16:38 UTC, matipojo requested changes

2020-09-16 16:38 UTC, matipojo commented on assets/dev/js/editor/document/elements/commands/paste-style.js
> +		// Moved from `editor/elements/views/base.js` `pasteStyle` function.
Remove comment.

2020-09-16 16:38 UTC, matipojo commented on assets/dev/js/editor/document/elements/commands/paste-style.js
> +		elementor.channels.data.trigger( 'element:before:paste:style', targetContainer.model );
Add a deprecatio notice.

2020-09-16 16:38 UTC, matipojo commented on assets/dev/js/editor/document/elements/commands/paste-style.js
> +		elementor.channels.data.trigger( 'element:after:paste:style', targetContainer.model );
Add a deprecatio notice.

2020-09-16 16:38 UTC, matipojo commented on assets/dev/js/editor/document/elements/commands/paste-style.js
> +				render: false, // Prevent double render.
`options: { external: true },`?

2020-09-16 17:07 UTC, iNewLegend commented on assets/dev/js/editor/document/elements/commands/paste-style.js
> +				render: false, // Prevent double render.
options: { internal: true },?

2020-09-17 06:01 UTC, iNewLegend commented on assets/dev/js/editor/document/elements/commands/paste-style.js
> +		elementor.channels.data.trigger( 'element:before:paste:style', targetContainer.model );
https://github.com/elementor/elementor/blob/develop/assets/dev/js/editor/document/backwards-compatibility.js#L22

2020-09-17 06:01 UTC, iNewLegend commented on assets/dev/js/editor/document/elements/commands/paste-style.js
> +		elementor.channels.data.trigger( 'element:after:paste:style', targetContainer.model );
https://github.com/elementor/elementor/blob/develop/assets/dev/js/editor/document/backwards-compatibility.js#L22

2020-09-17 12:49 UTC, iNewLegend commented on assets/dev/js/editor/document/elements/commands/paste-style.js
> +		// Moved from `editor/elements/views/base.js` `pasteStyle` function.
Done

2020-09-17 12:49 UTC, iNewLegend commented on assets/dev/js/editor/document/elements/commands/paste-style.js
> +				render: false, // Prevent double render.
done

2020-09-21 11:49 UTC, matipojo requested changes
Tests?

2020-09-22 07:53 UTC, iNewLegend commented
> Tests?

handled.

2020-09-23 12:41 UTC, matipojo approved these changes

2020-09-23 13:04 UTC, kobizz approved these changes

2020-09-23 13:12 UTC, rodolphebertozzo commented
@KingYes

2020-09-29 15:12 UTC, KingYes approved these changes

2020-09-29 15:12 UTC, merged