Tests: Refactor - Basic order to phpunit test suite.
elementor/elementor pull request #12757
Opened 2020-10-06 15:38 UTC by Nevoss

2020-10-15 15:11 UTC, matipojo requested changes

2020-10-15 15:11 UTC, matipojo commented on tests/bootstrap.php
> +require __DIR__ . '/phpunit/factories/factory-for-documents.php';
```suggestion
require __DIR__ . '/phpunit/factories/documents.php';
```

2020-10-15 15:44 UTC, matipojo approved these changes

2020-10-19 14:54 UTC, KingYes approved these changes

2020-10-19 14:54 UTC, merged