FontAwesome: Updated to version 5.15.1
elementor/elementor pull request #12780
Opened 2020-10-08 14:16 UTC by udidol

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [X] Other... Please describe: Update external lib

## Summary

This PR can be summarized in the following changelog entry:

* FontAwesome: Updated to version 5.15.1

2020-10-13 14:28 UTC, kobizz requested changes

2020-10-13 14:28 UTC, kobizz commented on assets/lib/font-awesome/css/all.css
> -.fa-adobe:before {
What happens with a user that has already chosen this icon?

2020-10-14 12:00 UTC, kobizz approved these changes

2020-10-25 15:57 UTC, matipojo approved these changes

2020-12-10 13:24 UTC, KingYes approved these changes

2020-12-10 13:24 UTC, merged