Select2: Tweak - New button for adding a new option to the select box.
elementor/elementor pull request #12795
Opened 2020-10-10 21:48 UTC by rotemee

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2020-10-14 08:43 UTC, kobizz requested changes

2020-10-14 08:43 UTC, kobizz commented on assets/lib/e-select2/js/e-select2.full.js
> +      container._setAllSelectedClass();
We have to find a way to do it as an external extension for select2

2020-10-15 14:06 UTC, KingYes requested changes

2020-10-15 14:06 UTC, KingYes commented on assets/dev/js/editor/utils/select2.js
> +		super.onInit(...args);
Fix JSlint here..

2020-10-18 11:33 UTC, kobizz requested changes

2020-10-19 06:33 UTC, kobizz requested changes

2020-10-19 06:33 UTC, kobizz commented on assets/dev/scss/editor/_select2.scss
> +	&:not(.select2-container--all-selected) .select2-selection--multiple .select2-search--inline::before {
Add to the `.select2-search--inline` class a `padding-top: 0.6px` to place it in the accurate location

2020-10-19 12:28 UTC, kobizz requested changes

2020-10-19 12:28 UTC, kobizz commented on assets/dev/scss/editor/_select2.scss
> +	& .select2-selection--multiple .select2-search--inline {
Remove the `&` character and add a comment to explain why this line is needed

2020-10-19 13:41 UTC, kobizz requested changes

2020-10-19 13:41 UTC, kobizz commented on assets/dev/scss/editor/_select2.scss
> +	/* Due to the add-new-item button, we need to make make the button vertically aligned to the selected item before it. */
```suggestion
	/* Due to the add-new-item button, we need to make the button vertically aligned to the selected item before it. */
```

2020-10-19 13:47 UTC, kobizz approved these changes

2020-10-20 09:18 UTC, matipojo approved these changes

2020-10-22 14:37 UTC, KingYes approved these changes

2020-10-22 14:37 UTC, merged