Tabs, Accordion, Toggle Widgets: Fix - aria-selected attribute missing for a11y accessibility.
elementor/elementor pull request #12818
Opened 2020-10-13 14:40 UTC by rotemee

In addition, in mobile devices, the titles of the Tabs widget were missing a link tag, that also was missing to get proper accessibility support.

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2020-10-13 15:11 UTC, kobizz approved these changes

2020-10-13 16:07 UTC, matipojo requested changes

2020-10-14 08:11 UTC, kobizz commented on includes/widgets/tabs.php
> +					<div <?php echo $this->get_render_attribute_string( $tab_title_mobile_setting_key ); ?>><a href=""><?php echo $item['tab_title']; ?></a></div>
It's valid.

https://stackoverflow.com/questions/5637969/is-an-empty-href-valid

2020-10-14 15:30 UTC, matipojo requested changes

2020-10-14 15:30 UTC, matipojo commented on includes/widgets/tabs.php
> +					<div <?php echo $this->get_render_attribute_string( $tab_title_mobile_setting_key ); ?>><a href=""><?php echo $item['tab_title']; ?></a></div>
It's valid but not friendly for accessibility as described in the link. you can add a `tabindex` in order to solve it.

2021-02-08 09:08 UTC, shilo-ey commented on includes/widgets/tabs.php
> +					<div <?php echo $this->get_render_attribute_string( $tab_title_mobile_setting_key ); ?>><a href=""><?php echo $item['tab_title']; ?></a></div>
+1

2021-02-22 06:39 UTC, shilo-ey commented
@joshmarom is this still relevant?

2022-12-14 08:13 UTC, closed without merging