DB: Deprecate - set_is_elementor_page
elementor/elementor pull request #12879
Opened 2020-10-20 10:36 UTC by Nevoss

2020-10-22 09:01 UTC, rodolphebertozzo commented on includes/db.php
> +			->get_modules('dev-tools')
->get_modules( 'dev-tools' )

2020-10-22 11:45 UTC, matipojo requested changes

2020-10-22 11:45 UTC, matipojo commented on core/admin/admin.php
> +		Plugin::$instance->documents->get( $post_id )->set_is_build_with_elementor( ! empty( $_POST['_elementor_post_mode'] ) );
```suggestion
		Plugin::$instance->documents->get( $post_id )->set_is_built_with_elementor( ! empty( $_POST['_elementor_post_mode'] ) );
```

2020-10-22 11:45 UTC, matipojo commented on core/base/document.php
> +	const BUILD_WITH_ELEMENTOR_META_KEY = '_elementor_edit_mode';
```suggestion
	const BUILT_WITH_ELEMENTOR_META_KEY = '_elementor_edit_mode';
```

2020-10-22 13:34 UTC, matipojo requested changes

2020-10-22 13:34 UTC, matipojo commented on tests/phpunit/elementor/modules/gutenberg/test-module.php
> +		$this->assertEmpty(get_post_meta($post->ID, Document::BUILT_WITH_ELEMENTOR_META_KEY, true));
PHPCS

2020-10-22 13:35 UTC, matipojo requested changes

2020-10-22 13:35 UTC, matipojo commented on tests/phpunit/elementor/modules/history/test-revisions-manager.php
> +		$this->assertEquals('builder', get_post_meta($post_id, Document::BUILT_WITH_ELEMENTOR_META_KEY, true));
PHPCS

2020-10-22 13:59 UTC, matipojo approved these changes

2020-10-25 11:27 UTC, kobizz requested changes

2020-10-25 11:27 UTC, kobizz commented on core/base/document.php
> +
Use the designated `Document::update_meta` and `Document::delete_meta` methods

2020-10-25 11:27 UTC, kobizz commented on core/base/document.php
> +		return ! ! get_post_meta( $this->post->ID, self::BUILT_WITH_ELEMENTOR_META_KEY, true );
Use the designated `Document::get_meta` method

2020-10-25 14:19 UTC, matipojo requested changes

2020-10-25 14:19 UTC, matipojo commented on tests/phpunit/elementor/core/admin/test-admin.php
> +		$_POST['_elementor_edit_mode_nonce'] = wp_create_nonce( 'admin.php' );
Separate to another test and another post.

2020-10-25 15:47 UTC, matipojo submitted a review, later dismissed

2020-10-27 12:37 UTC, kobizz submitted a review, later dismissed

2020-10-28 16:23 UTC, matipojo submitted a review, later dismissed

2020-11-10 13:04 UTC, rodolphebertozzo submitted a review, later dismissed

2020-11-22 15:43 UTC, KingYes approved these changes

2020-11-22 15:43 UTC, merged