Admin Bar: Fix - "edit with elementor" not works for empty pages.
elementor/elementor pull request #12893
Opened 2020-10-21 13:23 UTC by Nevoss

The action that catches the documents was triggered after the rendering of an empty pages.

2020-10-21 16:08 UTC, matipojo requested changes

2020-10-21 16:08 UTC, matipojo commented on includes/frontend.php
> -		do_action( 'elementor/frontend/get_builder_content', $document, $this->_is_excerpt, $with_css );
BC. (Backwards Compatibility)

2020-10-22 11:33 UTC, matipojo approved these changes, later dismissed

2020-10-27 06:41 UTC, kobizz requested changes

2020-10-27 06:41 UTC, kobizz commented on includes/frontend.php
> +		// BC
Add a todo note or a task to use `Deprecations::do_deprecated_action()` in v3.1

2020-10-28 16:06 UTC, matipojo approved these changes

2020-10-28 16:08 UTC, kobizz approved these changes

2020-10-29 10:46 UTC, KingYes approved these changes

2020-10-29 10:46 UTC, merged