DB: Deprecate - copy_elementor_meta
elementor/elementor pull request #12901
Opened 2020-10-22 14:42 UTC by Nevoss

2021-01-24 13:15 UTC, matipojo commented
We will ope

2021-04-20 11:33 UTC, matipojo requested changes
Please pull 3.3.0 and fix the CI errors.

2021-04-22 08:30 UTC, rodolphebertozzo requested changes

2021-04-22 08:30 UTC, rodolphebertozzo commented on includes/db.php
> +				'3.1.0',
```suggestion
				'3.3.0',
```

2021-04-22 08:30 UTC, rodolphebertozzo commented on includes/db.php
> +				'3.1.0',
```suggestion
				'3.3.0',
```

2021-07-19 10:43 UTC, rodolphebertozzo requested changes

2021-07-19 10:43 UTC, rodolphebertozzo commented on includes/db.php
> +				'3.1.0',
```suggestion
				'3.4.0',
```

2021-07-19 10:43 UTC, rodolphebertozzo commented on includes/db.php
> +				'3.1.0',
```suggestion
				'3.4.0',
```

2022-03-14 17:30 UTC, closed without merging