Editor: Fix - Paste without any data throw an error.
elementor/elementor pull request #12938
Opened 2020-10-27 07:52 UTC by Nevoss

2020-10-28 17:55 UTC, matipojo requested changes

2020-10-28 17:55 UTC, matipojo commented on assets/dev/js/editor/document/ui/commands/paste.js
> +		if ( ! this.target || 0 === this.storage.length ) {
Move to `getConditions`.

2020-10-29 08:30 UTC, matipojo approved these changes

2020-11-01 16:27 UTC, kobizz approved these changes

2020-11-01 16:27 UTC, merged