Module/Gutenberg: Fix - "edit with elementor" button removes drafts
elementor/elementor pull request #12946
Opened 2020-10-27 14:41 UTC by Nevoss

2020-10-28 16:28 UTC, matipojo requested changes

2020-10-28 16:28 UTC, matipojo commented on assets/dev/js/admin/gutenberg.js
> +					const isNewPost = 'auto-draft' === wp.data.select( 'core/editor' ).getCurrentPost().status;
Explain.

2020-10-29 08:58 UTC, matipojo requested changes

2020-10-29 08:58 UTC, matipojo commented on assets/dev/js/admin/gutenberg.js
> +					// New post mark automatically as 'auto-draft'.
```suggestion
					// A new post is initialized as an 'auto-draft'.
```

2020-10-29 09:18 UTC, matipojo approved these changes

2020-10-29 16:45 UTC, kobizz approved these changes

2020-10-29 16:45 UTC, merged