Base Object: Added method 'has_own_method()'
elementor/elementor pull request #12961
Opened 2020-10-29 15:28 UTC by udidol

To determine whether a given method was declared in the current instance or was inherited by a parent class. Included unit tests.

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [X] Other... Please describe: Maintenance

## Quality assurance

- [X] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

2020-11-01 14:39 UTC, kobizz requested changes

2020-11-02 11:13 UTC, udidol commented on core/base/base-object.php
> +		// Otherwise, the new (replacement) method should be run.
Removed.

2020-11-02 11:13 UTC, udidol commented on tests/phpunit/elementor/core/base/test-base-object.php
> +		$test_class = new Has_Own_Method_Test_Class();
Done.

2020-11-02 11:13 UTC, udidol commented on tests/phpunit/elementor/core/base/test-base-object.php
> +class Has_Own_Method_Test_Class extends Has_Own_Method_Parent_Test_Class {
Done.

2020-11-02 11:13 UTC, udidol commented on core/base/base-object.php
> +	 * If it was declared by the current instance, return true. If it was inherited, call the new unprefixed method.
Removed.

2020-11-03 09:28 UTC, kobizz submitted a review, later dismissed

2020-11-03 15:11 UTC, matipojo requested changes

2020-11-03 15:11 UTC, matipojo commented on core/base/base-object.php
> +		$reflection_method = new ReflectionMethod( $this, $method_name );
Remove the `use` from line 5.
```suggestion
		$reflection_method = new \ReflectionMethod( $this, $method_name );
```

2020-11-04 09:26 UTC, udidol commented on core/base/base-object.php
> +		$reflection_method = new ReflectionMethod( $this, $method_name );
Done

2020-11-04 10:00 UTC, kobizz approved these changes

2020-11-04 11:34 UTC, matipojo approved these changes

2020-11-15 16:51 UTC, merged