Ed 508 admin menu   core
elementor/elementor pull request #12982
Opened 2020-11-02 10:57 UTC by iNewLegend

2020-11-04 14:31 UTC, rodolphebertozzo commented on includes/settings/settings.php
> +
Remove line

2020-11-05 08:56 UTC, matipojo commented on includes/settings/settings.php
> +
Why?

2020-11-08 12:56 UTC, matipojo approved these changes

2020-11-09 16:01 UTC, kobizz requested changes

2020-11-09 16:01 UTC, kobizz commented on includes/settings/settings.php
> +			[ $this, 'elementor_custom_code' ]
Use an anonymous callback with reference to a private method

2020-11-10 09:42 UTC, kobizz approved these changes

2020-11-10 09:56 UTC, rodolphebertozzo approved these changes

2020-11-10 12:33 UTC, KingYes requested changes

2020-11-10 12:33 UTC, KingYes commented on includes/settings/settings.php
> +			function () {
```suggestion
			function() {
```

2020-11-10 12:34 UTC, merged