Tweak/dynamic import swiper
elementor/elementor pull request #13006
Opened 2020-11-04 11:46 UTC by rotemee

Depended on [#12953](https://github.com/elementor/elementor/pull/12953) .
## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2020-11-12 10:44 UTC, kobizz approved these changes, later dismissed

2020-11-19 18:03 UTC, matipojo requested changes

2020-11-19 18:03 UTC, matipojo commented on assets/dev/js/frontend/utils/swiper.js
> +		return new Promise( ( res ) => {
Rename: `res => resolve`.

2020-11-22 08:27 UTC, rotemee commented on includes/frontend.php
> +			array_push( $dependencies, 'swiper' );
Fixed.

2020-11-22 08:27 UTC, rotemee commented on assets/dev/js/frontend/utils/swiper.js
> +		return new Promise( ( res ) => {
Fixed.

2020-11-22 13:17 UTC, kobizz submitted a review, later dismissed

2020-11-26 15:06 UTC, matipojo approved these changes

2020-11-29 14:46 UTC, kobizz approved these changes

2020-12-06 14:46 UTC, merged