[Experiment] New WP Dashboard Widgets
elementor/elementor pull request #13013
Opened 2020-11-04 21:13 UTC by arielk

2020-11-04 21:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/elementor/elementor?pullRequest=13013) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/elementor/elementor?pullRequest=13013) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: arielk<br/>:x: yehuda-matat<br/><hr/>**yehuda-matat** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/elementor/elementor?pullRequest=13013) it.</sub>

2020-11-04 21:18 UTC, rodolphebertozzo commented
Base 3.1.0 ?

2020-11-05 08:32 UTC, matipojo requested changes

2020-11-05 08:32 UTC, matipojo commented on assets/dev/js/admin/admin.js
> +		$( '.elementor_finder' ).on( 'click', function(e) {
```suggestion
		$( '.elementor-finder' ).on( 'click', function( e ) {
```

2020-11-05 08:32 UTC, matipojo commented on core/admin/admin.php
> +					<h3 class="e-heading e-divider_bottom"><?php echo __( 'Recently Edited', 'elementor' ); ?></h3>
Always use `-` instead of `_` in class names.

2020-11-05 08:32 UTC, matipojo commented on modules/dashboard-widgets/module.php
> +
Remove empty line.

2020-11-05 08:32 UTC, matipojo commented on modules/dashboard-widgets/module.php
> +		//add_action( 'admin_enqueue_scripts', [ $this, 'load_assets' ] );
Remove.

2020-11-05 08:32 UTC, matipojo commented on modules/dashboard-widgets/module.php
> +			add_action( 'wp_dashboard_setup', [ $this, 'add_dashboard_widgets' ], 999 );
Why 999? (remove or explain vie code comment.)

2020-11-05 08:32 UTC, matipojo commented on modules/dashboard-widgets/module.php
> +			add_action( 'welcome_panel', [ $this, 'welcome_dashboard_widget_render' ], PHP_INT_MAX );
Why PHP_INT_MAX? (remove or explain vie code comment.)

2020-11-05 08:32 UTC, matipojo commented on modules/dashboard-widgets/module.php
> +
Empty line, please follow all lint errors: https://github.com/elementor/elementor/pull/13013/checks?check_run_id=1355195256

2020-11-05 08:32 UTC, matipojo commented on modules/dashboard-widgets/module.php
> +		$widget_backup = array();
```suggestion
		$widget_backup = [];
```

2020-11-05 08:32 UTC, matipojo commented on modules/dashboard-widgets/module.php
> +		foreach ( $widgets as $widget_id => $widget ) {
Explain the approach.

2020-11-05 08:32 UTC, matipojo commented on modules/dashboard-widgets/module.php
> +		$create_post_url = Utils::get_create_new_post_url( 'post' );
```suggestion
		$create_post_url = Utils::get_create_new_post_url( 'post' );
```

2020-11-05 08:32 UTC, matipojo commented on modules/dashboard-widgets/module.php
> +		$action_links = array(
Short arrays everywhere.

2020-11-05 17:24 UTC, KingYes commented
Please continue there: #13019

2020-11-05 17:24 UTC, closed without merging