Admin Notices: New - Show elementor-dev notice.
elementor/elementor pull request #13080
Opened 2020-11-16 18:50 UTC by Nevoss

Also creates a base notice class that can be extended and configure a notice.

ref: ED-407

2020-11-19 08:36 UTC, matipojo requested changes

2020-11-19 08:36 UTC, matipojo commented on core/admin/admin-notices.php
> +	private function get_class_notices() {
```suggestion
	private function get_notices() {
```

2020-11-19 08:36 UTC, matipojo commented on core/admin/admin-notices.php
> +			<?php echo $options['id'] ? 'data-notice_id="' . $options['id'] . '"' : ''; ?>
Extract to variables.

2020-11-19 08:36 UTC, matipojo commented on core/admin/admin-notices.php
> +			$this->print_admin_notice( $notice_instance->get_config() );
```suggestion
			$notice_instance->print();
```
form the `print` check if `should_print`.

2020-11-19 08:36 UTC, matipojo commented on core/admin/admin-notices.php
> +			return;
Explain

2020-11-19 08:36 UTC, matipojo commented on core/admin/notices/elementor-dev-notice.php
> +		'wordpress-beta-tester/wp-beta-tester.php',
Add Gutenberg plugin

2020-11-19 08:36 UTC, matipojo commented on core/admin/notices/elementor-dev-notice.php
> +	 * If ont of those options is enabled it will show the notice.
```suggestion
	 * If one of those options is enabled it will show the notice.
```

2020-11-19 08:36 UTC, matipojo commented on core/admin/notices/elementor-dev-notice.php
> +	public function should_print() {
protected. and call it from `print` method.

2020-11-19 08:36 UTC, matipojo commented on tests/phpunit/base-class.php
> +		set_current_screen('dashboard');
```suggestion
		set_current_screen( 'dashboard' );
```

2020-11-19 08:36 UTC, matipojo commented on tests/phpunit/elementor/core/admin/notices/test-elementor-dev-notice.php
> +
Remove line.

2020-11-19 08:36 UTC, matipojo commented on tests/phpunit/elementor/core/admin/test-admin-notices.php
> +		$notice->method( 'get_config' )->willReturn( [
Add line

2020-11-19 08:36 UTC, matipojo commented on tests/phpunit/elementor/core/admin/test-admin-notices.php
> +	) {
```suggestion
	public function test_admin_notices__should_not_print_if_should_print_returns_false() {
```

2020-11-19 08:36 UTC, matipojo commented on tests/phpunit/traits/auth-helpers.php
> +		]);
PHPCS.

2020-11-19 17:20 UTC, matipojo submitted a review, later dismissed

2020-12-01 13:28 UTC, matipojo requested changes

2020-12-01 13:28 UTC, matipojo commented on tests/phpunit/elementor/core/admin/notices/test-elementor-dev-notice.php
> +		$this->elementor()->experiments->add_feature([ 'name' => 'test_feature', ]);
Try remove the option and set as active by default.

2020-12-06 13:25 UTC, matipojo requested changes

2020-12-06 13:25 UTC, matipojo commented on tests/phpunit/elementor/core/admin/notices/test-elementor-dev-notice.php
> +	public function test_should_print__should_not_print_when_there_is_no_promotion_option_or_plugin_or_experiment_is_inactive_or_default() {
Shorten

2020-12-07 14:39 UTC, matipojo approved these changes

2020-12-13 14:06 UTC, KingYes approved these changes

2020-12-13 14:06 UTC, merged