Tweak/Experiments Dom Optimization
elementor/elementor pull request #13115
Opened 2020-11-19 17:38 UTC by kobizz

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2020-11-22 07:51 UTC, matipojo requested changes

2020-11-22 07:51 UTC, matipojo commented on core/editor/editor.php
> +
Move the a method `get_active_features`.

2020-11-22 07:51 UTC, matipojo commented on core/experiments/manager.php
> +			$on_state_change_callback = function( $old_state, $new_state ) use ( $experimental_data ) {
It look like the `feature` should be a class that handles his state change and other aspects.

2020-11-22 07:51 UTC, matipojo commented on core/experiments/manager.php
> +			'name' => 'e-dom_optimization',
```suggestion
			'name' => 'e_dom_optimization',
```

2020-11-26 13:41 UTC, matipojo requested changes

2020-11-29 16:38 UTC, kobizz commented on core/editor/editor.php
> +			'experimentalFeatures' => $active_experimental_features,
aca3205

2020-12-02 15:09 UTC, matipojo approved these changes, later dismissed

2020-12-06 12:44 UTC, KingYes submitted a review, later dismissed

2020-12-06 13:07 UTC, merged