Core/App: Change - Unable to partial extend app. ED-1027.
elementor/elementor pull request #13241
Opened 2020-12-06 16:04 UTC by iNewLegend

2020-12-06 16:25 UTC, matipojo approved these changes

2020-12-16 14:54 UTC, matipojo requested changes

2020-12-16 14:54 UTC, matipojo commented on core/app/assets/js/ui/modal/modal.js
> +							<span className="title">{ this.props.title }</span>
Use `Typography`

2020-12-16 16:34 UTC, joshmarom reviewed
Can you describe in a few words what was the objective and what was done to accomplish that...

I see some changes in SCSS bundling and RTL can you explain abut that too, and how it all comes together?

2020-12-16 16:34 UTC, joshmarom commented on core/app/assets/js/ui/modal/modal.js
> +				<Modal modalProps={this.state} title={ this.props.title } icon={ this.props.icon }>
```suggestion
				<Modal modalProps={this.state} {...this.props}>
```

2020-12-21 15:04 UTC, iNewLegend commented
> Can you describe in a few words what was the objective and what was done to accomplish that...
> 
> I see some changes in SCSS bundling and RTL can you explain abut that too, and how it all comes together?

The objective was: to create custom modal.
What was done to accomplish that:
1. minimal app-base for the requirements.
2. some of the components was not fully extend able, like modal - **eg:** we wanted to change the icon, title, etc.

"I see some changes",  for the minimal app-base css.

2020-12-21 15:07 UTC, iNewLegend commented on core/app/assets/js/ui/modal/modal.js
> +							<span className="title">{ this.props.title }</span>
Handled.

2020-12-21 15:07 UTC, iNewLegend commented on core/app/assets/js/ui/modal/modal.js
> +				<Modal modalProps={this.state} title={ this.props.title } icon={ this.props.icon }>
Handled.

2020-12-21 18:15 UTC, matipojo approved these changes

2020-12-23 08:06 UTC, joshmarom commented
I can't find anything wrong with this PR

2020-12-23 11:00 UTC, merged