Dev-Tools Module: Deprecations - Modified the `deprecated_argument()` method
elementor/elementor pull request #13240
Opened 2020-12-06 15:28 UTC by udidol

… to handle arguments by name and run `trigger_error()` messages instead of using WordPress's _deprecated_argument() function.

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [X] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

* Developer Tools: Deprecations class - modified the `deprecated_argument()` method to use argument variable names.

## Quality assurance

- [X] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

2020-12-14 07:51 UTC, kobizz requested changes

2020-12-14 07:51 UTC, kobizz commented on modules/dev-tools/deprecation.php
> +				trigger_error(
Use one `trigger_error` call and change only the string

2020-12-15 14:46 UTC, kobizz approved these changes

2020-12-16 12:36 UTC, matipojo approved these changes

2020-12-16 12:36 UTC, merged