Kits/Manager: New - Unit test for 'Show global dropdown to all users …
elementor/elementor pull request #13253
Opened 2020-12-08 12:49 UTC by iNewLegend

2020-12-08 15:32 UTC, matipojo approved these changes

2020-12-08 15:33 UTC, matipojo requested changes
Tests: Validate component available - User can edit kit FAILED

2020-12-09 14:43 UTC, matipojo approved these changes

2020-12-14 16:58 UTC, kobizz approved these changes

2020-12-14 16:58 UTC, merged