Editor: Fix - Add the “Theme” option to the page layout options
elementor/elementor pull request #13261
Opened 2020-12-09 09:35 UTC by Nevoss

2020-12-09 13:28 UTC, matipojo requested changes

2020-12-09 13:28 UTC, matipojo commented on core/kits/documents/tabs/settings-layout.php
> +		if ( isset( $page_templates[ PageTemplatesModule::TEMPLATE_THEME ] ) ) {
`unset` checks also if `isset`

2020-12-09 14:56 UTC, matipojo approved these changes

2020-12-16 07:09 UTC, kobizz approved these changes

2020-12-16 07:09 UTC, merged