Tweak: Added HTML Tag for title element in Divider widget closes #11499
elementor/elementor pull request #13439
Opened 2020-12-30 10:43 UTC by shilo-ey

2020-12-30 17:39 UTC, rodolphebertozzo commented on includes/widgets/divider.php
> +				<<?php echo $settings['html_tag'] .' '. $this->get_render_attribute_string( 'text' ); ?>><?php echo $settings['text']; ?></<?php echo $settings['html_tag'];?>>
```suggestion
				<<?php echo $settings['html_tag'] .' '. $this->get_render_attribute_string( 'text' ); ?>><?php echo $settings['text']; ?></<?php echo $settings['html_tag']; ?>>
```

2020-12-31 10:14 UTC, shilo-ey commented on includes/widgets/divider.php
> +				<<?php echo $settings['html_tag'] .' '. $this->get_render_attribute_string( 'text' ); ?>><?php echo $settings['text']; ?></<?php echo $settings['html_tag'];?>>
Thanks!

2021-01-05 07:21 UTC, kobizz approved these changes

2021-01-05 07:27 UTC, kobizz requested changes

2021-01-05 07:27 UTC, kobizz commented on includes/widgets/divider.php
> +				<<?php echo $settings['html_tag'] .' '. $this->get_render_attribute_string( 'text' ); ?>><?php echo $settings['text']; ?></<?php echo $settings['html_tag']; ?>>
```suggestion
				<<?php echo $settings['html_tag'] . ' ' . $this->get_render_attribute_string( 'text' ); ?>><?php echo $settings['text']; ?></<?php echo $settings['html_tag']; ?>>
```

2021-01-05 09:17 UTC, rodolphebertozzo approved these changes

2021-01-05 10:31 UTC, kobizz approved these changes

2021-01-05 10:31 UTC, merged