App/App-Base: Fix - Theme builder the "All parts" tab is cutted. ED-1…
elementor/elementor pull request #13455
Opened 2020-12-31 11:53 UTC by iNewLegend

2020-12-31 12:33 UTC, matipojo requested changes

2020-12-31 12:33 UTC, matipojo commented on core/app/assets/js/ui/grid/grid-api.scss
> +@import "../../../../../../assets/dev/scss/editor/_breakpoints.scss";
Explain

2020-12-31 13:03 UTC, iNewLegend commented on core/app/assets/js/ui/grid/grid-api.scss
> +@import "../../../../../../assets/dev/scss/editor/_breakpoints.scss";
Handled.

2020-12-31 14:32 UTC, matipojo approved these changes

2020-12-31 16:54 UTC, kobizz approved these changes

2021-01-06 09:58 UTC, matipojo requested changes
Please pull from 3.1.0 in order to pass the js lint.

2021-01-06 10:51 UTC, merged