Data: New - Allow the option to abort data request.
elementor/elementor pull request #13503
Opened 2021-01-06 07:16 UTC by Nevoss

A developer can send an AbortController signal and abort the request when the request is still pending.

ref: ED-1505

2021-01-07 19:09 UTC, matipojo requested changes
Fix QUnit error

2021-01-11 18:00 UTC, matipojo submitted a review, later dismissed

2021-01-13 10:31 UTC, kobizz requested changes

2021-01-13 10:31 UTC, kobizz commented on core/common/assets/js/api/core/data.js
> +				signal: requestData?.args?.options?.signal,
Where is it used?

2021-01-13 12:02 UTC, kobizz approved these changes

2021-01-13 12:02 UTC, merged