Add @iNewLegend to CODEOWNERS
elementor/elementor pull request #13512
Opened 2021-01-06 14:37 UTC by iNewLegend

2021-01-10 15:44 UTC, kobizz requested changes
Don't override existing rules

2021-01-12 09:25 UTC, iNewLegend commented
> Don't override existing rules
@kobizz 
please explain

2021-04-20 11:17 UTC, matipojo requested changes

2021-04-20 11:17 UTC, matipojo commented on .github/CODEOWNERS
> +*								@kingyes
Try to use spaces instead of tabs.

2021-04-22 06:49 UTC, iNewLegend commented on .github/CODEOWNERS
> +*								@kingyes
Handled.

2021-04-22 16:04 UTC, matipojo approved these changes

2021-04-22 16:04 UTC, merged