Editor Panel: Change - Make search input sticky
elementor/elementor pull request #13587
Opened 2021-01-14 12:53 UTC by StyleShit

2021-01-14 14:47 UTC, matipojo requested changes

2021-01-14 14:47 UTC, matipojo commented on assets/dev/scss/direction/editor-dark-mode.scss
> +	#elementor-panel-elements-search-area {
Nice! Please add screenshots before/after.

(Like here: https://github.com/elementor/elementor/pull/13586)

2021-01-14 18:03 UTC, StyleShit commented on assets/dev/scss/direction/editor-dark-mode.scss
> +	#elementor-panel-elements-search-area {
Before:

![image](https://user-images.githubusercontent.com/32631382/104629053-a56c6580-56a1-11eb-83f9-fefe4d447510.png)

After:

![image](https://user-images.githubusercontent.com/32631382/104630607-a1414780-56a3-11eb-9a06-19b9e90218b0.png)

2021-01-14 18:08 UTC, StyleShit commented on assets/dev/scss/direction/editor-dark-mode.scss
> +	#elementor-panel-elements-search-area {
Done

2021-01-17 11:42 UTC, matipojo requested changes

2021-01-17 11:42 UTC, matipojo commented on assets/dev/scss/editor/panel/_elements.scss
> +	z-index: 10;
Use `$first-layer`

2021-01-17 13:08 UTC, StyleShit commented on assets/dev/scss/editor/panel/_elements.scss
> +	z-index: 10;
Done

2021-01-17 14:56 UTC, matipojo submitted a review, later dismissed

2021-01-18 09:27 UTC, kobizz approved these changes

2021-02-15 12:14 UTC, kobizz submitted a review, later dismissed

2021-02-15 12:14 UTC, kobizz approved these changes

2021-02-18 12:58 UTC, matipojo approved these changes

2021-02-18 12:59 UTC, merged