Make the Main Section Customizable
elementor/elementor pull request #13618
Opened 2021-01-18 19:30 UTC by Oxibug

## PR Checklist

- [ x ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ x ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary
Closed PR #13449 Before forking

Give the developers the ability to customize the main section so they can use the main section background widely, like adding Canvas backgrounds instead of Videos or classic BG and it will be great to use the section background in anyway they wish.

## Description
Extend Element_Section class using action [elementor/elements/elements_registered] to add a new HTML output in the section's background such as using Canvas instead of Videos background,

## Test instructions
This PR can be tested by following these steps:

* In function [init_elements] located in Elements_Manager class, I need you to add **'$this'** word to action 'elementor/elements/elements_registered' So I'll be able to use the current class's function [register_element_type] .. like that:
**do_action( 'elementor/elements/elements_registered', $this );**

* Modify functions [**get_html_tag**] and [**print_shape_divider**] located in **Element_Section** class in [section.php] to public instead of private.

* Developer can add new controls using action '**elementor/element/section/section_advanced/after_section_end**' mentioned in the opened issue [3334](https://github.com/elementor/elementor/issues/3334#issuecomment-361611013)

* Now the developer can Extends the **Element_Section** class and override the functions [**content_template**], [**before_render**], [**after_render**]

## Quality assurance

- [ x ] I have tested this code to the best of my abilities
- [ x ] I have added unittests to verify the code works as intended
- [ x ] Docs have been added / updated (for bug fixes / features)

Fixes #

* Now, The developer can copy the three function [**content_template**], [**before_render**], [**after_render**] from **\elementor\includes\elements\section.php**
* Use the action [**elementor/elements/elements_registered**] after adding **$this** to point to the parent class and extend his new section **with the same implementation of the Elementor Plugin's Section** but now he can add his own HTML output as he wish

```
class ModifyElementorSection {

    public function __construct() {
        add_action( 'elementor/elements/elements_registered',         [ $this, 'modify_section' ] );
    }

    public function modify_section( $el_manager ) {        

        $el_manager->register_element_type( new Customizable_Section() );

    }

}

class Customizable_Section extends \Elementor\Element_Section {

    public function content_template() {
        /* Copy the Elementor's section form the Plugin Then append your new HTML output */
    }

    public function before_render() {
        /* Copy the Elementor's section form the Plugin Then append your new HTML output */
    }

    public function after_render() {
        /* Copy the Elementor's section form the Plugin Then append your new HTML output */
    }

}
```

2021-01-18 19:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/elementor/elementor?pullRequest=13618) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/elementor/elementor?pullRequest=13618) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/elementor/elementor?pullRequest=13618) it.</sub>

2021-03-02 08:35 UTC, Oxibug commented
@shilo-ey
Hi There, It seems like you forget the request, waiting for more than a month :) 
Is that feature possible? I made my own Elementor for just one word

2021-07-29 14:10 UTC, Oxibug commented
@shilo-ey 
Hi Pal, Can you look into this PR because I'm waiting for 6 months and after merging the new version I saw this msg [Block non-permitted User] 

I think I need to be approved manually from an authorized author, and the others [Waiting for status to be reported] msgs I don't know what should I do, I jus added onw word in the entire project.

I made a search and make an empty commit but it getting worst instead of 2 warnings I have 7 now :)

2021-07-29 16:12 UTC, shilo-ey commented
Hey @Oxibug 
Thank you for your contribution

Please remove the credit lines from the code itself. Elementor is an open source project and credit will be given in the Changelog.

Thanks!

2021-07-29 16:12 UTC, shilo-ey requested changes

2021-07-29 16:12 UTC, shilo-ey commented on includes/elements/section.php
> +	 * Modifed by Oxibug - NULL Commit
Please remove this line

2021-07-29 16:12 UTC, shilo-ey commented on includes/elements/section.php
> +	 * Modifed by Oxibug - NULL Commit
Please remove this line

2021-07-29 16:12 UTC, shilo-ey commented on includes/managers/elements.php
> +		 * Modified by Oxibug - NULL Commit
Please remove this line

2021-07-29 16:31 UTC, matipojo approved these changes

2021-07-29 16:33 UTC, matipojo requested changes

2021-07-29 16:33 UTC, matipojo commented on includes/elements/section.php
> +	public function get_html_tag() {
```suggestion
	protected function get_html_tag() {
```

2021-07-29 16:33 UTC, matipojo commented on includes/elements/section.php
> +	public function print_shape_divider( $side ) {
```suggestion
	protected function print_shape_divider( $side ) {
```

2021-07-29 16:45 UTC, matipojo approved these changes

2021-07-30 07:17 UTC, danielezerosi commented
@shilo-ey
@kobizz

Please approve the changes as this customization is very important to many developers

2021-08-01 12:32 UTC, shilo-ey approved these changes

2021-08-11 17:52 UTC, kobizz approved these changes

2021-08-12 09:19 UTC, merged