Document/Elements/Create: Fix - Invalid structure for section with index '0'. ED-1903
elementor/elementor pull request #13755
Opened 2021-01-31 13:08 UTC by iNewLegend

2021-02-01 16:42 UTC, matipojo requested changes

2021-02-01 16:42 UTC, matipojo commented on assets/dev/js/editor/document/hooks/data/document/elements/helper.js
> +				container.view.addChildModel( model );
Please add a test.

2021-02-07 11:06 UTC, iNewLegend commented
Check Inner section

2021-02-08 09:30 UTC, matipojo approved these changes

2021-02-08 11:04 UTC, merged