Utils: New - Extract WP export functionality to class. ED-2059
elementor/elementor pull request #13856
Opened 2021-02-09 12:52 UTC by iNewLegend

2021-02-09 13:27 UTC, matipojo requested changes
Nice work!

2021-02-09 13:27 UTC, matipojo commented on core/utils/wp-exporter.php
> + *  Remove filters.
We need the filters back.

2021-02-09 13:27 UTC, matipojo commented on core/utils/wp-exporter.php
> +		'status'     => false,
PHPCS

2021-02-09 13:27 UTC, matipojo commented on core/utils/wp-exporter.php
> +		'status'     => false,
Where is the limit & offset?

2021-02-09 13:27 UTC, matipojo commented on tests/phpunit/elementor/core/utils/test-wp-exporter.php
> +		$clean_wp_export_output = $this->remove_non_require_content( $original_wp_export_output );
Why not compare with all content?

2021-02-09 16:54 UTC, iNewLegend commented on core/utils/wp-exporter.php
> + *  Remove filters.
Handled.

2021-02-09 16:54 UTC, iNewLegend commented on core/utils/wp-exporter.php
> +		'status'     => false,
Handled.

2021-02-09 16:54 UTC, iNewLegend commented on tests/phpunit/elementor/core/utils/test-wp-exporter.php
> +		$clean_wp_export_output = $this->remove_non_require_content( $original_wp_export_output );
Handled.

2021-02-09 17:05 UTC, matipojo requested changes
Fix PHPUnit failure.

2021-02-10 10:00 UTC, matipojo requested changes

2021-02-10 10:00 UTC, matipojo commented on core/utils/wp-exporter.php
> +	public function run() {
Move to before private functions.

2021-02-10 10:00 UTC, matipojo commented on core/utils/wp-exporter.php
> +	public function run() {
Add PHPDoc for all methods.

2021-02-12 06:33 UTC, iNewLegend commented on core/utils/wp-exporter.php
> +	public function wxr_posts_list( $post_ids ) {
Handled.

2021-02-12 06:33 UTC, iNewLegend commented on core/utils/wp-exporter.php
> +	public function run() {
Handled.

2021-02-12 06:33 UTC, iNewLegend commented on core/utils/wp-exporter.php
> +	public function run() {
Handled.

2021-02-14 13:56 UTC, matipojo approved these changes, later dismissed

2021-03-16 12:22 UTC, closed without merging