Add `elementor-image` class in Image widget to DOM optimization experiment
elementor/elementor pull request #13915
Opened 2021-02-15 14:46 UTC by arielk

2021-02-15 16:48 UTC, kobizz requested changes

2021-02-15 16:48 UTC, kobizz commented on assets/dev/scss/frontend/widgets/image.scss
> +	a {
This softer selector might allow other selectors to override it. Could you keep it like before?
```
> a,
figure > a
```

2021-02-16 13:37 UTC, kobizz requested changes

2021-02-16 13:37 UTC, kobizz commented on includes/widgets/image.php
> +				var imgClass = '';
This line should be outside of the condition

2021-02-17 08:31 UTC, kobizz requested changes

2021-02-17 08:31 UTC, kobizz commented on includes/widgets/image.php
> +			<?php } ?>
```suggestion
			<?php } ?>
				var imgClass = '';
```

2021-02-17 10:29 UTC, arielk commented on includes/widgets/image.php
> +			<?php } ?>
Fixed: https://github.com/elementor/elementor/pull/13915/commits/c40c6d9c151cd3c73948306b667b9a0e8ef3c689

2021-02-17 10:30 UTC, kobizz approved these changes

2021-02-18 12:39 UTC, merged