Ed 2101 wp export add filter by meta
elementor/elementor pull request #13991
Opened 2021-02-22 14:33 UTC by iNewLegend

Depends on https://github.com/elementor/elementor/pull/13856

2021-02-22 17:57 UTC, matipojo requested changes

2021-02-22 17:57 UTC, matipojo commented on core/utils/wp-exporter.php
> +		'with_meta_key' => '', // If specified `meta_key` then will include all post(s) that have this meta_key.
```suggestion
		'meta_key' => '', // If specified `meta_key` then will include all post(s) that have this meta_key.
```

2021-02-22 17:57 UTC, matipojo commented on core/utils/wp-exporter.php
> +			$join .= "INNER JOIN {$this->wpdb->postmeta} ON ({$this->wpdb->posts}.ID = {$this->wpdb->postmeta}.post_id)";
```suggestion
			$join .= "LEFT JOIN {$this->wpdb->postmeta} ON ({$this->wpdb->posts}.ID = {$this->wpdb->postmeta}.post_id)";
```

2021-02-23 07:16 UTC, iNewLegend commented on core/utils/wp-exporter.php
> +		'with_meta_key' => '', // If specified `meta_key` then will include all post(s) that have this meta_key.
Handled.

2021-02-23 07:16 UTC, iNewLegend commented on core/utils/wp-exporter.php
> +			$join .= "INNER JOIN {$this->wpdb->postmeta} ON ({$this->wpdb->posts}.ID = {$this->wpdb->postmeta}.post_id)";
Handled.

2021-02-23 09:36 UTC, matipojo approved these changes

2021-02-23 09:41 UTC, iNewLegend commented
Handled in https://github.com/elementor/elementor/pull/13856

2021-02-23 09:41 UTC, closed without merging