Lightbox and Screenfull: Tweak - These utilities were loaded by default instead of only when needed - ED-448
elementor/elementor pull request #14012
Opened 2021-02-24 01:05 UTC by rotemee

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2021-02-24 09:39 UTC, kobizz requested changes

2021-02-24 09:39 UTC, kobizz commented on assets/dev/js/frontend/handlers/video.js
> +	async getLightbox() {
Remove this method

2021-02-24 09:39 UTC, kobizz commented on assets/dev/js/frontend/utils/lightbox/lightbox-manager.js
> +	async showLightbox( element ) {
Try moving it to the lightbox itself

2021-02-24 09:39 UTC, kobizz commented on assets/dev/js/frontend/utils/url-actions.js
> +				const lightbox = elementorFrontend.config.experimentalFeatures.e_optimized_assets_loading ?
Always use `await`

2021-02-24 09:41 UTC, kobizz requested changes

2021-02-24 09:41 UTC, kobizz commented on assets/dev/js/frontend/preloaded-modules.js
> +		elementorFrontend.utils.lightbox = new LightboxModule()
```suggestion
		elementorFrontend.utils.lightbox = new LightboxModule();
```

2021-02-24 12:23 UTC, rotemee commented on assets/dev/js/frontend/handlers/video.js
> +	async getLightbox() {
Done.

2021-02-24 12:23 UTC, rotemee commented on assets/dev/js/frontend/utils/lightbox/lightbox-manager.js
> +	async showLightbox( element ) {
Done.

2021-02-24 12:23 UTC, rotemee commented on assets/dev/js/frontend/utils/url-actions.js
> +				const lightbox = elementorFrontend.config.experimentalFeatures.e_optimized_assets_loading ?
Done.

2021-02-24 12:23 UTC, rotemee commented on assets/dev/js/frontend/preloaded-modules.js
> +		elementorFrontend.utils.lightbox = new LightboxModule()
Done.

2021-02-25 08:16 UTC, kobizz approved these changes

2021-02-28 08:25 UTC, iNewLegend requested changes

2021-02-28 08:25 UTC, iNewLegend commented on assets/dev/js/frontend/utils/lightbox/lightbox.js
> +		const initialSlideURL = element.dataset.elementorLightboxVideo ? element.dataset.elementorLightboxVideo : element.href;
```suggestion
		const initialSlideURL = element.dataset.elementorLightboxVideo || element.href;
```

2021-03-01 11:21 UTC, rotemee commented on assets/dev/js/frontend/utils/lightbox/lightbox.js
> +		const initialSlideURL = element.dataset.elementorLightboxVideo ? element.dataset.elementorLightboxVideo : element.href;
Fixed.

2021-03-01 11:57 UTC, kobizz approved these changes

2021-03-11 10:03 UTC, merged