Font Display Options: Tweak - Allowing to set a font-display value to Google Fonts - ED-2070
elementor/elementor pull request #14064
Opened 2021-02-28 17:45 UTC by rotemee

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2021-02-28 18:08 UTC, matipojo requested changes

2021-02-28 18:08 UTC, matipojo commented on includes/settings/settings.php
> +										'default' => __( 'Default (by default - auto)', 'elementor' ),
Why not use `'std' => 'auto',`?

2021-02-28 18:08 UTC, matipojo commented on includes/fonts.php
> +		return get_option( 'elementor_font_display' );
```suggestion
		return get_option( 'elementor_font_display', 'auto' );
```

2021-03-01 15:17 UTC, rotemee commented on includes/fonts.php
> +		return get_option( 'elementor_font_display' );
Fixed.

2021-03-01 15:58 UTC, kobizz approved these changes

2021-03-15 08:18 UTC, merged