Document: Fix - User can send unsafe settings.
elementor/elementor pull request #14065
Opened 2021-02-28 19:18 UTC by matipojo

2021-02-28 20:21 UTC, rodolphebertozzo requested changes

2021-02-28 20:21 UTC, rodolphebertozzo commented on core/base/document.php
> +			if ( Controls_Manager::SELECT !== $control_config['type'] && Controls_Manager::SELECT2  !== $control_config['type'] ) {
```suggestion
			if ( Controls_Manager::SELECT !== $control_config['type'] && Controls_Manager::SELECT2 !== $control_config['type'] ) {
```

2021-03-01 13:14 UTC, kobizz requested changes

2021-03-01 13:14 UTC, kobizz commented on core/base/document.php
> +	private function validate_elements_settings( array $elements ) {
Please make it a general loop so we can use it for other purposes (such as saving assets used by the page)

2021-03-01 13:14 UTC, kobizz commented on core/base/document.php
> +	private function validate_controls( array $settings, array $controls ) {
It's better to add a method inside the control class for validating saved values

2021-03-02 07:41 UTC, kobizz approved these changes

2021-03-02 07:41 UTC, merged