Tests/QUnit: Fix - Parents/modules/tests names. ED-2262
elementor/elementor pull request #14331
Opened 2021-03-22 19:40 UTC by iNewLegend

Depends on https://github.com/elementor/elementor/pull/14329

2021-04-12 10:49 UTC, StyleShit requested changes

2021-04-12 14:16 UTC, iNewLegend commented on tests/qunit/tests/assets/dev/js/editor/document/elements/component.spec.js
> +	//
@StyleShit @matipojo, the problem with that test that `resizeColumn` is based on a `div` with class name `elementor-container` which created in the backend to fix the issue we need to add a new mechanism to simulate it.

2021-04-12 14:17 UTC, iNewLegend commented on tests/screenshotter/backstop.js
>  			onBeforeScript: `${ __dirname }/scripts/on-before-ready.js`,
Handled.

2021-04-12 14:21 UTC, iNewLegend commented on tests/qunit/tests/core/common/assets/js/api/core/commands.spec.js
> +				}
Handled.

2021-04-12 14:22 UTC, iNewLegend commented on tests/qunit/tests/core/common/assets/js/api/core/commands.spec.js
> +				},
Handled.

2021-04-13 05:07 UTC, StyleShit approved these changes
LGTM

2021-05-23 07:23 UTC, Nevoss requested changes
Change the PR name to adjust to the new convention.
something like: `FIx: Tests/QUnit -  Parents/modules/tests names [ED-2262]`

2021-05-23 08:50 UTC, matipojo requested changes
Please pull from 3.3.0

2021-05-24 18:06 UTC, merged