Feature/2505 add browser classes to admin area
elementor/elementor pull request #14414
Opened 2021-04-04 12:56 UTC by nisan250

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2021-04-05 16:16 UTC, Nevoss requested changes
Maybe this feature should be on the editor as well? and not only on the admin side

2021-04-05 16:16 UTC, Nevoss commented on assets/dev/js/admin/admin.js
> +			}
```suggestion
Object.entries( environment ).forEach(([key, value]) => {
	if (! value) {
		return;
	}

	elementorCommon.elements.$body.classList.add( 'e--ua-' + key )
});
```

2021-04-06 07:21 UTC, nisan250 commented on assets/dev/js/admin/admin.js
> +			}
Done

2021-04-13 11:57 UTC, matipojo approved these changes

2021-04-13 11:57 UTC, merged