Fix: Kit/Manager - Prevent default kit from being reset when site cache. (ED-2396)
elementor/elementor pull request #14599
Opened 2021-04-18 16:13 UTC by nisan250

2021-04-21 12:20 UTC, StyleShit approved these changes
LGTM

2021-04-29 14:13 UTC, matipojo requested changes

2021-04-29 14:13 UTC, matipojo commented on core/kits/manager.php
> +		$id = get_option( self::OPTION_ACTIVE, null );
Why?

2021-05-30 12:51 UTC, matipojo requested changes

2021-05-30 12:51 UTC, matipojo commented on core/upgrade/upgrades.php
> +		$id = get_option( 'elementor_active_kit', null );
```suggestion
		$id = get_option( 'elementor_active_kit' );
```

2021-05-30 12:51 UTC, matipojo commented on core/upgrade/upgrades.php
> +		if ( ! $id ) {
```suggestion
		if ( $id ) {
```

2021-05-30 12:51 UTC, matipojo commented on core/upgrade/upgrades.php
> +			$wpdb->query( $wpdb->prepare( "UPDATE $wpdb->options SET autoload='no' WHERE option_name=%d", 'elementor_active_kit' ) );
```suggestion
			$wpdb->query( $wpdb->prepare( "UPDATE $wpdb->options SET autoload='no' WHERE option_name='elementor_active_kit'" ) );
```

2021-05-30 12:51 UTC, matipojo commented on core/upgrade/upgrades.php
> +
Add a test for it.

2021-05-31 11:15 UTC, matipojo commented
According to @KingYes it should be solved in another approach

2021-05-31 11:15 UTC, closed without merging