New: Kit-Library - Favorites
elementor/elementor pull request #14650
Opened 2021-04-22 07:57 UTC by Nevoss

ref: ED-2598

2021-04-25 06:06 UTC, StyleShit requested changes
Nice work! 😄

2021-04-25 06:06 UTC, StyleShit commented on core/app/modules/kit-library/data/repository.php
> +use Elementor\Core\App\Modules\KitLibrary\Data\Exceptions\Kit_Not_Found_Exception;
```suggestion
use Elementor\Core\App\Modules\KitLibrary\Data\Exceptions\Kit_Not_Found_Exception;
use Elementor\Core\Utils\Collection;
```

2021-04-25 06:06 UTC, StyleShit commented on core/app/modules/kit-library/data/repository.php
> +use Elementor\Core\App\Modules\KitLibrary\Data\Exceptions\Kit_Not_Found_Exception;
Ordered alphabetically.

2021-04-25 06:06 UTC, StyleShit commented on core/app/modules/kit-library/data/repository.php
> +	public function add_to_favorite( $user_id, $id ) {
```suggestion
	public function add_to_favorites( $user_id, $id ) {
```

2021-04-25 06:06 UTC, StyleShit commented on core/app/modules/kit-library/data/repository.php
> +	public function remove_from_favorite( $user_id, $id ) {
```suggestion
	public function remove_from_favorites( $user_id, $id ) {
```

2021-04-25 07:34 UTC, StyleShit approved these changes
LGTM

2021-05-02 12:33 UTC, matipojo requested changes

2021-05-02 12:33 UTC, matipojo commented on core/app/modules/kit-library/assets/js/hooks/use-kit-favorites-mutations.js
> +		queryClient.invalidateQueries( [ kitKey, data.data.id ] );
Explain

2021-05-02 12:33 UTC, matipojo commented on core/app/modules/kit-library/assets/js/pages/index/index-sidebar.js
> +				onClick={ () => ! props.filter.favorite && props.onChange( {
Use a route + current route

2021-05-02 12:33 UTC, matipojo commented on core/app/modules/kit-library/assets/js/pages/index/index.js
> +							isSuccess && data.length <= 0 &&
```suggestion
							isSuccess && ! data.length &&
```

2021-05-02 12:33 UTC, matipojo commented on core/app/modules/kit-library/assets/js/pages/overview/overview.js
> +			sidebar={ <OverviewSidebar model={ kit } groupedKitContent={ documentsByType } isLoading={ isFetching } /> }
```suggestion
			sidebar={ <OverviewSidebar model={ kit } groupedKitContent={ documentsByType } isFetching ={ isFetching } /> }
```

2021-05-02 12:33 UTC, matipojo commented on core/app/modules/kit-library/data/repository.php
> +	public function find( $id, $user_id = null, $manifest_included = true ) {
```suggestion
	public function find( $id, $user_id = null, $options = [] ) {
```

2021-05-02 12:33 UTC, matipojo commented on core/app/modules/kit-library/data/repository.php
> +		}
Remove

2021-05-02 12:33 UTC, matipojo commented on includes/template-library/sources/local.php
> +		};
Remove

2021-05-03 14:34 UTC, matipojo requested changes

2021-05-03 14:34 UTC, matipojo commented on core/app/modules/kit-library/data/repository.php
> +	}
Can you re-use the similar existing method?
https://github.com/elementor/elementor/blob/31629fa3b3b45b58356208102016a8406d21a7eb/includes/template-library/sources/base.php#L190-L204

2021-05-05 13:29 UTC, matipojo requested changes

2021-05-05 13:29 UTC, matipojo commented on core/app/modules/kit-library/data/kits/endpoints/favorites.php
> +			$kit = $repository->add_to_favorites( $id );
$kit or success?

2021-05-05 13:29 UTC, matipojo commented on core/app/modules/kit-library/data/repository.php
> +			throw new Wp_Error_Exception(
A `find` method should throw an error?

2021-05-05 13:29 UTC, matipojo commented on core/app/modules/kit-library/data/repository.php
> +		$this->user_favorites->add( 'elementor', 'kits', $kit['id'] );
```suggestion
		$success = $this->user_favorites->add( 'elementor', 'kits', $kit['id'] );
```

2021-05-05 13:29 UTC, matipojo commented on core/app/modules/kit-library/data/repository.php
> +				'is_favorite' => in_array( $kit->_id, $favorites, true ),
```suggestion
				'is_favorite' => $this->is_favorite( $kit ),
```

2021-05-05 13:29 UTC, matipojo commented on modules/library/user-favorites.php
> +		update_user_meta( $this->user_id, self::USER_META_KEY, $all_favorites );
```suggestion
		$success = update_user_meta( $this->user_id, self::USER_META_KEY, $all_favorites );
		
		if ( $success ) ...
```
Here and all methods should return a bool (success/failed)

2021-05-09 15:01 UTC, matipojo requested changes

2021-05-09 15:01 UTC, matipojo commented on modules/library/user-favorites.php
> +			throw new \Exception( 'Failed to save user favorites.' );
Translate

2021-05-09 15:55 UTC, matipojo approved these changes

2021-05-11 14:51 UTC, matipojo approved these changes

2021-05-11 14:52 UTC, merged