Tweak: Kit-Library - Sorting
elementor/elementor pull request #14737
Opened 2021-04-27 15:32 UTC by Nevoss

ref: ED-2597

2021-04-29 09:56 UTC, StyleShit requested changes

2021-04-29 09:56 UTC, StyleShit commented on core/app/modules/kit-library/assets/js/components/kit-list.js
> +		<CssGrid spacing={ 24 } colMinWidth={ 250 } >
Redundant space

2021-04-29 09:56 UTC, StyleShit commented on core/app/modules/kit-library/assets/js/pages/index/index.scss
> +		}
Maybe combine the `min-width` so when someone in the future will change this property, he won't need to go and search for the second occurrence, both of them will get changed.

2021-04-29 11:39 UTC, StyleShit commented on core/app/modules/kit-library/assets/js/pages/index/index.scss
> +		}
```CSS
		&-search,
		&-sort {
			min-width: 265px;
		}

		&-search {
			flex: 1;
		}

		&-sort--safari-support {
			@include margin-start( spacing( 24 ) );
		}
```

2021-04-29 11:46 UTC, StyleShit approved these changes

2021-05-02 12:40 UTC, matipojo requested changes

2021-05-02 12:40 UTC, matipojo commented on core/app/assets/js/ui/molecules/search-input.scss
> +	height: 42px;
Use an existing unit.

2021-05-02 12:40 UTC, matipojo commented on core/app/assets/js/ui/organisims/sort-select.scss
> +		height: 42px;
As above

2021-05-02 12:40 UTC, matipojo commented on core/app/modules/kit-library/assets/js/hooks/use-kits.js
> +function sortData( item1, item2, sortValue ) {
Move up

2021-05-02 12:40 UTC, matipojo commented on core/app/modules/kit-library/assets/js/models/kit.js
> +			updatedAt: kit.updated_at ? new Date( kit.updated_at ) : null,
Add TODO to remove on the API is stable

2021-05-02 12:40 UTC, matipojo commented on core/app/modules/kit-library/assets/js/pages/index/index.js
> +								{ label: 'Trending', value: 'trendIndex' },
Add a translations test.

2021-05-02 12:40 UTC, matipojo commented on core/app/modules/kit-library/data/repository.php
> +				'updated_at' => isset( $kit->updated_at ) ? $kit->updated_at : null,
TODO

2021-05-16 11:32 UTC, matipojo approved these changes

2021-05-16 11:33 UTC, merged