Fix: Panel search bar appeared above the loader (ED-2787)
elementor/elementor pull request #14776
Opened 2021-05-02 08:51 UTC by StyleShit

2021-05-23 07:26 UTC, Nevoss approved these changes

2021-05-27 15:33 UTC, matipojo requested changes

2021-05-27 15:33 UTC, matipojo commented on assets/dev/scss/editor/panel/_elements.scss
> +		z-index: 2;
Please use `$second-layer`

2021-05-27 15:33 UTC, matipojo requested changes
Pull from 3.3.0

2021-05-30 04:51 UTC, StyleShit commented on assets/dev/scss/editor/panel/_elements.scss
> +		z-index: 2;
Done.

2021-05-30 15:08 UTC, matipojo approved these changes

2021-05-30 15:09 UTC, merged