Tweak: System Info - New experiments reporter.
elementor/elementor pull request #14800
Opened 2021-05-03 16:40 UTC by iNewLegend

2021-05-20 16:20 UTC, matipojo requested changes
Please update the JSON schema.

2021-05-21 03:00 UTC, iNewLegend commented
@matipojo
> Please update the JSON schema.

it was updated here: https://github.com/elementor/elementor/pull/13406/

this only log reporter see https://github.com/elementor/elementor/pull/14800/files#diff-b21c1bcebdf04abc54e1aeaf2161eafb86bb97d211ebb58f1105d160b3abdb24R68-R75

2021-07-01 11:39 UTC, matipojo requested changes
Please pull from 3.4.0

2021-07-07 18:07 UTC, matipojo requested changes

2021-07-07 18:07 UTC, matipojo commented on core/experiments/manager.php
> +	 * @since 3.3.0
3.4.0

2021-07-07 18:07 UTC, matipojo commented on includes/tracker.php
> +		$reports = Plugin::$instance->system_info->load_reports( System_Info\Main::get_allowed_tracked_reports() );
Replace all `tracked` with `usage`

2021-07-08 09:00 UTC, iNewLegend commented on core/experiments/manager.php
> +	 * @since 3.3.0
Handled.

2021-07-08 09:00 UTC, iNewLegend commented on includes/tracker.php
> +		$reports = Plugin::$instance->system_info->load_reports( System_Info\Main::get_allowed_tracked_reports() );
Handled.

2021-07-08 15:55 UTC, matipojo approved these changes

2021-07-08 15:56 UTC, matipojo requested changes
Please pull from develop

2021-08-23 07:37 UTC, StyleShit requested changes

2021-08-23 07:37 UTC, StyleShit commented on modules/system-info/reporters/experiments.php
> +		return 'Elementor Experiments';
```suggestion
		return esc_html__( 'Elementor Experiments', 'elementor' );
```

2021-08-23 07:37 UTC, StyleShit commented on modules/system-info/reporters/experiments.php
> +			$output .= '<tr><td>' . $experiment['title'] . ': </td>';
It should be escaped?
```suggestion
			$output .= '<tr><td>' . esc_html( $experiment['title'] ) . ': </td>';
```

2021-08-23 08:05 UTC, iNewLegend commented on modules/system-info/reporters/experiments.php
> +		return 'Elementor Experiments';
done.

2021-08-23 08:05 UTC, iNewLegend commented on modules/system-info/reporters/experiments.php
> +			$output .= '<tr><td>' . $experiment['title'] . ': </td>';
done.

2021-08-23 09:10 UTC, StyleShit requested changes

2021-08-23 09:10 UTC, StyleShit commented on modules/system-info/reporters/experiments.php
> +		return 'Elementor Experiments';
I don't see the change

2021-08-23 10:45 UTC, StyleShit approved these changes

2021-10-07 15:38 UTC, matipojo requested changes

2021-10-12 15:15 UTC, matipojo requested changes

2021-10-12 15:15 UTC, matipojo requested changes
PHP Lint

2021-10-13 05:59 UTC, merged