Core/Document: New - Filter before save, to manipulation of  data. ED-3102
elementor/elementor pull request #14824
Opened 2021-05-05 11:00 UTC by iNewLegend

2021-05-16 11:35 UTC, matipojo requested changes

2021-05-16 11:35 UTC, matipojo commented on core/base/document.php
> +		$data = apply_filters( 'elementor/document/get_data', $data, $this );
```suggestion
		$data = apply_filters( 'elementor/document/save/data', $data, $this );
```

2021-05-19 07:15 UTC, iNewLegend commented on core/base/document.php
> +		$data = apply_filters( 'elementor/document/get_data', $data, $this );
Handled.

2021-05-19 14:49 UTC, matipojo requested changes

2021-05-19 16:43 UTC, iNewLegend commented on core/base/document.php
> +		 *
Handled.

2021-05-20 15:20 UTC, merged