Fix: Kit-Library - Taxonomies new API scheme [ED-3143]
elementor/elementor pull request #14864
Opened 2021-05-09 16:05 UTC by Nevoss

ref: ED-3143

2021-05-10 05:07 UTC, StyleShit requested changes
LGTM :D

2021-05-10 05:07 UTC, StyleShit commented on core/utils/collection.php
> +		});
```suggestion
		} );
```
Sorry, OCD...

2021-05-10 07:08 UTC, StyleShit approved these changes

2021-05-11 14:59 UTC, matipojo approved these changes

2021-05-11 15:00 UTC, merged