Fix: PHP Lint errors. [ED-3163] [ED-2901]
elementor/elementor pull request #14883
Opened 2021-05-10 13:37 UTC by StyleShit

2021-05-10 14:33 UTC, iNewLegend requested changes

2021-05-10 14:35 UTC, StyleShit commented on includes/utils.php
> +		'a',
That's necessary as a dependency for the Pro PR.

2021-05-10 14:42 UTC, iNewLegend approved these changes

2021-05-11 15:56 UTC, matipojo approved these changes

2021-05-11 15:57 UTC, merged