Tweak: Hidden Elements Behavior - Add the ability to select hidden elements behavior [ED-2963]
elementor/elementor pull request #14901
Opened 2021-05-11 11:17 UTC by guyc-E

…ments behvior

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2021-05-12 13:39 UTC, udidol requested changes

2021-05-12 13:39 UTC, udidol commented on assets/dev/js/editor/components/settings/editor-preferences/manager.js
> +		elementor.on( 'globals:loaded', this.OnShowHiddenElementsChange );
Don't run this here, add the appropriate classes where body classes for the Preview section are added.

2021-05-18 12:35 UTC, udidol requested changes

2021-05-18 12:35 UTC, udidol commented on includes/frontend.php
> +
This should only happen in the Editor, not in the frontend.
Try adding a check for `Plugin::$instance->editor->is_edit_mode()`

2021-05-18 13:24 UTC, udidol commented on includes/frontend.php
> +		if( $is_preview_mode ){
```suggestion
		if( Plugin::$instance->preview->is_preview_mode() ){
```

2021-05-18 13:49 UTC, udidol approved these changes

2021-05-25 07:00 UTC, kobizz requested changes

2021-05-25 09:32 UTC, guyc-E commented on assets/dev/js/editor/components/settings/editor-preferences/manager.js
> +			show_hidden_elements: this.OnShowHiddenElementsChange,
I think you forgot to change your suggested code. it looks exactly the same

2021-05-26 08:57 UTC, kobizz requested changes

2021-05-26 08:57 UTC, kobizz commented on assets/dev/js/editor/components/settings/editor-preferences/manager.js
> +		elementor.$previewContents.find( 'body' ).toggleClass( 'e-preview--show-hidden-elements' );
Use `elementorFrontend.elements.$body` instead

2021-05-30 07:51 UTC, kobizz approved these changes

2021-05-30 07:52 UTC, merged