Hotfix: PHP Lint - Security Linter
elementor/elementor pull request #14948
Opened 2021-05-14 10:08 UTC by guyc-E

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2021-05-14 10:17 UTC, guyc-E commented
Lint / PHP-Lint (pull_request) - Fails on files I didn't changed.

2021-06-03 13:25 UTC, kobizz requested changes

2021-06-03 13:25 UTC, kobizz commented on modules/library/traits/library.php
> +		//PHPCS - Not user input
```suggestion
		//PHPCS - Not a user input
```

2021-06-03 13:25 UTC, kobizz commented on modules/library/traits/library.php
> +		printf( '<a href="%s">%s</a>', esc_url( $admin_filter_url ), $this->get_title() ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
You don't need to escape this url

2021-06-17 08:39 UTC, kobizz approved these changes

2021-06-17 09:35 UTC, matipojo commented on phpcs.xml
> -		<exclude name="WordPress.CSRF.NonceVerification.NoNonceVerification" />
It's OK the final rules will be set later.

2021-06-17 09:45 UTC, merged