New: Eslint - elementor plugin [ED-3235]
elementor/elementor pull request #15055
Opened 2021-05-23 11:43 UTC by Nevoss

2021-05-23 13:06 UTC, iNewLegend approved these changes

2021-05-23 13:36 UTC, matipojo requested changes

2021-05-23 13:36 UTC, matipojo commented on package.json
> +		"@elementor/eslint-plugin-elementor": "^0.3.0",
```suggestion
		"@elementor/eslint-plugin": "^0.3.0",
```

2021-05-24 16:56 UTC, matipojo approved these changes

2021-05-24 16:58 UTC, merged