Tweak: Widgets search accepts non-english strings [ED-3145]
elementor/elementor pull request #15050
Opened 2021-05-23 05:03 UTC by StyleShit

2021-05-23 10:33 UTC, matipojo requested changes

2021-05-23 10:33 UTC, matipojo commented on assets/dev/js/editor/regions/panel/pages/elements/views/search.js
> +		'keyup @ui.input': 'onInputChanged',
Try to paste, instead of typing.

2021-05-23 11:56 UTC, StyleShit commented on assets/dev/js/editor/regions/panel/pages/elements/views/search.js
> +		'keyup @ui.input': 'onInputChanged',
See #15056

2021-05-23 13:50 UTC, matipojo commented on assets/dev/js/editor/regions/panel/pages/elements/views/search.js
> +		'keyup @ui.input': 'onInputChanged',
Try with the mouse context menu.

2021-05-24 05:23 UTC, StyleShit commented on assets/dev/js/editor/regions/panel/pages/elements/views/search.js
> +		'keyup @ui.input': 'onInputChanged',
@matipojo 
See #15062

2021-05-27 15:06 UTC, matipojo approved these changes

2021-05-27 15:28 UTC, merged