Fix: Setting zero offset in sticky motion effects not working properly [ED-3514]
elementor/elementor pull request #15191
Opened 2021-06-03 05:26 UTC by StyleShit

The value was parsed as a integer instead of string. Therefore, it was considered an empty value.

2021-06-03 09:00 UTC, ItzhakAvm approved these changes

2021-06-03 16:53 UTC, matipojo requested changes

2021-06-06 05:09 UTC, StyleShit commented on assets/dev/js/frontend/frontend.js
> +		const handlers = {
That's the eslint auto-fix probably. Fixed :)

2021-06-14 16:27 UTC, matipojo approved these changes

2021-07-21 15:30 UTC, merged