Fix: Kits - Prevent recreate kit when kit not exists. [ED-2394]
elementor/elementor pull request #15224
Opened 2021-06-06 11:38 UTC by Nevoss

2021-06-09 05:01 UTC, StyleShit commented on assets/dev/js/editor/editor-base.js
> +			message: __( 'Seems like your kit was deleted, please create new one.' ),
```suggestion
			message: __( 'Seems like your kit was deleted, please create new one.', 'elementor' ),
```

2021-06-09 05:16 UTC, StyleShit requested changes

2021-06-09 05:16 UTC, StyleShit commented on assets/dev/js/editor/editor-base.js
> +			message: __( 'Seems like your kit was deleted, please create new one.' ),
```suggestion
			message: __( 'Seems like your kit was deleted, please create new one.', 'elementor' ),
```

2021-06-09 05:16 UTC, StyleShit commented on tests/phpunit/base-class.php
> +use Elementor\Core\Kits\Manager;
```suggestion
use Elementor\Core\Kits\Manager;
use Elementor\Core\Wp_Api;
```

2021-06-09 05:17 UTC, StyleShit commented
Nice Work :)
I would add some PHPDoc for fun 😛

2021-06-09 05:18 UTC, StyleShit commented on tests/phpunit/base-class.php
> +use Elementor\Core\Kits\Manager;
A-Z

2021-06-09 07:14 UTC, Nevoss commented on assets/dev/js/editor/editor-base.js
> +			message: __( 'Seems like your kit was deleted, please create new one.' ),
Nice Catch!

2021-06-09 07:18 UTC, Nevoss commented on assets/dev/js/editor/editor-base.js
> +			message: __( 'Seems like your kit was deleted, please create new one.' ),
Done

2021-06-09 07:19 UTC, Nevoss commented on tests/phpunit/base-class.php
> +use Elementor\Core\Kits\Manager;
Done

2021-06-09 07:32 UTC, StyleShit approved these changes

2021-06-09 16:06 UTC, matipojo requested changes
Please resolve the conflict

2021-06-09 16:06 UTC, matipojo commented on tests/phpunit/elementor/core/utils/test-wp-import.php
> +		$this->remove_default_kit();
Explain

2021-06-09 16:06 UTC, matipojo commented on tests/phpunit/elementor/core/utils/test-wp-exporter.php
> +		$this->remove_default_kit();
Exaplain

2021-06-10 06:16 UTC, Nevoss commented on assets/dev/js/editor/editor-base.js
> +			headerMessage: __( 'Your site doesn’t have a default kit', 'elementor' ),
Done

2021-06-10 06:19 UTC, Nevoss commented on assets/dev/js/editor/editor-base.js
> +			message: __( 'Seems like your kit was deleted, please create new one.', 'elementor' ),
Done

2021-06-10 06:24 UTC, Nevoss commented on tests/phpunit/elementor/core/utils/test-wp-exporter.php
> +		$this->remove_default_kit();
Done

2021-06-10 06:24 UTC, Nevoss commented on tests/phpunit/elementor/core/utils/test-wp-import.php
> +		$this->remove_default_kit();
Done

2021-06-10 16:05 UTC, merged