Tweak: Controls System Optimization (ED-3378)
elementor/elementor pull request #15247
Opened 2021-06-07 16:05 UTC by udidol

2021-06-17 09:50 UTC, kobizz requested changes

2021-06-17 09:50 UTC, kobizz commented on core/breakpoints/manager.php
> +	 * @access public
```suggestion
	 * @access private
```

2021-06-17 09:50 UTC, kobizz commented on core/breakpoints/manager.php
> +	public function get_breakpoints_config() {
Add doc

2021-06-17 09:50 UTC, kobizz commented on core/experiments/manager.php
> +							. '<br /><strong>' . __( 'Please note! Conditioning controls on values of responsive controls is not supported when this mode is active.', 'elementor' ) . '</strong>',
Use `esc_html__` for translations

2021-06-20 10:35 UTC, udidol commented on core/experiments/manager.php
> +							. '<br /><strong>' . __( 'Please note! Conditioning controls on values of responsive controls is not supported when this mode is active.', 'elementor' ) . '</strong>',
Done.

2021-06-20 10:35 UTC, udidol commented on core/breakpoints/manager.php
> +	public function get_breakpoints_config() {
Done.

2021-06-20 10:35 UTC, udidol commented on core/breakpoints/manager.php
> +	 * @access public
Done.

2021-06-22 13:06 UTC, kobizz requested changes

2021-06-22 13:06 UTC, kobizz commented on includes/editor-templates/panel.php
> +				var deviceLabel = 'desktop' === device ? elementor.config.responsive.desktop_label : activeBreakpoints[ device ].label,
```suggestion
				var deviceLabel = 'desktop' === device ? '<?php echo __( 'Desktop', 'elementor' ); ?>': activeBreakpoints[ device ].label,
```

2021-06-22 13:06 UTC, kobizz commented on core/editor/editor.php
> +				'desktop_label' => __( 'Desktop', 'elementor' ),
You don't need this variable. See below

2021-06-22 13:48 UTC, udidol commented on core/editor/editor.php
> +				'desktop_label' => __( 'Desktop', 'elementor' ),
Done.

2021-06-22 13:48 UTC, udidol commented on includes/editor-templates/panel.php
> +				var deviceLabel = 'desktop' === device ? elementor.config.responsive.desktop_label : activeBreakpoints[ device ].label,
Done.

2021-06-22 13:48 UTC, udidol commented on assets/dev/scss/editor/_responsive-bar.scss
> +i.eicon-tilted {
Done.

2021-06-22 13:48 UTC, udidol commented on assets/dev/scss/direction/editor-dark-mode.scss
> +$devices: 'widescreen', 'desktop', 'laptop', 'tablet_extra', 'tablet', 'mobile_extra', 'mobile';
Done.

2021-06-22 15:07 UTC, merged