Tweak: Added option to define unlinked values that are not 0 in the dimensions control [ED-3542]
elementor/elementor pull request #15325
Opened 2021-06-13 11:34 UTC by ItzhakAvm

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2021-06-14 15:53 UTC, nisan250 approved these changes

2021-06-21 10:37 UTC, matipojo approved these changes

2021-06-22 07:26 UTC, kobizz requested changes

2021-06-22 07:26 UTC, kobizz commented on assets/dev/js/editor/controls/dimensions.js
> -		var dimensions = this.getPossibleDimensions(),
If you remove this functionality you should also remove the entire linked/unlinked functionality and markup

2021-06-24 08:49 UTC, kobizz commented on assets/dev/js/editor/controls/dimensions.js
> -		var dimensions = this.getPossibleDimensions(),
It causes a bug: Inside widget go to Advanced -> Padding, unlink the dimensions and change one of the fields. It won't work

2021-06-24 13:15 UTC, kobizz requested changes

2021-06-24 13:15 UTC, kobizz commented on assets/dev/js/editor/controls/dimensions.js
> -		var dimensions = this.getPossibleDimensions(),
It causes a bug: Inside widget go to Advanced -> Padding, unlink the dimensions and change one of the fields. It won't work

2021-06-28 16:07 UTC, closed without merging