Tweak: Docs - Container element [ED-3809]
elementor/elementor pull request #15400
Opened 2021-06-17 12:08 UTC by StyleShit

2021-06-17 16:20 UTC, Nevoss approved these changes

2021-06-17 18:32 UTC, matipojo requested changes

2021-06-17 18:32 UTC, matipojo commented on docs/core/container-element.md
> +The main one is the DnD aspect. DnD-ing into a `flex container` is a real challenge by itself, and when you add the fact that you need to support the old existing DnD mechanism, it becomes a huge pai
Language!

2021-06-17 18:32 UTC, matipojo commented on docs/core/container-element.md
> +The main one is the DnD aspect. DnD-ing into a `flex container` is a real challenge by itself, and when you add the fact that you need to support the old existing DnD mechanism, it becomes a huge pai
```suggestion
The main one is the DnD (Drag & Drop) aspect. DnD-ing into a `flex container` is a real challenge by itself, and when you add the fact that you need to support the old existing DnD mechanism, it becomes a huge pain in the a**.
```

2021-06-17 18:32 UTC, matipojo commented on docs/core/container-element.md
> +- How do you even resize a `flex item`?
```suggestion
- How do you even resize a `flex item` if there are some calculations like grow/shrink?
```

2021-06-20 05:09 UTC, StyleShit commented on docs/core/container-element.md
> +The main one is the DnD aspect. DnD-ing into a `flex container` is a real challenge by itself, and when you add the fact that you need to support the old existing DnD mechanism, it becomes a huge pai
Done

2021-06-20 05:09 UTC, StyleShit commented on docs/core/container-element.md
> +The main one is the DnD aspect. DnD-ing into a `flex container` is a real challenge by itself, and when you add the fact that you need to support the old existing DnD mechanism, it becomes a huge pai
Done 😅

2021-06-20 05:10 UTC, StyleShit commented on docs/core/container-element.md
> +- How do you even resize a `flex item`?
Done.

2021-06-20 05:12 UTC, StyleShit commented on docs/core/container-element.md
> +- How do you even resize a `flex item`?
BTW, the file name/path are ok?

2021-06-20 07:03 UTC, matipojo commented on docs/core/container-element.md
> +- How do you even resize a `flex item`?
It should mirror the original file

2021-06-21 16:59 UTC, matipojo requested changes
Move to the `container` branch

2021-11-09 12:17 UTC, merged