JS API/Docs/Extras/HashCommands: New - Documentation. [ED-3806]
elementor/elementor pull request #15401
Opened 2021-06-17 12:21 UTC by iNewLegend

2021-06-17 16:19 UTC, Nevoss approved these changes

2021-06-17 18:08 UTC, matipojo requested changes

2021-06-17 18:08 UTC, matipojo commented on docs/core/common/assets/js/api/core/extras/hash-commands.md
> +    `http://localhost/wp-admin/post.php?post=1&action=elementor#e:run:panel/global/open&panel/history/revisions`
```suggestion
    `http://localhost/wp-admin/post.php?post=1&action=elementor#e:run:panel/global/open&e:route:panel/history/revisions`
```

2021-07-29 14:25 UTC, matipojo approved these changes

2021-07-29 14:26 UTC, merged