Fix: Recreate kit button is not showing when deleting default kit [ED-3843]
elementor/elementor pull request #15420
Opened 2021-06-20 14:17 UTC by Nevoss

2021-06-20 14:29 UTC, matipojo approved these changes

2021-06-20 14:30 UTC, matipojo requested changes

2021-06-20 14:30 UTC, matipojo commented on includes/settings/tools.php
> +		if ( ! Plugin::$instance->kits_manager->get_active_kit()->get_id() ) {
Tests?

2021-06-22 09:33 UTC, Nevoss commented on includes/settings/tools.php
> +		if ( ! Plugin::$instance->kits_manager->get_active_kit()->get_id() ) {
Done

2021-06-22 16:28 UTC, matipojo approved these changes

2021-06-22 16:29 UTC, merged