Tweak: Breakpoints Manager Unit test
elementor/elementor pull request #15465
Opened 2021-06-24 14:05 UTC by udidol

Removed Redundant `add_feature` call from a Breakpoints Manager Unit test.

2021-06-30 09:57 UTC, rodolphebertozzo commented
Please, see : https://github.com/elementor/elementor/issues/15473

2021-07-08 09:56 UTC, kobizz requested changes

2021-07-08 09:56 UTC, kobizz commented on assets/dev/scss/frontend/_devices.scss
> +			content: 'tablet-extra';
```suggestion
			content: 'tablet_extra';
```

2021-07-08 09:56 UTC, kobizz commented on assets/dev/scss/frontend/_devices.scss
> +			content: 'mobile-extra';
```suggestion
			content: 'mobile_extra';
```

2021-07-08 09:56 UTC, kobizz commented on core/breakpoints/manager.php
> +		$additional_breakpoints = [ 'mobile_extra', 'tablet_extra', 'laptop', 'widescreen' ];
Use constants

2021-07-08 09:56 UTC, kobizz commented on assets/dev/scss/helpers/variables.scss
> +		widescreen: 2400px
Check if we need these new variables

2021-07-08 10:00 UTC, kobizz requested changes

2021-07-08 10:00 UTC, kobizz commented on core/responsive/files/frontend.php
> +				}
Fix PHP-Lint

2021-07-08 14:16 UTC, udidol commented on assets/dev/scss/frontend/_devices.scss
> +			content: 'tablet-extra';
Done.

2021-07-08 14:17 UTC, udidol commented on assets/dev/scss/frontend/_devices.scss
> +			content: 'mobile-extra';
Done.

2021-07-08 14:17 UTC, udidol commented on core/breakpoints/manager.php
> +		$additional_breakpoints = [ 'mobile_extra', 'tablet_extra', 'laptop', 'widescreen' ];
Done.

2021-07-08 14:17 UTC, udidol commented on assets/dev/scss/helpers/variables.scss
> +		widescreen: 2400px
Seems we don't. Removed.

2021-07-08 14:17 UTC, udidol commented on core/responsive/files/frontend.php
> +				}
Done.

2021-07-15 13:38 UTC, merged