JS API/HashCommands: Tweak - Run commands sequentially. [ED-3828]
elementor/elementor pull request #15503
Opened 2021-06-27 17:47 UTC by iNewLegend

2021-06-27 18:48 UTC, iNewLegend commented on core/common/assets/js/api/extras/hash-commands.js
> +		// To allow validate the method without creating promise.
Promise should be rejected.

2021-06-28 13:54 UTC, Nevoss approved these changes
Nice work!

2021-07-01 08:57 UTC, matipojo requested changes

2021-07-01 08:57 UTC, matipojo commented on core/common/assets/js/api/extras/hash-commands.js
> +				return Promise.reject( Error( `Attempting to run unsafe or non exist command: \`${ hashCommand.command }\`.` ) );
```suggestion
				return Promise.reject( new Error( `Attempting to run unsafe or non exist command: \`${ hashCommand.command }\`.` ) );
```

2021-07-01 08:57 UTC, matipojo commented on tests/qunit/tests/core/common/assets/js/api/extras/hash-commands.spec.js
> +		// Give him tick to reach 2.
Explain

2021-07-01 14:56 UTC, iNewLegend commented on core/common/assets/js/api/extras/hash-commands.js
> +				return Promise.reject( Error( `Attempting to run unsafe or non exist command: \`${ hashCommand.command }\`.` ) );
Handled.

2021-07-01 14:56 UTC, iNewLegend commented on tests/qunit/tests/core/common/assets/js/api/extras/hash-commands.spec.js
> +		// Give him tick to reach 2.
Handled.

2021-07-01 14:59 UTC, iNewLegend commented on tests/qunit/tests/core/common/assets/js/api/extras/hash-commands.spec.js
> +		// Give him tick to reach 2.
Handled.

2021-07-04 11:24 UTC, matipojo approved these changes

2021-07-07 17:34 UTC, merged