Fix: Basic Gallery - SVG Icon is not displayed in the Basic Gallery widget [ED-4046]
elementor/elementor pull request #15551
Opened 2021-07-04 16:40 UTC by guyc-E

…idget [ED-4046]

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2021-08-12 10:24 UTC, matipojo requested changes

2021-08-12 10:24 UTC, matipojo commented on assets/dev/js/editor/controls/gallery.js
> +	setUploadMimeType() {
```suggestion
	addSvgMimeType() {
	if ( ! FilesUploadHandler.isUploadEnabled( 'svg' ) ) {
		return;
	}
```

2021-08-12 10:56 UTC, kobizz requested changes

2021-08-12 11:00 UTC, kobizz commented
@guyc-E Please merge release/3.4.0

2021-08-12 12:03 UTC, guyc-E commented on assets/dev/js/editor/controls/gallery.js
> +		// Set svg as only allowed upload extensions
You're right. I copied this code from another file and changed it but forgot to change the function's name and the comment.

2021-08-12 12:03 UTC, guyc-E commented on assets/dev/js/editor/controls/gallery.js
> +	setUploadMimeType() {
Thanks

2021-08-16 09:12 UTC, kobizz approved these changes

2021-08-16 09:20 UTC, matipojo approved these changes

2021-08-16 09:21 UTC, merged