Fix: WP_Query - Editor performance all queries -> `no_found_rows' => true`. [ED-3150]
elementor/elementor pull request #15688
Opened 2021-07-18 09:28 UTC by iNewLegend

2021-07-19 09:10 UTC, matipojo requested changes

2021-07-19 09:10 UTC, matipojo commented on core/admin/admin-notices.php
> +			$elementor_pages = new \WP_Query( [ // 'no_found_rows' => false.
Go over all queries and check if needed

2021-07-20 08:07 UTC, iNewLegend commented on core/app/modules/import-export/directories/post-type.php
> +		$query = new \WP_Query( $query_args ); // 'no_found_rows' => true.
Handled.

2021-07-20 08:07 UTC, iNewLegend commented on core/admin/admin-notices.php
> +			$elementor_pages = new \WP_Query( [ // 'no_found_rows' => false.
Handled.

2021-07-20 08:09 UTC, matipojo requested changes

2021-07-20 08:09 UTC, matipojo commented on core/admin/admin-notices.php
> +			$elementor_pages = new \WP_Query( [ // SQL_CALC_FOUND_ROWS is used.
Why?

2021-07-20 08:09 UTC, matipojo commented on includes/utils.php
> +		return new \WP_Query( $args ); // SQL_CALC_FOUND_ROWS is used.
Why?

2021-07-20 08:47 UTC, iNewLegend commented on core/admin/admin-notices.php
> +			$elementor_pages = new \WP_Query( [ // SQL_CALC_FOUND_ROWS is used.
Handled.

2021-07-20 08:47 UTC, iNewLegend commented on includes/utils.php
> +		return new \WP_Query( $args ); // SQL_CALC_FOUND_ROWS is used.
Handled.

2021-07-25 17:14 UTC, matipojo approved these changes

2021-07-25 17:15 UTC, merged