Fix: Header Handle - Edit header handles don't show up if the z-index of the header section is above 99 (for release 3.5.0) [ED-1628]
elementor/elementor pull request #15700
Opened 2021-07-19 12:43 UTC by guyc-E

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2021-07-19 12:46 UTC, guyc-E commented
I also fixed the handle of a section. ( check video in jira task comments )

2021-09-13 10:30 UTC, kobizz requested changes

2021-09-13 10:30 UTC, kobizz commented on assets/dev/scss/editor/preview/preview.scss
> +	z-index: 1;
Add a comment that explains this index is needed

2021-09-18 22:18 UTC, kobizz requested changes

2021-09-18 22:18 UTC, kobizz commented on assets/dev/scss/editor/preview/preview.scss
> +	z-index: 1; // Fix: Handle-Setting disappear when mouse hover the handle-setting in a section beneath the header.
It only happens if the header has a high z-index. You should mention it.

2021-10-05 10:07 UTC, kobizz commented
@guyc-E Screenshotter is failing

2021-10-13 14:13 UTC, merged