Fix: Kit-Library - Connect Error caused by URL changes in Kit and template Library [ED-4353]
elementor/elementor pull request #15757
Opened 2021-07-25 10:31 UTC by Nevoss

2021-07-26 09:11 UTC, matipojo requested changes

2021-07-26 09:11 UTC, matipojo commented on core/common/modules/connect/apps/base-app.php
> +	 * @param array $options
Remove

2021-07-26 09:11 UTC, matipojo commented on core/common/modules/connect/apps/base-app.php
> +		$is_rest = defined( 'REST_REQUEST' ) && REST_REQUEST;
Test

2021-07-26 11:03 UTC, Nevoss commented on core/common/modules/connect/apps/base-app.php
> +	 * @param array $options
Done

2021-07-26 11:03 UTC, Nevoss commented on core/common/modules/connect/apps/base-app.php
> +		$is_rest = defined( 'REST_REQUEST' ) && REST_REQUEST;
Done

2021-07-26 11:29 UTC, ItzhakAvm approved these changes

2021-07-27 14:47 UTC, matipojo requested changes

2021-07-27 14:47 UTC, matipojo commented on tests/phpunit/elementor/core/common/modules/connect/apps/test-common-app.php
> +		add_filter( 'wp_doing_ajax', $filter );
```suggestion
		add_filter( 'wp_doing_ajax', '__return_true' );
```

2021-07-27 14:47 UTC, matipojo commented on tests/phpunit/elementor/core/common/modules/connect/apps/test-common-app.php
> +		};
```suggestion
```

2021-07-27 14:47 UTC, matipojo commented on tests/phpunit/elementor/core/common/modules/connect/apps/test-common-app.php
> +		remove_filter( 'wp_doing_ajax', $filter );
```suggestion
		remove_filter( 'wp_doing_ajax', '__return_true' );
```

2021-07-28 07:20 UTC, Nevoss commented on tests/phpunit/elementor/core/common/modules/connect/apps/test-common-app.php
> +		add_filter( 'wp_doing_ajax', $filter );
Done

2021-07-28 07:20 UTC, Nevoss commented on tests/phpunit/elementor/core/common/modules/connect/apps/test-common-app.php
> +		};
Done

2021-07-28 07:20 UTC, Nevoss commented on tests/phpunit/elementor/core/common/modules/connect/apps/test-common-app.php
> +		remove_filter( 'wp_doing_ajax', $filter );
Doen

2021-07-28 15:33 UTC, matipojo approved these changes

2021-07-28 15:33 UTC, merged