Fix: Kit-Library - RTL + UI [ED-4297]
elementor/elementor pull request #15762
Opened 2021-07-25 12:14 UTC by Nevoss

2021-07-25 13:00 UTC, StyleShit requested changes

2021-07-25 13:00 UTC, StyleShit commented on core/app/modules/kit-library/assets/js/components/tags-filter.scss
> +
Is it related to the RTL issues?

2021-07-25 14:08 UTC, Nevoss commented on core/app/assets/js/ui/card/card-image.js
> +	const image = <img src={ props.src } alt={ props.alt } className="eps-card__image" loading="lazy" />;
no

2021-07-25 14:08 UTC, Nevoss commented on core/app/modules/kit-library/assets/js/components/tags-filter.scss
> +
no

2021-07-26 06:54 UTC, StyleShit approved these changes

2021-07-26 08:49 UTC, matipojo approved these changes

2021-07-26 08:50 UTC, merged