Fix: Gallery widget with dynamic tags can't be edited [ED-4443]
elementor/elementor pull request #15912
Opened 2021-08-08 12:28 UTC by StyleShit

closes #15529

2021-08-09 08:40 UTC, matipojo requested changes

2021-08-09 08:40 UTC, matipojo commented on assets/dev/js/editor/container/container.js
> +		if ( this.view && this.view instanceof Marionette.CompositeView ) {
Find a better solution

2021-08-09 12:00 UTC, StyleShit commented on assets/dev/js/editor/container/container.js
> +		if ( this.view && this.view instanceof Marionette.CompositeView ) {
Done.

2021-08-09 12:04 UTC, iNewLegend requested changes

2021-08-09 12:04 UTC, iNewLegend commented on assets/dev/js/editor/container/container.js
> +
```suggestion
	isViewElement() {
		return this.view && this.model.get( 'elType' );
	}

```

2021-08-09 12:04 UTC, iNewLegend commented on assets/dev/js/editor/container/container.js
> +		if ( this.view && this.isElement() ) {
```suggestion
		if ( this.isViewElement() ) {
```

2021-08-09 12:32 UTC, StyleShit commented on assets/dev/js/editor/container/container.js
> +		if ( this.view && this.isElement() ) {
Done.

2021-08-09 12:33 UTC, StyleShit commented on assets/dev/js/editor/container/container.js
> +
Done.

2021-08-11 07:47 UTC, matipojo approved these changes

2021-08-11 07:47 UTC, merged