Fix: Autoplay not working for Vimeo videos in Lightbox (ED-4796)
elementor/elementor pull request #16068
Opened 2021-08-19 13:38 UTC by udidol

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

* Fix: Autoplay not working for Vimeo videos in Lightbox (Fixes #16008)

2021-08-23 08:47 UTC, rotemee commented on assets/dev/js/frontend/utils/lightbox/lightbox.js
> +				videoURL = videoURL.slice( 0, timeMatch.index ) + videoURL.slice( timeMatch.index + timeMatch[ 0 ].length ) + timeMatch[ 0 ];
Please change to `.replace(regexValue, '') + regexValue`.

2021-08-23 13:41 UTC, rotemee approved these changes

2021-08-25 09:16 UTC, kobizz requested changes

2021-08-25 09:16 UTC, kobizz commented on assets/dev/js/frontend/utils/lightbox/lightbox.js
> +			}
Do it in the loader

2021-08-25 11:00 UTC, udidol commented on assets/dev/js/frontend/utils/lightbox/lightbox.js
> +			}
Done.

2021-08-25 14:10 UTC, kobizz approved these changes

2021-08-25 14:10 UTC, merged