Fix: Data Updater causes fatal error due to DB corruption [ED-4839]
elementor/elementor pull request #16195
Opened 2021-08-29 16:13 UTC by Nevoss

2021-08-30 04:46 UTC, iNewLegend requested changes

2021-08-30 04:46 UTC, iNewLegend commented on modules/usage/module.php
> +					'document_name' => $document->get_name(),
```suggestion
					'document_id' => $document->get_id(),
					'document_name' => $document->get_name(),
```

2021-08-30 07:25 UTC, Nevoss commented on modules/usage/module.php
> +					'document_name' => $document->get_name(),
Done

2021-08-30 07:27 UTC, iNewLegend approved these changes

2021-08-30 08:48 UTC, matipojo requested changes

2021-08-30 08:48 UTC, matipojo commented on modules/usage/module.php
>  				return; // Do nothing.
```suggestion
				return;
```

2021-08-31 12:39 UTC, matipojo approved these changes

2021-08-31 12:39 UTC, merged