Internal: Nested elements POC
elementor/elementor pull request #16208
Opened 2021-08-31 09:44 UTC by iNewLegend

2021-08-31 19:14 UTC, matipojo requested changes

2021-09-01 15:03 UTC, iNewLegend commented on assets/dev/js/editor/document/elements/component.js
> +					return !! elementor.widgetsCache[ parentModel.get( 'widgetType' ) ]?.support_repeater_elements;
Handled.

2021-09-01 15:03 UTC, iNewLegend commented on assets/dev/js/editor/elements/models/element-repeater.js
> +					const sectionView = container.view.addElement( new ElementRepeaterModel( {
Handled.

2021-09-01 15:03 UTC, iNewLegend commented on assets/dev/js/editor/elements/views/base.js
> +					ChildView = require( 'elementor-elements/views/widget-repeater' );
Handled.

2021-09-01 15:35 UTC, iNewLegend commented on assets/dev/js/editor/utils/helpers.js
> +					},
Check is required.

2021-09-01 15:35 UTC, iNewLegend commented on assets/dev/js/editor/elements/collections/elements.js
> +			debugger;
```suggestion
```

2021-09-02 07:29 UTC, iNewLegend commented on includes/widgets/tabs-v2.php
> +					</div>
```suggestion
				<# view.printChildren( index ) #>
```

2021-09-02 10:27 UTC, iNewLegend commented on includes/base/widget-container-base.php
> +	}
```suggestion
```
Always render into `.children` class.

2021-10-17 16:41 UTC, closed without merging