Internal: Unwanted text in the Maps widget [ED-4782]
elementor/elementor pull request #16259
Opened 2021-09-05 21:57 UTC by ItzhakAvm

2021-09-09 09:17 UTC, iNewLegend approved these changes

2021-09-14 08:47 UTC, matipojo requested changes

2021-09-14 08:47 UTC, matipojo commented on includes/widgets/google-maps.php
> +							esc_html__( 'Set your Google Maps API Key in Elementor\'s %1$s page. Create your key %2$s', 'elementor' ),
It's better to make translatable text in one paragraph and not separate them into many parts, please look at [this example](https://github.com/elementor/elementor/blob/6d61615d9b4cc9a5d659da19ab9cdd5bd6ca9f35/core/experiments/manager.php#L424) and add also the "Translators" comment

2021-09-29 09:34 UTC, matipojo commented on includes/widgets/google-maps.php
> +							esc_html__( 'Set your Google Maps API Key in Elementor\'s %1$s page. Create your key %2$s', 'elementor' ),
@ItzhakAvm Please fix like the example above (with the "translators" comment, and the HTML as a translation parameter)

2021-09-29 14:53 UTC, matipojo requested changes

2021-09-29 14:53 UTC, matipojo commented on includes/widgets/google-maps.php
> +							esc_html__( 'Set your Google Maps API Key in Elementor\'s %1$sIntegrations Settings%3$s page. Create your key %3$shere.%3$s', 'elementor' ),
```suggestion
							esc_html__( 'Set your Google Maps API Key in Elementor\'s %1$sIntegrations Settings%2$s page. Create your key %3$shere.%2$s', 'elementor' ),
```

2021-09-29 14:53 UTC, matipojo commented on includes/widgets/google-maps.php
> +						/* translators: %1$s Integration settings link open tag, %2$s: Link close tag, %3$s Create API key link open tag, %4$s: Link close tag. */
```suggestion
						/* translators: %1$s Integration settings link open tag, %2$s: Link close tag, %3$s Create API key link open tag. */
```

You can use the close tag (the second parameter) also for closing the second link. please remove the 4th parameter (line 121)

2021-09-30 11:39 UTC, matipojo requested changes
Please fix the Lint

2021-10-04 15:55 UTC, Aviad-Herman commented
Hey @matipojo can you please retarget to 3.5.0?

2021-10-05 12:08 UTC, matipojo requested changes

2021-10-05 12:08 UTC, matipojo commented on includes/widgets/google-maps.php
> +						/* translators: %1$s: Integration settings link open tag, %2$s: Create API key link open tag, %3$s: Link close tag. */
The translation comment should be one line above the translation.
```suggestion
```

2021-10-05 12:08 UTC, matipojo commented on includes/widgets/google-maps.php
> +							esc_html__( 'Set your Google Maps API Key in Elementor\'s %1$sIntegrations Settings%3$s page. Create your key %2$shere.%3$s', 'elementor' ),
Please use `1:` & `2:` in the translation comment.
```suggestion
							/* translators: 1: Integration settings link open tag, 2: Create API key link open tag, %3$s: Link close tag. */
							esc_html__( 'Set your Google Maps API Key in Elementor\'s %1$sIntegrations Settings%3$s page. Create your key %2$shere.%3$s', 'elementor' ),
```

2021-10-05 14:32 UTC, rodolphebertozzo requested changes
Pull from 3.5.0

2021-10-07 09:52 UTC, merged