Internal: Use UI States in Color Sampler [ED-4663]
elementor/elementor pull request #16286
Opened 2021-09-09 09:33 UTC by StyleShit

2021-09-09 16:14 UTC, iNewLegend approved these changes

2021-10-04 15:57 UTC, Aviad-Herman commented
Hey @matipojo can you please retarget to 3.5.0?

2021-10-07 15:13 UTC, matipojo requested changes

2021-10-10 12:12 UTC, matipojo approved these changes

2021-10-10 12:14 UTC, merged