Internal: Usage data calculations only for users that opted in.
elementor/elementor pull request #16457
Opened 2021-10-03 09:35 UTC by iNewLegend

2021-10-03 11:05 UTC, matipojo requested changes

2021-10-03 11:05 UTC, matipojo commented on modules/usage/usage-reporter.php
> +		return Tracker::is_allow_track();
Please remove also from the post saving

2021-10-03 11:11 UTC, nisan250 requested changes

2021-10-03 11:11 UTC, nisan250 commented on core/upgrade/upgrades.php
> +		if ( Tracker::is_allow_track() ) {
If not

2021-10-03 12:58 UTC, iNewLegend commented on modules/usage/usage-reporter.php
> +		return Tracker::is_allow_track();
Handled.

2021-10-03 12:58 UTC, iNewLegend commented on core/upgrade/upgrades.php
> +		if ( Tracker::is_allow_track() ) {
Handled.

2021-10-03 13:47 UTC, nisan250 approved these changes

2021-10-03 13:58 UTC, matipojo requested changes

2021-10-03 13:58 UTC, matipojo commented on core/upgrade/upgrades.php
> +		if ( ! Tracker::is_allow_track() ) {
On optin the usage data - please recalc the usage in the background

2021-10-12 16:45 UTC, matipojo requested changes

2021-10-12 16:46 UTC, matipojo reviewed
Nice Work! 🔥

2021-10-17 15:27 UTC, matipojo approved these changes

2021-10-17 15:27 UTC, merged