Tweak: Made placeholder values clearer in controls with CSS units [ED-4841]
elementor/elementor pull request #16488
Opened 2021-10-05 17:31 UTC by ItzhakAvm

2021-10-06 05:04 UTC, StyleShit requested changes

2021-10-06 05:04 UTC, StyleShit commented on assets/dev/js/editor/controls/base-units.js
> +		if ( placeholder && placeholder !== this.getControlValue( 'unit' ) ) {
```suggestion
		if ( placeholder !== this.getControlValue( 'unit' ) ) {
```

2021-10-06 11:05 UTC, StyleShit approved these changes

2021-10-12 17:19 UTC, matipojo approved these changes

2021-10-12 17:19 UTC, merged