Internal: Use consistent names in JS events [ED-4842]
elementor/elementor pull request #16534
Opened 2021-10-10 10:44 UTC by StyleShit

2021-10-12 06:46 UTC, nisan250 approved these changes

2021-10-12 17:05 UTC, matipojo requested changes

2021-10-12 17:20 UTC, matipojo requested changes
Please pull from 3.5.0

2021-10-17 15:30 UTC, matipojo approved these changes

2021-10-17 15:30 UTC, merged