Tweak: Added option to change the color of the navigation dots in carousel type widgets [ED-4970]
elementor/elementor pull request #16646
Opened 2021-10-20 09:00 UTC by nisan250

https://share.vidyard.com/watch/UmCja9w1Hhpn6EvzEqPAQN?

2021-10-20 13:24 UTC, StyleShit requested changes

2021-10-25 06:20 UTC, StyleShit approved these changes

2021-10-25 13:51 UTC, matipojo requested changes

2021-11-11 15:53 UTC, matipojo approved these changes

2021-11-11 15:53 UTC, matipojo commented on includes/widgets/image-carousel.php
> +			'dots_color_inactive',
```suggestion
			'dots_inactive_color',
```

2021-11-14 07:35 UTC, nisan250 commented on includes/widgets/image-carousel.php
> +			'dots_color_inactive',
Done

2021-11-28 13:53 UTC, matipojo requested changes

2021-11-28 13:53 UTC, matipojo commented on includes/widgets/image-carousel.php
> +			'dots_inactive_color',
Please keep consistency
```suggestion
			'dots_color_inactive',
```

2021-11-28 19:22 UTC, nisan250 commented on includes/widgets/image-carousel.php
> +			'dots_inactive_color',
Done

2021-12-12 17:19 UTC, merged