Internal: Fix Data/V2  force `$callback` to be `base_callback`. [ED-5293]
elementor/elementor pull request #16730
Opened 2021-10-28 10:04 UTC by iNewLegend

2021-10-28 10:51 UTC, matipojo requested changes

2021-10-28 10:52 UTC, matipojo requested changes
PHP-Lint

2021-10-28 12:38 UTC, matipojo requested changes

2021-10-28 12:41 UTC, matipojo requested changes

2021-11-01 15:51 UTC, iNewLegend commented on docs/data/base/v2/controller.md
> +	| `Controller::get_permission_callback()` |  `WP_REST_Request` $request    | `Boolean`                                      | Retrieves the state of should this request allow to run.
```suggestion
	| `Controller::get_permission_callback()` |  `WP_REST_Request` $request    | `Boolean`                                      | Retrieves the state of should this request allow to run.
```
```suggestion
	| `Controller::get_permission_callback()` |  `WP_REST_Request` $request    | `Boolean`                                      | Retrieves the permission status for each request, `true` allow running.
```

2021-11-02 05:06 UTC, iNewLegend commented on data/v2/base/controller.php
> +
```suggestion
```

2021-11-11 16:37 UTC, matipojo requested changes

2021-11-11 16:37 UTC, matipojo commented on data/v2/base/base-route.php
> +					return true;
I didn't understand. if the real check is not here - remove it.

2021-11-14 08:34 UTC, iNewLegend commented on data/v2/base/base-route.php
> +					return true;
Handled.

2021-11-14 08:37 UTC, iNewLegend commented on data/v2/base/base-route.php
> +		 * and `get_item_permission_callback()` or `get_items_permission_callback()` and such for `get_permission_callback()`.
Handled.

2021-11-16 10:55 UTC, matipojo requested changes

2021-11-16 10:55 UTC, matipojo commented on data/v2/base/base-route.php
> +		 * Iif it's a one item request and should call `get_item_permission_callback()` or it's mutil items request and should call `get_items_permission_callback()`.
```suggestion
		 * Whether it's a one item request and should call `get_item_permission_callback()` or it's mutil items request and should call `get_items_permission_callback()`.
```

2021-11-16 10:55 UTC, matipojo commented on tests/phpunit/elementor/data/v2/base/test-base-route.php
> +		$this->assertEquals( 'rest_forbidden', $data['code'] );
Why it's not an HTTP code?

2021-11-16 11:20 UTC, iNewLegend commented on tests/phpunit/elementor/data/v2/base/test-base-route.php
> +		$this->assertEquals( 'rest_forbidden', $data['code'] );
Handled.

2021-11-17 08:28 UTC, matipojo approved these changes

2021-11-17 08:30 UTC, merged