POC : image box widget
elementor/elementor pull request #16905
Opened 2021-11-11 10:47 UTC by rodolphebertozzo

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2021-11-11 16:15 UTC, rodolphebertozzo commented
@matipojo

2021-11-11 17:40 UTC, matipojo commented
Hi, @rodolphebertozzo Thanks!
Can you please attach some screenshots with how it looks like on the Editor Panel/ Fronend?

2021-11-11 18:16 UTC, rodolphebertozzo commented
@matipojo : 
![matipojo](https://user-images.githubusercontent.com/56270626/141348681-f128e49d-7f98-4cd3-b5c9-f4501d695a8e.PNG)

2021-11-11 20:49 UTC, rodolphebertozzo commented
Hi @matipojo, can you help me, I can't get the caption to appear, yet the method seems to be the right one, do you have an idea?

2021-11-14 16:04 UTC, matipojo requested changes

2021-11-14 16:04 UTC, matipojo commented on includes/widgets/image-box.php
> +		$image_caption = $this->get_image_caption( $attachment );
Where is the initialization of the `$attachment`

2021-12-20 15:04 UTC, closed without merging