Fix: Text in beta users "Get beta updates" modal [ED-5446]
elementor/elementor pull request #16929
Opened 2021-11-14 11:28 UTC by Nevoss

2021-11-15 11:37 UTC, nisan250 approved these changes

2021-11-16 12:00 UTC, matipojo requested changes

2021-11-16 12:00 UTC, matipojo commented on includes/admin-templates/beta-tester.php
> +				/* translators: %1$s is the "Terms of service" link, %2$s is the "Privacy policy" link */
```suggestion
				/* translators: 1. "Terms of service" link, 2. "Privacy policy" link */
```

2021-11-16 12:00 UTC, matipojo commented on includes/admin-templates/beta-tester.php
> +					'<a href="%1$s" target="_blank" rel="nofollow">%2$s</a>',
```suggestion
					'<a href="%1$s" target="_blank">%2$s</a>',
```

2021-11-16 13:20 UTC, Nevoss commented on includes/admin-templates/beta-tester.php
> +					'<a href="%1$s" target="_blank" rel="nofollow">%2$s</a>',
Done

2021-11-16 13:26 UTC, merged