Internal: Skip required workflow in GitHub CI [ED-5930]
elementor/elementor pull request #17275
Opened 2021-12-22 09:44 UTC by Nevoss

2021-12-26 19:50 UTC, matipojo requested changes

2021-12-26 19:50 UTC, matipojo commented on .github/workflows/phpunit.yml
> +    if: ${{ always() }}
Why not
```suggestion
```

2021-12-26 19:50 UTC, matipojo commented on .github/workflows/phpunit.yml
> +    name: Test Results
```suggestion
    name: PHPUnit - Test Results
```

2022-01-02 10:06 UTC, Nevoss commented on .github/workflows/phpunit.yml
> +    name: Test Results
Done

2022-01-02 10:06 UTC, Nevoss commented on .github/workflows/phpunit.yml
> +    runs-on: ubuntu-18.04
Done

2022-01-02 10:06 UTC, Nevoss commented on .github/workflows/phpunit.yml
> +    if: ${{ always() }}
Added a comment

2022-01-02 10:15 UTC, merged