Fix: New dragged widgets get inserted to the bottom [ED-6170]
elementor/elementor pull request #17438
Opened 2022-01-11 06:29 UTC by StyleShit

2022-01-11 06:29 UTC, StyleShit commented on assets/dev/js/editor/utils/jquery-html5-dnd.js
> +			);
Same as in the Container branch

2022-01-11 06:30 UTC, StyleShit commented on assets/dev/js/editor/utils/jquery-html5-dnd.js
> +				settings.onAfterDrop( currentSide, event );
Newly added code

2022-01-12 10:28 UTC, matipojo requested changes

2022-01-12 10:28 UTC, matipojo commented on assets/dev/js/editor/views/add-section/inline.js
> +		this.destroy();
How has it worked until now?

2022-01-12 10:28 UTC, matipojo commented on assets/dev/js/editor/views/base-container.js
> +					at: options.at,
How has it worked until now?

2022-01-12 14:04 UTC, closed without merging