Fix: Lower custom breakpoints didn't inherits upper breakpoints values in frontend [ED-6235]
elementor/elementor pull request #17475
Opened 2022-01-13 15:29 UTC by guyc-E

2022-01-24 12:52 UTC, udidol requested changes

2022-01-25 12:22 UTC, guyc-E commented on assets/dev/js/editor/utils/conditions.js
> +				if ( ! value && controls ) {
You're right, it's redundant

2022-01-25 12:23 UTC, guyc-E commented on core/breakpoints/manager.php
> +
Done

2022-01-31 15:28 UTC, udidol approved these changes

2022-03-01 13:26 UTC, merged