Fix/video widget a11y updates
elementor/elementor pull request #17559
Opened 2022-01-24 09:41 UTC by louiswol94

## PR Checklist

- [x] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:
Tweak: Added focus state and description on play icon in Video widget
*

2022-01-24 09:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/elementor/elementor?pullRequest=17559) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/elementor/elementor?pullRequest=17559) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/elementor/elementor?pullRequest=17559) it.</sub>

2022-02-14 13:05 UTC, udidol requested changes

2022-02-14 13:05 UTC, udidol commented on assets/dev/js/frontend/handlers/video.js
> +			if ( ENTER_KEY === event.keyCode ) {
Add support for the play button as well

2022-02-14 13:29 UTC, louiswol94 commented on assets/dev/js/frontend/handlers/video.js
> +			if ( ENTER_KEY === event.keyCode ) {
@udidol Done.

2022-02-14 13:35 UTC, udidol approved these changes

2022-02-28 15:10 UTC, merged