Infra - QUnit tests elements helper refactor. [ED-6418]
elementor/elementor pull request #17660
Opened 2022-02-01 14:33 UTC by iNewLegend

2022-02-01 16:40 UTC, ItzhakAvm requested changes

2022-02-01 16:40 UTC, ItzhakAvm commented on tests/qunit/tests/assets/dev/js/editor/document/elements/helper.js
> +		return this.createWidgetButton( eContainer, settings );
```suggestion
		return this.createAuto( 'widget' );
```

2022-02-01 16:41 UTC, ItzhakAvm approved these changes

2022-02-16 06:17 UTC, iNewLegend commented
@matipojo, Please review

2022-02-23 16:48 UTC, matipojo requested changes

2022-02-23 16:48 UTC, matipojo commented on tests/qunit/tests/assets/dev/js/editor/document/elements/commands/paste-style.spec.js
> +					eWidgetStyled = ElementsHelper.createAutoButton( null, {
```suggestion
					eWidgetStyled = ElementsHelper.createWrappedButton( null, {
```

2022-02-24 05:41 UTC, iNewLegend commented on tests/qunit/tests/assets/dev/js/editor/document/elements/commands/paste-style.spec.js
> +					eWidgetStyled = ElementsHelper.createAutoButton( null, {
Handled

2022-03-13 13:44 UTC, matipojo requested changes
Please resolve the conflicts

2022-04-11 15:27 UTC, merged