Tweak: Adjusted the inline icon control for design flexibility [OBXT-…
elementor/elementor pull request #17696
Opened 2022-02-03 09:12 UTC by louiswol94

…546]

## PR Checklist

- [x] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

Tweak: Adjusted the inline icon control for design flexibility

## Description
An explanation of what is done in this PR

On the Icons control "inline skin" we added the ability for a developer to add the following settings:

1) Option to toggle on/off the control (Allow no active state)
2) Option to change the icons
3) Option to change the tooltip text

## Test instructions
This PR can be tested by following these steps:

You can test this by adding the following settings to icon controls:

```
'disable_initial_active_state' => false,
'skin_settings' => [
    'inline' => [
        'none' => [
            'label' => 'Tes',
            'icon' => 'eicon-ban',
        ],
        'svg' => [
            'label' => 'Test',
            'icon' => 'eicon-ban',
        ],
        'icon' => [
            'label' => 'Testtt',
            'icon' => 'eicon-upload',
        ],
    ],
],
```

`disable_initial_active_state` will give the ability to not have any of the icons marked as checked on initial DD of the widget. Before this change 'None' was always selected if no default icon was specified.

I created the array in the format of `$skin_settings['inline']['...']` so that if we want to make any changes to the "media skin" later on it can just form part of this same array `$skin_settings['media']['...']`

2022-02-14 13:34 UTC, udidol requested changes

2022-02-14 13:34 UTC, udidol commented on includes/controls/icons.php
> +						}
Same for here

2022-02-14 14:11 UTC, louiswol94 commented on includes/controls/icons.php
> +						}
Hi @udidol I guess I was just trying to be extra safe. But you are right, the values will always be there so the `if` statements are unnecessary :-)
Done.

2022-02-15 13:40 UTC, udidol approved these changes

2022-02-28 15:17 UTC, merged