Fix: Favorites with WooCommerce widgets throws a critical error if WooCommerce is deactivated [ED-6442]
elementor/elementor pull request #17731
Opened 2022-02-07 12:23 UTC by ItzhakAvm

2022-02-07 12:46 UTC, iNewLegend approved these changes

2022-02-08 09:50 UTC, Nevoss approved these changes

2022-02-08 09:50 UTC, Nevoss requested changes

2022-02-08 11:05 UTC, ItzhakAvm commented on modules/favorites/types/widgets.php
> +				$widget->set_config( 'categories', [ static::CATEGORY_SLUG ] );
[https://github.com/elementor/elementor/blob/develop/tests/phpunit/elementor/includes/base/test-widget-base.php](Already has)

2022-02-09 21:02 UTC, Nevoss requested changes

2022-02-09 21:02 UTC, Nevoss commented on tests/phpunit/elementor/modules/favorites/types/test-widgets.php
> +		$widget_type = $widget->get_name();
Maybe you can add another mock widget (you can create them with the PHPUnit mock builder - talk to me if need help) and register only one of the widgets, then check thank only one widget is in the config (then maybe you can remove the other test).
Let me know what do you think about it.

2022-02-10 16:58 UTC, Nevoss approved these changes

2022-02-13 08:15 UTC, merged