Internal: Nested Infra - CommandHistory `useHistory` option.
elementor/elementor pull request #17851
Opened 2022-02-15 14:56 UTC by iNewLegend

2022-02-16 13:54 UTC, nisan250 approved these changes

2022-02-16 14:19 UTC, StyleShit requested changes

2022-02-16 14:19 UTC, StyleShit commented on assets/dev/js/editor/document/commands/base/command-history.js
> +		const options = { useHistory: true };
Who can override this?

2022-02-17 05:45 UTC, StyleShit commented
Qunit fails

2022-02-17 08:29 UTC, nisan250 approved these changes

2022-02-17 08:59 UTC, StyleShit approved these changes

2022-02-17 09:17 UTC, merged