Internal: React Navigator fixes [ED-6586]
elementor/elementor pull request #17960
Opened 2022-02-23 23:05 UTC by ItzhakAvm

2022-02-24 16:23 UTC, matipojo requested changes

2022-02-24 16:26 UTC, matipojo requested changes
Please fix the checks errors

2022-02-27 13:21 UTC, ItzhakAvm commented on assets/dev/js/editor/regions/navigator/components/items/element-item.js
> +};
Done.

2022-02-27 13:21 UTC, ItzhakAvm commented on assets/dev/js/editor/regions/navigator/hooks/use-navigator-jquery-sortable.js
> +						autoExpand = true;
Done.

2022-03-15 03:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/elementor/elementor?pullRequest=17960) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/elementor/elementor?pullRequest=17960) before we can accept your contribution.<br/><hr/>**Itzhak** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/elementor/elementor?pullRequest=17960) it.</sub>

2022-04-11 15:33 UTC, merged