Fix: Container - Widget width control is broken when Container experiment is active [ED-6565]
elementor/elementor pull request #18033
Opened 2022-03-01 13:19 UTC by StyleShit

2022-03-01 13:23 UTC, StyleShit commented on includes/widgets/common.php
> +				] ),
That's reverted to the original behavior:

https://github.com/elementor/elementor/blob/master/includes/widgets/common.php#L1274-L1281

2022-03-03 10:17 UTC, matipojo requested changes

2022-03-03 10:17 UTC, matipojo commented on assets/dev/js/editor/elements/views/behaviors/widget-resizeable.js
> +			widthSetting = this.getDeviceSetting( this.getWidthKey() );
```suggestion
		const elementWidthSettingKey = this.getDeviceSetting( '_element_width' ),
			widthSettingKey = this.getDeviceSetting( this.getWidthKey() );
```

2022-03-03 10:17 UTC, matipojo commented on assets/dev/js/editor/elements/views/behaviors/widget-resizeable.js
> +		const { unit } = this.getSetting( widthSetting ),
```suggestion
		const { unit } = this.getSetting( widthSettingKey ),
```

2022-03-03 10:17 UTC, matipojo commented on assets/dev/js/editor/elements/views/behaviors/widget-resizeable.js
> +			[ widthSetting ]: {
```suggestion
			[ elementWidthSettingKey ]: 'initial',
			[ widthSettingKey ]: {
```

2022-03-03 10:25 UTC, matipojo requested changes
Please resolve the conflicts

2022-03-03 10:51 UTC, merged