Fix: Import export from kit library [ED-6684]
elementor/elementor pull request #18047
Opened 2022-03-02 13:06 UTC by Nevoss

2022-03-02 13:12 UTC, rodolphebertozzo requested changes

2022-03-02 13:12 UTC, rodolphebertozzo commented on core/app/modules/import-export/module.php
> +				throw new \Error( __( 'Cannot verify import file url', 'elementor' ) );
```suggestion
				throw new \Error( esc_html__( 'Cannot verify import file url', 'elementor' ) );
```

2022-03-02 13:13 UTC, Nevoss commented on core/app/modules/import-export/module.php
> +				throw new \Error( __( 'Cannot verify import file url', 'elementor' ) );
Thanks

2022-03-03 10:27 UTC, matipojo requested changes

2022-03-03 10:27 UTC, matipojo commented on core/app/modules/import-export/module.php
> +	public function on_admin_init() {
Why

2022-03-03 10:29 UTC, Nevoss commented on core/app/modules/import-export/module.php
> +	public function on_admin_init() {
mistake

2022-03-09 18:24 UTC, merged