Fix: JS API Refactor Backward Compatibility [ED-6591]
elementor/elementor pull request #18068
Opened 2022-03-04 07:03 UTC by iNewLegend

2022-03-06 07:05 UTC, StyleShit requested changes

2022-03-06 07:05 UTC, StyleShit commented on core/common/assets/js/api/modules/command-infra.js
> +
Why do you need `defineProperty`? Can't you do it like that?

```JS
get currentCommand() { ... }
```

2022-03-06 07:05 UTC, StyleShit commented on core/common/assets/js/api/core/routes.js
> +		this.trigger( 'run:before', component, route, args );
Shouln't we deprecate it?

2022-03-06 07:05 UTC, StyleShit commented on core/common/assets/js/api/core/routes.js
> +		this.trigger( 'run:after', component, route, args, results );
Same as above

2022-03-06 10:02 UTC, iNewLegend commented on core/common/assets/js/api/core/routes.js
> +		this.trigger( 'run:before', component, route, args );
We don't have hooks on `$e.routes` yet.

2022-03-06 10:12 UTC, StyleShit approved these changes

2022-03-08 12:59 UTC, matipojo approved these changes

2022-03-08 12:59 UTC, merged