Internal: Nested Infra - Fix Experiments manager module dependency [ED-6757]
elementor/elementor pull request #18094
Opened 2022-03-08 10:09 UTC by iNewLegend

2022-03-08 10:11 UTC, iNewLegend commented on core/experiments/manager.php
>  				$experimental_data['dependencies'][ $key ] = $dependency::instance();
```suggestion
```

2022-03-13 12:25 UTC, matipojo requested changes
Please cover with tests

2022-03-13 12:25 UTC, matipojo commented on core/experiments/wrap-core-dependency.php
> +		return new self( $feature_data );
```suggestion
		return new static( $feature_data );
```

2022-03-13 13:29 UTC, matipojo requested changes

2022-03-13 13:29 UTC, matipojo commented on tests/phpunit/elementor/core/experiments/test-manager.php
> +
```suggestion

		// Assert.
```

2022-03-13 13:30 UTC, merged