Tweak: Import All command should skip the Plugins screen and start import process[ED-6510]
elementor/elementor pull request #18131
Opened 2022-03-10 13:37 UTC by davseve

2022-03-14 12:37 UTC, StyleShit requested changes

2022-03-15 11:09 UTC, yossi-elementor requested changes

2022-03-15 13:12 UTC, davseve commented on core/app/modules/import-export/assets/js/pages/import/import-plugins/components/import-kit-library-plugins/import-kit-library-plugins.js
> +		<span>.</span>
This file has been deleted

2022-03-15 13:18 UTC, davseve commented on core/app/modules/import-export/assets/js/pages/import/import-plugins/components/import-kit-library-plugins/import-kit-library-plugins.js
> +		plugins = importContext.data.plugins || {},
This file has been deleted

2022-03-15 13:19 UTC, davseve commented on core/app/modules/import-export/assets/js/pages/import/import-plugins/components/import-kit-library-plugins/import-kit-library-plugins.js
> +			handleRequiredPlugins();
This file has been deleted

2022-03-15 13:21 UTC, davseve commented on core/app/modules/import-export/assets/js/pages/import/import-plugins/components/import-kit-library-plugins/import-kit-library-plugins.js
> +	plugins: PropTypes.array,
This file has been deleted
This is probably a leftover of previous changes

2022-03-15 13:21 UTC, davseve commented on core/app/modules/import-export/assets/js/pages/import/import-plugins/components/import-kit-library-plugins/import-kit-library-plugins.js
> +
This file has been deleted

2022-03-15 13:30 UTC, davseve commented on core/app/modules/import-export/assets/js/pages/import/import-plugins/components/import-kit-library-plugins/import-kit-library-plugins.js
> +			if ( missing?.length ) {
This file has been deleted

2022-03-15 13:31 UTC, davseve commented on core/app/modules/import-export/assets/js/pages/import/import-plugins/hooks/use-import-kit-library-plugins.js
> +export default function UseImportKitLibraryPlugins() {
This file has been deleted, But I will pay more attention to it in the future.

2022-03-15 13:41 UTC, davseve commented on core/app/modules/import-export/assets/js/pages/import/import-process/import-process.js
> +		}
Done

2022-03-15 13:41 UTC, davseve commented on core/app/modules/import-export/assets/js/context/import-context/import-context-reducer.js
> +		case 'SET_ACTIONTYPE':
Done

2022-03-15 13:46 UTC, davseve commented on core/app/modules/import-export/assets/js/pages/import/import-process/import-process.js
> +		const cpt = kitState?.data?.manifest[ 'custom-post-type-title' ] || importContext?.data?.uploadedData?.manifest[ 'custom-post-type-title' ];
Removed unnecessary questions mark, if you think I can remove even more please tell me.

2022-03-15 13:55 UTC, davseve commented on core/app/modules/import-export/module.php
> +			throw new \Error( self::PERMISSIONS_ERROR_KEY );
Can you please explain?

2022-03-15 13:57 UTC, davseve commented on core/app/modules/import-export/assets/js/pages/import/import-plugins/hooks/use-import-kit-library-plugins.js
> +		};
This file was removed, I wanted to go through it with Yossi, that is why I left it in the PR.
This file was deleted.

2022-03-15 14:12 UTC, StyleShit commented on core/app/modules/import-export/module.php
> +			throw new \Error( self::PERMISSIONS_ERROR_KEY );
https://stackoverflow.com/a/64072873/3829526

2022-03-15 14:24 UTC, davseve commented on core/app/modules/import-export/assets/js/pages/import/import-plugins/components/import-kit-library-plugins/import-kit-library-plugins.js
> +		{ missing } = importPluginsData || {},
The `missing` name is used all across the import/export app.
Maybe we should fix it in a dedicated patch.

2022-03-15 14:25 UTC, davseve commented on core/app/modules/import-export/assets/js/pages/import/import-process/import-process.js
> +					<ImportKitLibraryPlugins />
Refactored

2022-03-15 16:58 UTC, yossi-elementor requested changes

2022-03-15 16:58 UTC, yossi-elementor commented on core/app/modules/import-export/assets/js/context/import-context/import-context-provider.js
> +export function shouldResolveConflict() {
Remove

2022-03-15 16:58 UTC, yossi-elementor commented on core/app/modules/import-export/assets/js/pages/import/import-kit/hooks/use-import-kit-library-apply-all-plugins.js
> +		if ( ! plugins.length ) {
`plugins && ! plugins.length`

2022-03-15 17:14 UTC, yossi-elementor approved these changes

2022-03-15 17:54 UTC, merged