Tweak: Adjust all external system links to include `noopener` attribute [ED-6580]
elementor/elementor pull request #18224
Opened 2022-03-22 14:54 UTC by StyleShit

2022-03-24 08:29 UTC, Nevoss requested changes

2022-03-24 08:29 UTC, Nevoss commented on modules/admin-top-bar/assets/js/components/connection-button/connection-button.js
> +		rel = '';
```suggestion
		rel = null;
```

2022-03-24 08:29 UTC, Nevoss commented on modules/admin-top-bar/assets/js/components/connection-button/connection-button.js
> +		rel = '';
Did you check that it is working?

2022-03-24 10:14 UTC, StyleShit commented on modules/admin-top-bar/assets/js/components/connection-button/connection-button.js
> +		rel = '';
Done

2022-03-24 14:20 UTC, Nevoss approved these changes

2022-03-31 14:15 UTC, matipojo commented
The modern browsers are already handling it:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#:~:text=target%3D%22_blank%22%20implies%20rel%3D%22noopener%22%20behavior

2022-03-31 14:15 UTC, closed without merging