Internal: Nested Elements - Infra fixes & tests [ED-6591]
elementor/elementor pull request #18297
Opened 2022-03-29 10:08 UTC by iNewLegend

2022-03-29 11:12 UTC, matipojo requested changes

2022-03-29 11:12 UTC, matipojo commented on assets/dev/js/editor/elements/manager.js
>  	getElementType( elType, widgetType = false ) {
Try to use the widget as an element
```suggestion
	getElementType( elType ) {
```

2022-03-29 11:12 UTC, matipojo commented on assets/dev/js/editor/elements/manager.js
> +		const index = element instanceof WidgetBase ? element.getWidgetType() : element.getType();
```suggestion
		const index = element.getType();
```

2022-03-29 11:12 UTC, matipojo commented on assets/dev/js/editor/elements/manager.js
> +	 * @param {ElementBase|WidgetBase} element
```suggestion
	 * @param {ElementBase} element
```

2022-03-30 08:36 UTC, iNewLegend commented on assets/dev/js/editor/elements/manager.js
>  	getElementType( elType, widgetType = false ) {
Handled.

2022-03-30 08:36 UTC, iNewLegend commented on assets/dev/js/editor/elements/manager.js
> +		const index = element instanceof WidgetBase ? element.getWidgetType() : element.getType();
Handled.

2022-03-30 08:36 UTC, iNewLegend commented on assets/dev/js/editor/elements/manager.js
> +	 * @param {ElementBase|WidgetBase} element
Handled.

2022-03-30 08:37 UTC, iNewLegend commented on assets/dev/js/editor/elements/manager.js
>  	getElementType( elType, widgetType = false ) {
Handled.

2022-03-30 08:37 UTC, iNewLegend commented on assets/dev/js/editor/elements/manager.js
> +		const index = element instanceof WidgetBase ? element.getWidgetType() : element.getType();
Handled.

2022-03-30 08:37 UTC, iNewLegend commented on assets/dev/js/editor/elements/manager.js
> +	 * @param {ElementBase|WidgetBase} element
Handled.

2022-03-31 14:27 UTC, merged

2022-03-31 14:28 UTC, matipojo reviewed
Please fix the checks errors and re-create a pull request