Internal: Update karma conf to support docker headless testing [ED-6942]
elementor/elementor pull request #18347
Opened 2022-04-04 12:15 UTC by maork-elementor

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2022-04-05 11:39 UTC, matipojo requested changes
Please resolve the conflicts

2022-04-05 11:39 UTC, matipojo commented on karma.conf.js
> +		browserDisconnectTimeout: 6000,
CS

2022-04-06 07:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/elementor/elementor?pullRequest=18347) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/elementor/elementor?pullRequest=18347) before we can accept your contribution.<br/>**6** out of **7** committers have signed the CLA.<br/><br/>:white_check_mark: ManorHazaz<br/>:white_check_mark: StyleShit<br/>:white_check_mark: TzviRabinovitch<br/>:white_check_mark: shilo-ey<br/>:white_check_mark: maork-elementor<br/>:white_check_mark: udidol<br/>:x: elementorbot<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/elementor/elementor?pullRequest=18347) it.</sub>

2022-04-06 07:33 UTC, maork-elementor commented on karma.conf.js
> +		browserDisconnectTimeout: 6000,
done

2022-04-12 14:07 UTC, merged