Internal: Routes - Add routes to global trace [ER-6978]
elementor/elementor pull request #18401
Opened 2022-04-10 11:36 UTC by iNewLegend

2022-04-10 13:50 UTC, matipojo requested changes
Please cover with tests

2022-04-11 13:07 UTC, iNewLegend commented on tests/jest/unit/modules/web-cli/assets/js/core/routes.test.js
> +		// Assert - Ensure route leave global commands trace.
```suggestion
		// Assert.
```

2022-04-12 08:49 UTC, matipojo requested changes

2022-04-12 08:49 UTC, matipojo commented on tests/jest/unit/modules/web-cli/assets/js/core/routes.test.js
> +			trace.push( ... $e.commands.constructor.trace );
```suggestion
			// Save it for the assertion.
			trace.push( ... $e.commands.constructor.trace );
```

2022-04-12 08:49 UTC, merged