Fix: Kit Library - See it live opens a blank page and not the Home Page [ED-6906]
elementor/elementor pull request #18409
Opened 2022-04-11 07:58 UTC by guyc-E

2022-04-11 08:16 UTC, ManorHazaz approved these changes

2022-06-06 07:03 UTC, yossi-elementor approved these changes

2022-07-25 09:05 UTC, ManorHazaz requested changes

2022-07-25 09:05 UTC, ManorHazaz commented on core/app/modules/import-export/module.php
> +		return $document->get_wp_preview_url();
Won't work anymore

2022-07-26 06:55 UTC, closed without merging