feat(carousel-image): add Title and Caption on Carousel Image
elementor/elementor pull request #18452
Opened 2022-04-15 22:33 UTC by pmaldi

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
This feature adds the possibility to add the title of the image in addition to the caption in carousel image.
The style section has been updated too.

![Image Carousel - Title](https://zupimages.net/up/22/15/o78e.png)

*

## Test instructions
This PR can be tested by following these steps:

1. Add a Image Carousel with your images.
2. Edit "Title" fied in "Content Section"
![Image Carousel Section](https://zupimages.net/up/22/15/wvno.png)
3. Apply style if needed.
![Image Carousel](https://zupimages.net/up/22/15/4t8c.png)

*

## Quality assurance

- [X] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2022-04-15 22:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/elementor/elementor?pullRequest=18452) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/elementor/elementor?pullRequest=18452) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/elementor/elementor?pullRequest=18452) it.</sub>

2022-04-16 16:04 UTC, rodolphebertozzo requested changes

2022-04-16 16:04 UTC, rodolphebertozzo commented on includes/widgets/image-carousel.php
> +		$this->add_control(
Make responsive

2022-04-16 16:11 UTC, pmaldi commented on includes/widgets/image-carousel.php
> +		$this->add_control(
Hello @rodolphebertozzo what is wrong ?

2022-04-16 16:17 UTC, rodolphebertozzo commented on includes/widgets/image-carousel.php
> +		$this->add_control(
```suggestion
		$this->add_responsive_control(
```

2022-04-16 16:29 UTC, rodolphebertozzo approved these changes

2023-02-16 14:30 UTC, rami-elementor reviewed
Elementor doesn't display both the title and the caption.

If usually let the user choose the to display in the `<figcaption>` element, ether the attachment title or the caption.

2023-02-16 14:30 UTC, rami-elementor commented on includes/widgets/image-carousel.php
>  				$slide_html .= '<figcaption class="elementor-image-carousel-caption">' . wp_kses_post( $image_caption ) . '</figcaption>';
Is this valid? to display 2 `<figcaption>` tags inside a `<figure>` element?

2024-05-21 16:03 UTC, yotamselementor commented
Hi @pmaldi ,
This PR was unintentionally closed - I removed the obsolete master branch which caused a chain effect of auto-closing all PRs directed at that branch.
I am looking for a way to reopen these PRs against main.

Thanks for understanding!

2026-06-03 06:41 UTC, closed without merging