Internal: Knowledge Transfer - Container [ED-7047]
elementor/elementor pull request #18568
Opened 2022-05-03 08:02 UTC by StyleShit

2022-05-03 13:33 UTC, Nevoss requested changes

2022-05-03 13:33 UTC, Nevoss commented on docs/includes/elements/container.md
> +- The whole DnD is based on an internal DnD library by @kobizz:
```suggestion
- The whole DnD is based on an internal DnD library by us:
```

2022-05-04 04:56 UTC, StyleShit commented on docs/includes/elements/container.md
> +- The whole DnD is based on an internal DnD library by @kobizz:
Done

2022-05-04 08:11 UTC, Nevoss approved these changes

2022-05-04 13:22 UTC, merged