Internal: Add playwright sanity tests for Carousel [ED-6915]
elementor/elementor pull request #18617
Opened 2022-05-10 12:44 UTC by ShayHel

2022-05-11 12:13 UTC, matipojo requested changes

2022-05-12 12:53 UTC, matipojo requested changes
The test is failing because you need to attach the Linux image from the artifact

2022-05-12 12:53 UTC, matipojo commented on tests/playwright/sanity/image-carousel.test.js
> +  await page.click('#elementor-navigator__close');
JSLInt

2022-05-16 15:11 UTC, ShayHel commented on tests/playwright/sanity/carousel.test.js
> +  await page.setInputFiles( 'input[type="file"]', './tests/playwright/resources/A.jpg' );
Done

2022-05-18 12:37 UTC, ShayHel commented on tests/playwright/sanity/carousel.test.js
> +  expect(await editor.getPreviewFrame().locator('div.elementor-image-carousel-wrapper.swiper-container.swiper-container-initialized').screenshot()).toMatchSnapshot('carousel.png');
I did the reduction of the baseline, but reducing the widget width I am afraid will affect the quality of the test.

2022-05-19 11:13 UTC, ShayHel commented on tests/playwright/sanity/image-carousel.test.js
> +  await page.click('#elementor-navigator__close');
Done

2022-05-19 17:02 UTC, matipojo requested changes
Please fix the checks errors

2022-06-16 15:31 UTC, merged