Internal: Core - Better handling file reading [ED-7104]
elementor/elementor pull request #18670
Opened 2022-05-17 12:20 UTC by nahmana

2022-05-17 13:16 UTC, StyleShit requested changes

2022-05-17 13:16 UTC, StyleShit commented on composer.json
> +		"allow-plugins": {
Move to another PR

2022-05-18 07:01 UTC, nahmana commented on composer.json
> +		"allow-plugins": {
Done.

2022-05-18 07:31 UTC, StyleShit approved these changes

2022-05-22 13:42 UTC, matipojo requested changes

2022-05-22 13:42 UTC, matipojo commented on tests/phpunit/elementor/includes/test-utils.php
> +		$file_name = 'non-file';
```suggestion
		// Elementor Logo
		$file_name = 'https://avatars.githubusercontent.com/u/47606894';
```

2022-05-22 13:59 UTC, merged