Internal: 'Source' field was added to Pendo events
elementor/elementor pull request #18676
Opened 2022-05-18 05:58 UTC by iNewLegend

2022-05-24 08:47 UTC, matipojo requested changes

2022-05-24 08:47 UTC, matipojo commented on assets/dev/js/editor/components/settings/base/manager.js
> +			callback: () => $e.route( `${ namespace }/settings`, {}, {
Use constants from a new `editor-constants.js`

2022-05-24 08:47 UTC, matipojo commented on modules/web-cli/assets/js/core/routes.js
> +	beforeRun( route, args, meta = {} ) {
Fix lint

2022-05-24 08:47 UTC, matipojo commented on modules/web-cli/assets/js/core/commands.js
> +	beforeRun( command, args, addTrace = true ) {
Restore

2022-05-24 08:47 UTC, matipojo commented on modules/web-cli/assets/js/core/commands.js
>  		this.trigger( 'run:after', component, command, args, results );
```suggestion
		this.trigger( 'run:after', component, command, args, results, meta );
```

2022-05-24 16:53 UTC, iNewLegend commented on assets/dev/js/editor/components/settings/base/manager.js
> +			callback: () => $e.route( `${ namespace }/settings`, {}, {
Handled.

2022-05-26 10:45 UTC, matipojo requested changes

2022-05-26 10:45 UTC, matipojo commented on assets/dev/js/editor/components/settings/base/manager.js
> +import { Sources } from 'elementor-editor/editor-constants';
Please remove the `activateTab` from component base in order to add the correct meta for the panel and template-library.

2022-05-26 10:45 UTC, matipojo commented on assets/dev/js/editor/components/settings/base/manager.js
> +import { Sources } from 'elementor-editor/editor-constants';
Please support `meta` for `$e.shortcuts`

2022-05-26 10:45 UTC, matipojo commented on assets/dev/js/editor/components/settings/base/manager.js
> +import { Sources } from 'elementor-editor/editor-constants';
Please separate infra from implementation

2023-03-26 16:54 UTC, matipojo commented on modules/web-cli/assets/js/core/routes.js
> +		super.afterRun( route, args, results, meta, false );
Fix order

2023-03-26 16:54 UTC, matipojo commented on modules/web-cli/assets/js/core/commands.js
> +     * @param {{}}      meta
```suggestion
	 * @param {{}}      meta
```

2023-03-26 16:55 UTC, matipojo commented on modules/web-cli/assets/js/core/commands.js
> +			this.afterRun( command, args, meta, results );
Fix order

2023-03-26 16:56 UTC, matipojo commented on modules/web-cli/assets/js/core/commands.js
> +                meta
```suggestion
				meta
```

2026-06-02 06:36 UTC, closed without merging