Internal: Usage - Fixes for Add additional Usage data [ED-1229]
elementor/elementor pull request #18687
Opened 2022-05-19 04:50 UTC by iNewLegend

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2022-05-24 08:59 UTC, matipojo requested changes
Test repeater value / multidimensional

2022-05-24 08:59 UTC, matipojo commented on includes/base/controls-stack.php
> -use Elementor\Core\Breakpoints\Manager as Breakpoints_Manager;
Restore

2022-05-24 08:59 UTC, matipojo commented on modules/usage/module.php
> +			delete_option( self::DOCUMENT_OPTION_NAME ); // Since recalc triggers save witch increases the usage of documents.
```suggestion
			delete_option( self::DOCUMENT_OPTION_NAME ); // Since recalc triggers save which increases the usage of documents.
```

2022-05-25 05:05 UTC, iNewLegend commented on modules/usage/module.php
> +			delete_option( self::DOCUMENT_OPTION_NAME ); // Since recalc triggers save witch increases the usage of documents.
https://github.com/elementor/elementor/pull/18687/commits/931f2a44ab0ebf2e73eef7b59c7e7796ca06c443

2022-05-25 05:05 UTC, iNewLegend commented on includes/base/controls-stack.php
> +
https://github.com/elementor/elementor/pull/18687/commits/931f2a44ab0ebf2e73eef7b59c7e7796ca06c443

2022-05-25 05:05 UTC, iNewLegend commented on includes/base/controls-stack.php
> -use Elementor\Core\Breakpoints\Manager as Breakpoints_Manager;
https://github.com/elementor/elementor/pull/18687/commits/931f2a44ab0ebf2e73eef7b59c7e7796ca06c443

2022-05-25 06:03 UTC, iNewLegend commented
> Test repeater value / multidimensional

Repeater value does not exist, repeater always multidimensional and its already tested here:
https://github.com/elementor/elementor/blob/feature/documents-usage-data/tests/phpunit/elementor/modules/usage/test-module.php#L131

2022-05-26 10:53 UTC, matipojo requested changes

2022-05-26 10:53 UTC, matipojo commented on core/base/document.php
> +		static $blacklist = [
```suggestion
		static $ignore_list = [
```

2022-05-31 10:27 UTC, matipojo requested changes

2022-05-31 10:27 UTC, matipojo commented on core/breakpoints/manager.php
> +	public static function get_backwards_compatability_config() {
It's used only in the kit, maybe move it as a private method in the kit?

2022-06-19 14:48 UTC, matipojo requested changes

2022-06-19 14:48 UTC, matipojo commented on core/kits/documents/tabs/settings-layout.php
> +use Elementor\Core\Breakpoints\Manager;
```suggestion
```

2022-06-19 14:48 UTC, matipojo commented on core/kits/documents/tabs/settings-layout.php
> +			$this->add_control( Manager::BREAKPOINT_SETTING_PREFIX . $key, [ 'type' => Controls_Manager::HIDDEN ] );
```suggestion
		foreach ( array_keys( Breakpoints_Manager::get_backwards_compatability_config() ) as $key ) {
			$this->add_control( Breakpoints_Manager::BREAKPOINT_SETTING_PREFIX . $key, [ 'type' => Controls_Manager::HIDDEN ] );
```

2022-06-19 14:52 UTC, merged