Internal: Editor - Allow in-place editing [ED-7272]
elementor/elementor pull request #18716
Opened 2022-05-23 13:53 UTC by Nevoss

2022-05-24 08:24 UTC, matipojo requested changes

2022-05-24 12:42 UTC, Nevoss commented on assets/dev/js/frontend/documents-manager.js
> +		let documentElements = $parentEl.find( this.getSettings( 'selectors' ).document )
this.elements.$documents changed over time, it saves the documents from the first render, but a widget can be changed and documents can be created over time.

2022-06-06 16:45 UTC, matipojo requested changes
Please cover with tests

2022-06-07 07:44 UTC, Nevoss commented on assets/dev/js/editor/elements/views/widget.js
> +		}
So here I will trigger an event?

2022-06-08 15:37 UTC, Nevoss commented
Changed the way we approach it.

2022-06-08 15:37 UTC, closed without merging