New: Nested elements experiment [ED-2256]
elementor/elementor pull request #18728
Opened 2022-05-24 09:49 UTC by iNewLegend

2022-05-29 10:02 UTC, matipojo requested changes
Please fix the checks errors

2022-06-16 14:10 UTC, matipojo requested changes

2022-06-16 14:10 UTC, matipojo commented on modules/nested-elements/assets/js/editor/nested-repeater/hooks/data/document/elements/move/nested-repeater-prevent-moving-building-block-containers.js
> +export class NestedRepeaterPreventMovingBuildingBlockContainers extends $e.modules.hookData.Dependency {
We should create an infra for `locked` element that can't be moved.

2022-06-19 09:36 UTC, matipojo requested changes

2022-06-19 09:36 UTC, matipojo commented on assets/dev/js/frontend/preloaded-modules.js
> +		'tabs-v2.default': TabsV2,
Only if the experiment is on

2022-06-19 09:36 UTC, matipojo commented on modules/nested-elements/assets/js/editor/nested-repeater/component.js
> +		elementor.addControlView( 'nested-elements-repeater', RepeaterControl );
Move to the module

2022-06-19 09:36 UTC, matipojo commented on modules/nested-elements/assets/js/editor/nested-repeater/hooks/data/document/elements/move/nested-repeater-prevent-moving-building-block-containers.js
> +export class NestedRepeaterPreventMovingBuildingBlockContainers extends $e.modules.hookData.Dependency {
See [ED-7366]

2022-06-19 09:36 UTC, matipojo commented on modules/nested-elements/assets/js/editor/nested-repeater/hooks/data/document/repeater/insert/nested-repeater-create-container.js
> +import Base from '../../../base';
Try to create a command for it instead of a hook

2022-06-19 09:36 UTC, matipojo commented on modules/tabs-v2/assets/js/editor/index.js
> +	new ( await import( '../editor/module' ) ).default();
Replace with an event from the `nestedElements` and a listener here

2022-06-19 09:36 UTC, matipojo commented on modules/tabs-v2/assets/js/editor/views/view.js
> +/**
Should be moved to the `nested` infra.

2022-06-22 14:19 UTC, matipojo commented on modules/nested-elements/assets/js/editor/nested-repeater/component.js
> +	getChildrenTitle( container, index ) {
Move to the module

2022-06-22 14:20 UTC, matipojo commented on modules/nested-elements/assets/js/editor/component.js
> +export default class Component extends $e.modules.ComponentBase {
Try to move to the module

2022-06-28 07:43 UTC, Nevoss approved these changes, later dismissed

2022-11-15 14:24 UTC, closed without merging