Internal: Update Container Docs [ED-3174]
elementor/elementor pull request #18749
Opened 2022-05-26 08:52 UTC by iNewLegend

2022-05-26 11:06 UTC, StyleShit requested changes

2022-05-26 11:06 UTC, StyleShit commented on docs/includes/elements/container.md
> +		return Model;
Can you explain about those values?

2022-05-29 09:57 UTC, iNewLegend commented on docs/assets/dev/js/editor/elements/manager.md
> +			};
I don't know, @matipojo, maybe you know?

2022-05-29 10:29 UTC, iNewLegend commented on docs/includes/elements/container.md
> +		return Model;
In the `manager.md`

2022-05-29 10:29 UTC, iNewLegend commented on docs/assets/dev/js/editor/elements/manager.md
> +- #### Example of registering a container element.
Handled.

2022-05-29 10:29 UTC, iNewLegend commented on docs/assets/dev/js/editor/elements/manager.md
> +elementor.elementsManager.registerElementType( new class extends elementor.elements.types.Base {} );
Handled.

2022-05-29 10:29 UTC, iNewLegend commented on docs/assets/dev/js/editor/elements/manager.md
> + - #### The capabilities
too

2022-05-31 12:18 UTC, matipojo requested changes

2022-05-31 12:18 UTC, matipojo commented on docs/assets/dev/js/editor/elements/manager.md
> +> Note: `elementor.elementsManager` is managing the elements only in the editor JS.
```suggestion
```

2022-05-31 12:18 UTC, matipojo commented on docs/assets/dev/js/editor/elements/manager.md
> +* **Description**: The Elements Manager is a global object that handles all the elements in the editor.
```suggestion
* **Description**: The Elements Manager is a global object that handles all the element types in the editor.
```

2022-05-31 12:18 UTC, matipojo commented on docs/assets/dev/js/editor/elements/manager.md
> +  > `elementor.elements.types.Base` is external of `ElementBase` class.
```suggestion
  > `elementor.elements.types.Base` is the global expose of `ElementBase` class.
```

2022-05-31 12:18 UTC, matipojo commented on docs/assets/dev/js/editor/elements/manager.md
> +### How to register a new element? and what are the capabilities it brings?
### How to register a new element type?
```

2022-05-31 12:18 UTC, matipojo commented on docs/assets/dev/js/editor/elements/manager.md
> +* To register a new element, you need to create a new class that extends the `elementor.elements.types.Base` class, eg:
```suggestion
* To register a new element type, you need to create a new class that extends the `elementor.elements.types.Base` class, eg:
```

2022-05-31 12:18 UTC, matipojo commented on docs/assets/dev/js/editor/elements/manager.md
> +#### Externals:
```suggestion
#### Global access:
```

2022-05-31 12:18 UTC, matipojo commented on docs/assets/dev/js/editor/elements/manager.md
> +}
Replace with links to the existing code

2022-05-31 12:18 UTC, matipojo commented on docs/includes/elements/container.md
> +```
Replace with a link

2022-06-15 04:59 UTC, iNewLegend commented on docs/assets/dev/js/editor/elements/manager.md
> +### How to register a new element? and what are the capabilities it brings?
Handled

2022-06-15 05:00 UTC, iNewLegend commented on docs/assets/dev/js/editor/elements/manager.md
> +}
Why?

2022-06-15 05:00 UTC, iNewLegend commented on docs/includes/elements/container.md
> +```
Why?

2026-06-02 06:36 UTC, closed without merging