Tweak: Add "Skip & Deactivate" text button to deactivation survey
elementor/elementor pull request #18779
Opened 2022-05-29 12:46 UTC by mark-elementor

2022-05-29 13:15 UTC, ManorHazaz requested changes

2022-05-29 13:15 UTC, ManorHazaz commented on assets/dev/js/admin/admin-feedback.js
> -							if ( ! elementorAdmin.config.feedback.is_tracker_opted_in ) {
Maybe we also should delete the `is_tracker_opted_in` from the config if we no longer using it?

2022-05-29 13:40 UTC, ManorHazaz approved these changes

2022-06-02 13:37 UTC, yossi-elementor requested changes

2022-06-02 13:37 UTC, yossi-elementor commented on core/admin/feedback.php
> -	protected function get_init_settings() {
If the whole method was removed, shouldn't we handle the places that invoked this method?

2022-06-02 13:56 UTC, yossi-elementor commented on core/admin/feedback.php
> -	protected function get_init_settings() {
Answered: no need.

2022-06-02 13:56 UTC, yossi-elementor approved these changes

2022-06-02 13:56 UTC, merged