Internal: Elements State [ED-7244]
elementor/elementor pull request #18809
Opened 2022-06-01 05:12 UTC by StyleShit

2022-06-01 06:15 UTC, ManorHazaz commented on assets/dev/js/editor/document/elements/commands/delete.js
> +	static reducer( state, { payload } ) {
``
```suggestion
	}
	
	static reducer( state, { payload } ) {
```

2022-06-01 15:51 UTC, matipojo requested changes
🔥

2022-06-02 04:47 UTC, StyleShit commented on assets/dev/js/editor/document/elements/commands-internal/populate.js
> +			$e.store.get( 'document/elements' ).actions.populate( {
Done

2022-06-02 04:48 UTC, StyleShit commented on assets/dev/js/editor/document/elements/commands-internal/populate.js
> +		const { documentId, elements } = args;
It happens in the `$e.internal( 'document/load' )` command. I don't know if (and how) we can combine them

2022-06-02 04:49 UTC, StyleShit commented on assets/dev/js/editor/document/elements/commands-internal/set-settings.js
> +		};
Just to avoid nesting, but OK 🤷

2022-06-02 04:50 UTC, StyleShit commented on assets/dev/js/editor/document/elements/commands/delete.js
> +		if ( ! state[ documentId ] ) {
Done

2022-06-02 04:50 UTC, StyleShit commented on assets/dev/js/editor/document/elements/commands/empty.js
> +				// TODO: Find a better solution - Try to remove the `addChildModel()` call, and use some command.
Done

2022-06-02 04:51 UTC, StyleShit commented on assets/dev/js/editor/document/hooks/data/document/elements/helper.js
> +				$e.store.dispatch(
As long as we keep the original shape of the Container, it should be fine. Plus, it's a legacy code for Sections which would probably get removed when we'll use the new state

2022-06-02 04:55 UTC, StyleShit commented on tests/jest/unit/assets/dev/js/editor/document/elements/commands-internal/populate.test.js
> +						},
It doesn't really matter since it's recursive.. but OK..

2022-06-02 04:58 UTC, StyleShit commented on tests/jest/unit/assets/dev/js/editor/document/elements/commands-internal/populate.test.js
> +} );
Done

2022-06-06 10:59 UTC, matipojo requested changes

2022-06-06 10:59 UTC, matipojo commented on assets/dev/js/editor/document/elements/commands-internal/populate.js
> +		const { documentId, elements } = args;
Please give a try. Add the code to the command, and call the command from `$e.internal( 'document/load' )`

2022-06-12 11:38 UTC, StyleShit commented on assets/dev/js/editor/document/elements/commands-internal/populate.js
> +		const { documentId, elements } = args;
Done

2022-06-12 11:40 UTC, StyleShit commented on assets/dev/js/editor/document/elements/commands-internal/populate.js
> +	validateArgs( args = {} ) {
```suggestion
	validateArgs() {
```

2022-06-12 11:40 UTC, StyleShit commented on tests/jest/unit/assets/dev/js/editor/document/elements/commands/empty.test.js
> +import { createContainer, mockElementsComponent } from '../mock/component';
```suggestion
import { mockElementsComponent } from '../mock/component';
```

2022-06-12 11:40 UTC, StyleShit commented on assets/dev/js/editor/document/elements/commands-internal/populate.js
> +		elementor.initPreviewView( document );
```suggestion
		elementor.initElements();
		elementor.initPreviewView( document );
```

2022-06-16 08:58 UTC, matipojo requested changes

2022-06-16 08:58 UTC, matipojo commented on assets/dev/js/editor/components/documents/commands/internal/attach-preview.js
> +			$e.internal( 'document/elements/populate', {
Only init the elements

2022-06-16 16:31 UTC, merged