Ed 7310 internal context menu api
elementor/elementor pull request #18828
Opened 2022-06-02 08:13 UTC by nahmana

2022-06-06 10:32 UTC, matipojo requested changes
Please add manager.md

2022-06-06 10:32 UTC, matipojo commented on packages/context-menu/manager.js
> +			dimensions,
Remove

2022-06-06 10:32 UTC, matipojo commented on packages/context-menu/manager.js
> +		return rootGroups.map( ( rGroup ) => {
```suggestion
		return rootGroups.map( ( rootGroup ) => {
```

2022-06-06 10:32 UTC, matipojo commented on packages/context-menu/manager.js
> +		this.groups = this.groups.map( ( group ) => {
Please update only the selected group

2022-06-06 10:32 UTC, matipojo commented on packages/context-menu/manager.js
> +		this.groups = this.groups.map( ( group ) => {
Please use `updateGroup`

2022-06-06 10:32 UTC, matipojo commented on packages/context-menu/manager.js
> +		this.groups = this.groups.map( ( group ) => {
Use `updateGroup`

2022-06-07 12:00 UTC, nahmana commented on packages/context-menu/manager.js
> +		return rootGroups.map( ( rGroup ) => {
Done.

2022-06-07 12:00 UTC, nahmana commented on packages/context-menu/manager.js
> +		this.groups = this.groups.map( ( group ) => {
Done.

2022-06-07 12:01 UTC, nahmana commented on packages/context-menu/manager.js
> +		this.groups = this.groups.map( ( group ) => {
Done.

2022-06-07 12:01 UTC, nahmana commented on packages/context-menu/manager.js
> +		this.groups = this.groups.map( ( group ) => {
Done.

2022-06-08 10:18 UTC, StyleShit requested changes

2022-06-08 10:21 UTC, nahmana commented on packages/context-menu/manager.js
> +export class ContextMenuManager {
Done.

2022-06-08 10:24 UTC, nahmana commented on packages/context-menu/manager.js
> +export class ContextMenuManager {
Done

2022-06-08 12:40 UTC, nahmana commented on packages/context-menu/manager.js
> +		return rootGroups.map( ( rootGroup ) => {
Done.

2022-06-08 12:49 UTC, nahmana commented on packages/context-menu/manager.js
> +			return rootGroup;
No.

2022-06-08 14:21 UTC, nahmana commented on packages/context-menu/manager.js
> +		this.groups.push( { ...structuredClone( this.groupDefault ), ...newGroup } );
Done.

2022-06-08 14:22 UTC, nahmana commented on packages/context-menu/manager.js
> +	};
No.

2022-06-08 14:41 UTC, nahmana commented on packages/context-menu/manager.js
> +		this.updateGroupData( groupId, groupData );
There is a reason for the `updateGroup` /  `updateGroupData` duplication.
When updating **a group** directly - the group properties must be sanitized first, the method `updateGroup` is used for the API, and will be called from 3P, which cannot directly add items[], etc.

But when updating a group when updating an item - the group must not be sanitized, so for 'internal' uses - `updateGroupData` is the best choice.

2022-06-08 14:44 UTC, nahmana commented on packages/context-menu/manager.js
> +		this.updateGroupData( groupId, groupData );
see `updateItem()` method, that uses the smethod  `updateGroupData` and cannot use the `updateGroup`.

2022-06-08 14:54 UTC, nahmana commented on packages/context-menu/manager.js
> +		this.groups[ groupIndex ] = { ...this.groups[ groupIndex ], ...groupData };
No. Mati wanted to update the specific group without iterating through the entire groups and re-assigning the groups. 
see above, I implemented exactly what you purpose, he ask me to change.

2022-06-08 14:57 UTC, nahmana commented on packages/context-menu/manager.js
> +		}
As above, the findIndex is required, so must check it returns a valid index.

2022-06-08 14:58 UTC, nahmana commented on packages/context-menu/manager.js
> +		this.groups[ groupIndex ].items.push( { ...structuredClone( this.itemDefault ), ...newItem } );
Done, without the map.

2022-06-08 14:59 UTC, nahmana commented on packages/context-menu/manager.js
> +		}
No, as above.

2022-06-08 14:59 UTC, nahmana commented on packages/context-menu/manager.js
> +		this.updateGroupData( groupId, currentGroup );
No, again :)

2022-06-08 15:00 UTC, nahmana commented on packages/context-menu/manager.js
> +		this.updateGroupData( groupId, currentGroup );
No, again.

2022-06-08 15:04 UTC, nahmana commented on tests/jest/unit/packages/context-menu/manager.test.js
> +	test( 'Check main flow', () => {
Lets talk about it...

2022-06-09 09:16 UTC, nahmana commented on tests/jest/unit/packages/context-menu/manager.test.js
> +		const manager = new ContextMenuManager();
Done.

2022-06-09 09:19 UTC, nahmana commented on tests/jest/unit/packages/context-menu/manager.test.js
> +		expect( manager.getConfig( {} ) ).toEqual( [
Done.

2022-06-09 09:23 UTC, nahmana commented on packages/context-menu/manager.js
> +		mouseLeave: null,
Done.

2022-06-09 09:23 UTC, nahmana commented on tests/jest/unit/packages/context-menu/manager.test.js
> +		expect( manager.getConfig( {} ) ).toEqual( [
Done.

2022-06-09 09:27 UTC, nahmana commented on packages/context-menu/manager.js
> +		parentItemId: '',
Parent id indicates the tree structure - to know who is the parent.
We decided that it is faster and more convenient to add it to the child and not to the parent.

2022-06-09 09:31 UTC, nahmana commented on tests/jest/unit/packages/context-menu/manager.test.js
> +	test( 'updateGroup', () => {
Done.

2022-06-12 06:46 UTC, StyleShit requested changes

2022-06-12 08:00 UTC, nahmana commented on tests/jest/unit/packages/context-menu/manager.test.js
> +	test( 'Check main flow', () => {
Done.

2022-06-12 08:01 UTC, nahmana commented on packages/context-menu/ContextMenuManager.js
> +		const currentGroup = this.groups.find( ( group ) => group.id === groupId );
Done.

2022-06-12 08:03 UTC, nahmana commented on packages/context-menu/ContextMenuManager.js
> +		if ( ! newItem.id || ! this.groups[ groupIndex ] || this.itemExists( groupId, newItem.id ) ) {
Done.

2022-06-12 08:05 UTC, nahmana commented on packages/context-menu/ContextMenuManager.js
> +export class ContextMenuManager {
Done.

2022-06-12 12:10 UTC, StyleShit requested changes

2022-06-12 12:10 UTC, StyleShit commented on tests/jest/unit/packages/context-menu/context-menu-manager.js
> +	test( 'Should test validation of not existing', () => {
```suggestion
	test( 'Should test validation of not existing groups', () => {
```

2022-06-12 12:10 UTC, StyleShit commented on tests/jest/unit/packages/context-menu/context-menu-manager.js
> +	test( 'Should check the main flow', () => {
```suggestion
	it( 'Should check the main flow', () => {
```

2022-06-12 12:10 UTC, StyleShit commented on tests/jest/unit/packages/context-menu/context-menu-manager.js
> +	test( 'Should  not displaying groups that their parentItemId points to non-existing items', () => {
```suggestion
	test( 'Should not display groups that their parentItemId points to non-existing items', () => {
```

2022-06-12 12:10 UTC, StyleShit commented on tests/jest/unit/packages/context-menu/context-menu-manager.js
> +	test( 'Should  not displaying groups that their parentItemId points to non-existing items', () => {
also others

2022-06-12 12:10 UTC, StyleShit commented on tests/jest/unit/packages/context-menu/context-menu-manager.js
> +	test( 'Should test validation of not authorized properties', () => {
```suggestion
	test( 'Should test validation of unauthorized properties', () => {
```

2022-06-12 12:23 UTC, nahmana commented on tests/jest/unit/packages/context-menu/context-menu-manager.js
> +	test( 'updateGroup', () => {
Done.

2022-06-12 12:23 UTC, nahmana commented on tests/jest/unit/packages/context-menu/context-menu-manager.js
> +	test( 'Should test validation of not existing', () => {
Done.

2022-06-12 12:24 UTC, nahmana commented on tests/jest/unit/packages/context-menu/context-menu-manager.js
> +	test( 'Should check the main flow', () => {
Done.

2022-06-12 12:25 UTC, nahmana commented on tests/jest/unit/packages/context-menu/context-menu-manager.js
> +	test( 'Should  not displaying groups that their parentItemId points to non-existing items', () => {
Done.

2022-06-12 12:26 UTC, nahmana commented on tests/jest/unit/packages/context-menu/context-menu-manager.js
> +	test( 'Should test validation of not authorized properties', () => {
Done.

2022-06-12 12:54 UTC, StyleShit requested changes

2022-06-12 12:54 UTC, StyleShit commented on tests/jest/unit/packages/context-menu/context-menu-manager.js
> +	test( 'Should update a group', () => {
```suggestion
	it( 'Should update a group', () => {
```

also others.....

2022-06-12 13:54 UTC, nahmana commented on tests/jest/unit/packages/context-menu/context-menu-manager.js
> +	test( 'Should update a group', () => {
Done.

2022-06-13 04:52 UTC, StyleShit requested changes

2022-06-13 04:52 UTC, StyleShit commented on tests/jest/unit/packages/context-menu/context-menu-manager.js
> +import { ContextMenuManager } from 'elementor/packages/context-menu/context-menu-manager';
rename the file to `.test.js`...

2022-06-13 11:01 UTC, nahmana commented on tests/jest/unit/packages/context-menu/context-menu-manager.js
> +import { ContextMenuManager } from 'elementor/packages/context-menu/context-menu-manager';
Done.

2022-06-13 12:30 UTC, StyleShit approved these changes

2026-06-02 06:36 UTC, closed without merging