Tweak : Add action hook before load Elementor dynamic css
elementor/elementor pull request #18846
Opened 2022-06-05 10:11 UTC by manzurahammed

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary
Add an action hook before loading dynamic assets in Elemenor 

## Description
Please check this issue https://github.com/elementor/elementor/issues/18845

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [x] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2022-06-05 10:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/elementor/elementor?pullRequest=18846) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/elementor/elementor?pullRequest=18846) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/elementor/elementor?pullRequest=18846) it.</sub>

2022-06-26 16:08 UTC, rami-elementor commented
I like the direction of this PR, but in order make the enqueue hooks consistent with similar Elementor hooks, I suggest to use the `before` and `after` prefixes for the two hooks in this method.

* `do_action( "elementor/css-file/{$name}/before-enqueue", $this );`
* `do_action( "elementor/css-file/{$name}/after-enqueue", $this );`

2022-07-04 09:20 UTC, manzurahammed commented
Hi @rami-elementor 
I have changed the hook's name. 
Could you please review this?

2022-07-13 11:20 UTC, manzurahammed commented
Hi @rami-elementor as per your instruction, I have changed the deprecate hook version 3.6.8 to 3.8.0.
could you please check?

2022-08-30 10:07 UTC, rudlinkon requested changes
Please update the `@since version`

2022-08-30 10:07 UTC, rudlinkon commented on core/files/css/base.php
> +		 * @since 3.6.8
```suggestion
		 * @since 3.8.0
```

2022-08-30 10:07 UTC, rudlinkon commented on core/files/css/base.php
> +		 * @since 3.6.8
```suggestion
		 * @since 3.8.0
```

2022-10-10 09:46 UTC, rudlinkon commented
Thank you @manzurahammed for your changes. @matipojo can you check, please?

2022-10-10 09:46 UTC, rudlinkon approved these changes
LGTM

2025-10-15 06:40 UTC, closed without merging