Internal: Added elements selection state [ED-7518]
elementor/elementor pull request #19022
Opened 2022-06-28 05:06 UTC by StyleShit

2022-06-28 13:18 UTC, StyleShit commented on assets/dev/js/editor/document/elements/component.js
> +		elementor.once( 'document:loaded', () => {
@matipojo 
Do you think there is a better event for that?

2022-06-30 09:02 UTC, matipojo requested changes

2022-06-30 10:27 UTC, StyleShit commented on assets/dev/js/editor/document/elements/commands/select-all.js
> +				return elementor.getContainer( element.id );
Done

2022-06-30 11:21 UTC, StyleShit commented on assets/dev/js/editor/document/elements/component.js
> +		elementor.once( 'document:loaded', () => {
Done

2022-06-30 11:22 UTC, StyleShit commented on assets/dev/js/editor/document/elements/component.js
> +			$e.store.subscribe( () => {
Done

2022-06-30 11:22 UTC, StyleShit commented on assets/dev/js/editor/document/elements/utils.js
> +	updateNavigator();
Done

2022-06-30 11:23 UTC, StyleShit commented on assets/dev/js/editor/document/elements/selectors.js
> +		}
Can't

2023-05-31 05:13 UTC, closed without merging