Tweak: Added default padding to containers [ED-7593]
elementor/elementor pull request #19111
Opened 2022-07-07 16:47 UTC by hein-obox

2022-07-11 13:33 UTC, udidol requested changes

2022-07-11 15:29 UTC, hein-obox commented on assets/dev/scss/frontend/_container.scss
> +
fixed

2022-07-11 15:41 UTC, hein-obox commented on assets/dev/scss/frontend/_container.scss
> +	--container-default-padding-left: 10px;
@udidol 

Default padding variable: removed. 

`Advanced > Layout > Padding: ` 
- My padding is the default padding css variable: `--padding-top: var( --container-default-padding-top, 10px );`
- The default padding overwritten with the container padding set in the advanced control: `padding-top: var( --padding-top );`

2022-07-12 06:27 UTC, udidol requested changes

2022-07-12 06:27 UTC, udidol commented on core/kits/documents/tabs/settings-layout.php
> +
remove empty line

2022-07-12 07:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/elementor/elementor?pullRequest=19111) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/elementor/elementor?pullRequest=19111) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: matipojo<br/>:white_check_mark: heinvv-abangani<br/>:white_check_mark: mark-elementor<br/>:x: elementorbot<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/elementor/elementor?pullRequest=19111) it.</sub>

2022-07-12 07:05 UTC, hein-obox commented on core/kits/documents/tabs/settings-layout.php
> +
updated

2022-07-12 07:37 UTC, closed without merging