chore: Add support link while opening an issue
elementor/elementor pull request #19154
Opened 2022-07-14 07:59 UTC by sulunemre

Issue template chooser menu items require a URL otherwise they are not shown to to the user.
This PR adds the missing URL for Support.

Here, `❓ Support Question` doesn't appear.
![image](https://user-images.githubusercontent.com/17709306/178932054-ed1a7996-26bd-4eb8-9e83-7dec7d5a4e20.png)

2022-07-14 07:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/elementor/elementor?pullRequest=19154) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/elementor/elementor?pullRequest=19154) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/elementor/elementor?pullRequest=19154) it.</sub>

2022-07-27 11:21 UTC, sulunemre commented
Hi @KingYes , this is a very trivial change and can be merged quickly.

2022-08-24 10:06 UTC, KingYes requested changes

2022-08-24 10:06 UTC, KingYes commented on .github/ISSUE_TEMPLATE/config.yml
> +    url: https://wordpress.org/support/plugin/elementor
```suggestion
    url: https://wordpress.org/support/plugin/elementor/
```

2022-08-24 10:06 UTC, KingYes commented on .github/ISSUE_TEMPLATE/config.yml
>      url: https://wordpress.org/support/plugin/elementor
```suggestion
    url: https://elementor.com/support/
```

2022-08-24 10:09 UTC, merged

2022-08-24 10:09 UTC, KingYes commented
Thanks!