Internal: Merge loop builder CORE to 3.8 CORE [ED-7714]
elementor/elementor pull request #19193
Opened 2022-07-18 13:33 UTC by TzviRabinovitch

2022-07-21 08:06 UTC, StyleShit requested changes

2022-07-21 08:06 UTC, StyleShit commented on includes/admin-templates/new-template.php
> +			wp_add_inline_script( 'elementor-admin', 'var elementor_new_template_form_controls = ' . wp_json_encode( $additional_controls ) . ';' );
```suggestion
			wp_add_inline_script( 'elementor-admin', 'const elementor_new_template_form_controls = ' . wp_json_encode( $additional_controls ) . ';' );
```

2022-07-21 08:06 UTC, StyleShit commented on includes/template-library/forms/new-template-form.php
> +					throw new \Exception( 'Not supported control type' );
```suggestion
					throw new \Exception( '"' . $control['type'] . '" control type is not supported );
```

Maybe?

2022-07-21 08:06 UTC, StyleShit commented on includes/template-library/forms/new-template-form.php
> +		<div id="<?php echo esc_html( $control_id ); ?>__wrapper" class="elementor-form-field <?php echo esc_html( $wrapper_class ); ?>">
```suggestion
		<div id="<?php echo esc_attr( $control_id ); ?>__wrapper" class="elementor-form-field <?php echo esc_attr( $wrapper_class ); ?>">
```

also others

2022-07-28 12:21 UTC, matipojo requested changes

2022-07-28 12:21 UTC, matipojo commented on assets/dev/js/admin/new-template/layout.js
> +			elementorAdmin.templateControls.setDynamicFieldsVisibility( lookupControlIdPrefix, elementor_new_template_form_controls );
```suggestion
			dynamicFieldsVisibilityListener();
```

2022-07-28 12:21 UTC, matipojo commented on assets/dev/js/admin/new-template/template-controls.js
> +	setDynamicFieldsVisibility( lookupControlIdPrefix, controls ) {
```suggestion
	setDynamicControlsVisibility( lookupControlIdPrefix, controls ) {
```

2022-07-28 12:21 UTC, matipojo commented on core/admin/admin.php
> +		}
Insert before the filter

2022-08-04 07:29 UTC, StyleShit requested changes

2022-08-04 07:29 UTC, StyleShit commented on assets/dev/js/editor/components/documents/commands/internal/attach-preview.js
> +		const { selector = '.elementor-' + document.id, scroll = true } = args;
```suggestion
		const { selector = '.elementor-' + document.id, shouldScroll = true } = args;
```
Maybe?

2022-08-04 07:29 UTC, StyleShit commented on core/base/document.php
> +		// apply this filter to allow the attributes to be modified by different sources
kinda redundant

2022-08-14 10:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/elementor/elementor?pullRequest=19193) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/elementor/elementor?pullRequest=19193) before we can accept your contribution.<br/>**16** out of **17** committers have signed the CLA.<br/><br/>:white_check_mark: StuartElementor<br/>:white_check_mark: TzviRabinovitch<br/>:white_check_mark: rodolphebertozzo<br/>:white_check_mark: udidol<br/>:white_check_mark: matipojo<br/>:white_check_mark: davseve<br/>:white_check_mark: maork-elementor<br/>:white_check_mark: StyleShit<br/>:white_check_mark: hein-obox<br/>:white_check_mark: guyc-E<br/>:white_check_mark: yotamselementor<br/>:white_check_mark: louiswol94<br/>:white_check_mark: arielk<br/>:white_check_mark: ManorHazaz<br/>:white_check_mark: shilo-ey<br/>:white_check_mark: ramiy<br/>:x: elementorbot<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/elementor/elementor?pullRequest=19193) it.</sub>

2022-08-31 04:39 UTC, TzviRabinovitch commented on core/admin/admin.php
> +		}
done

2022-08-31 04:41 UTC, TzviRabinovitch commented on assets/dev/js/editor/components/documents/commands/internal/attach-preview.js
> +		const { selector = '.elementor-' + document.id, scroll = true } = args;
Done

2022-08-31 04:42 UTC, TzviRabinovitch commented on assets/dev/js/admin/new-template/template-controls.js
> +	setDynamicFieldsVisibility( lookupControlIdPrefix, controls ) {
Done

2022-08-31 04:44 UTC, TzviRabinovitch commented on assets/dev/js/admin/new-template/layout.js
> +			elementorAdmin.templateControls.setDynamicFieldsVisibility( lookupControlIdPrefix, elementor_new_template_form_controls );
Done

2022-08-31 05:46 UTC, merged