Fix: Notes - Promotion dialog not opening in Panel menu [ED-7744]
elementor/elementor pull request #19192
Opened 2022-07-18 11:58 UTC by mark-elementor

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Quality assurance

- [x] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2022-07-19 11:49 UTC, ManorHazaz submitted a review, later dismissed

2022-07-26 06:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/elementor/elementor?pullRequest=19192) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/elementor/elementor?pullRequest=19192) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: mark-elementor<br/>:x: yossi-elementor<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/elementor/elementor?pullRequest=19192) it.</sub>

2022-07-31 05:24 UTC, StyleShit requested changes

2022-07-31 05:24 UTC, StyleShit commented on modules/notes/assets/js/hooks/ui/panel/state-ready/notes-add-panel-menu-item.js
> +						top: '-3',
I think it should be:
```suggestion
						blockStart: '-3',
```

2022-08-03 07:16 UTC, merged