Tweak: Don't show exit-to modal if exit-to value was changed [ED-7484]
elementor/elementor pull request #19279
Opened 2022-07-27 11:40 UTC by davseve

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2022-07-31 06:30 UTC, ManorHazaz requested changes
🔥

2022-07-31 06:30 UTC, ManorHazaz commented on assets/dev/js/editor/regions/panel/pages/menu/menu.js
> +	if ( currentValue !== defaultValue || PanelMenu.exitShouldRedirect ) {
```suggestion

	if ( currentValue !== defaultValue || PanelMenu.exitShouldRedirect ) {
```
Just add space.

2022-07-31 10:03 UTC, ManorHazaz approved these changes, later dismissed

2022-07-31 10:09 UTC, ManorHazaz approved these changes

2022-08-02 13:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/elementor/elementor?pullRequest=19279) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/elementor/elementor?pullRequest=19279) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: davseve<br/>:x: yossi-elementor<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/elementor/elementor?pullRequest=19279) it.</sub>

2022-08-02 13:57 UTC, merged