New: Add the ability to add new classes for any document type [ED-7811]
elementor/elementor pull request #19272
Opened 2022-07-26 14:28 UTC by TzviRabinovitch

2022-07-27 12:11 UTC, udidol requested changes
Check PHPLint. Not sure why it is suddenly failing.

2022-07-27 12:11 UTC, udidol commented on core/base/document.php
> +		return apply_filters( 'elementor/document/container_attributes', $attributes, $this );
Please add doc for this explaining it

2022-07-27 13:38 UTC, StuartElementor commented
I merged in a fix for that php lint issue .all checks passed.

2022-07-28 08:41 UTC, TzviRabinovitch commented on core/base/document.php
> +		return apply_filters( 'elementor/document/container_attributes', $attributes, $this );
Done

2022-07-28 08:52 UTC, udidol commented on core/base/document.php
> +		// apply this filter to allow the attributes to be modified by different sources
```suggestion
		/**
		 * Document Container Attributes
		 *
		 * This filter allows modifying the HTML attributes on the document's wrapping tag
		 *
		 * @param array $attributes
		 * @param Document $this
		 */
```

2022-07-28 09:02 UTC, udidol approved these changes

2022-07-28 10:20 UTC, udidol approved these changes

2022-07-31 07:27 UTC, merged