Tweak: Add to the GoPro link URL from the Kit Library more UTM parameters [ED-7745]
elementor/elementor pull request #19336
Opened 2022-08-03 06:51 UTC by davseve

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2022-08-04 05:39 UTC, mark-elementor requested changes

2022-08-04 05:39 UTC, mark-elementor commented on core/app/modules/kit-library/assets/js/components/item-header.js
> +					let cleanTitle = model.title.replace( /[^\w\s]/g, '' ).replace( /\s/g, '-' ).toLowerCase();
- Should use `const` instead.
- What if the title already includes a dash? Would not it be better to switch the replaces?
`const cleanTitle = model.title.replace( /\s/g, '-' ).replace( /[^\w\s-]/g, '' ).toLowerCase();`

2022-08-04 05:39 UTC, mark-elementor commented on core/app/modules/kit-library/assets/js/components/item-header.js
> +				if ( model.title ) {
- I would add linebreaks before and after the `if` s for better readability.
- Is there a chance there will be no model.title or no model.id?

2022-08-04 05:39 UTC, mark-elementor commented on core/app/modules/kit-library/assets/js/components/item-header.js
> +				url: buildSubscriptionLink(),
I would call it something like "getButtonURL" instead.

2022-08-04 05:39 UTC, mark-elementor commented on core/common/modules/connect/module.php
> +				'promotion_url' => "https://elementor.com/pro/?utm_source=$context&utm_medium=wp-dash&utm_campaign=gopro",
Second thought on this - the variable can easily be mistaken for a part of the string here.
So for nobody to do a mistake here again, maybe it is better to do:
`'https://elementor.com/pro/?utm_source=' . $context . '&utm_medium=wp-dash&utm_campaign=gopro'`

2022-08-04 05:39 UTC, mark-elementor commented on core/common/modules/connect/module.php
> +				'promotion_url' => "https://elementor.com/pro/?utm_source=$context&utm_medium=wp-dash&utm_campaign=goexpert",
Same as above.

2022-08-04 12:33 UTC, mark-elementor approved these changes

2022-08-08 08:13 UTC, yossi-elementor approved these changes

2022-08-08 08:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/elementor/elementor?pullRequest=19336) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/elementor/elementor?pullRequest=19336) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: davseve<br/>:x: yossi-elementor<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/elementor/elementor?pullRequest=19336) it.</sub>

2022-08-08 11:44 UTC, merged