Internal: Restrict users from being able to create new Pro assets via Add New modal when license is inactive [ED-7730]
elementor/elementor pull request #19414
Opened 2022-08-10 08:56 UTC by StyleShit

2022-08-10 10:35 UTC, TzviRabinovitch approved these changes, later dismissed

2022-08-14 09:13 UTC, matipojo requested changes
Please cover with tests

2022-08-14 09:13 UTC, matipojo commented on assets/dev/js/admin/new-template/layout.js
> +			.replace( /%2\$s/g, 'wp-dash' );
{placeholder}

2022-08-14 09:13 UTC, matipojo commented on includes/admin-templates/new-template.php
> +							wp_json_encode( $lock_configs[ $value ] ),
```suggestion
							esc_attr( wp_json_encode( $lock_configs[ $value ] ) ),
```

2022-08-14 10:36 UTC, StyleShit commented on includes/admin-templates/new-template.php
> +							wp_json_encode( $lock_configs[ $value ] ),
PHPCS doesn't require it

2022-08-14 10:36 UTC, StyleShit commented on assets/dev/js/admin/new-template/layout.js
> +			.replace( /%2\$s/g, 'wp-dash' );
Done

2022-08-14 15:25 UTC, merged