Internal: Extract /core/apps library into the root directory [ED-7996]
elementor/elementor pull request #19576
Opened 2022-08-23 14:17 UTC by udidol

2022-08-24 12:08 UTC, matipojo requested changes
Please add BC for 3rd party plugins.
You can see some BC here:
https://github.com/matipojo/elementor/tree/b45e7fb45845f0328ebf9f44babb1933a7c42c04/core/app

2022-08-25 08:19 UTC, matipojo requested changes

2022-08-25 08:19 UTC, matipojo commented on core/app/modules/import-export/module.php
> +	}
Remove

2022-08-25 08:42 UTC, udidol commented on core/app/modules/import-export/module.php
> +	}
Done

2022-08-25 09:24 UTC, matipojo requested changes
Please resolve the conflicts

2022-08-25 09:24 UTC, matipojo commented on app/assets/js/ui/grid/grid.scss
> +// COMPONENT: GRID
Why it's considered as a new file? It's not a move of an existing file?

2022-08-25 09:24 UTC, matipojo commented on core/app/modules/kit-library/connect/kit-library.php
> +	public function is_connected() {
Mark the class and method as deprecated

2022-08-25 09:32 UTC, udidol commented on core/app/modules/kit-library/connect/kit-library.php
> +	public function is_connected() {
WIll mark all BC classes as deprecated

2022-08-25 09:35 UTC, udidol commented on core/app/modules/kit-library/connect/kit-library.php
> +	public function is_connected() {
Done @matipojo

2022-08-31 10:43 UTC, matipojo approved these changes

2022-09-04 10:58 UTC, merged