Fix: Background Image Custom X/Y Position and Custom Size controls not shown for Mobile/Tablet [ED-8126]
elementor/elementor pull request #19677
Opened 2022-09-01 10:01 UTC by udidol

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

* Fix: Background Image Custom X/Y Position and Custom Size controls not shown for Mobile/Tablet [ED-8126]

Fixes #19487 and #19669

2022-09-01 11:06 UTC, matipojo requested changes
Please cover with tests

2022-09-01 14:40 UTC, TzviRabinovitch approved these changes

2022-09-01 14:43 UTC, matipojo approved these changes

2022-09-01 14:44 UTC, merged

2022-09-02 18:01 UTC, mattmckenny commented
**Heads up. This "fix" breaks the frontend.**

The fix here to simply remove the `device_args` will fix the editor but breaks the frontend.`device_args` were removed from from the `_element_custom_width` control in includes/widgets/common.php and now custom sizing for tablet and mobile doesn't work if desktop is left as "default". Reference this:
https://github.com/elementor/elementor/issues/19528#issuecomment-1221177390

2022-09-05 06:42 UTC, udidol commented
@mattmckenny You are right, there is an additional problem that is related to handling `device_args`. A fix for that will be released in the upcoming patch version.