Tweak: Change default Google fonts loading method to "Swap" [ED-7896]
elementor/elementor pull request #19692
Opened 2022-09-04 06:46 UTC by maork-elementor

2022-09-04 07:06 UTC, arielk requested changes
@maork-elementor please change the new default **only** for **new** installs, not for all sites.

2022-09-04 08:36 UTC, maork-elementor commented
> @maork-elementor please change the new default **only** for **new** installs, not for all sites.
done

2022-09-04 09:44 UTC, matipojo requested changes
Please cover with tests

2022-09-04 09:44 UTC, matipojo commented on includes/fonts.php
> +		return get_option( 'elementor_font_display', $is_new_install ? 'swap' : 'auto' );
You don't need to compare the version, the code will be merged to 3.8.0

2022-09-04 11:36 UTC, matipojo requested changes
Please cover with tests

2022-09-04 11:36 UTC, matipojo commented on includes/maintenance.php
> +			if ( ! get_option( $option_name ) ) {
Validate it's not 0, `\Elementor\Utils::is_empty`

2022-09-04 11:36 UTC, matipojo commented on includes/maintenance.php
> +				update_option( $option_name, $option_value );
```suggestion
				add_option( $option_name, $option_value );
```

2022-09-04 11:43 UTC, matipojo requested changes

2022-09-04 11:43 UTC, matipojo commented on includes/maintenance.php
> +
Only for new installs

2022-09-05 12:02 UTC, maork-elementor commented
@matipojo 
Test added.

2022-09-05 13:19 UTC, matipojo requested changes

2022-09-05 13:19 UTC, matipojo commented on includes/settings/settings.php
> +									'std' => 'swap',
Revert

2022-09-06 11:33 UTC, merged