Fix: Custom Width on tablet/mobile generates wrong value when desktop is set to default [ED-8122]
elementor/elementor pull request #19700
Opened 2022-09-04 17:43 UTC by udidol

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

* Fix: Custom Width on tablet/mobile generates wrong value when desktop is set to default
* Fix: Conditions for responsive controls worked in the Editor but not in the frontend in some cases

## Description
An explanation of what is done in this PR

* Fixes #19542, #19528
* If a responsive control was conditioned upon a responsive control (Like in `Advanced > Layout > Width`), the conditioning was respected in the Editor, allowing you to edit the responsive values of the conditioned control when the condition was met. However, in such cases, non-desktop values did not get applied in the front end's CSS. That was the bug.

2022-09-05 14:14 UTC, TzviRabinovitch requested changes
tests?

2022-09-07 13:22 UTC, TzviRabinovitch commented on tests/phpunit/elementor/includes/base/test-controls-stack.php
> +		 * Arrange
duplicate comment

2022-09-07 13:23 UTC, TzviRabinovitch submitted a review, later dismissed

2022-09-08 10:28 UTC, TzviRabinovitch approved these changes

2022-09-08 10:29 UTC, merged

2022-09-08 11:26 UTC, Michaelgimii commented
@udidol , Are the following things addressed in this amendment? (as a reminder)

- Custom position & Size in background : https://prnt.sc/gw-mQJqGcFOR
- Custom position & Size in background overlay
- The above cases occur even in the background widgets. https://prnt.sc/xTlXFXBeWwb5

2022-09-08 12:28 UTC, udidol commented
@Michaelgimii All of these cases should be fixed by this ammendment.