wip
elementor/elementor pull request #19733
Opened 2022-09-07 11:05 UTC by yossi-elementor

2022-09-07 11:26 UTC, ManorHazaz requested changes

2022-09-07 11:26 UTC, ManorHazaz commented on assets/dev/scss/editor/panel/_menu.scss
> -		padding: 10px;
Will break the budge.

2022-09-08 05:27 UTC, StyleShit requested changes

2022-09-08 05:27 UTC, StyleShit commented on assets/dev/scss/editor/panel/_menu.scss
> +		  	padding: 10px 0 10px 10px;
Is it RTL friendly?

2022-09-08 05:27 UTC, StyleShit commented on assets/dev/scss/editor/panel/_menu.scss
> +		  	padding: 10px 10px 10px 0;
same as above

2022-09-12 07:57 UTC, yossi-elementor commented on assets/dev/scss/editor/panel/_menu.scss
> +		  	padding: 10px 0 10px 10px;
It is now. Thanks!

2022-09-12 07:57 UTC, yossi-elementor commented on assets/dev/scss/editor/panel/_menu.scss
> +		  	padding: 10px 10px 10px 0;
Same as above ;)

2022-09-12 11:37 UTC, ManorHazaz approved these changes

2022-09-12 11:37 UTC, ManorHazaz commented on assets/dev/scss/editor/panel/_menu.scss
> +		  	padding: 10px 0;
Redundant.

2022-09-12 11:46 UTC, merged