Internal: Elements Regression - Use config [ED-8228]
elementor/elementor pull request #19824
Opened 2022-09-15 16:37 UTC by Nevoss

TODO: 
- [x] Fix snapshot with space at the end
- [x] Try generate elements config dynamicly

2022-09-19 15:41 UTC, matipojo requested changes

2022-09-19 15:41 UTC, matipojo commented on tests/elements-regression/lib/controls/control-base.js
> +		if ( 'string' === typeof value && '' === value.trim() ) {
Explain

2022-09-19 15:41 UTC, matipojo commented on tests/elements-regression/lib/controls/control-base.js
> +		const toggleControlName = Object.keys( this.config?.condition )[ 0 ].replace( '!', '' );
Explain

2022-09-19 15:41 UTC, matipojo commented on tests/elements-regression/lib/controls/control-base.js
> +		return isObject( this.config.condition ) || isObject( this.config.conditions );
Explain

2022-09-19 15:41 UTC, matipojo commented on tests/elements-regression/lib/controls/index.js
> +	text: Text,
a-z

2022-09-19 15:41 UTC, matipojo commented on tests/elements-regression/lib/widgets/heading.js
> +const { Widget } = require( './widget' );
src

2022-09-19 15:41 UTC, matipojo commented on tests/elements-regression/playwright.config.js
> +		storageState: './tests/elements-regression/storage-state.json',
__dirname

2022-09-19 15:41 UTC, matipojo commented on tests/elements-regression/tests/elements-regression.test.js-snapshots/.gitignore
> +!*-linux.*
Revert

2022-09-19 15:41 UTC, matipojo commented on tests/elements-regression/tests/elements-regression.test.js
> +		// TODO: If the user use "grep" it will always fail.
Add a summary.

2022-09-20 05:13 UTC, Nevoss commented on tests/elements-regression/lib/controls/control-base.js
> +		if ( 'string' === typeof value && '' === value.trim() ) {
Done

2022-09-20 05:14 UTC, Nevoss commented on tests/elements-regression/lib/controls/control-base.js
> +		const toggleControlName = Object.keys( this.config?.condition )[ 0 ].replace( '!', '' );
Done

2022-09-20 05:16 UTC, Nevoss commented on tests/elements-regression/lib/controls/control-base.js
> +		return isObject( this.config.condition ) || isObject( this.config.conditions );
Done

2022-09-20 05:17 UTC, Nevoss commented on tests/elements-regression/lib/controls/index.js
> +	text: Text,
Done

2022-09-20 05:19 UTC, Nevoss commented on tests/elements-regression/lib/widgets/heading.js
> +const { Widget } = require( './widget' );
Done

2022-09-20 07:47 UTC, Nevoss commented on tests/elements-regression/playwright.config.js
> +		storageState: './tests/elements-regression/storage-state.json',
Done

2022-09-20 08:54 UTC, Nevoss commented on tests/elements-regression/tests/elements-regression.test.js
> +		// TODO: If the user use "grep" it will always fail.
Task: ED-8292

2022-09-20 11:34 UTC, StyleShit requested changes

2022-09-20 13:42 UTC, merged