Internal: Update PR template with quality action items
elementor/elementor pull request #19887
Opened 2022-09-22 14:53 UTC by yotamselementor

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2022-09-22 16:13 UTC, matipojo requested changes

2022-09-22 16:13 UTC, matipojo commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] I have tested this code against all the relevant Core versions
```suggestion
```

2022-09-28 05:30 UTC, StyleShit requested changes

2022-09-28 05:30 UTC, StyleShit commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] I have tested this code against relevant plugins
```suggestion
- [ ] I have tested this code against relevant 3rd party plugins
```

maybe?

2022-09-28 06:45 UTC, StyleShit approved these changes

2024-05-21 15:29 UTC, closed without merging