Fix: Custom background position not inherited on mobile and front end [ED-8329]
elementor/elementor pull request #19883
Opened 2022-09-22 08:42 UTC by udidol

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

* Fix: Custom background position not inherited on mobile and front end
* Fix: Responsive controls with responsive conditions whose values are arrays (Base Multiple) did not apply in the front end for non-desktop devices.

## Description
An explanation of what is done in this PR

* If a responsive control was conditioned upon another responsive control, and that conditioning control was a Base Multiple control (which means - the control value was an array(PHP)/object(JS) - such as Slider controls [size, unit]) - the responsive values were not applied in the front end

2022-09-22 08:52 UTC, udidol commented on includes/base/controls-stack.php
> -			if ( $condition_sub_key && is_array( $instance_value ) ) {
I moved this block up

2022-09-22 10:44 UTC, matipojo requested changes, later dismissed
Please cover with tests

2022-10-19 08:22 UTC, TzviRabinovitch approved these changes, later dismissed

2022-10-19 08:48 UTC, TzviRabinovitch approved these changes

2022-10-19 08:49 UTC, TzviRabinovitch approved these changes

2022-10-19 08:50 UTC, merged