Fix: Control Conditions - Using respon. values in selector placeholders causes fatal error [ED-8355]
elementor/elementor pull request #19934
Opened 2022-09-28 08:32 UTC by udidol

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

* Fix: Control Conditions - Using responsive control values in selectors and selector values causes a fatal error [ED-8355]

2022-09-29 09:43 UTC, kobizz requested changes

2022-09-29 09:43 UTC, kobizz commented on core/files/css/base.php
> +				$control = $controls_stack[ $parser_control_name . $device_suffix ] ?? $controls_stack[ $parser_control_name ];
When you want to set a condition that depends only on other's control desktop value, it won't work

2022-09-29 11:55 UTC, kobizz approved these changes

2022-10-02 08:00 UTC, TzviRabinovitch approved these changes

2022-10-02 08:01 UTC, merged