Fix. PHP errors caused by deprecation module
elementor/elementor pull request #20063
Opened 2022-10-17 14:05 UTC by gerasimovdaniel

## PR Checklist

- [x] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

* Fix. PHP errors caused by deprecation module

## Description
An explanation of what is done in this PR

* Deprecation module method [apply_deprecated_filter](https://github.com/elementor/elementor/blob/97f2db9d04a34dd3b1fc9fc101ab2536d6834528/modules/dev-tools/deprecation.php#L350) uses [apply_filters_ref_array](https://developer.wordpress.org/reference/functions/apply_filters_ref_array/) which expect the second argument to be an array of filter arguments, but in [/core/breakpoints/manager.php](https://github.com/elementor/elementor/blob/master/core/breakpoints/manager.php#L533)  actual value is given. It causes PHP errors when "Site Settings" is saved. In PHP 8.0+ it causes fatal errors.

## Test instructions
This PR can be tested by following these steps:

* Activate Elementor Pro
* Add global color in "Site Settings"
* Save

## Quality assurance

- [x] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #20062

2022-11-03 07:34 UTC, gerasimovdaniel commented
@matipojo @KingYes is there anything I can do to get a PR review?

2022-11-08 06:24 UTC, StyleShit requested changes

2022-11-08 06:24 UTC, StyleShit commented on modules/dev-tools/deprecation.php
>  	public function apply_deprecated_filter( $hook, $args, $version, $replacement = '', $base_version = null ) {
```suggestion
	public function apply_deprecated_filter( $hook, array $args, $version, $replacement = '', $base_version = null ) {
```

2022-11-08 06:24 UTC, StyleShit commented on modules/dev-tools/deprecation.php
> +			return $args[0];
```suggestion
			return $args[0] ?? null;
```

2022-11-08 07:59 UTC, StyleShit requested changes

2022-11-08 07:59 UTC, StyleShit commented on modules/dev-tools/deprecation.php
>  	public function apply_deprecated_filter( $hook, $args, $version, $replacement = '', $base_version = null ) {
```suggestion
	public function apply_deprecated_filter( $hook, array $args, $version, $replacement = '', $base_version = null ) {
```

2022-11-08 07:59 UTC, StyleShit commented on modules/dev-tools/deprecation.php
> +			return $args[0];
```suggestion
			return $args[0] ?? null;
```

2022-11-08 08:03 UTC, StyleShit requested changes

2022-11-08 08:03 UTC, StyleShit commented on modules/dev-tools/deprecation.php
> +	public function apply_deprecated_filter( $hook, array $args, $version, $replacement = '', $base_version = null ) {
```suggestion
	public function apply_deprecated_filter( $hook, $args, $version, $replacement = '', $base_version = null ) {
```

2022-11-08 09:51 UTC, StyleShit requested changes

2022-11-08 09:51 UTC, StyleShit commented on modules/dev-tools/deprecation.php
> +			return $args[0] ?? null;
```suggestion
			// `$args` should be an array, but in order to keep BC, we need to support non-array values.
			if ( is_array( $args ) ) {
				return $args[0] ?? null;
			}

			return $args;
```

2022-11-08 12:13 UTC, StyleShit approved these changes

2022-11-08 12:15 UTC, merged

2022-11-08 12:15 UTC, matipojo commented
Thanks @gerasimovdaniel !