New: Kit Elements Defaults - Introduction
elementor/elementor pull request #20113
Opened 2022-10-23 11:03 UTC by Nevoss

2022-10-23 11:07 UTC, matipojo commented on core/modules-manager.php
> +			'kit-elements-defaults',
```suggestion
			'performance-lab',
			'kit-elements-defaults',
```

2022-10-27 16:20 UTC, matipojo requested changes

2022-10-30 08:13 UTC, Nevoss commented on modules/kit-elements-defaults/assets/js/editor/commands/delete.js
> +			// TODO: Show error toast.
Done

2022-10-30 08:42 UTC, Nevoss commented on modules/kit-elements-defaults/assets/js/editor/commands/create.js
> +		} );
Done

2022-10-30 08:48 UTC, Nevoss commented on modules/kit-elements-defaults/assets/js/editor/commands/create.js
> +	}
Done

2022-10-30 08:59 UTC, Nevoss commented on modules/kit-elements-defaults/utils/settings-sanitizer.php
> +
Done

2022-10-31 15:55 UTC, matipojo approved these changes

2022-10-31 15:56 UTC, merged