Fix: Align items controls are not working (...) [ED-8382]
elementor/elementor pull request #20147
Opened 2022-10-26 15:00 UTC by hein-obox

2022-10-26 15:02 UTC, hein-obox commented on assets/dev/scss/frontend/widgets/spacer.scss
> +		--flex-shrink: 0;
I have limited the usage of `--align-self: stretch` to the 'container row`. The `container column` will use the `initial` value.

2022-10-26 15:40 UTC, hein-obox commented on assets/dev/scss/frontend/widgets/spacer.scss
> +		position: absolute;
I have fixed the display of the empty placeholder.

2022-11-06 09:17 UTC, TzviRabinovitch requested changes
please fix conflicts

2022-11-06 22:10 UTC, hein-obox commented
@TzviRabinovitch Merge conflicts solved.

2022-11-09 07:35 UTC, merged