Release/1.6.0
elementor/elementor pull request #2037
Opened 2017-07-19 09:36 UTC by kobizz

2017-07-23 16:43 UTC, KingYes requested changes

2017-07-23 16:43 UTC, KingYes commented on includes/settings/settings.php
> +									'type' => 'checkbox',
Change to select control

2017-07-23 16:59 UTC, KingYes requested changes

2017-07-23 16:59 UTC, KingYes commented on includes/widgets/image-gallery.php
> +		return [
You can write this in one line..

2017-07-23 17:01 UTC, KingYes requested changes

2017-07-23 17:01 UTC, KingYes commented on includes/widgets/video.php
> +					'' => __( 'Center', 'elementor' ),
Why the default like this?

2017-07-24 07:55 UTC, kobizz commented on includes/widgets/video.php
> +					'' => __( 'Center', 'elementor' ),
Because of the selector

2017-07-24 12:40 UTC, merged