Internal: Elements Regression - Summary for tested controls [ED-8292]
elementor/elementor pull request #20402
Opened 2022-11-14 15:39 UTC by matipojo

2022-11-14 22:54 UTC, Nevoss requested changes

2022-11-14 22:54 UTC, Nevoss commented on tests/elements-regression/tests/elements-regression.test.js
> +		console.log( 'summaryData', summary( testedElements, elementsConfig ) );
Add disable lint comment

2022-11-14 22:54 UTC, Nevoss commented on tests/elements-regression/src/utils.js
> +	summary: ( tested, expected ) => {
Maybe we should use a custom reporter alongside the regular reporter?
https://playwright.dev/docs/test-reporters#custom-reporters

2022-12-05 12:58 UTC, matipojo commented on tests/elements-regression/tests/elements-regression.test.js
> +		console.log( 'summaryData', summary( testedElements, elementsConfig ) );
```suggestion
		// eslint-disable-next-line no-console
		console.log( 'summaryData', summary( testedElements, elementsConfig ) );
```

2022-12-05 14:48 UTC, matipojo commented on tests/elements-regression/tests/elements-regression.test.js
> +		console.log( 'summaryData', summary( testedElements, elementsConfig ) );
```suggestion
		const summaryData = summary( testedElements, elementsConfig );
		test.info().annotations.push( { type: 'summary', description: JSON.stringify( summaryData ) } );
```

2022-12-05 15:08 UTC, matipojo commented on tests/elements-regression/tests/elements-regression.test.js
> +		test.info().annotations.push( { type: 'summary', description: JSON.stringify( summaryData ) } );
```suggestion
		// eslint-disable-next-line no-console
		console.log( 'summaryData', summary( testedElements, elementsConfig ) );
```

2022-12-05 15:26 UTC, merged