New: Nested Tabs - Responsive section [ed-7331]
elementor/elementor pull request #20417
Opened 2022-11-15 19:06 UTC by hein-obox

2022-11-22 15:25 UTC, davseve requested changes

2022-11-22 15:29 UTC, hein-obox commented on tests/playwright/sanity/modules/nested-tabs/nested-tabs.test.js
> +		} );
@davseve I don't think I am using custom breakpoints.

2022-11-22 15:30 UTC, hein-obox commented on tests/playwright/sanity/modules/nested-tabs/nested-tabs.test.js
> +		await wpAdmin.setExperiments( {
Nice one.

I am not even 100% about the expectations here, but I this guideline works for me.

2022-11-22 15:31 UTC, hein-obox commented on tests/playwright/sanity/modules/nested-tabs/nested-tabs.test.js
> +		expect( desktopTabWrapper ).toBeVisible();
Let's do it. 
It might be nice to get Udi's take on this sometime (not urgent).

2022-11-22 15:31 UTC, hein-obox commented on modules/nested-tabs/assets/scss/frontend.scss
> -// Tabs v2
I am not sure. This was existing code to indicate the widget name. I have left it as is.

2022-11-22 16:16 UTC, davseve approved these changes, later dismissed

2022-11-23 11:18 UTC, udidol approved these changes

2022-11-23 11:31 UTC, merged