Internal: Restrict users from being able to create new Theme Parts via Theme Builder when license is inactive [HTS-22]
elementor/elementor pull request #20519
Opened 2022-11-24 15:10 UTC by mark-elementor

## PR Checklist

- [x] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [x] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2022-11-27 08:17 UTC, ManorHazaz requested changes

2022-11-27 08:17 UTC, ManorHazaz commented on app/services/account/account-service.js
> +	 * @since 3.9.0
```suggestion
	 * @since 3.10.0
```

2022-11-27 08:17 UTC, ManorHazaz commented on app/services/base-service.php
> +	/**
```suggestion

	/**
```

2022-11-27 09:37 UTC, ManorHazaz approved these changes, later dismissed

2022-11-28 09:43 UTC, nivnoimanelementor submitted a review, later dismissed
Looks good, just update branch please.

2022-11-30 10:52 UTC, rodolphebertozzo reviewed
Please, see: https://github.com/mark-elementor/elementor/pull/1

2022-12-14 08:12 UTC, closed without merging