Fix: Styles of child nested tabs are affected by patent nested tabs styles [ed-8835]
elementor/elementor pull request #20530
Opened 2022-11-25 15:57 UTC by hein-obox

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2022-11-27 07:13 UTC, davseve requested changes

2022-11-27 09:50 UTC, hein-obox commented on modules/nested-tabs/widgets/nested-tabs.php
> +					"{{WRAPPER}}{$transform_selector_class} .e-n-tab-title:hover" => '--n-tabs-title-color-hover: {{VALUE}}',
@davseve Fixed. It was a mistake indeed.

2022-11-27 14:43 UTC, davseve approved these changes, later dismissed

2022-11-28 09:22 UTC, TzviRabinovitch requested changes
tests ?

2022-11-29 07:18 UTC, TzviRabinovitch submitted a review, later dismissed

2022-11-29 12:28 UTC, TzviRabinovitch approved these changes

2022-11-29 12:29 UTC, merged