Tweak: Added new dynamic tag for due date in Countdown widget (#7737) [ED-7194]
elementor/elementor pull request #20543
Opened 2022-11-27 14:21 UTC by StyleShit

2022-11-30 11:01 UTC, Nevoss requested changes

2022-11-30 11:54 UTC, StyleShit commented on assets/dev/scss/editor/panel/_controls.scss
> +@import "controls/date_time";
Nope, it's a generic text input

2022-11-30 12:06 UTC, Nevoss approved these changes

2022-12-04 10:02 UTC, rotemee approved these changes

2022-12-04 11:25 UTC, merged