Tweak: Image Box widget - Added units for size
elementor/elementor pull request #20575
Opened 2022-11-30 13:29 UTC by rodolphebertozzo

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2022-11-30 13:30 UTC, rodolphebertozzo commented on includes/widgets/image-box.php
> +						'min' => 1,
```suggestion
						'min' => 5,
```

2022-11-30 13:30 UTC, rodolphebertozzo commented on includes/widgets/image-box.php
> +					'size' => 25,
```suggestion
					'size' => 30,
```

2022-11-30 13:31 UTC, rodolphebertozzo commented
@rami-elementor @arielk

2022-11-30 21:08 UTC, rodolphebertozzo commented
@KingYes

2022-12-04 14:56 UTC, rami-elementor requested changes
The new units you added to the image-width ok a good change.

But changing the image-border-radius control (from SLIDER to DIMENSIONS) has the potential to break existing sites. Please revert this.

2022-12-04 18:00 UTC, rodolphebertozzo commented
> The new units you added to the image-width ok a good change.
> 
> But changing the image-border-radius control (from SLIDER to DIMENSIONS) has the potential to break existing sites. Please revert this.

Done @rami-elementor

2022-12-11 16:07 UTC, rodolphebertozzo commented
@arielk

2022-12-11 16:17 UTC, arielk commented
@rodolphebertozzo It looks like the image size change (`includes/widgets/image-box.php`) has the potential to break existing sites, please revert this change and I'll merge itץ

2022-12-11 16:29 UTC, rodolphebertozzo commented
@arielk Done

2022-12-11 16:41 UTC, closed without merging