Tweak: Added more sections on System info [ED-8741]
elementor/elementor pull request #20662
Opened 2022-12-08 12:29 UTC by KingYes

2022-12-15 12:59 UTC, StyleShit requested changes

2022-12-15 12:59 UTC, StyleShit commented on modules/usage/module.php
> +		$settings = array_merge( $settings_tab[ \Elementor\Settings::TAB_GENERAL ]['sections'], $settings_tab[ \Elementor\Settings::TAB_ADVANCED ]['sections'] );
```suggestion
		$settings = array_merge( 
			$settings_tab[ Settings::TAB_GENERAL ]['sections'], 
			$settings_tab[ Settings::TAB_ADVANCED ]['sections']
		);
```

2022-12-15 12:59 UTC, StyleShit commented on modules/usage/module.php
> +				if ( ! empty( $field_data['field_args']['std'] ) && $setting_value === $field_data['field_args']['std'] ) {
Maybe extract to `$is_default_value`?

2022-12-15 12:59 UTC, StyleShit commented on modules/usage/settings-reporter.php
> +		foreach ( $settings as $setting_name => $setting_value ) {
```suggestion
		$usage_settings_text = '';
		$settings = Module::get_settings_usage();
		
		foreach ( $settings as $setting_name => $setting_value ) {
```

2022-12-15 12:59 UTC, StyleShit commented on modules/usage/settings-reporter.php
> +		$settings = Module::get_settings_usage();
```suggestion
		$usage_settings = PHP_EOL;
		$settings = Module::get_settings_usage();
		
```

2022-12-15 12:59 UTC, StyleShit commented on modules/usage/settings-reporter.php
> +class Settings_Reporter extends Base_Reporter {
tests?

2022-12-19 07:54 UTC, Nevoss approved these changes

2022-12-19 07:56 UTC, Nevoss requested changes
Without test? and there is a lot of workflow that failed

2022-12-19 13:53 UTC, Nevoss requested changes

2022-12-19 13:53 UTC, Nevoss commented on tests/phpunit/elementor/modules/usage/test-module.php
> +
```suggestion
		update_option( 'elementor_disable_color_schemes', 'no' );
		update_option( 'elementor_css_print_method', 'external' ); // Default value should not exist in the result
		update_option( 'elementor_editor_break_lines', '1' );
		
		update_option( Settings::UPDATE_TIME_FIELD, time() ); // Not an Elementor option should not exist in the result

```

2022-12-19 13:56 UTC, Nevoss requested changes

2022-12-19 13:56 UTC, Nevoss commented on tests/phpunit/elementor/modules/usage/test-module.php
> +		$this->assertEquals( '1', $settings_usage['editor_break_lines'] );
```suggestion
		$this->assertEquals( 'no', $settings_usage['disable_color_schemes'] );
		$this->assertEquals( '1', $settings_usage['editor_break_lines'] );

		$this->assertArrayNotHasKey( 'css_print_method', $settings_usage );
		$this->assertArrayNotHasKey( Settings::UPDATE_TIME_FIELD, $settings_usage );
```

2022-12-19 14:20 UTC, Nevoss approved these changes

2022-12-19 14:29 UTC, merged