Tweak: Add caption space option to image carousel widget
elementor/elementor pull request #20727
Opened 2022-12-13 14:08 UTC by rodolphebertozzo

2022-12-13 14:09 UTC, rodolphebertozzo commented
@arielk

2022-12-13 14:51 UTC, rodolphebertozzo commented on includes/widgets/image-gallery.php
> +
```suggestion
```

2022-12-13 21:11 UTC, rodolphebertozzo commented
@arielk

2022-12-15 08:50 UTC, rodolphebertozzo commented
@rotemee

2022-12-15 19:20 UTC, kobizz requested changes, later dismissed

2022-12-15 19:20 UTC, kobizz commented on includes/widgets/image-gallery.php
> +					'{{WRAPPER}} gallery-item .gallery-caption' => 'margin-top: {{SIZE}}{{UNIT}};',
```suggestion
					'{{WRAPPER}} .gallery-item .gallery-caption' => 'margin-top: {{SIZE}}{{UNIT}};',
```

2022-12-15 19:35 UTC, rodolphebertozzo commented on includes/widgets/image-gallery.php
> +					'{{WRAPPER}} gallery-item .gallery-caption' => 'margin-top: {{SIZE}}{{UNIT}};',
Done.

2022-12-28 18:11 UTC, rodolphebertozzo commented
@TzviRabinovitch

2023-01-07 18:02 UTC, rodolphebertozzo commented
@KingYes

2023-01-08 12:49 UTC, rodolphebertozzo commented
@arielk

2023-01-08 12:54 UTC, rodolphebertozzo commented
@rami-elementor

2023-01-19 14:18 UTC, rodolphebertozzo commented
@arielk

2023-02-19 11:18 UTC, rodolphebertozzo commented
@arielk @rami-elementor Status ?

2023-03-06 13:50 UTC, rodolphebertozzo commented
@rami-elementor

2023-03-10 09:24 UTC, rami-elementor commented
I personally like this PR, it adds consistency to Elementor widgets using image captions.

It's in my TODO list to test this patch.

2023-06-20 12:15 UTC, doronwolf commented
Hi @rodolphebertozzo 
A. There is a bug in the display of the light box's icons on the top right side.. which may or may not be related to the changes in this build, but on the other hand I didn't run into it in other builds either.. so maybe it is related? (see the first screenshot)
![Screenshot1](https://github.com/elementor/elementor/assets/89334998/7001d7cd-a5a8-4388-b357-bf2936f2aba6)

B. Even when choosing the 'hide' option for the caption, the spacing slider is still available 
and also the text shadow also continues to appear (see the second screenshot)
![Screenshot2](https://github.com/elementor/elementor/assets/89334998/2267371f-f8db-40a9-80b5-ae03f7795d04)

C. Before this addition the default distance of the caption from the images was 0.75rem but after the change, the default distance is different (smaller, and until you don't move the slider, it is probably only affected by the line height of the text) and although it is a seemingly small difference, it is a bit of a problem for backward compatibility

  ...Beyond those issues, I actually think it's a great feature and I'm sure that those who do use captions will be happy with this addition so please review those issues and once they are fixed we would be happy to approve it :)

2023-07-10 19:34 UTC, rodolphebertozzo commented
Hi, I've corrected the underlined aspects by adding conditions and default values (0.75 rem = 12px) so that there won't be any backward compatibility problems with sites that already display captions. Adding this control without a default value surely overrides what is agreed in the SASS file at this level.
As for the lightbox, it's very strange. Any ideas?

2023-07-10 19:35 UTC, rodolphebertozzo commented
@doronwolf Hi, I've corrected the underlined aspects by adding conditions and default values (0.75 rem = 12px) so that there won't be any backward compatibility problems with sites that already display captions. Adding this control without a default value surely overrides what is agreed in the SASS file at this level.
As for the lightbox, it's very strange. Any ideas?

2023-07-11 11:27 UTC, doronwolf commented
Hi @rodolphebertozzo thank you very much for making the necessary changes 🙏 looks very good!
about the lightbox - I agree, it seems not related to your code
I need to do a few more tests on my end but I believe they will go smoothly and then we all approve and merge this PR
will try to update here once I have news

2023-07-11 20:16 UTC, rodolphebertozzo commented
> Hi @rodolphebertozzo thank you very much for making the necessary changes 🙏 looks very good! about the lightbox - I agree, it seems not related to your code I need to do a few more tests on my end but I believe they will go smoothly and then we all approve and merge this PR will try to update here once I have news

Hello,
I've just checked the SASS files, it seems that there are no default style rules for the caption, so it's the PHP file that manages this and prints some style rules in the DOM for this default control. Yes, I've just restored all the files as they were, and the problem is not with my PR

2023-07-12 06:54 UTC, doronwolf commented
Hi @rodolphebertozzo I also checked again... there is a default style rules for the caption - but it comes from the theme (see the attached screenshot) in my case it's the 'hello' theme
![Screenshot 2023-07-12 at 9 46 48](https://github.com/elementor/elementor/assets/89334998/6a82da73-399d-48dd-88f1-b0a9b3ca921c) but since we can't know which theme each user chooses to use, and other themes may have different default (or no default) then I agree with you👍 and thanks for the catch

I hope this is the only change you reverted? because initially when choosing the 'hide' option for the caption, the spacing slider, and the text-shadow were still available, and that was a fix you shouldn't revert

2023-07-12 08:52 UTC, rodolphebertozzo commented
> Salut@rodolphebertozzoJ'ai également vérifié à nouveau... il y a des règles de style par défaut pour la légende - mais cela vient du thème (voir la capture d'écran ci-jointe) dans mon cas c'est le thème 'hello' mais puisque nous ne pouvons pas savoir quel thème chaque utilisateur ![Capture d'écran 2023-07-12 à 9 46 48](https://user-images.githubusercontent.com/89334998/252878498-6a82da73-399d-48dd-88f1-b0a9b3ca921c.png)choisit à utiliser, et d'autres thèmes peuvent avoir des valeurs par défaut différentes (ou aucune valeur par défaut), alors je suis d'accord avec vous👍et merci pour la prise
> 
> J'espère que c'est le seul changement que vous avez annulé? parce qu'au départ, lors du choix de l'option 'masquer' pour la légende, le curseur d'espacement et l'ombre du texte étaient toujours disponibles, et c'était une solution que vous ne devriez pas revenir

For text shadow and spacing, I've added the condition that the control is only displayed if the caption is active.

2023-12-24 13:35 UTC, rami-elementor requested changes

2023-12-24 13:35 UTC, rami-elementor commented on includes/widgets/image-carousel.php
> +					'{{WRAPPER}} .elementor-image-carousel-caption' => 'margin-top: {{SIZE}}{{UNIT}};',
```suggestion
					'{{WRAPPER}} .elementor-image-carousel-caption' => 'margin-block-start: {{SIZE}}{{UNIT}};',
```

2023-12-24 13:35 UTC, rami-elementor commented on includes/widgets/image-gallery.php
> +					'{{WRAPPER}} .gallery-item .gallery-caption' => 'margin-top: {{SIZE}}{{UNIT}};',
```suggestion
					'{{WRAPPER}} .gallery-item .gallery-caption' => 'margin-block-start: {{SIZE}}{{UNIT}};',
```

2023-12-24 13:35 UTC, rami-elementor commented on includes/widgets/image-gallery.php
> +					],
```suggestion
```

You don't need to set this as this is already set by default for `%` units.

2023-12-24 13:35 UTC, rami-elementor commented on includes/widgets/image-carousel.php
> +					],
```suggestion
```

You don't need to set this as this is already set by default for `%` units.

2023-12-24 13:35 UTC, rami-elementor commented on includes/widgets/image-carousel.php
> +					'unit' => 'px',
```suggestion
```

Remove, the default unit is `px`, you don't need to set this again.

2023-12-24 13:35 UTC, rami-elementor commented on includes/widgets/image-gallery.php
> +					'unit' => 'px',
```suggestion
```

Remove, the default unit is `px`, you don't need to set this again.

2023-12-24 14:34 UTC, rami-elementor requested changes

2023-12-24 14:34 UTC, rami-elementor commented on includes/widgets/image-carousel.php
> +				],
```suggestion
```

Remove the default value. This way we keep backwards compatibility.

2023-12-24 14:34 UTC, rami-elementor commented on includes/widgets/image-gallery.php
> +				],
```suggestion
```

Remove the default value. This way we keep backwards compatibility.

2023-12-24 14:34 UTC, rami-elementor commented on includes/widgets/image-carousel.php
> +				],
```suggestion
```

Remove this section, you are redefining default range values.

2023-12-24 14:34 UTC, rami-elementor commented on includes/widgets/image-gallery.php
> +				],
```suggestion
```

Remove this section, you are redefining default range values.

2023-12-24 14:57 UTC, rami-elementor approved these changes, later dismissed

2023-12-24 22:10 UTC, rodolphebertozzo commented
Hello @rami-elementor,
Yes, I've just been made aware of your changes. At the time I started working on this improvement, I wasn't fully aware of how Elementor works with units, and even less of the fact that they are set in a separate file, and that specifying maximum, minimum or default unit values is only done if you want to get away from the operating logic in a specific case.

2023-12-25 07:30 UTC, rami-elementor commented
@rodolphebertozzo 

Thank you for your valuable contribution! I approved this PR. Moving to @arielk to merge.

2023-12-25 12:53 UTC, arielk approved these changes, later dismissed

2023-12-25 13:01 UTC, rami-elementor approved these changes

2023-12-25 13:15 UTC, arielk approved these changes

2023-12-25 13:43 UTC, arielk approved these changes

2023-12-25 13:56 UTC, merged