Tweak/ed 9040 tweak added hover animation control to tabs hover in tabs widget 20733
elementor/elementor pull request #20745
Opened 2022-12-14 13:44 UTC by hein-obox

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2022-12-14 19:38 UTC, TzviRabinovitch approved these changes

2022-12-15 06:28 UTC, davseve requested changes

2022-12-15 06:28 UTC, davseve commented on modules/nested-tabs/widgets/nested-tabs.php
> +				array_push( $tab_title_mobile_classes, 'elementor-animation-' . $settings['hover_animation'] );
Why Do we need animation on mobile? 
Should hover state work on mobile?

2022-12-15 06:33 UTC, davseve approved these changes

2022-12-15 08:18 UTC, merged