Fix: Various Carousel widgets are not working in Nested Tabs [ED-9149]
elementor/elementor pull request #20845
Opened 2022-12-26 05:58 UTC by StuartElementor

… Nested Tabs

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2022-12-28 10:13 UTC, udidol requested changes
@StuartElementor
There is a carousel widget in the Core - Image Carousel. Please add tests using Image Carousel.
Otherwise fix looks good, nice work.

2022-12-30 01:50 UTC, StuartElementor commented
> @StuartElementor There is a carousel widget in the Core - Image Carousel. Please add tests using Image Carousel. Otherwise fix looks good, nice work.

Thanks 😊
RE the Image Carousel. good find. I've adedd a test using this widget.

2023-01-02 08:29 UTC, louiswol94 commented
@StuartElementor Just a random question out of curiosity... Did you try these configs?

```
observer: true,
observeParents: true
```

2023-01-02 13:45 UTC, udidol approved these changes

2023-01-02 13:46 UTC, merged