Tweak: Remove 'kit by plan' filtering [ED-9138]
elementor/elementor pull request #20853
Opened 2022-12-26 12:51 UTC by ranshoshani34

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:
Removed 'Kit by plan' filtering from kit library
*

## Description
An explanation of what is done in this PR
Removed 'Kit by plan' filtering from the kit library, and the badges indicating plans.
*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [x ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2022-12-26 14:37 UTC, mark-elementor approved these changes, later dismissed

2022-12-28 14:33 UTC, ManorHazaz requested changes

2022-12-28 14:33 UTC, ManorHazaz commented on app/modules/kit-library/assets/js/components/kit-list-item.js
> +import Badge from "./badge";
Fix lint

2022-12-28 14:33 UTC, ManorHazaz commented on app/modules/kit-library/assets/js/components/kit-list-item.js
> +					{ ! elementorAppConfig.hasPro &&	subscriptionPlan?.label && <Badge
Span?

2022-12-28 14:33 UTC, ManorHazaz commented on package.json
> +        "lint:js": "eslint --fix ."
Nice

2022-12-28 14:33 UTC, ManorHazaz commented on tests/phpunit/elementor/app/kit-library/data/taxonomies/test-controller.php
> +		$this->assertCount( 5, $result['data'] );
FIx test

2022-12-28 14:33 UTC, ManorHazaz commented on assets/dev/js/editor/components/template-library/views/library-layout.js
> +		const subscriptionPlan = subscriptionPlans[ closestAccessLevel ] ?? subscriptionPlans[ subscriptionPlans.length - 1 ];
FIx it from closestAccessLevel.

2022-12-28 15:16 UTC, ManorHazaz approved these changes, later dismissed

2022-12-29 12:38 UTC, ManorHazaz approved these changes

2023-01-01 12:38 UTC, nivnoimanelementor approved these changes

2023-01-01 13:33 UTC, merged