Fix: Justify Content icons are inverted Dir = "Column" & RTL [ED-8458]
elementor/elementor pull request #20866
Opened 2022-12-28 10:00 UTC by TzviRabinovitch

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2022-12-28 10:05 UTC, rodolphebertozzo submitted a review, later dismissed

2022-12-28 10:26 UTC, davseve requested changes

2022-12-28 10:26 UTC, davseve commented on assets/dev/scss/editor/_flex-icons.scss
> +  &:is(.eicon-justify-start-h,.eicon-justify-start-h) {
There is a small mistake,
It should be:
`&:is(.eicon-justify-start-h,.eicon-justify-end-h)`

2022-12-29 10:32 UTC, udidol approved these changes

2022-12-29 10:33 UTC, merged