Internal: Editor V2 - i18n [ED-9205]
elementor/elementor pull request #20910
Opened 2023-01-03 17:07 UTC by Nevoss

2023-01-04 06:41 UTC, StyleShit requested changes

2023-01-04 06:41 UTC, StyleShit commented on packages/tools/extract-i18n-expressions-webpack-plugin/index.js
> +			this.translationsRegexps.some( ( regexp ) => ! ( regexp instanceof RegExp ) )
```suggestion
			! Array.isArray( translationsRegexps ) ||
			translationsRegexps.some( ( regexp ) => ! ( regexp instanceof RegExp ) )
```

2023-01-04 06:41 UTC, StyleShit commented on packages/tools/extract-i18n-expressions-webpack-plugin/index.js
> +			return new RegExp( regex.source, `${ flags }` );
```suggestion
			return new RegExp( regex.source, flags );
```

2023-01-05 14:01 UTC, Nevoss commented on packages/tools/extract-i18n-expressions-webpack-plugin/index.js
> +			this.translationsRegexps.some( ( regexp ) => ! ( regexp instanceof RegExp ) )
Doen

2023-01-08 16:20 UTC, closed without merging