Tweak: Adjusted the increments of `em` and `rem` when scrubbing (#19399) [ED-8551]
elementor/elementor pull request #21096
Opened 2023-01-22 14:23 UTC by StyleShit

2023-01-23 13:16 UTC, Nevoss requested changes

2023-01-23 13:16 UTC, Nevoss commented on assets/dev/js/editor/controls/behaviors/scrubbing.js
> +				input.value = this.getModifiedValue( input.value, movementEvent.movementX, 'valueModifier' );
```suggestion
				input.value = this.getModifiedValue( input.value, movementEvent.movementX, this.scrubSettings.valueModifier );
```

2023-01-24 06:01 UTC, StyleShit commented on assets/dev/js/editor/controls/behaviors/scrubbing.js
> +				input.value = this.getModifiedValue( input.value, movementEvent.movementX, 'valueModifier' );
Done

2023-01-24 08:54 UTC, Nevoss approved these changes

2023-01-24 08:59 UTC, merged