Fix: Keyboard actions are not blocked in Nested Tabs [ED-9355]
elementor/elementor pull request #21106
Opened 2023-01-23 09:58 UTC by StyleShit

2023-01-23 13:38 UTC, Nevoss requested changes

2023-01-23 13:38 UTC, Nevoss commented on assets/dev/js/editor/document/ui/component.js
> +			const hasLockedContainers = selectedElements.some( ( container ) => container.isLocked() );
```suggestion
			const hasLockedContainers = selectedElements.some( ( container ) => container?.isLocked?.() );
```

2023-01-23 13:49 UTC, StyleShit commented on assets/dev/js/editor/document/ui/component.js
> +			const hasLockedContainers = selectedElements.some( ( container ) => container.isLocked() );
Done

2023-01-23 14:54 UTC, Nevoss approved these changes

2023-01-24 12:08 UTC, rotemee approved these changes

2023-01-24 14:36 UTC, merged