Internal: Editor V2 - Fix `typescript-eslint` rules [ED-9485]
elementor/elementor pull request #21111
Opened 2023-01-23 14:32 UTC by StyleShit

2023-01-24 11:54 UTC, rotemee requested changes

2023-01-24 11:54 UTC, rotemee commented on packages/packages/v1-adapters/src/dispatchers/utils.ts
> +	return !! value &&
Consider adding parenthesis.

2023-01-24 12:09 UTC, rotemee approved these changes, later dismissed

2023-01-25 11:18 UTC, Nevoss requested changes

2023-01-25 11:18 UTC, Nevoss commented on packages/packages/v1-adapters/src/dispatchers/__tests__/index.test.ts
> +	let eRun: jest.Mock, eRoute: jest.Mock;
```suggestion
	let eRun: jest.Mock,
		eRoute: jest.Mock;
```

2023-01-31 13:40 UTC, StyleShit commented on packages/packages/v1-adapters/src/dispatchers/__tests__/index.test.ts
> +	let eRun: jest.Mock, eRoute: jest.Mock;
Done

2023-01-31 13:44 UTC, StyleShit commented on packages/packages/v1-adapters/src/listeners/__tests__/index.test.ts
> +		type ExtendedWindow = Window & {
I don't want other packages to know about global variables they shouldn't know

2023-01-31 14:00 UTC, Nevoss commented on packages/packages/v1-adapters/src/listeners/__tests__/index.test.ts
> +		type ExtendedWindow = Window & {
What about internal use?

2023-02-02 09:18 UTC, Nevoss approved these changes

2023-02-02 09:45 UTC, merged