Internal: Add IsTouch to elementor environments  [ED-9380]
elementor/elementor pull request #21110
Opened 2023-01-23 14:09 UTC by TzviRabinovitch

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2023-01-23 14:36 UTC, louiswol94 requested changes

2023-01-23 14:36 UTC, louiswol94 commented on core/common/assets/js/utils/environment.js
> +
@TzviRabinovitch For sanity, please just double check for me if this is returning the correct value?
When I run the old way I get `false` for my Desktop view, but with this method I get `true`.
Check the attached screenshot on how I tested it.
![Screenshot 2023-01-23 at 16 33 25](https://user-images.githubusercontent.com/20996103/214066307-0b4ae03d-4a9a-47fb-87a9-e0d9cc510294.png)

2023-01-23 14:42 UTC, louiswol94 commented on core/common/assets/js/utils/environment.js
> +
Okay cool.

2023-01-23 14:45 UTC, louiswol94 approved these changes

2023-01-24 10:00 UTC, udidol approved these changes

2023-01-24 10:17 UTC, merged