Tweak: Refactor - separate overview widget to sections [ED-9571]
elementor/elementor pull request #21196
Opened 2023-01-30 13:11 UTC by lenalElementor

2023-01-30 13:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/elementor/elementor?pullRequest=21196) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/elementor/elementor?pullRequest=21196) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/elementor/elementor?pullRequest=21196) it.</sub>

2023-01-30 16:33 UTC, nivnoimanelementor requested changes
Please check the request changes,

2023-01-30 16:33 UTC, nivnoimanelementor commented on core/admin/admin.php
> +	public function elementor_dashboard_overview_recently_edited( $args = [], $show_heading = true ) {
Don't use show_heading. Instead split it into another function that can be invoke.

2023-02-01 07:54 UTC, mark-elementor requested changes

2023-02-01 07:54 UTC, mark-elementor commented on core/admin/admin.php
> +	 * @access public
```suggestion
```

2023-02-01 07:54 UTC, mark-elementor commented on core/admin/admin.php
> +	public function elementor_dashboard_overview_recently_edited( $args = [], $show_heading = true ) {
```suggestion
	public function elementor_dashboard_overview_recently_edited( array $args = [], bool $show_heading = true ) {
```
Also, maybe "is_heading_shown" or something like that?

2023-02-01 07:54 UTC, mark-elementor commented on core/admin/admin.php
> +	 *
```suggestion
```

2023-02-01 07:54 UTC, mark-elementor commented on core/admin/admin.php
> +	public function elementor_dashboard_overview_news_updates( $limit_feed = 0, $show_heading = true ) {
```suggestion
	public function elementor_dashboard_overview_news_updates( int $limit_feed = 0, bool $show_heading = true ) {
```
$show_heading naming?

2023-02-01 07:54 UTC, mark-elementor commented on core/admin/admin.php
> +	 * @access public
```suggestion
```

2023-02-01 07:54 UTC, mark-elementor commented on core/admin/admin.php
> +	 *
```suggestion
```

2023-02-01 07:54 UTC, mark-elementor commented on core/admin/admin.php
> +	 *
```suggestion
```

2023-02-01 07:54 UTC, mark-elementor commented on core/admin/admin.php
> +	 * @access public
```suggestion
```

2023-02-01 07:55 UTC, mark-elementor commented
General comment - maybe should move the dashboard widgets to a separate class?

2023-02-01 11:56 UTC, lenalElementor commented on core/admin/admin.php
> +	public function elementor_dashboard_overview_header( $show_versions = true, $show_create_post = true ) {
I don’t think we support param type declaration.

2023-02-01 11:57 UTC, lenalElementor commented on core/admin/admin.php
> +	 * @access public
Why remove this line?

2023-02-01 11:57 UTC, lenalElementor commented on core/admin/admin.php
> +	 *
Why?

2023-02-01 14:33 UTC, mark-elementor commented on core/admin/admin.php
> +	 * @access public
Something weird happent here.

2023-02-02 06:17 UTC, mark-elementor submitted a review, later dismissed

2023-02-05 13:30 UTC, nivnoimanelementor requested changes
please check this last thing 🙏

2023-02-05 13:30 UTC, nivnoimanelementor commented on assets/dev/scss/admin/_dashboard-widget.scss
> +.e-dashboard-overview {
why we still have all the style in the class ID as well ?
why not to replace the `#` to `.` at the original ?

2023-02-06 13:12 UTC, nivnoimanelementor approved these changes

2023-02-08 14:04 UTC, merged