Internal: Editor V2 - Publish button [ED-9656]
elementor/elementor pull request #21244
Opened 2023-02-06 06:31 UTC by StyleShit

2023-02-08 10:08 UTC, rotemee requested changes

2023-02-08 10:08 UTC, rotemee commented on packages/packages/documents/src/sync/__tests__/test-utils.ts
> +export function makeV1Settings<T extends object>( settings: T ) {
Add comment.

2023-02-08 10:10 UTC, rotemee submitted a review, later dismissed

2023-02-08 13:08 UTC, Nevoss requested changes

2023-02-08 13:08 UTC, Nevoss commented on packages/packages/documents/src/sync/utils.ts
> +	const isAutoSave = documentData.config.revisions.current_id !== documentData.id;
```suggestion
	const isUnpublishedRevision = documentData.config.revisions.current_id !== documentData.id;
```

with comment of draft and autosave

2023-02-08 13:08 UTC, Nevoss commented on packages/packages/documents/src/components/top-bar/__tests__/primary-action.test.tsx
> +	it( 'should save the current document on click', () => {
```suggestion
	it( 'should save the active document on click', () => {
```

2023-02-08 14:12 UTC, StyleShit commented on packages/packages/documents/src/components/top-bar/primary-action.tsx
> +	const shouldShowSpinner = document.isSaving && ! isDisabled;
Done

2023-02-08 14:12 UTC, StyleShit commented on packages/packages/documents/src/hooks/__tests__/use-active-document.test.tsx
> +			type: 'page',
Done

2023-02-08 14:13 UTC, StyleShit commented on packages/packages/documents/src/sync/utils.ts
> +	const isAutoSave = documentData.config.revisions.current_id !== documentData.id;
Done

2023-02-08 14:13 UTC, StyleShit commented on packages/packages/documents/src/components/top-bar/__tests__/primary-action.test.tsx
> +	it( 'should save the current document on click', () => {
Done

2023-02-09 12:37 UTC, Nevoss approved these changes, later dismissed

2023-02-09 12:40 UTC, Nevoss approved these changes

2023-02-09 12:54 UTC, merged