Internal: Editor V2 - Adjust panel header & footer [ED-9695]
elementor/elementor pull request #21258
Opened 2023-02-07 14:21 UTC by StyleShit

2023-02-08 12:17 UTC, rotemee submitted a review, later dismissed

2023-02-08 13:20 UTC, Nevoss requested changes

2023-02-08 13:20 UTC, Nevoss commented on packages/packages/elements-panel/src/sync/__tests__/sync-panel-title.test.ts
> +		mockIsRouteActive.mockReturnValue( false );
mock implementaion

2023-02-08 14:22 UTC, StyleShit commented on packages/packages/elements-panel/src/sync/__tests__/sync-panel-title.test.ts
> +		mockIsRouteActive.mockReturnValue( false );
Done

2023-02-09 12:39 UTC, Nevoss approved these changes

2023-02-09 13:10 UTC, merged