Internal: Editor V2 - Run on Elementor root build
elementor/elementor pull request #21260
Opened 2023-02-07 16:02 UTC by Nevoss

2023-02-08 05:59 UTC, StyleShit approved these changes, later dismissed

2023-02-12 12:41 UTC, StyleShit requested changes

2023-02-12 12:41 UTC, StyleShit commented on packages/.eslintrc.js
> +				devDependencies: false,
explain

2023-02-12 12:41 UTC, StyleShit commented on packages/.eslintrc.js
> +		// Override import/internal-regex that defined in @wordpress/eslint-plugin.
```suggestion
		// Override `import/internal-regex` that is defined in `@wordpress/eslint-plugin`.
```

2023-02-12 12:41 UTC, StyleShit commented on packages/.eslintrc.js
> +				'*.js', // Root level files.
ts?

2023-02-12 15:26 UTC, Nevoss commented on packages/.eslintrc.js
> +				devDependencies: false,
Done

2023-02-12 15:26 UTC, Nevoss commented on packages/.eslintrc.js
> +		// Override import/internal-regex that defined in @wordpress/eslint-plugin.
Done

2023-02-12 15:27 UTC, Nevoss commented on packages/.eslintrc.js
> +				'*.js', // Root level files.
Done

2023-02-13 05:50 UTC, StyleShit approved these changes

2023-02-13 08:23 UTC, rotemee approved these changes

2023-02-13 13:46 UTC, merged