Internal: Editor V2 - Manage Website button [ED-9717]
elementor/elementor pull request #21273
Opened 2023-02-09 06:42 UTC by StyleShit

2023-02-09 13:04 UTC, Nevoss requested changes

2023-02-09 13:04 UTC, Nevoss commented on core/editor/config-providers/editor-v2-config-provider.php
> +					'dashboard' => admin_url(),
```suggestion
					'admin_url' => admin_url(),
```

2023-02-09 13:04 UTC, Nevoss commented on core/editor/config-providers/editor-common-configs.php
> +		$suffix = ( Utils::is_script_debug() || Utils::is_elementor_tests() ) ? '' : '.min';
Move to class

2023-02-09 13:04 UTC, Nevoss commented on core/editor/editor-loader.php
> +		$client_settings = $this->config_provider->get_client_settings();
Normalize and validations like assets

2023-02-09 14:01 UTC, StyleShit commented on core/editor/assets/js/editor-loader-v2.js
> +	);
Done

2023-02-09 14:01 UTC, StyleShit commented on core/editor/config-providers/editor-v2-config-provider.php
> +					'dashboard' => admin_url(),
Done

2023-02-09 14:01 UTC, StyleShit commented on core/editor/config-providers/editor-common-configs.php
> +		$suffix = ( Utils::is_script_debug() || Utils::is_elementor_tests() ) ? '' : '.min';
Done

2023-02-09 14:01 UTC, StyleShit commented on core/editor/editor-loader.php
> +		$client_settings = $this->config_provider->get_client_settings();
Done

2023-02-12 13:03 UTC, Nevoss requested changes

2023-02-12 13:03 UTC, Nevoss commented on tests/phpunit/elementor/core/editor/test-editor-loader.php
> +		$this->mock_config_provider->method( 'get_script_configs' )->willReturn( [
try to use data_provider

2023-02-12 13:15 UTC, StyleShit commented on core/editor/config-providers/editor-common-configs.php
> +				'config' => Editor_Common_Client_Settings::get_client_settings(),
Done

2023-02-12 13:15 UTC, StyleShit commented on core/editor/config-providers/editor-v2-config-provider.php
> +			'name' => 'elementorEditorV2Config',
Done

2023-02-12 13:16 UTC, StyleShit commented on packages/packages/editor/src/contexts/__tests__/settings-context.test.tsx
> +		// TODO: Mock the `console.error` because `@testing-library/react-hooks` takes over the `console.error`
Done

2023-02-12 13:16 UTC, StyleShit commented on packages/packages/editor/src/index.ts
> +export { useSettings } from './contexts/settings-context';
Done

2023-02-12 14:23 UTC, StyleShit commented on tests/phpunit/elementor/core/editor/test-editor-loader.php
> +		$this->mock_config_provider->method( 'get_script_configs' )->willReturn( [
Done

2023-02-12 15:29 UTC, Nevoss submitted a review, later dismissed

2023-02-13 07:29 UTC, rotemee requested changes

2023-02-13 07:29 UTC, rotemee commented on packages/packages/editor/src/init.tsx
> +		<SettingsContextProvider settings={ settings }>
```suggestion
		<SettingsProvider settings={ settings }>
```

2023-02-13 07:29 UTC, rotemee commented on tests/phpunit/elementor/core/editor/test-editor-loader.php
> +
Remove.

2023-02-13 07:29 UTC, rotemee commented on tests/phpunit/elementor/core/editor/test-editor-loader.php
> +		return [
Explain by a comment above each case.

2023-02-13 07:29 UTC, rotemee commented on packages/packages/editor/src/contexts/settings-context.tsx
> +export function SettingsContextProvider( { children, settings }: PropsWithChildren<{ settings: Settings }> ) {
```suggestion
export function SettingsProvider( { children, settings }: PropsWithChildren<{ settings: Settings }> ) {
```

2023-02-13 07:29 UTC, rotemee commented on packages/packages/editor/src/contexts/__tests__/settings-context.test.tsx
> +				},
Move out?

2023-02-13 07:29 UTC, rotemee commented on packages/packages/editor/src/contexts/__tests__/settings-context.test.tsx
> +	it( 'should throw when not rendered inside a <SettingsContextProvider />', () => {
```suggestion
	it( 'should throw when not rendered inside a <SettingsProvider />', () => {
```

2023-02-13 07:29 UTC, rotemee commented on packages/packages/editor/src/contexts/__tests__/settings-context.test.tsx
> +		expect( result.error?.message ).toEqual( 'The `useSettings()` hook must be used within an `<SettingsContextProvider />`' );
```suggestion
		expect( result.error?.message ).toEqual( 'The `useSettings()` hook must be used within an `<SettingsProvider />`' );
```

2023-02-13 08:06 UTC, StyleShit commented on packages/packages/editor/src/init.tsx
> +		<SettingsContextProvider settings={ settings }>
Done

2023-02-13 08:06 UTC, StyleShit commented on tests/phpunit/elementor/core/editor/test-editor-loader.php
> +
Done

2023-02-13 08:09 UTC, StyleShit commented on tests/phpunit/elementor/core/editor/test-editor-loader.php
> +		return [
Done

2023-02-13 08:09 UTC, StyleShit commented on packages/packages/editor/src/contexts/settings-context.tsx
> +export function SettingsContextProvider( { children, settings }: PropsWithChildren<{ settings: Settings }> ) {
Done

2023-02-13 08:10 UTC, StyleShit commented on packages/packages/editor/src/contexts/__tests__/settings-context.test.tsx
> +				},
Done

2023-02-13 08:10 UTC, StyleShit commented on packages/packages/editor/src/contexts/__tests__/settings-context.test.tsx
> +	it( 'should throw when not rendered inside a <SettingsContextProvider />', () => {
Dpne

2023-02-13 08:10 UTC, StyleShit commented on packages/packages/editor/src/contexts/__tests__/settings-context.test.tsx
> +		expect( result.error?.message ).toEqual( 'The `useSettings()` hook must be used within an `<SettingsContextProvider />`' );
Done

2023-02-13 08:19 UTC, rotemee approved these changes

2023-02-13 08:39 UTC, merged