Internal: Editor V2 - Breakpoints Selector [ED-9726]
elementor/elementor pull request #21364
Opened 2023-02-16 08:18 UTC by StyleShit

2023-02-20 11:53 UTC, rotemee requested changes

2023-02-20 11:53 UTC, rotemee commented on packages/packages/responsive/src/sync/sync-store.ts
> +	return extendedWindow.elementor?.channels?.deviceMode?.request?.( 'currentMode' ) ?? null;
```suggestion
	return extendedWindow.elementor?.channels?.deviceMode?.request?.( 'currentMode' ) || null;
```

2023-02-20 11:54 UTC, StyleShit commented on packages/packages/responsive/src/__tests__/breakpoints-config.ts
> +export function getBreakpointsConfig() {
Removed

2023-02-20 11:54 UTC, StyleShit commented on packages/packages/responsive/src/components/breakpoints-switcher.tsx
> +			},
Done

2023-02-20 11:54 UTC, StyleShit commented on packages/packages/responsive/src/components/breakpoints-switcher.tsx
> +	const onChange = ( e: unknown, value: BreakpointId ) => activate( value );
Done

2023-02-20 11:55 UTC, StyleShit commented on packages/packages/responsive/src/components/breakpoints-switcher.tsx
> +					const title = labelsMap[ type ?? 'default' ]
Done

2023-02-20 11:55 UTC, StyleShit commented on packages/packages/responsive/src/components/breakpoints-switcher.tsx
> +							sx={ { padding: '4px' } }
Done

2023-02-20 11:55 UTC, StyleShit commented on packages/packages/responsive/src/components/breakpoints-switcher.tsx
> +						.replace( '%d', width?.toString() ?? '' );
Done

2023-02-20 11:57 UTC, StyleShit commented on packages/packages/responsive/src/hooks/__tests__/use-breakpoints.test.tsx
> +		expect( jest.mocked( runCommand ) ).toHaveBeenCalledWith(
It will require me to mock the store, and it's already tested in another test

2023-02-20 11:58 UTC, StyleShit commented on packages/packages/responsive/src/icons/widescreen-icon.tsx
> +const WidescreenIcon = React.forwardRef( ( props: SvgIconProps, ref ) => {
Done

2023-02-20 12:00 UTC, StyleShit commented on packages/packages/responsive/src/store/index.ts
> +	entities: {} as State['entities'],
IDK.... feels odd

2023-02-20 12:08 UTC, StyleShit commented on packages/packages/responsive/src/store/index.ts
> +					}, {} as State['entities'] );
Done

2023-02-20 12:57 UTC, rotemee approved these changes, later dismissed

2023-02-21 09:03 UTC, Nevoss requested changes

2023-02-21 09:03 UTC, Nevoss commented on packages/packages/responsive/src/index.ts
> +export * from './store/selectors';
Remove

2023-02-21 09:05 UTC, StyleShit commented on packages/packages/responsive/src/index.ts
> +export * from './store/selectors';
Done

2023-02-21 11:31 UTC, StyleShit commented on packages/packages/responsive/src/components/breakpoints-switcher.tsx
> +		label: __( 'Mobile Landscape', 'elementor' ),
Done

2023-02-21 11:31 UTC, StyleShit commented on packages/packages/responsive/src/components/breakpoints-switcher.tsx
> +						/>
Done

2023-02-21 11:31 UTC, StyleShit commented on packages/packages/responsive/src/components/breakpoints-switcher.tsx
> +	const { all, active, activate } = useBreakpoints();
Done

2023-02-21 12:53 UTC, Nevoss approved these changes

2023-02-21 14:24 UTC, merged