[Mega Menu] [Infra] Ensure the Mega Menu is A11Y - Core code [ED-9775]
elementor/elementor pull request #21410
Opened 2023-02-21 10:44 UTC by hein-obox

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2023-02-21 11:43 UTC, davseve approved these changes

2023-02-21 11:46 UTC, davseve requested changes
Please change the PR name to a valid name.
You pushed your local Playwright config to the repo.

2023-02-21 12:32 UTC, davseve approved these changes, later dismissed

2023-02-22 09:13 UTC, louiswol94 commented
Comments on Slace

2023-02-22 10:58 UTC, louiswol94 approved these changes

2023-02-22 12:12 UTC, heinvv-abangani commented
test

2023-02-22 12:28 UTC, TzviRabinovitch approved these changes

2023-02-22 12:29 UTC, merged