Internal: Editor V2 - Finder [ED-9732]
elementor/elementor pull request #21427
Opened 2023-02-22 14:35 UTC by StyleShit

2023-02-23 10:26 UTC, rotemee submitted a review, later dismissed

2023-02-23 12:02 UTC, Nevoss requested changes

2023-02-23 12:02 UTC, Nevoss commented on packages/packages/finder/src/hooks/__tests__/use-action-props.test.ts
> +	} );
Remove

2023-02-26 08:56 UTC, StyleShit commented on packages/packages/finder/src/hooks/__tests__/use-action-props.test.ts
> +	} );
Done

2023-02-26 09:19 UTC, Nevoss approved these changes

2023-02-26 09:26 UTC, merged