Internal: Editor V2 - Documents UI package [ED-9866]
elementor/elementor pull request #21444
Opened 2023-02-23 11:32 UTC by StyleShit

2023-02-23 11:47 UTC, Nevoss requested changes

2023-02-23 11:47 UTC, Nevoss commented on core/editor/config-providers/editor-v2-config-provider.php
> +		'documents',
I think this is still an extension, it cannot live outside of the editor like `store` or `locations`

2023-02-26 07:56 UTC, Nevoss submitted a review, later dismissed

2023-02-26 13:28 UTC, rotemee approved these changes

2023-02-26 13:41 UTC, merged