Internal: Editor V2 - Improve test-utils lib part 1
elementor/elementor pull request #21441
Opened 2023-02-23 08:53 UTC by Nevoss

2023-02-23 09:31 UTC, Nevoss commented on packages/packages/documents/src/components/top-bar/settings-button.tsx
> +			<span>
Done

2023-02-23 10:55 UTC, StyleShit submitted a review, later dismissed

2023-02-23 13:57 UTC, rotemee requested changes

2023-02-23 13:57 UTC, rotemee commented on packages/packages/documents/src/components/top-bar/settings-button.tsx
> +			<span aria-label={ undefined }>
```suggestion
			<Box component="span">
```

2023-02-23 13:57 UTC, rotemee commented on packages/packages/top-bar/src/components/ui/toolbar-menu-item.tsx
> +			<span aria-label={ undefined }>
Box.

2023-02-23 13:57 UTC, rotemee commented on packages/packages/top-bar/src/components/ui/toolbar-menu-toggle-item.tsx
> +			<span aria-label={ undefined }>
Box.

2023-02-26 08:02 UTC, Nevoss commented on packages/packages/documents/src/components/top-bar/settings-button.tsx
> +			<span aria-label={ undefined }>
Done

2023-02-26 08:03 UTC, Nevoss commented on packages/packages/top-bar/src/components/ui/toolbar-menu-item.tsx
> +			<span aria-label={ undefined }>
Done

2023-02-26 08:03 UTC, Nevoss commented on packages/packages/top-bar/src/components/ui/toolbar-menu-toggle-item.tsx
> +			<span aria-label={ undefined }>
Done

2023-02-26 08:30 UTC, rotemee approved these changes

2023-02-26 08:50 UTC, merged