Fix: Video Widget creating space inside it's wrapper [ED-9809]
elementor/elementor pull request #21484
Opened 2023-02-28 06:24 UTC by arielk

2023-02-28 08:04 UTC, StyleShit submitted a review, later dismissed

2023-03-06 12:49 UTC, hein-obox commented
Screenshot updated, because the video widget has changed.

2023-03-06 12:59 UTC, louiswol94 requested changes

2023-03-06 12:59 UTC, louiswol94 commented on tests/playwright/sanity/video.test.js
> +		const editor = await wpAdmin.useElementorCleanPost(),
This `const` before `editor` is not needed.

2023-03-06 12:59 UTC, louiswol94 commented on tests/playwright/sanity/video.test.js
> +
Looks like some indentation issues.

2023-03-06 12:59 UTC, louiswol94 commented on tests/playwright/sanity/video.test.js
> +		const editor = await wpAdmin.useElementorCleanPost(),
Same feedback as in the container test.

2023-03-06 13:18 UTC, hein-obox commented on tests/playwright/sanity/video.test.js
> +		const editor = await wpAdmin.useElementorCleanPost(),
Updated.

2023-03-06 13:23 UTC, hein-obox commented on tests/playwright/sanity/video.test.js
> +
Updated

2023-03-06 13:24 UTC, louiswol94 requested changes

2023-03-06 13:24 UTC, louiswol94 commented on tests/playwright/sanity/video.test.js
> +		expect( containerHeight ).toBe( videoIframeHeight );
```suggestion
		expect( containerHeight ).toEqual( videoIframeHeight );
```
Better readability

2023-03-06 13:59 UTC, hein-obox commented on tests/playwright/sanity/video.test.js
> +		expect( containerHeight ).toBe( videoIframeHeight );
Updated

2023-03-06 15:10 UTC, louiswol94 approved these changes

2023-03-07 14:40 UTC, merged