Internal: Improve playwright widget adding functionality [ED-9984]
elementor/elementor pull request #21564
Opened 2023-03-06 14:02 UTC by TzviRabinovitch

2023-03-06 14:06 UTC, yotamselementor requested changes

2023-03-06 14:06 UTC, yotamselementor commented on tests/playwright/pages/editor-page.js
> +		return widgetId;
Add return value to JSDoc

2023-03-09 11:55 UTC, yotamselementor approved these changes

2023-03-09 12:03 UTC, dmaziar approved these changes

2023-03-09 17:24 UTC, merged