Internal: Editor V2 - Add `import/no-cycle` eslint rule [ED-9997]
elementor/elementor pull request #21574
Opened 2023-03-07 09:05 UTC by StyleShit

2023-03-07 15:00 UTC, Nevoss requested changes

2023-03-07 15:00 UTC, Nevoss commented on packages/.eslintrc.js
> +		// Prevent circular dependencies.
```suggestion
		// Prevent circular dependencies. (if the lint is slow consider removing it)
```

2023-03-07 15:02 UTC, Nevoss requested changes

2023-03-07 15:02 UTC, Nevoss commented on packages/packages/documents/src/types.ts
> +import type { createSlice } from './store';
?

2023-03-08 05:59 UTC, StyleShit commented on packages/packages/documents/src/types.ts
> +import type { createSlice } from './store';
Changed

2023-03-08 10:23 UTC, Nevoss approved these changes

2023-03-08 11:42 UTC, merged