Fix: Flex Container-Border radius not affecting the Background ... [ED-10015]
elementor/elementor pull request #21645
Opened 2023-03-13 16:29 UTC by hein-obox

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2023-03-17 11:54 UTC, louiswol94 requested changes

2023-03-17 11:54 UTC, louiswol94 commented on tests/playwright/sanity/container.test.js
> +	test( 'Fallback image is not on top of background video AND border radius with background image', async ( { page }, testInfo ) => {
@hein-obox What is this snapshot for? `tests/playwright/sanity/accordion.test.js-snapshots/accordion-darwin.jpeg`

2023-03-17 12:50 UTC, louiswol94 approved these changes, later dismissed

2023-03-17 14:03 UTC, StuartElementor approved these changes, later dismissed

2023-03-20 08:26 UTC, StuartElementor approved these changes

2023-03-20 09:24 UTC, merged