Fix: Add `aspect-ratio` fallback in Video widget for old browsers
elementor/elementor pull request #21662
Opened 2023-03-15 11:57 UTC by rami-elementor

Fixes #21454

2023-03-28 10:36 UTC, StyleShit requested changes

2023-03-28 10:36 UTC, StyleShit commented on assets/dev/scss/frontend/widgets/video.scss
> +					left: 0;
inset?

2023-03-28 10:36 UTC, StyleShit commented on includes/widgets/video.php
> +					'916' => '0.5625',
maybe add a comment in each line?

```
// 16 / 9
```

2023-03-28 11:01 UTC, rami-elementor commented on includes/widgets/video.php
> +					'916' => '0.5625',
OK.

2023-03-28 11:03 UTC, rami-elementor commented on includes/widgets/video.php
> +					'916' => '0.5625',
```suggestion
					'169' => '1.77777', // 16 / 9
					'219' => '2.33333', // 21 / 9
					'43' => '1.33333', // 4 / 3
					'32' => '1.5', // 3 / 2
					'11' => '1', // 1 / 1
					'916' => '0.5625', // 9 / 16
```

2023-03-29 08:33 UTC, StyleShit approved these changes, later dismissed

2023-03-29 12:01 UTC, arielk approved these changes, later dismissed

2023-03-29 12:13 UTC, arielk commented
@rami-elementor change to 3.13

2023-03-29 16:44 UTC, arielk approved these changes

2023-03-29 16:44 UTC, merged