Internal: Implement Gap control [ED-9894]
elementor/elementor pull request #21672
Opened 2023-03-16 11:21 UTC by ArmanPurtoian

2023-03-17 11:56 UTC, louiswol94 approved these changes, later dismissed

2023-03-20 09:38 UTC, TzviRabinovitch requested changes

2023-03-20 09:38 UTC, TzviRabinovitch commented on tests/playwright/sanity/container.test.js
> +			container_grid: true,
maybe use a new test file for the container grid?

2023-03-20 09:38 UTC, TzviRabinovitch commented on tests/playwright/sanity/container.test.js
> +		// Set container type to grid.
We have editor.setSelectControlValuefunction ( in pro ) maybe copy it to core if we don't have a similar one

2023-03-20 09:43 UTC, hein-obox commented on includes/controls/groups/grid-container.php
> +				'{{SELECTOR}}' => '--gap: {{ROW}}{{UNIT}} {{COLUMN}}{{UNIT}}',
@TzviRabinovitch 
I believe it is safe to use this, as Evyatar had introduced this to the flex container already.
We do inherite the value from the site settings inside the SCSS: 
`--gap: var( --widgets-spacing, 20px ); // Use the gap from `Site Settings` or default to 20px.`

2023-03-20 10:31 UTC, TzviRabinovitch approved these changes

2023-03-20 10:35 UTC, louiswol94 approved these changes

2023-03-20 10:36 UTC, merged