Internal: Editor V2 - Change tab name to "Widgets" [ED-10070]
elementor/elementor pull request #21692
Opened 2023-03-19 10:33 UTC by StyleShit

2023-03-20 16:20 UTC, rotemee submitted a review, later dismissed

2023-03-22 14:09 UTC, Nevoss requested changes

2023-03-22 14:09 UTC, Nevoss commented on core/editor/assets/scss/editor-v2-overrides.scss
> +}
I think it should be a change in the normal design and not only in V2

2023-03-22 21:38 UTC, Nevoss approved these changes

2023-03-23 05:33 UTC, merged