Internal: Add Justify Content and Align Content controls [ED-9897]
elementor/elementor pull request #21721
Opened 2023-03-21 12:23 UTC by ArmanPurtoian

2023-03-21 17:52 UTC, louiswol94 requested changes

2023-03-21 17:52 UTC, louiswol94 commented on assets/dev/scss/frontend/_container.scss
> +	--grid-justify-content: start;
@ArmanPurtoian please nest these variables under e-grid class. The flex container does not need these variables.

2023-03-22 10:58 UTC, louiswol94 requested changes

2023-03-22 10:58 UTC, louiswol94 commented on includes/controls/groups/grid-container.php
> +				//'space-between' => [
@ArmanPurtoian You can delete the comments

2023-03-22 11:12 UTC, louiswol94 approved these changes, later dismissed

2023-03-22 12:59 UTC, TzviRabinovitch approved these changes

2023-03-22 15:38 UTC, merged