Tweak: Add recently added menu to top bar
elementor/elementor pull request #21806
Opened 2023-03-29 08:58 UTC by lenalElementor

2023-03-29 12:09 UTC, ranshoshani34 requested changes

2023-03-30 12:49 UTC, rotemee requested changes

2023-03-30 12:49 UTC, rotemee commented on packages/packages/recently-edited/src/components/top-bar/__tests__/recently-edited.test.tsx
> +) );
```suggestion
jest.mock( '../../../utils/fetch-posts', () => ( {
		default: jest.fn( () => Promise.resolve( [] ) ),
		__esModule: true,
} ) );
```

2023-03-30 12:49 UTC, rotemee commented on packages/packages/recently-edited/src/components/top-bar/__tests__/recently-edited.test.tsx
> +		} ] as Post[];
```suggestion
		const fetchReturnData: Post[] = [ {
			id: 1,
			title: 'Test post',
			edit_url: 'some_url',
			type: {
				post_type: 'post',
				doc_type: 'wp-post',
				label: 'Post',
			},
			date_modified: 123,
		} ];
```

2023-03-30 12:49 UTC, rotemee commented on packages/packages/recently-edited/src/utils/fetch-posts.ts
> +			.then( ( response ) => response as Post[] );
As part of the custom hook, normalize the data - for example:  define the doc_type as DocType, and then you might be able to get rid of all the casting ("as DocType") in the other components.

2023-03-30 12:49 UTC, rotemee commented on packages/packages/recently-edited/src/utils/fetch-posts.ts
> +		const baseUrl = ( window as unknown as ExtendedWindow ).elementorWebCliConfig?.urls?.rest;
We need to consult with @Nevoss about this.

2023-03-30 12:49 UTC, rotemee commented on packages/packages/recently-edited/src/components/top-bar/chip-doc-type.tsx
> +	loop_item: LoopItemTemplateIcon,
header, footer, popup, loop - we need to verify with @KingYes that it's ok to include "Pro" content in the "Core".

2023-03-30 12:49 UTC, rotemee commented on packages/packages/recently-edited/src/components/top-bar/posts-list.tsx
> +			<ListSubheader sx={ { fontSize: 12, fontStyle: 'italic', pl: 4 } } component="div" id="nested-list-subheader">
Please test the entire UI in RTL mode.

2023-03-30 12:49 UTC, rotemee commented on packages/packages/recently-edited/src/components/top-bar/posts-list.tsx
> +			{ recentPosts.map( ( { title, edit_url: editUrl, type, id } ) => (
Instead of changing the variable name to "editUrl" try to do it in the data normalization in the new custom hook.

2023-03-30 19:35 UTC, lenalElementor commented on packages/packages/recently-edited/src/components/top-bar/__tests__/recently-edited.test.tsx
> +			buttons[ 0 ].click(); // Opens the recently edited menu
I got errors before i wrapped it.

2023-03-30 19:35 UTC, lenalElementor commented on packages/packages/recently-edited/src/components/top-bar/__tests__/recently-edited.test.tsx
> +		await waitFor( () => {
I got errors before i wrapped it.

2023-04-04 07:44 UTC, Nevoss requested changes

2023-04-04 07:44 UTC, Nevoss commented on packages/packages/recently-edited/package.json
> +		"@wordpress/url": "*"
Please set versions

2023-04-04 07:44 UTC, Nevoss commented on packages/packages/recently-edited/package.json
> +		"@elementor/v1-adapters": "*",
Can you remove it?

2023-04-04 07:44 UTC, Nevoss commented on packages/packages/recently-edited/src/hooks/use-recent-posts.ts
> +export default function useRecentPosts( document: unknown ) {
If you need only document id, just use documentId, and then you can type it as number

2023-04-04 11:24 UTC, rotemee requested changes

2023-04-04 11:24 UTC, rotemee commented on packages/packages/recently-edited/src/components/top-bar/posts-list.tsx
> +					<Typography variant="caption" sx={ { color: 'grey.500', fontStyle: 'italic', fontWeight: 300, p: 4, ...( isRTL() ? { pl: '25px' } : { pr: '25px' } ) } } component="div" aria-label={ undefined }>
1. No need to handle the RTL flip, Material does this for you, just use the LTR version value.
2. Please don't use hard-coded values (25px), use the spacing values from the Storybook (the value of 7 will be 24px for example).
3. Are you sure you need the font-weight 300?

2023-04-04 11:33 UTC, lenalElementor commented on packages/packages/recently-edited/src/hooks/use-recent-posts.ts
> +		const baseUrl = ( window as unknown as ExtendedWindow ).elementorWebCliConfig?.urls?.rest;
Already done.

2023-04-04 14:05 UTC, rotemee approved these changes

2023-04-04 14:41 UTC, nivnoimanelementor approved these changes

2023-04-04 14:42 UTC, merged