Internal: Editor V2 - Support dark mode in Site Settings [ED-9951]
elementor/elementor pull request #21834
Opened 2023-03-30 05:56 UTC by StyleShit

2023-03-30 08:55 UTC, rotemee submitted a review, later dismissed

2023-04-03 08:00 UTC, Nevoss requested changes

2023-04-03 08:00 UTC, Nevoss commented on packages/packages/editor/src/components/theme-provider.tsx
> +}
Make it short

2023-04-03 08:00 UTC, Nevoss commented on packages/packages/editor/src/components/theme-provider.tsx
> +	}, [] );
separate effects

2023-04-03 08:00 UTC, Nevoss commented on packages/packages/editor/src/components/theme-provider.tsx
> +				const isUserPreferences = event.args?.container?.id === 'editorPreferences_settings';
remove

2023-04-03 08:00 UTC, Nevoss commented on packages/packages/editor/src/components/theme-provider.tsx
> +				const isColorScheme = event.args?.settings && 'ui_theme' in event.args.settings;
Explain

2023-04-03 09:21 UTC, StyleShit commented on packages/packages/editor/src/components/theme-provider.tsx
> +	}, [] );
Done

2023-04-03 09:21 UTC, StyleShit commented on packages/packages/editor/src/components/theme-provider.tsx
> +				const isUserPreferences = event.args?.container?.id === 'editorPreferences_settings';
Done

2023-04-03 11:29 UTC, Nevoss approved these changes

2023-04-03 11:47 UTC, merged