Internal: Editor V2 - Using packages [ED-10284]
elementor/elementor pull request #22085
Opened 2023-04-17 12:59 UTC by Nevoss

2023-04-30 13:16 UTC, StyleShit submitted a review, later dismissed
🔥

2023-05-02 11:26 UTC, rotemee requested changes

2023-05-02 11:34 UTC, Nevoss commented on .grunt-config/webpack.packages.js
> +	.filter( ( packageName ) => !! packageName.startsWith( '@elementor/' ) )
Done

2023-05-02 11:34 UTC, Nevoss commented on .grunt-config/webpack.packages.js
> +	.filter( ( packageName ) => !! packageName.startsWith( '@elementor/' ) )
Done

2023-05-02 11:43 UTC, rotemee approved these changes

2023-05-02 13:31 UTC, merged