Tweak: Prevent WooCommerce page creation on import
elementor/elementor pull request #22098
Opened 2023-04-18 12:32 UTC by ranshoshani34

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2023-04-18 13:57 UTC, ZeyadMahagna requested changes
small request

2023-04-18 13:57 UTC, ZeyadMahagna commented on app/modules/import-export/module.php
> +		if ( '1' === ElementorUtils::get_super_global_value( $_SERVER, 'HTTP_X_ELEMENTOR_IMPORT' ) ) {
Can you save the "1" as a const? would be easier to read

2023-04-18 14:02 UTC, ZeyadMahagna submitted a review, later dismissed

2023-04-19 08:48 UTC, ManorHazazE approved these changes

2023-05-09 10:00 UTC, merged