Tweak: Improve Elementor Navigator accessibility [ED-10583]
elementor/elementor pull request #22262
Opened 2023-05-01 15:03 UTC by rami-elementor

2023-05-05 12:06 UTC, arielk submitted a review, later dismissed

2023-05-07 08:39 UTC, StyleShit requested changes

2023-05-07 08:39 UTC, StyleShit commented on assets/dev/js/editor/regions/navigator/element.js
> +		}
```suggestion
		if ( ENTER_KEY === event.keyCode ) {
			this.onItemClick( event );
			return;
		}

		if ( SPACE_KEY === event.keyCode ) {
			this.onToggleListClick( event );
			return;
		}
```

should theoretically never happen. but just for readability

2023-05-07 09:06 UTC, StyleShit approved these changes

2023-05-07 09:50 UTC, merged