Internal: Editor V2 - Support client settings per package [ED-10161]
elementor/elementor pull request #22270
Opened 2023-05-02 04:46 UTC by StyleShit

2023-05-03 11:19 UTC, Nevoss requested changes

2023-05-03 11:19 UTC, Nevoss commented on core/editor/client-settings.php
> +class Client_Settings {
I think @KingYes should review this part

2023-05-09 06:49 UTC, rotemee approved these changes, later dismissed

2023-05-10 06:01 UTC, Nevoss requested changes

2023-05-10 07:30 UTC, StyleShit commented on core/editor/assets/js/editor-environment-v2.js
> +window.__UNSTABLE__elementorPackages.env.initEnv( window.elementorEditorV2Settings );
Done

2023-05-10 07:47 UTC, StyleShit commented on core/editor/config-providers/editor-v2-config-provider.php
> +	}
Done

2023-05-10 15:34 UTC, Nevoss approved these changes

2023-05-11 05:26 UTC, merged