Internal: Added `@deprecated` tags to mark deprecated JS symbols [ED-10606]
elementor/elementor pull request #22316
Opened 2023-05-03 19:23 UTC by rami-elementor

2023-05-04 06:54 UTC, udidol requested changes

2023-05-04 06:54 UTC, udidol commented on assets/dev/js/editor/components/template-library/manager.js
> +	/**
See JS Lint

2023-05-04 06:54 UTC, udidol commented on assets/dev/js/editor/container/container.js
> +	/**
See JS Lint

2023-05-04 06:54 UTC, udidol commented on assets/dev/js/editor/container/container.js
> +	/**
See JS Lint

2023-05-04 13:09 UTC, udidol submitted a review, later dismissed

2023-05-07 14:34 UTC, matipojo requested changes

2023-05-07 14:34 UTC, matipojo commented on assets/dev/js/editor/controls/repeater.js
> +	 * @deprecated since 3.0.0, use `$e.run( 'document/repeater/insert' )` instead.
It's not deprecated, only "add models directly to the repeater" is deprecated

2023-05-07 14:34 UTC, matipojo commented on assets/dev/js/frontend/utils/lightbox/lightbox.js
> +	 * @deprecated since 3.1.4
Only `if ( window.elementorCommon )`

2023-05-08 12:32 UTC, arielk approved these changes

2023-05-09 10:31 UTC, matipojo approved these changes

2023-05-15 11:06 UTC, merged