Tweak: Adding packages loading config validation [ED-10249]
elementor/elementor pull request #22344
Opened 2023-05-07 13:08 UTC by rotemee

2023-05-09 09:26 UTC, StyleShit requested changes

2023-05-09 09:26 UTC, StyleShit commented on core/editor/config-providers/editor-v2-config-provider.php
> +						$name => array_replace([
```suggestion
						$name => array_replace( [
```

2023-05-09 09:26 UTC, StyleShit commented on core/editor/config-providers/editor-v2-config-provider.php
> +					return isset( $package_data['handle'] );
```suggestion
					return ! empty( $package_data['handle'] );
```

maybe?

2023-05-09 09:51 UTC, rotemee commented on core/editor/config-providers/editor-v2-config-provider.php
> +						$name => array_replace([
Done.

2023-05-09 09:51 UTC, rotemee commented on core/editor/config-providers/editor-v2-config-provider.php
> +					return isset( $package_data['handle'] );
Done.

2023-05-09 10:04 UTC, StyleShit submitted a review, later dismissed

2023-05-10 06:13 UTC, Nevoss approved these changes, later dismissed

2023-05-10 06:45 UTC, StyleShit approved these changes

2023-05-10 06:45 UTC, Nevoss approved these changes

2023-05-10 07:36 UTC, merged