Tweak: Improve Button widget accessibility [ED-10602]
elementor/elementor pull request #22416
Opened 2023-05-11 06:05 UTC by rami-elementor

If the button has a links, it should not have `role` attribute.

If the button doesn’t have a link, it can have `role` attribute.

2023-05-11 06:24 UTC, rami-elementor commented
The commit above fixies the issue.

The next commits are not related to a11y, they match the JS and PHP render attributes.

2023-05-16 10:00 UTC, arielk approved these changes, later dismissed

2023-05-20 19:54 UTC, rami-elementor commented
This PR fixes the button widget, the failed screen-shotter test is in the alert widget. Not related to this PR.

2023-05-21 09:52 UTC, TzviRabinovitch requested changes

2023-05-21 09:52 UTC, TzviRabinovitch commented on tests/playwright/selectors/editor-selectors.js
> +		getByName: ( name ) => `a[class="elementor-button"]:has-text("${ name }")`,
```suggestion
		getByName: ( name ) => `.elementor-button:has-text("Click here"),
```

2023-05-21 11:09 UTC, TzviRabinovitch requested changes

2023-05-21 11:09 UTC, TzviRabinovitch commented on tests/playwright/selectors/editor-selectors.js
> +		getByName: ( name ) => `.elementor-button:has-text("Click here"),
```suggestion
		getByName: ( name ) => `.elementor-button:has-text("Click here")`,
```

2023-05-21 11:41 UTC, TzviRabinovitch approved these changes

2023-05-21 13:35 UTC, merged