Internal: Github action of creating release branches [ED-10633]
elementor/elementor pull request #22600
Opened 2023-05-30 06:48 UTC by maork-elementor

2023-05-30 09:05 UTC, matipojo requested changes

2023-05-30 09:05 UTC, matipojo commented on .github/workflows/create-release-branch.yml
> +          git config --global user.name "ElementorBot"
- Move to before the commit action.
- 
```suggestion
          git config --global user.name "${{ secrets.MAINTAIN_USERNAME }}"
          git config --global user.email "${{ secrets.MAINTAIN_EMAIL }}"
```

2023-05-30 09:05 UTC, matipojo commented on .github/workflows/create-release-branch.yml
> +          increment_version=$(echo $current_branch_version | awk -F. -v OFS=. '{$NF++;print}')
Test various cases

2023-05-30 09:08 UTC, matipojo requested changes

2023-05-30 11:24 UTC, maork-elementor commented on .github/workflows/create-release-branch.yml
> +          git config --global user.name "ElementorBot"
Done

2023-05-30 11:24 UTC, maork-elementor commented on .github/workflows/create-release-branch.yml
> +          # e.g 3.14
Done

2023-05-30 11:25 UTC, maork-elementor commented on .github/workflows/create-release-branch.yml
> +          #e.g refs/heads/3.14
Done

2023-05-30 11:26 UTC, maork-elementor commented on .github/workflows/create-release-branch.yml
> +          increment_version=$(echo $current_branch_version | awk -F. -v OFS=. '{$NF++;print}')
Work on case such as 

3.13
3.0
3.6

2023-05-30 11:35 UTC, maork-elementor commented on .github/workflows/create-release-branch.yml
> +  create-branch:
Done

2023-06-04 06:49 UTC, matipojo approved these changes

2023-06-04 06:49 UTC, matipojo approved these changes

2023-06-04 18:30 UTC, merged