Images AI Tweaks
elementor/elementor pull request #22649
Opened 2023-06-01 22:36 UTC by bainternet

2023-06-02 09:17 UTC, arielk submitted a review, later dismissed

2023-06-04 10:01 UTC, KingYes requested changes

2023-06-04 10:01 UTC, KingYes commented on modules/ai/assets/js/editor/ai-behavior.js
> +		this.mediaButtonLabel = __( 'Create with AI', 'elementor' );
move outside

2023-06-04 10:01 UTC, KingYes commented on modules/ai/assets/js/editor/ai-behavior.js
> +		const defaultValue = this.getOption( 'additionalOptions' )?.defaultValue;
change the logic

2023-06-04 14:10 UTC, KingYes approved these changes

2023-06-04 14:44 UTC, merged