Internal: Fix flaky PW tests [ED-10774]
elementor/elementor pull request #22718
Opened 2023-06-09 07:22 UTC by mykytamurzin

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [X ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

* Fix flaky tests

## Description
An explanation of what is done in this PR

* Fix flaky tests

## Test instructions
This PR can be tested by following these steps:

* Run PW tests

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2023-06-09 07:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/elementor/elementor?pullRequest=22718) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/elementor/elementor?pullRequest=22718) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/elementor/elementor?pullRequest=22718) it.</sub>

2023-06-12 07:27 UTC, Barcov approved these changes

2023-06-12 08:32 UTC, Barcov requested changes

2023-06-12 08:32 UTC, Barcov commented on tests/playwright/sanity/assets/dev/js/editor/elements/views/widget.test.js
> +	test( 'Check if the empty placeholder is displayed inside the Basic Gallery widget', async ( { page }, testInfo ) => {
@mykytamurzin I notice these tests still fail because of long loading times after the responsive breakpoints are updated.

2023-06-12 08:32 UTC, Barcov commented on tests/playwright/sanity/includes/elements/section/reverse-columns/reverse-columns.test.js
> +	test( 'Reverse columns:All - Experiment breakpoints:Off ', async ( { page }, testInfo ) => {
@mykytamurzin Same with this one.

2023-06-12 08:32 UTC, Barcov commented on tests/playwright/sanity/includes/elements/section/reverse-columns/reverse-columns.test.js
> +		test( `Reverse columns:${ testDevice } - Experiment breakpoints:On`, async ( { page }, testInfo ) => {
@mykytamurzin Same with this one.

2023-06-12 08:32 UTC, Barcov commented on tests/playwright/sanity/includes/elements/section/reverse-columns/reverse-columns.test.js
> +	test( 'Reverse columns:All - Experiment breakpoints:On', async ( { page }, testInfo ) => {
@mykytamurzin Same with this one.

2023-06-12 19:25 UTC, hein-obox commented on tests/playwright/sanity/assets/dev/js/editor/elements/views/widget.test.js
>  		const emptyViewPlaceholderCount = await editor.getPreviewFrame().locator( '.elementor-widget-image-gallery .elementor-widget-empty-icon' ).count();
About line 99:

Can we try to make this less flaky?

Could we use the 'waitForSelector', like on line 27: 

`await editor.getPreviewFrame().waitForSelector( '.elementor-widget .elementor-widget-empty-icon' );`

2023-06-13 10:01 UTC, Barcov submitted a review, later dismissed

2023-06-13 10:01 UTC, Barcov commented on tests/playwright/sanity/includes/elements/section/reverse-columns/reverse-columns.js
> +			const searchParams = pageUrl.searchParams;
Nice

2023-06-13 11:05 UTC, louiswol94 commented
@mykytamurzin As discussed, please check Pro's implementation, and see if it can fix core. Thanks!

2023-06-13 14:45 UTC, louiswol94 approved these changes

2023-06-13 14:45 UTC, merged