New: Image AI Tools [ED-11009]
elementor/elementor pull request #22716
Opened 2023-06-08 18:17 UTC by rotemee

2023-06-11 16:23 UTC, bainternet approved these changes, later dismissed

2023-06-11 17:39 UTC, bainternet approved these changes

2023-06-12 10:14 UTC, KingYes requested changes

2023-06-12 10:14 UTC, KingYes commented on modules/ai/connect/ai.php
> +		$payload .= 'Content-Disposition: form-data; name="' . $name . '"; filename="' . $name . '"' . "\r\n";
Add `esc_attr` here

2023-06-12 10:14 UTC, KingYes commented on modules/ai/connect/ai.php
> +		$temp_file = tempnam( sys_get_temp_dir(), 'ai' ) . $file_ext;
Try use `wp_tempnam` function

2023-06-12 10:14 UTC, KingYes commented on modules/ai/connect/ai.php
> +			@unlink( $temp_file );
use `file_exists` and `unlink` without `@`

2023-06-12 11:35 UTC, KingYes approved these changes

2023-06-12 11:44 UTC, merged