Tweak/ed 11035 ai tests
elementor/elementor pull request #22825
Opened 2023-06-19 15:28 UTC by KingYes

2023-06-19 16:04 UTC, TzviRabinovitch requested changes

2023-06-19 16:04 UTC, TzviRabinovitch commented on tests/playwright/sanity/modules/ai/ai-text.test.js
> +			await page.locator( 'button[aria-label="close"]' ).click();
maybe extract this to a function in the editor-page.js

2023-06-19 16:04 UTC, TzviRabinovitch commented on tests/playwright/sanity/modules/ai/user-information.mock.js
> +export const userInformationMock = getJsonMock( {
maybe extract to another file or an external resouces

2023-06-19 16:04 UTC, TzviRabinovitch commented on tests/playwright/sanity/modules/ai/user-information.test.js
> +			await page.route( '/wp-admin/admin-ajax.php', async ( route ) => {
maybe extract all AI Routs to a function in the editor or somewhere else?

2023-06-19 16:17 UTC, dmaziar commented on tests/playwright/sanity/modules/ai/ai-button.test.js
> +			await expect( page.locator( '.elementor-control-title.elementor-control-type-textarea .e-ai-button' ) ).toHaveCount(1 );
```
	const widgets = [ 'heading', 'text-editor', 'image'];
			for ( const i in widgets ) {
				const id = await editorPage.addWidget( widgets[ i ] );
				await expect( page.getByRole( 'button', { name: 'Write with AI' } ) ).toHaveCount( 1 );
				await editorPage.removeElement( id );
			}

```

2023-06-19 16:18 UTC, dmaziar commented on tests/playwright/sanity/modules/ai/ai-button.test.js
> +			await page.click( '.elementor-panel-navigation-tab.elementor-tab-control-advanced' );
I would move it to a separate test.

2023-06-19 16:19 UTC, dmaziar commented on tests/playwright/sanity/modules/ai/ai-button.test.js
> +			await page.locator( '.elementor-control-_background_background.elementor-control-type-choose label[data-tooltip="Classic"]' ).click();
await page.locator('[data-tooltip="Classic"]').click() will do the same

2023-06-21 11:41 UTC, louiswol94 commented on tests/playwright/sanity/modules/ai/ai-button.test.js
> +			await page.locator(  '.elementor-control-_background_background .eicon-paint-brush' ).click();
```suggestion
			await page.locator( '.elementor-control-_background_background .eicon-paint-brush' ).click();
```

2023-06-21 11:44 UTC, KingYes commented on package.json
> +		"test:playwright:ai": "npx cross-env TEST_SUITE=@ai playwright test -c tests/playwright/playwright.config.js",
I fixed all this file to tabs.

2023-06-21 11:50 UTC, TzviRabinovitch approved these changes

2023-06-21 14:54 UTC, merged