Internal: Generic warning message for upload JSON [ED-11138]
elementor/elementor pull request #22832
Opened 2023-06-20 07:57 UTC by Nevoss

2023-06-21 08:45 UTC, StyleShit requested changes

2023-06-21 08:45 UTC, StyleShit commented on assets/dev/js/admin/admin.js
> +import { showJsonWarningMessageIfNeeded } from '../utils/upload-json-warning-message';
```suggestion
import { showJsonUploadWarningMessageIfNeeded } from '../utils/json-upload-warning-message';
```

maybe

2023-06-21 08:45 UTC, StyleShit commented on assets/dev/js/editor/components/template-library/views/parts/import.js
> +import { showJsonWarningMessageIfNeeded } from '../../../../../utils/upload-json-warning-message';
```suggestion
import { showJsonWarningMessageIfNeeded } from 'elementor-utils/upload-json-warning-message';
```

2023-06-21 08:45 UTC, StyleShit commented on assets/dev/js/utils/introduction.js
> +	setIntroductionMap( source ) {
```suggestion
	setIntroductionMap( map ) {
```

OR 

```suggestion
	setIntroductionMap( introductionMap ) {
```

IDK

2023-06-21 08:45 UTC, StyleShit commented on assets/dev/js/utils/upload-json-warning-message.js
> +		genericWarningModal = createGenericWarningModal( Introduction );
```suggestion
		genericWarningModal = createGenericWarningModal( IntroductionClass );
```

maybe?

2023-06-21 08:45 UTC, StyleShit commented on assets/dev/js/utils/upload-json-warning-message.js
> +			// Translators: %1$s: Opening strong tag, %2$s: Closing strong tag.
```suggestion
```

2023-06-21 17:20 UTC, Nevoss commented on assets/dev/js/admin/admin.js
> +import { showJsonWarningMessageIfNeeded } from '../utils/upload-json-warning-message';
Done

2023-06-21 17:22 UTC, Nevoss commented on assets/dev/js/editor/components/template-library/views/parts/import.js
> +import { showJsonWarningMessageIfNeeded } from '../../../../../utils/upload-json-warning-message';
Done

2023-06-21 17:22 UTC, Nevoss commented on assets/dev/js/utils/introduction.js
> +	setIntroductionMap( source ) {
Done

2023-06-21 17:24 UTC, Nevoss commented on assets/dev/js/utils/upload-json-warning-message.js
> +			// Translators: %1$s: Opening strong tag, %2$s: Closing strong tag.
Opss.. done

2023-06-25 04:53 UTC, StyleShit submitted a review, later dismissed

2023-06-26 06:00 UTC, StyleShit approved these changes

2023-06-26 06:08 UTC, merged