Tweak: Remove deprecated schemes area [ED-9386]
elementor/elementor pull request #22952
Opened 2023-07-02 15:09 UTC by KingYes

2023-07-03 06:57 UTC, Nevoss requested changes

2023-07-03 06:57 UTC, Nevoss commented on core/upgrade/upgrades.php
> -	public static function _v_3_5_0_remove_old_elementor_scheme() {
Why not keep it? if users comes from old version so the schema will be removed

2023-07-03 06:57 UTC, Nevoss commented on includes/plugin.php
> -			new Elementor_3_Re_Migrate_Globals();
Maybe we still need it?

2023-07-03 10:07 UTC, KingYes commented on includes/plugin.php
> -			new Elementor_3_Re_Migrate_Globals();
It's used with a deprecation functions.

2023-07-04 06:30 UTC, Nevoss approved these changes, later dismissed

2023-07-04 07:59 UTC, matipojo requested changes
Please keep the PHP public API, so, old plugins and themes that calling [`Elementor::instance()->schemes_manager`](https://github.com/search?type=code&q=-%3Eschemes_manager) will not throw a fatal error.

2023-07-04 16:11 UTC, arielk approved these changes

2023-07-05 14:16 UTC, matipojo approved these changes

2023-07-05 14:41 UTC, merged