Internal: Image AI Refactor [ED-11037]
elementor/elementor pull request #22953
Opened 2023-07-03 07:42 UTC by rotemee

2023-07-03 12:15 UTC, KingYes requested changes, later dismissed

2023-07-03 12:37 UTC, rotemee commented on modules/ai/assets/js/editor/page-content.js
> +		const needsUpgradeChip = ! hasSubscription || usagePercentage <= 80;
it should be displayed only when below 80 no? (It was presented to me when I had 83 in the credits is it correct?).

2023-07-03 12:39 UTC, rotemee commented on modules/ai/assets/js/editor/pages/form-media/components/image-actions.js
> +ImageActions.CopyIcon = CopyIcon;
Why not? (https://www.patterns.dev/posts/compound-pattern)

2023-07-03 13:23 UTC, rotemee commented on modules/ai/assets/js/editor/page-content.js
> +		const needsUpgradeChip = ! hasSubscription || usagePercentage <= 80;
My bad, I thought it was credited - fixed.

2023-07-04 12:28 UTC, bainternet approved these changes

2023-07-04 12:29 UTC, merged