Fix: WC page settings on Elementor site settings won't save correctly [ED-11236]
elementor/elementor pull request #23040
Opened 2023-07-12 11:12 UTC by ArmanPurtoian

2023-07-12 14:04 UTC, louiswol94 requested changes
@ArmanPurtoian In general, I don't think this **save command** is supposed to be aware of any **specific settings**. So we should not do the `startsWith( 'woocommerce' )`.

Then, we should always remove the default, otherwise it will create a huge payload.

My suggestion is after removing the defaults, check that every item in `container.settings.changed` is in the `settings` object that will be saved. This will make sure any settings that were changed will be in the payload.

`document.container.settings.changed`:
```
{
    "woocommerce_myaccount_page_id": "9"
}
```

WDYT?

2023-07-13 12:35 UTC, louiswol94 requested changes

2023-07-13 14:08 UTC, louiswol94 commented on assets/dev/js/editor/document/save/commands/internal/save.js
> +	checkIfPersistentSettingsAddedToPayload( settings, container ) {
```suggestion
	maybeAddPersistentSettingsToPayload( settings, container ) {
```

2023-07-14 16:00 UTC, louiswol94 commented on assets/dev/js/editor/document/save/commands/internal/save.js
> +				settings[ setting ] = container.settings.defaults[ setting ];
```suggestion
				settings[ setting ] = container?.settings?.defaults[ setting ];
```

2023-07-14 16:15 UTC, louiswol94 approved these changes

2023-07-16 06:59 UTC, TzviRabinovitch approved these changes

2023-07-16 07:00 UTC, merged