Fix: Packages Global Variable Name [ED-11296]
elementor/elementor pull request #23079
Opened 2023-07-17 09:19 UTC by rotemee

2023-07-17 12:50 UTC, StyleShit submitted a review, later dismissed

2023-07-17 12:54 UTC, Nevoss requested changes

2023-07-17 12:54 UTC, Nevoss commented on core/admin/admin.php
> +				$config = $assets_config_provider->get( $package );
```suggestion
				$config = $assets_config_provider->load( $package )->get( $package );
				
				if ( ! $config ) { return; } 
```

2023-07-18 09:23 UTC, StyleShit approved these changes

2023-07-18 09:26 UTC, Nevoss approved these changes

2023-07-18 10:58 UTC, merged