New: Nested Tabs - Accessibility [ED-7339]
elementor/elementor pull request #23298
Opened 2023-08-03 12:55 UTC by hein-obox

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2023-08-03 12:56 UTC, hein-obox commented on modules/nested-tabs-html/assets/js/frontend/handlers/nested-tabs-html.js
> +				ArrowLeft: elementorFrontendConfig.is_rtl ? 'next' : 'previous',
Using strings instead of integers makes it easier to read this.

2023-08-03 13:02 UTC, hein-obox commented on modules/nested-tabs-html/assets/js/frontend/handlers/nested-tabs-html.js
> -	onTabKeyDown( event ) {
I have cleaned up old functions as much as possible.

2023-08-03 13:03 UTC, hein-obox commented on modules/nested-tabs-html/assets/js/frontend/handlers/nested-tabs-html.js
> -	getVisibleTabTitle( tabTitleFilter ) {
This is old code used for a previous round of A11Y implementations, before we changed the Nested Elements markup.

2023-08-04 03:40 UTC, hein-obox commented on modules/nested-tabs-html/assets/js/frontend/handlers/nested-tabs-html.js
> +		if ( 'Escape' !== event.key ) {
@ArmanPurtoian 'keyCode' has been deprecated: https://www.toptal.com/developers/keycode/escape. 
Do you have a reference for the support of 'Escape'?

2023-08-04 03:50 UTC, hein-obox commented on modules/nested-tabs-html/assets/js/frontend/handlers/nested-tabs-html.js
> +			const currentTabIndex = parseInt( this.getTabIndex( event.currentTarget ) ),
I have added '|| 1' to guarantee a valid value.

2023-08-04 13:07 UTC, ArmanPurtoian requested changes

2023-08-04 13:24 UTC, ArmanPurtoian submitted a review, later dismissed

2023-08-07 12:35 UTC, hein-obox commented on assets/dev/js/frontend/handlers/accessibility/title-keyboard-handler.js
> +	geTitleFilterSelector( titleIndex ) {
Updated.

2023-08-07 12:44 UTC, hein-obox commented on modules/nested-tabs-html/widgets/nested-tabs-html.php
> +			<div class="e-n-tabs-heading" role="tablist">
The @axe-core/playwright testing tool required that we wrap the 'role="tablist"' directly around the 'role="tab"' elements.

2023-08-07 12:45 UTC, hein-obox commented on package.json
> +		"@axe-core/playwright": "^4.7.3",
I have added the @axe-core/playwright library to the playwright configuration.

2023-08-07 15:37 UTC, ArmanPurtoian requested changes

2023-08-08 08:33 UTC, hein-obox commented on assets/dev/js/frontend/handlers/accessibility/nested-title-keyboard-handler.js
> +				ArrowLeft: elementorFrontendConfig.is_rtl ? 'next' : 'previous',
Updated.

2023-08-08 08:33 UTC, hein-obox commented on assets/dev/js/frontend/handlers/accessibility/nested-title-keyboard-handler.js
> +		const indexAttribute = this.getSettings( 'datasets' ).titleIndex;
Updated.

2023-08-08 08:33 UTC, hein-obox commented on assets/dev/js/frontend/handlers/accessibility/nested-title-keyboard-handler.js
> +		const indexAttribute = this.getSettings( 'datasets' ).titleIndex;
Updated.

2023-08-08 10:50 UTC, rami-elementor approved these changes

2023-08-08 10:53 UTC, ArmanPurtoian approved these changes

2023-08-08 14:54 UTC, merged