Internal: AI - Send site context for generate layout request
elementor/elementor pull request #23352
Opened 2023-08-09 06:36 UTC by Nevoss

2023-08-09 08:06 UTC, StyleShit requested changes

2023-08-09 09:21 UTC, Nevoss commented on modules/ai/module.php
> +				) {
Done

2023-08-09 09:22 UTC, StyleShit approved these changes

2023-08-10 04:54 UTC, rotemee approved these changes

2023-08-10 05:13 UTC, merged