Internal: Remove event listeners in grid container handler [ED-11747]
elementor/elementor pull request #23409
Opened 2023-08-14 13:13 UTC by StyleShit

2023-08-14 14:30 UTC, Nevoss requested changes

2023-08-14 14:30 UTC, Nevoss commented on assets/dev/js/frontend/handlers/container/grid-container.js
> +	__construct( settings ) {
What about other handlers?

2023-08-15 04:56 UTC, StyleShit commented on assets/dev/js/frontend/handlers/container/grid-container.js
> +	__construct( settings ) {
From what I saw, they're fine

2023-08-15 05:56 UTC, Nevoss approved these changes

2023-08-15 12:07 UTC, merged