Internal: AI-Layout - Connect Prompt enhancement [ED-11730]
elementor/elementor pull request #23428
Opened 2023-08-15 15:20 UTC by Nevoss

2023-08-16 07:05 UTC, StyleShit requested changes

2023-08-16 07:05 UTC, StyleShit commented on modules/ai/assets/js/editor/pages/form-layout/components/prompt-form.js
> +			<GenerateButton disabled={ isLoading || ! isActive || '' === prompt || isEnhancing } />
maybe extract the buttons' disabled state to a variable?

2023-08-16 08:34 UTC, StyleShit approved these changes

2023-08-17 06:36 UTC, rotemee approved these changes

2023-08-17 07:08 UTC, merged