Tweak: Upgrade minimum required PHP version from 7.0 to 7.3 [ED-11983]
elementor/elementor pull request #23619
Opened 2023-08-30 10:53 UTC by rami-elementor

Ref: https://developers.elementor.com/elementors-roadmap-to-upgrade-php-versions/

2023-08-30 10:56 UTC, yotamselementor requested changes, later dismissed

2023-08-30 10:56 UTC, yotamselementor commented on readme.txt
> += Recommend Requirements =
```suggestion
= Recommended Requirements =
```

2023-08-30 12:22 UTC, matipojo requested changes, later dismissed

2023-08-30 12:22 UTC, matipojo commented on .github/workflows/phpunit.yml
> +        php_versions: ['7.3', '7.4', '8.0', '8.1', '8.2']
```suggestion
        php_versions: ['7.3', '7.4']
```

2023-09-03 12:37 UTC, rami-elementor commented
Hi @yotamselementor , 

@matipojo suggested to spilt all the test-related code changes to a separate task.

2023-09-03 13:05 UTC, yotamselementor commented
> 

@rami-elementor I don't understand - what other changes do we have here that you want to split out?

2023-09-04 07:09 UTC, arielk approved these changes

2023-09-04 08:44 UTC, TzviRabinovitch approved these changes

2023-09-04 11:51 UTC, merged

2023-09-18 04:46 UTC, StyleShit commented
what about composer.json?

2023-09-18 10:58 UTC, rami-elementor commented
@StyleShit see https://github.com/elementor/elementor/pull/23619#issuecomment-1704295003 above