Internal: [Rating] [Style] Added Spacing control [ED-11944]
elementor/elementor pull request #23675
Opened 2023-09-05 15:04 UTC by TzviRabinovitch

2023-09-05 15:08 UTC, louiswol94 approved these changes

2023-09-06 05:44 UTC, davseve requested changes

2023-09-06 05:44 UTC, davseve commented on includes/widgets/rating.php
> +					],
Should we add defaults for PX?

2023-09-06 05:44 UTC, davseve commented on includes/widgets/rating.php
> +					'{{WRAPPER}}' => '--e-rating-gap: {{SIZE}}{{UNIT}}',
I am not sure about that.
AFAIK, as the implementation of `--e-rating-gap` is at the moment we will have vertical and horizontal gaps.
Shouldn't the gap be horizontal only?

2023-09-06 06:02 UTC, davseve approved these changes

2023-09-06 08:59 UTC, merged