Fix: Widget panel is empty for Editor role with 'Access to edit content only'
elementor/elementor pull request #23929
Opened 2023-10-02 06:52 UTC by Nevoss

2023-10-02 15:19 UTC, blackcolt commented on assets/dev/js/editor/components/settings/page/component.js
> +		const { activeControl, refresh } = args;
Do we need default?

2023-10-03 07:04 UTC, ManorHazazE requested changes

2023-10-03 07:04 UTC, ManorHazazE commented on assets/dev/js/editor/components/settings/page/component.js
> +		const { activeControl, refresh } = args;
+1

2023-10-03 08:41 UTC, Nevoss commented on assets/dev/js/editor/components/settings/page/component.js
> +		const { activeControl, refresh } = args;
Done

2023-10-03 08:52 UTC, ghost approved these changes

2023-10-03 10:04 UTC, merged