Tweak: Background Image Size Options are missing when choosing a dynamic image [ED-9824]
elementor/elementor pull request #24146
Opened 2023-10-30 11:34 UTC by KingYes

2023-10-30 15:10 UTC, rodolphebertozzo requested changes

2023-10-30 15:10 UTC, rodolphebertozzo commented on includes/controls/media.php
> +				<div class="elementor-control-field-description"><?php echo esc_html__( 'Image size settings don’t apply to Dynamic Images.', 'elementor' ); ?></div>
Why don't you use a <p> tag to display the error message?

2025-02-02 13:03 UTC, rami-elementor commented on includes/controls/media.php
> +				<div class="elementor-control-field-description"><?php echo esc_html__( 'Image size settings don’t apply to Dynamic Images.', 'elementor' ); ?></div>
@rodolphebertozzo

Currently, Elementor use a `<div>` tag to display field descriptions. So, for consistency, this control should use a `<div>` too.

However, you are correct, to improve semantics we should replace this to `<p>`. We will do that in a separate PR.

2025-02-02 13:31 UTC, arielk approved these changes

2025-02-02 13:45 UTC, merged