Internal: Add new "Upgrade" icon to e-icons [ED-12521]
elementor/elementor pull request #24147
Opened 2023-10-30 12:37 UTC by hein-obox

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2023-10-30 15:28 UTC, TzviRabinovitch requested changes

2023-10-30 15:28 UTC, TzviRabinovitch commented on assets/lib/eicons/css/elementor-icons.css
I think that the version also needs to be updated in lines 3 & 4

2023-10-31 07:14 UTC, hein-obox commented on assets/lib/eicons/css/elementor-icons.css
@TzviRabinovitch Updated

2023-10-31 07:20 UTC, louiswol94 approved these changes

2023-10-31 07:57 UTC, TzviRabinovitch approved these changes

2023-10-31 07:57 UTC, merged