Fix: Import Kit Issues - other plugins interference in the Import process [12524]
elementor/elementor pull request #24295
Opened 2023-11-15 08:21 UTC by Omerisra6

2023-11-15 08:41 UTC, mark-elementor commented on app/modules/import-export/module.php
> +				 current_user_can( 'manage_options' )
Please remove diff.

2023-11-15 08:42 UTC, mark-elementor commented on app/modules/import-export/assets/js/shared/process-failed-dialog/process-failed-dialog.js
> +		text: __( 'Other plugins ', 'elementor' ),
Don't forget to update the text before merging :)

2023-11-22 07:20 UTC, StyleShit requested changes

2023-11-22 07:20 UTC, StyleShit commented on app/modules/import-export/assets/js/hooks/use-kit.js
> +			return await runRequest( ajaxConfig ).catch( ( error ) => {
```suggestion
			return runRequest( ajaxConfig ).catch( ( error ) => {
```

2023-11-22 07:20 UTC, StyleShit commented on app/modules/import-export/assets/js/shared/process-failed-dialog/process-failed-dialog.js
> +		text: __( 'This is due to a conflict with one or more third-party plugins already active on your site. Try disabling them, and then give the download another go. ', 'elementor' ),
```suggestion
		text: __( 'This is due to a conflict with one or more third-party plugins already active on your site. Try disabling them, and then give the download another go.', 'elementor' ),
```

2023-11-22 07:20 UTC, StyleShit commented on app/modules/import-export/module.php
> +			'wp_',
what about global classes? (PHP's builtins, etc.)

2023-11-22 07:20 UTC, StyleShit commented on tests/phpunit/elementor/app/import-export/test-module.php
> +	}
I would try to test a real class instead of passing a string manually
maybe test the actual "handle_ajax" method instead...

2023-11-22 13:35 UTC, StyleShit commented on app/modules/import-export/module.php
> +	public function is_native_class( $class ) {
let's think about a better name

2023-11-23 13:02 UTC, Omerisra6 commented on app/modules/import-export/module.php
> +	public function is_native_class( $class ) {
Maybe is third party class?

2023-11-26 06:50 UTC, StyleShit approved these changes

2023-11-26 06:50 UTC, StyleShit commented on app/modules/import-export/module.php
> +			if ( isset( $this->import ) && $this->is_third_party_class( $e->getTrace()[0]['class'] ) ) {
🤮

2023-11-26 11:10 UTC, merged