Fix: Update 'Need Help' link for grid container [ED-12592]
elementor/elementor pull request #24478
Opened 2023-12-03 15:20 UTC by ronenboxer

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2023-12-04 07:46 UTC, louiswol94 requested changes
Hey @ronenelementor , this was a good deep dive ;)
But the controls stack is a base that should not be aware of any specific feature (like the container).
Also your solution does not work when the "Container Layout" option is changed.
I suggest you look into editing `/assets/dev/js/editor/elements/views/container.js`

2023-12-04 11:05 UTC, louiswol94 approved these changes, later dismissed

2023-12-04 17:56 UTC, hein-obox commented on tests/playwright/sanity/container-grid.test.ts
> +		const wpAdmin = new WpAdminPage( page, testInfo );
```suggestion
		const wpAdmin = new WpAdminPage( page, testInfo ),
```

2023-12-04 17:56 UTC, hein-obox commented on tests/playwright/sanity/container-grid.test.ts
> +		const editor = await wpAdmin.openNewPage(),
```suggestion
		editor = await wpAdmin.openNewPage(),
```

2023-12-04 17:56 UTC, hein-obox commented on tests/playwright/sanity/container-grid.test.ts
> +			let linkElement = page.locator( '#elementor-panel__editor__help__link' );
```suggestion
			const linkElement = page.locator( '#elementor-panel__editor__help__link' );
```

2023-12-05 08:27 UTC, hein-obox commented on tests/playwright/sanity/container-grid.test.ts
> +		editor = await wpAdmin.openNewPage(),
Indentation.

2023-12-05 08:27 UTC, hein-obox commented on tests/playwright/sanity/container-grid.test.ts
> +			let linkElement = page.locator( '#elementor-panel__editor__help__link' );
```suggestion
			const linkElement = page.locator( '#elementor-panel__editor__help__link' );
```

2023-12-05 08:49 UTC, ronenelementor commented on tests/playwright/sanity/container-grid.test.ts
> +			let linkElement = page.locator( '#elementor-panel__editor__help__link' );
Done

2023-12-05 08:50 UTC, ronenelementor commented on tests/playwright/sanity/container-grid.test.ts
> +		editor = await wpAdmin.openNewPage(),
Done

2023-12-05 09:07 UTC, hein-obox approved these changes

2023-12-05 09:10 UTC, louiswol94 approved these changes

2023-12-05 09:10 UTC, merged