Patchstack - WordPress Elementor Website Builder Plugin <= 3.17.3 is vulnerable to Arbitrary File Upload [ED-12938]
elementor/elementor pull request #24481
Opened 2023-12-04 10:13 UTC by mark-elementor

## PR Checklist

- [x] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] Security fix

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [x] I have tested this code to the best of my abilities
- [x] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2023-12-04 11:40 UTC, StyleShit requested changes

2023-12-04 16:13 UTC, mark-elementor commented on tests/phpunit/elementor/core/files/test-uploads-manager.php
> +		foreach ( $file_names_to_test as $file_name ) {
Done.

2023-12-04 16:13 UTC, mark-elementor commented on tests/phpunit/elementor/core/files/test-uploads-manager.php
> +		$template = json_encode( self::$mock_template );
The mock is larger than the code here, so is it really needed?

2023-12-05 11:17 UTC, StyleShit approved these changes, later dismissed

2023-12-05 14:39 UTC, Omerisra6 submitted a review, later dismissed

2023-12-06 07:51 UTC, StyleShit approved these changes

2023-12-06 07:53 UTC, merged