Internal: Add What's New icon inside the Top Bar [ED-13681]
elementor/elementor pull request #25099
Opened 2024-02-12 08:19 UTC by KingYes

2024-02-12 13:47 UTC, rotemee requested changes, later dismissed

2024-02-12 13:47 UTC, rotemee commented on modules/notifications/assets/js/components/editor-v2.js
> +				priority: 5,
Is it needed?

2024-02-12 13:47 UTC, rotemee commented on modules/notifications/module.php
> +		$is_editor_v2 = current_action() === 'elementor/editor/v2/scripts/enqueue';
What is it current_action? (can't find it in the code).

2024-02-12 13:47 UTC, rotemee commented on modules/notifications/assets/js/components/editor-drawer.js
> +			setIsRead={ setIsRead }
Why do you need it reactive? (if you also don't read the isRead value nowhere), instead you can just use it as an event and remove the isRead state:
```suggestion
			markAsRead={ () =>  document.body.classList.remove( 'e-has-notification' ) }
```

2024-02-12 13:47 UTC, rotemee commented on modules/notifications/assets/js/components/editor-on-button-clicked.js
> +			<EditorDrawer />,
Dark mode? RTL?

2024-02-28 16:30 UTC, arielk approved these changes

2024-02-28 16:30 UTC, merged