Internal: Fix JS Lint warnings - React [ED-13584]
elementor/elementor pull request #25129
Opened 2024-02-14 08:46 UTC by mark-elementor

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2024-02-14 08:53 UTC, StyleShit requested changes

2024-02-14 08:53 UTC, StyleShit commented on app/assets/js/index.js
maybe instead of copy-pasting the same function over and over it's worth creating a util?

2024-02-14 08:53 UTC, StyleShit commented on assets/dev/js/editor/components/icons-manager/components/icon-manager.js
> +import PropTypes from 'prop-types';
```suggestion
import * as PropTypes from 'prop-types';
```

shouldn't be like this?

2024-02-14 08:53 UTC, StyleShit commented on assets/dev/js/editor/components/icons-manager/icons-manager.js
> +
```suggestion
import { createRoot } from 'react-dom/client';
```

2024-02-14 08:53 UTC, StyleShit commented on assets/dev/js/editor/components/icons-manager/icons-manager.js
> +		}
maybe do this?

```JS
const unmount = ourCustomRenderFunction( app, domEl )

// ...

unmount();
```

2024-02-14 08:53 UTC, StyleShit commented on assets/dev/js/editor/elements/views/container/empty-view.js
> +		}
same as above

2024-02-14 08:53 UTC, StyleShit commented on modules/ai/assets/js/editor/utils/editor-integration.js
> +
why do you move it? I would keep it in the same place is possible, to have less diff

2024-02-14 08:56 UTC, StyleShit requested changes, later dismissed

2024-02-14 08:56 UTC, StyleShit commented on modules/styleguide/assets/js/styleguide-app-initiator.js
> +		}
same as above

2024-02-25 16:02 UTC, rotemee requested changes

2024-02-28 13:39 UTC, rotemee approved these changes, later dismissed

2024-02-28 14:58 UTC, mark-elementor commented on assets/dev/js/utils/react.js
> +	return { root };
Done

2024-02-28 14:58 UTC, mark-elementor commented on modules/styleguide/assets/js/styleguide-app-initiator.js
> +		}
Done.

2024-02-28 14:59 UTC, mark-elementor commented on assets/dev/js/editor/elements/views/container/empty-view.js
> +		}
Done.

2024-02-28 14:59 UTC, mark-elementor commented on assets/dev/js/editor/components/icons-manager/icons-manager.js
> +		}
Done.

2024-02-28 14:59 UTC, mark-elementor commented on app/assets/js/index.js
Done

2024-02-28 17:08 UTC, blackcolt submitted a review, later dismissed

2024-02-29 09:02 UTC, rotemee approved these changes

2024-02-29 09:06 UTC, merged