Tweak: Add units to Shape Divider [ED-13900]
elementor/elementor pull request #25293
Opened 2024-02-27 08:31 UTC by rami-elementor

2024-02-27 12:27 UTC, rodolphebertozzo requested changes

2024-02-27 12:27 UTC, rodolphebertozzo commented on includes/elements/section.php
>  					'label' => esc_html__( 'Width', 'elementor' ) . ' (%)',
```suggestion
					'label' => esc_html__( 'Width', 'elementor' ),
```

2024-02-27 12:49 UTC, rami-elementor commented on includes/elements/section.php
>  					'label' => esc_html__( 'Width', 'elementor' ) . ' (%)',
Thank you @rodolphebertozzo

2024-03-01 12:41 UTC, arielk approved these changes

2024-03-01 12:41 UTC, merged