Tweak: Improve counter widget [ED-13915]
elementor/elementor pull request #25313
Opened 2024-02-28 13:41 UTC by rami-elementor

2024-02-29 09:27 UTC, rodolphebertozzo requested changes

2024-02-29 09:27 UTC, rodolphebertozzo commented on includes/widgets/counter.php
> +			'counter-align',
A control name with a - (dash) character might cause unexpected behavior.

2024-02-29 09:28 UTC, rami-elementor commented on includes/widgets/counter.php
> +			'counter-align',
Good catch!

2024-02-29 10:01 UTC, rami-elementor commented on includes/widgets/counter.php
> +			'counter-align',
Fixed.

2024-03-27 13:57 UTC, arielk approved these changes

2024-03-27 14:31 UTC, merged