Tweak: Plgs for all AI features before connect [ED-14096]
elementor/elementor pull request #25505
Opened 2024-03-24 07:51 UTC by DennisNerush

2024-03-24 12:02 UTC, rotemee requested changes

2024-03-24 14:16 UTC, DennisNerush commented on modules/ai/assets/js/editor/ai-behavior.js
> +			}
I move the getPromotionTexts up but the button needs to stay here as it doesn't get the bounding at that point

2024-03-24 14:17 UTC, DennisNerush commented on modules/ai/assets/js/editor/components/ai-promotion-infotip-content.js
> +			<CardHeader subheader="ELEMENTOR UI" />
AI :)

2024-03-24 14:18 UTC, DennisNerush commented on modules/ai/assets/js/editor/components/ai-promotion-infotip-wrapper.js
> +					/> }
what was changed?

2024-03-24 15:34 UTC, rotemee commented on modules/ai/assets/js/editor/components/ai-promotion-infotip-wrapper.js
> +					/> }
@DennisNerush - the rounded parenthesis:
`
content={ (
 // ...
) }
`

2024-03-25 11:55 UTC, matipojo commented on modules/ai/assets/js/editor/helpers/focus-out-listener.js
> +		};
```suggestion
		return remove;
```

2024-03-25 11:58 UTC, matipojo approved these changes, later dismissed
Tests?

2024-03-25 12:04 UTC, rotemee requested changes

2024-03-25 12:04 UTC, rotemee commented on modules/ai/assets/js/editor/components/ai-promotion-infotip-wrapper.js
> +					<AiPromotionInfotip anchor={ anchor[ 0 ] }
```suggestion
					<AiPromotionInfotip anchor={ anchor }
```

2024-03-25 12:04 UTC, rotemee commented on modules/ai/assets/js/editor/ai-behavior.js
> +					anchor={ $button }
```suggestion
					anchor={ $button[ 0 ] }
```

2024-03-25 12:04 UTC, rotemee commented on modules/ai/assets/js/editor/ai-behavior.js
> +				<AiPromotionInfotipWrapper
Seems that there is a certain offset with the info-tip pointer, have you seen it as well?

2024-03-25 13:49 UTC, rotemee requested changes

2024-03-25 13:49 UTC, rotemee commented on modules/ai/assets/js/editor/helpers/focus-out-listener.js
> +				} }
```suggestion
					opacity: 0,
					position: 'fixed',
				} }
```
@DennisNerush  - to fix the vertical offset.

2024-03-25 13:49 UTC, rotemee commented on modules/ai/assets/js/editor/components/ai-promotion-infotip-content.js
> +		<Card sx={ { width: 300 } }>
```suggestion
		<Card sx={ { width: 300 } } elevation={ 0 }>
```
@DennisNerush  - to fix the color difference between the box and the arrow of the tooltip.

2024-03-26 07:24 UTC, rotemee approved these changes

2024-03-26 07:58 UTC, merged