Tweak: PLG for adding new containers [AI-771]
elementor/elementor pull request #25563
Opened 2024-03-28 14:44 UTC by DennisNerush

2024-03-31 15:43 UTC, matipojo submitted a review, later dismissed

2024-04-02 06:14 UTC, rotemee requested changes

2024-04-02 08:22 UTC, DennisNerush commented on modules/ai/assets/js/editor/module.js
> +		const element = args.container.view.$el[ 0 ];
it's the enchor

2024-04-04 14:39 UTC, rotemee commented on modules/ai/assets/js/editor/module.js
> +		const element = args.container.view.$el[ 0 ];
@DennisNerush - I meant that maybe you can set the value (`args.container.view.$el[ 0 ]`)  directly in the anchor prop (without declaring the variable).

2024-04-08 08:34 UTC, dmaziar commented on tests/playwright/pages/editor-page.ts
> +		window.sessionStorage.setItem( 'ai_promotion_introduction_editor_session_key', window.EDITOR_SESSION_ID );
obviously window is not define in playwright context.
Please use this code from Pro https://github.com/elementor/elementor-pro/blob/dbbb022f0059eef40400e23232b3822714b9ce44/tests/playwright/pages/wp-admin-page.ts#L312
and put it here in core https://github.com/elementor/elementor/blob/fd0c505639dafdf4ad279d4932ab37cd0de8b3d3/tests/playwright/pages/wp-admin-page.ts#L249
We handle pop-ups in this `closeAnnouncementsIfVisible` function

2024-04-08 08:35 UTC, dmaziar commented on tests/elements-regression/tests/elements-regression.test.ts
> +			await editorPage.hideAiPromotion();
Please remove this line and read comment below

2024-04-09 07:40 UTC, AdirD approved these changes

2024-04-10 05:14 UTC, rotemee approved these changes

2024-04-10 05:51 UTC, merged