Fix: Fatal error when updating a page
elementor/elementor pull request #25817
Opened 2024-04-23 13:11 UTC by thorbergurharaldsson

## PR Checklist

- [x] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

* Fixed a fatal error that occurs when an undefined array index is accessed in nested-tabs.php.

## Description
An explanation of what is done in this PR

* In the Nested Tabs widget, there is an issue where the code tries to call print_element() on a potentially non-existent element of the $children array without prior validation. This leads to a fatal error if the $children array at the specified index does not contain an element. The proposed change adds a check to ensure the element exists before attempting to call print_element() on it.

## Test instructions
This PR can be tested by following these steps:

1. Navigate to a page that uses the Nested Tabs widget in Elementor.
2. Ensure that the widget is set up in a way that might previously have triggered the error (e.g., by setting conditions that could lead to an unset index).
3. Verify that the page loads without PHP errors.

## Quality assurance

- [x] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2024-04-23 14:03 UTC, louiswol94 requested changes
@thorbergurharaldsson Do you perhaps have some more clearer steps to reproduce?
Thanks!

2024-04-23 14:03 UTC, louiswol94 commented on modules/nested-tabs/widgets/nested-tabs.php
> +	public function print_child($index, $item_settings = []) {
Hi @thorbergurharaldsson 
Thanks for the PR.
Can you please keep the original spacing? The PHP Lint is failing: https://github.com/elementor/elementor/actions/runs/8801041716/job/24155726088?pr=25817
This diff should be 3-5 lines in total.

2024-04-23 14:03 UTC, louiswol94 commented on modules/nested-tabs/widgets/nested-tabs.php
> +	    }
```suggestion
	    if ( isset( $children[ $index ] ) ) {
	        $children[ $index ]->print_element();
	    }
```
You can remove the comment and the `else {}`

2024-04-23 14:03 UTC, louiswol94 commented on modules/nested-tabs/widgets/nested-tabs.php
> +
```suggestion
```
Remove

2024-04-23 20:31 UTC, thorbergurharaldsson commented
> @thorbergurharaldsson Do you perhaps have some more clearer steps to reproduce? Thanks!

TBH I have no idea how it happened, I was having unrelated trouble with nested tabs on a page, I was going to try it on a another page to check if there was something wrong with the template on the original page and that's where I started to get the 500 error when trying to update that page, I some how was able to update after adding the tabs but was unable to delete or edit them afterwards and just got the 500 error, I was able to update after editing that code snippet

2024-04-24 08:32 UTC, louiswol94 commented on modules/nested-tabs/widgets/nested-tabs.php
> +
Please revert line 1150

2024-04-24 13:44 UTC, davseve submitted a review, later dismissed

2024-04-24 13:45 UTC, louiswol94 commented on modules/nested-tabs/widgets/nested-tabs.php
> +
```suggestion

```

2024-04-24 13:46 UTC, louiswol94 approved these changes

2024-04-24 13:46 UTC, davseve approved these changes

2024-04-24 13:55 UTC, louiswol94 commented
Note: We were able to reproduce this.

2024-04-24 14:02 UTC, merged

2024-04-24 14:10 UTC, louiswol94 commented
Thanks @thorbergurharaldsson