Internal: Conversion Center - Contact Buttons - Send Message
elementor/elementor pull request #25921
Opened 2024-04-29 14:39 UTC by mserino

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

* Conversion Center: Contact Button - Send Message section

## Description
An explanation of what is done in this PR

* Conversion Center: Contact Button - Send Message section

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [x] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2024-04-29 16:18 UTC, louiswol94 requested changes

2024-04-29 16:18 UTC, louiswol94 commented on modules/conversion-center/classes/render/contact-buttons-render-base.php
> +	}
This code looks duplicated, right? If so, please extract it somehow.

2024-04-29 16:18 UTC, louiswol94 commented on modules/conversion-center/classes/render/contact-buttons-render-base.php
> +	}
```suggestion
	public function build_viber_link() {
		$chat_button_number = $this->settings['chat_button_number'];
		$viber_action = $this->settings['chat_button_viber_action'];

		if ( empty( $chat_button_number ) ) {
			return '';
		}

		$action = 'contact';

		if ( ! empty( $viber_action ) ) {
			$action = $viber_action;
		}

		return add_query_arg( [
			'number' => urlencode( $chat_button_number ),
		], 'viber://' . $action );
	}
```
Just some spacing

2024-04-29 16:39 UTC, louiswol94 commented on modules/conversion-center/classes/render/contact-buttons-render-base.php
> +						<?php Utils::print_unescaped_internal_string( $send_button_text ); ?>
Are you sure this should be unescaped? It is free text input, it can be open to Stored XSS attacks.

2024-04-29 16:42 UTC, louiswol94 commented on modules/conversion-center/classes/render/contact-buttons-render-base.php
> +						<?php Utils::print_unescaped_internal_string( $send_button_text ); ?>
Also, did we use `print_unescaped_internal_string()` in other places in the widgets as well where we maybe shouldn't have? User input should always be escaped. Or is there a reason why you think these shouldn't be escaped?

2024-04-29 16:48 UTC, louiswol94 commented on modules/conversion-center/classes/render/contact-buttons-render-base.php
> +						<?php Utils::print_unescaped_internal_string( $send_button_text ); ?>
@mserino @nicoladj77  I was able to to a stored XSS attack on the Link In Bio widget for example. We've had a plethora of these security issues coming in recently, so I decided to check it here as well :)

<img width="1508" alt="Screenshot 2024-04-29 at 6 47 14 PM" src="https://github.com/elementor/elementor/assets/20996103/3f54919f-74bd-45e9-a5e6-621c38507d04">

2024-04-30 11:49 UTC, louiswol94 commented on modules/conversion-center/classes/providers/social-network-provider.php
> +	}
@mserino There is already a function `build_email_link()` in `elementor/modules/conversion-center/classes/render/render-base.php`

Can you add it to the trait and use it in both these places?

2024-04-30 11:57 UTC, louiswol94 requested changes

2024-04-30 11:57 UTC, louiswol94 commented on modules/conversion-center/classes/render/contact-buttons-render-base.php
> +					<p class="e-contact-buttons__message-bubble-time" data-time-format="<?php echo esc_html( $time_format ); ?>"></p>
```suggestion
					<p class="e-contact-buttons__message-bubble-time" data-time-format="<?php echo esc_attr( $time_format ); ?>"></p>
```
Maybe?

2024-04-30 11:57 UTC, louiswol94 commented on modules/conversion-center/classes/render/contact-buttons-render-base.php
> +			<button <?php echo $this->widget->get_render_attribute_string( 'button-' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?> type="button" aria-label="<?php echo esc_html__( 'Op
```suggestion
			<button <?php echo $this->widget->get_render_attribute_string( 'button-' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?> type="button" aria-label="<?php echo esc_attr__( 'Open Contact Buttons', 'elementor' ); ?>">
```
Maybe?

2024-04-30 11:57 UTC, louiswol94 commented on modules/conversion-center/classes/render/contact-buttons-render-base.php
> +			<button type="button" class="e-contact-buttons__close-button" aria-label=<?php echo esc_html__( 'Close Contact Buttons', 'elementor' ); ?>>
```suggestion
			<button type="button" class="e-contact-buttons__close-button" aria-label=<?php echo esc_attr__( 'Close Contact Buttons', 'elementor' ); ?>>
```
Maybe?

2024-04-30 11:57 UTC, louiswol94 commented on modules/conversion-center/classes/providers/social-network-provider.php
> +	}
Oh sorry, I see you deleted it in the other file!

2024-04-30 12:26 UTC, mserino commented on modules/conversion-center/classes/render/contact-buttons-render-base.php
> +			<button type="button" class="e-contact-buttons__close-button" aria-label=<?php echo esc_html__( 'Close Contact Buttons', 'elementor' ); ?>>
done!

2024-04-30 12:26 UTC, mserino commented on modules/conversion-center/classes/render/contact-buttons-render-base.php
> +			<button <?php echo $this->widget->get_render_attribute_string( 'button-' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?> type="button" aria-label="<?php echo esc_html__( 'Op
done!

2024-04-30 13:21 UTC, louiswol94 approved these changes

2024-04-30 13:21 UTC, merged