- test workflow
elementor/elementor pull request #27987
Opened 2024-07-08 17:03 UTC by blackcolt

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2024-07-10 12:30 UTC, yotamselementor requested changes

2024-07-10 12:30 UTC, yotamselementor commented on bin/print-ttfb.sh
> +# Loop through each JSON file that starts with "ihr" and ends with ".json"
what are these files? why are we printing them?

2024-07-10 12:30 UTC, yotamselementor commented on .performanceLighthouserc.js
> +			numberOfRuns: 1,
Probably not for this PR, but would we want more than 1 run?

2024-07-10 12:30 UTC, yotamselementor commented on .performanceLighthouserc.js
> +					'server-response-time', // This is TTFB
Good comment

2024-07-10 12:30 UTC, yotamselementor commented on .github/workflows/performance-test.yml
> +    name: Performance test - ${{ matrix.shardIndex }} on PHP 8.0
```suggestion
    name: Performance test on PHP 8.0
```

2024-07-10 12:30 UTC, yotamselementor commented on .github/workflows/performance-test.yml
> +        run: npm install -g @lhci/cli
Move this to package.json

2024-07-10 12:31 UTC, yotamselementor requested changes
Can we handle this error?
https://github.com/elementor/elementor/actions/runs/9858085586/job/27218763073?pr=27987#step:11:17

2024-07-11 05:42 UTC, Nevoss requested changes
We split the issue into 4 separate tacks for a reason. the idea is to fine-tune each step, to allow:
1. running the env with specific requirements in local env and CI env.
2. running the same action in core and pro
3. simplify the way we are writing GitHub actions and allow sharing composite actions between workflows

The first track was to create a simple workflow for creating WordPress env, something like this:
```yaml
- name: Setup wp-env
  uses: actions/setup-wp-env@vSOMETHING
  with:
    php-version: '8.0'
    wp-version: '6.6'
```

then use these actions in exiting workflow in core and pro

2025-01-09 08:13 UTC, closed without merging