Tweak: Merge "Lazy Load Background Images" feature and move to Settings [ED-15336]
elementor/elementor pull request #28076
Opened 2024-07-15 19:35 UTC by rami-elementor

2024-07-22 14:03 UTC, KingYes requested changes

2024-07-22 14:03 UTC, KingYes commented on modules/lazyload/module.php
> +	private static function is_lazy_load_background_images_enabled() : bool {
```suggestion
	private static function is_lazy_load_background_images_enabled(): bool {
```

2024-07-22 14:03 UTC, KingYes commented on modules/lazyload/module.php
> +		return (bool) get_option( 'elementor_lazy_load_background_images', '1' );
```suggestion
		return '1' === get_option( 'elementor_lazy_load_background_images', '1' );
```

2024-07-23 10:56 UTC, louiswol94 approved these changes

2024-07-23 12:06 UTC, KingYes approved these changes

2024-07-23 12:49 UTC, merged