Fix typos
elementor/elementor pull request #28081
Opened 2024-07-16 07:00 UTC by szepeviktor

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] Other... Please describe: fix misspellings, even in file names

## Summary

Found few misspellings.

https://github.com/crate-ci/typos

2024-07-16 07:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/elementor/elementor?pullRequest=28081) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/elementor/elementor?pullRequest=28081) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/elementor/elementor?pullRequest=28081) it.</sub>

2024-07-16 07:05 UTC, szepeviktor commented
Actually `$optin_url` is `$opt_in_url`
https://www.merriam-webster.com/dictionary/opt%20in

2024-07-16 12:36 UTC, toineenzo commented
@szepeviktor Great catches! Hope they will merge your clean-up soon. It looks good.

2024-07-16 12:38 UTC, toineenzo approved these changes

2024-07-16 15:43 UTC, szepeviktor commented
@davseve Could you merge this before got conflict goes boom? 💣

2024-07-16 17:29 UTC, rami-elementor requested changes

2024-07-16 19:55 UTC, szepeviktor commented on modules/nested-accordion/assets/js/frontend/handlers/nested-accordion-title-keyboard-handler.js
> +	handleTitleLinkEnterOrSpaceEvent( event ) {
@rami-elementor All 3 were reverted.

2024-07-18 06:04 UTC, rami-elementor approved these changes

2024-07-18 06:06 UTC, rami-elementor commented
@matipojo @shilo-ey Please review AI-related changes. The PR renames the components folder.

2024-07-21 11:57 UTC, matipojo approved these changes

2024-07-21 13:04 UTC, merged

2024-07-21 13:05 UTC, yotamselementor commented
Thanks @szepeviktor, this is much appreciated!

2024-07-21 13:08 UTC, szepeviktor commented
Glad to contribute.