Internal: Update the plugin's regression test with a plugin to avoid ED-15079 [ED-15360]
elementor/elementor pull request #28102
Opened 2024-07-16 16:31 UTC by matipojo

2024-07-16 17:27 UTC, DennisNerush submitted a review, later dismissed

2024-07-16 18:08 UTC, yotamselementor requested changes, later dismissed

2024-07-16 18:08 UTC, yotamselementor commented on tests/playwright/plugin-tester-plugins/enqueue-media-on-front.zip
What builds this zip file?

2024-07-17 08:54 UTC, DennisNerush approved these changes

2024-07-17 12:16 UTC, merged