Tweak: Merge "Editor Top Bar" feature to version [ED-15945]
elementor/elementor pull request #29051
Opened 2024-10-26 13:42 UTC by rami-elementor

2024-11-19 11:32 UTC, kunsang commented
I need this feature, elementor editor is broken for me now, pls fix 🙏
Theme builder is broken aswell 🙁

2025-05-07 17:29 UTC, arielk approved these changes, later dismissed

2025-05-07 18:17 UTC, rami-elementor commented on core/settings/editor-preferences/model.php
> -
Not relevant with top bar.

2025-05-12 10:41 UTC, StyleShit requested changes

2025-05-12 10:41 UTC, StyleShit commented on assets/dev/js/editor/regions/panel/footer.js
> +			const deviceView = 'desktop';
you can remove the whole `else` I  think
and probably this whole footer file

2025-05-12 10:41 UTC, StyleShit commented on tests/phpunit/elementor/modules/editor-app-bar/test-module.php
> +	public function test_it__dequeues_responsive_bar_script_and_style() {
this is the entry we can delete
write it down for next PR

2025-05-12 10:52 UTC, rami-elementor commented on assets/dev/js/editor/regions/panel/footer.js
> +			const deviceView = 'desktop';
Deleted in a separate PR.

2025-05-12 11:00 UTC, StyleShit submitted a review, later dismissed

2025-05-14 04:59 UTC, StyleShit approved these changes, later dismissed

2025-05-15 08:31 UTC, Nevoss approved these changes, later dismissed

2025-05-15 14:11 UTC, rami-elementor commented
Playwright test: https://github.com/elementor/elementor/actions/runs/15047105465

2025-05-15 14:30 UTC, TzviRabinovitch approved these changes

2025-05-15 14:30 UTC, merged