Internal: Don't run CI on every PR
elementor/elementor pull request #29128
Opened 2024-10-30 12:20 UTC by asafdl

## PR Checklist

- [x] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

* CI QoL improvement

## Description
An explanation of what is done in this PR

* skip running full CI on changes that are irrelevant

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [x] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2024-10-30 14:26 UTC, ronenelementor submitted a review, later dismissed

2024-10-31 09:44 UTC, yotamselementor requested changes

2024-10-31 09:44 UTC, yotamselementor commented on .github/workflows/build.yml
> +      - 'composer.lock'
I would remove this as it affects the build (apply this comment to other actions too)

2024-10-31 09:44 UTC, yotamselementor commented on .github/workflows/pr-checks-noop.yml
> +      - 'docs/**'
Can we put this list in one file and use it in all the actions?

2024-10-31 14:52 UTC, yotamselementor approved these changes

2024-10-31 14:54 UTC, merged