Internal: Add background-color control [ED-15932]
elementor/elementor pull request #29123
Opened 2024-10-30 05:56 UTC by mykytamurzin

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2024-10-30 09:58 UTC, Omerisra6 requested changes

2024-10-30 09:58 UTC, Omerisra6 commented on tests/phpunit/elementor/modules/atomic-widgets/styles/test-styles-renderer.php
> +							'background-color' => '#0c6b2099',
You don't need to add this test, the prop type is already exists

2024-10-30 09:59 UTC, Omerisra6 requested changes

2024-10-31 10:28 UTC, Omerisra6 approved these changes

2024-10-31 12:05 UTC, ronenelementor approved these changes

2024-10-31 12:42 UTC, merged