Tweak: Promoted "Optimized Markup" feature to Beta status and activate for new sites [ED-16025]
elementor/elementor pull request #29215
Opened 2024-11-07 14:22 UTC by louiswol94

2024-11-08 06:15 UTC, ramiy approved these changes

2024-11-08 06:20 UTC, rami-elementor submitted a review, later dismissed

2024-11-08 08:01 UTC, rami-elementor commented
@louiswol94 maybe the testes should check whether the experiment active or not, and use then use the relevant selector? We did something similar for the Editor Top Bar.

2025-05-01 21:44 UTC, rami-elementor requested changes

2025-05-01 21:44 UTC, rami-elementor commented on core/experiments/manager.php
> +				'minimum_installation_version' => '3.26.0',
```suggestion
				'minimum_installation_version' => '3.30.0',
```

2025-05-01 22:00 UTC, rami-elementor approved these changes

2025-05-06 16:28 UTC, arielk approved these changes

2025-05-06 17:26 UTC, merged