New: Internal animate with AI [ED-16191]
elementor/elementor pull request #29361
Opened 2024-11-21 19:49 UTC by naorsabag

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2024-11-21 21:18 UTC, DennisNerush commented on modules/ai/assets/js/editor/hooks/use-animation-prompt.js
> +		const processProps = ( props ) => {
call it "processOtherProps" and drop the comment

2024-11-21 21:19 UTC, DennisNerush commented on modules/ai/assets/js/editor/hooks/use-animation-prompt.js
> +	const digestResult = ( jsonString ) => {
this whole file and this part in particular is pretty complex, how about some unit tests to test the logic?

2024-11-21 21:20 UTC, DennisNerush submitted a review, later dismissed

2024-11-24 10:05 UTC, matipojo requested changes

2024-11-24 10:05 UTC, matipojo commented on modules/ai/assets/js/editor/module.js
> +			const getControlValue = () => Object.values( elementor.widgetsCache.heading.controls )
Why `heading`?

2024-11-24 10:05 UTC, matipojo commented on modules/ai/assets/js/editor/page-content.js
> +			elementor.documents.getCurrent().history.setActive( false );
Why false?

Maybe use `restorePrevSettings`

2024-11-24 10:05 UTC, matipojo commented on modules/ai/assets/js/editor/pages/form-animation/index.js
> +		const summery = Object.keys( result )
```suggestion
		const summary = Object.keys( result )
```

2024-11-24 10:05 UTC, matipojo commented on modules/ai/assets/js/editor/pages/form-animation/index.js
> +				// Const value = ! item.isParent && item.value && ! item.value.sizes?.length ? `<br/>&nbsp;&#8226;&nbsp;${ item.value.size ?? item.value }` : '';
```suggestion
```

2024-11-24 10:05 UTC, matipojo commented on modules/ai/assets/js/editor/pages/form-animation/index.js
> +						{ /* <PromptLibraryLink libraryLink={ 'https://go.elementor.com/ai-prompt-library-animation/' } />*/ }
```suggestion
```

2024-11-24 10:05 UTC, matipojo commented on modules/ai/module.php
> +		$app = $this->get_ai_app();
```suggestion
		$data['editor_post_id'] = $data['payload']['postId'];
		$this->verify_upload_permissions( $data );
		
		$app = $this->get_ai_app();
```

2024-11-24 14:03 UTC, matipojo approved these changes

2024-11-24 14:26 UTC, merged