Internal: Update @elementor/ui version [EDS-631]
elementor/elementor pull request #29376
Opened 2024-11-24 09:30 UTC by MiryamOren

2024-11-24 09:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/elementor/elementor?pullRequest=29376) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/elementor/elementor?pullRequest=29376) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/elementor/elementor?pullRequest=29376) it.</sub>

2024-12-02 04:04 UTC, rotemee requested changes

2024-12-02 04:04 UTC, rotemee commented on package.json
> +		"@elementor/ui": "^1.21.13",
```suggestion
		"@elementor/ui": "1.21.13",
```
On purpose, for not being updated automatically.

2024-12-02 10:08 UTC, rotemee submitted a review, later dismissed

2024-12-02 10:25 UTC, ronenelementor submitted a review, later dismissed

2024-12-02 12:19 UTC, ronenelementor approved these changes

2024-12-02 12:19 UTC, merged