Internal: [V2] Link control ajax autocomplete for heading widg[ED-16303]
elementor/elementor pull request #29696
Opened 2024-12-26 10:44 UTC by ronenelementor

2025-01-06 14:03 UTC, Omerisra6 requested changes

2025-01-06 15:09 UTC, ronenelementor commented on includes/utils.php
> +		if ( ! empty( $post_types_to_exclude ) ) {
Done

2025-01-06 15:09 UTC, ronenelementor commented on modules/atomic-widgets/controls/types/query-control.php
> +	public function set_post_query(): self {
Done

2025-01-07 04:14 UTC, davseve commented on modules/atomic-widgets/widgets/atomic-heading.php
> +			}
Maybe extract this functionality to have cleaner code?

2025-01-07 09:01 UTC, ronenelementor commented on modules/atomic-widgets/controls/types/query-control.php
> +class Query_Control extends Atomic_Control_Base {
Done

2025-01-07 09:03 UTC, ronenelementor commented on includes/utils.php
> +	public static function get_posts_per_post_type_map( $post_types_to_exclude = [] ) {
Done

2025-01-07 09:30 UTC, ronenelementor commented on includes/utils.php
> +			'numberposts' => -1,
Will be implemented when the ajax bill be added

2025-01-09 08:20 UTC, Omerisra6 requested changes

2025-01-09 08:20 UTC, Omerisra6 commented on modules/atomic-widgets/widgets/atomic-heading.php
> +	private function get_posts_per_post_type_map( $excluded_types = [] ) {
I am not sure where it should be placed, maybe in a `utils` file under a `link-control` folder?

@Nevoss WDTY?

2025-01-09 09:14 UTC, ronenelementor commented on modules/atomic-widgets/widgets/atomic-heading.php
> +			}
Done

2025-01-09 09:14 UTC, ronenelementor commented on modules/atomic-widgets/controls/types/link-control.php
> +		if ( ! $this->validate_options_scheme( $options ) ) {
Not sure, this can be removed, I thought it might save our asses

2025-01-09 11:17 UTC, Omerisra6 commented on modules/atomic-widgets/controls/types/link-control.php
> +		if ( ! $this->validate_options_scheme( $options ) ) {
Try to add the phpDOC to describe the param. 
It will improve DX when using the control

2025-01-09 12:41 UTC, Omerisra6 commented on modules/atomic-widgets/widgets/atomic-heading.php
> +		$post_types = new Collection( get_post_types( [ 'public' => true ], 'object' ) );
Can we test it somehow?

2025-01-09 14:00 UTC, Nevoss commented on modules/atomic-widgets/widgets/atomic-heading.php
> +	private function get_posts_per_post_type_map( $excluded_types = [] ) {
Seems like this code does a lot of work to load the options, which block the editor from being rendered, as I know the original idea was to load the options async and not on the initial request, is it right?

2025-01-09 14:03 UTC, Nevoss commented on modules/atomic-widgets/widgets/atomic-heading.php
> +		return array_merge( [ 'e-floating-buttons', 'e-landing-page', 'elementor_library', 'attachment' ], $additional_exclusions );
What about third party post_types? maybe you should create an "allowList" and not "blockList"

2025-01-09 14:27 UTC, Omerisra6 approved these changes

2025-01-09 15:00 UTC, ronenelementor commented on modules/atomic-widgets/widgets/atomic-heading.php
> +	private function get_posts_per_post_type_map( $excluded_types = [] ) {
@Nevoss , you're right, we have a task to replace that and have the logic move to a REST

2025-01-09 15:18 UTC, merged