Internal: V2 textareashould not be null error [ED-16718]
elementor/elementor pull request #29719
Opened 2024-12-30 12:29 UTC by mugurelLupu

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2024-12-31 11:58 UTC, asafdl submitted a review, later dismissed

2025-01-01 08:53 UTC, davseve commented on modules/atomic-widgets/controls/types/textarea-control.php
> +	public function set_value( string $value ): self {
maybe?
```suggestion
	public function set_value( string $value = '' ): self {
```

2025-01-01 08:53 UTC, davseve commented on modules/atomic-widgets/widgets/atomic-heading.php
> +						->set_value( '' ),
If we add a fallback in the function itself than it can be removed from here 
```suggestion
						->set_value(),
```

2025-01-01 09:00 UTC, davseve commented on modules/atomic-widgets/controls/types/textarea-control.php
> +	}
maybe adding a default value?
WDYT?
```suggestion
	public function set_value( string $value = null ): self {
		$this->value = $value ?? '';

		return $this;
	}
```

2025-01-01 13:44 UTC, Omerisra6 requested changes

2025-01-01 13:44 UTC, Omerisra6 commented on modules/atomic-widgets/controls/types/textarea-control.php
I think we should handle this error in the `elementor-packages` repo and just set the default state to empty string

2025-01-01 15:05 UTC, davseve commented on modules/atomic-widgets/controls/types/textarea-control.php
It seems that this issue was already solved
Thanks :)

2025-01-01 15:05 UTC, closed without merging

2025-01-02 07:40 UTC, eyalmrejen-elementor commented on modules/atomic-widgets/controls/types/textarea-control.php
> +	public function set_default_value( string $value = null ): self {
Why not set the `$value` to an empty string in the function arguments and lose that complicated condition on line 26? This is what this capability is for

2025-01-02 07:43 UTC, eyalmrejen-elementor commented on modules/atomic-widgets/widgets/atomic-heading.php
> +						->set_default_value(),
I know it's a small bug, but I would add a small test for this. Once a test is there, this bug will NEVER come back