Internal: Change global classes api response format [EDS-1103]
elementor/elementor pull request #29724
Opened 2024-12-31 13:03 UTC by Omerisra6

2025-01-01 06:23 UTC, Nevoss requested changes

2025-01-01 06:23 UTC, Nevoss commented on modules/global-classes/utils/error.php
> +	public function get() {
```suggestion
	public function build() {
```

Maybe?

2025-01-01 06:23 UTC, Nevoss commented on modules/global-classes/utils/error.php
> +class Error {
```suggestion
class Error_Builder {
```

Maybe?

2025-01-01 06:23 UTC, Nevoss commented on modules/global-classes/utils/response.php
> +class Response {
```suggestion
class Response_Builder {
```

2025-01-01 06:23 UTC, Nevoss commented on modules/global-classes/global-classes-rest-api.php
> +				->get();
Remove the `get` and call it in the rest wrapper?

2025-01-01 12:31 UTC, Omerisra6 commented on modules/global-classes/global-classes-rest-api.php
> +				->get();
I think it is better that way

2025-01-02 13:26 UTC, Nevoss requested changes

2025-01-02 13:26 UTC, Nevoss commented on tests/phpunit/elementor/modules/atomic-widgets/test-atomic-widget-base.php
> +					'id' => 's-1234',
Check for label

2025-01-05 06:31 UTC, Nevoss approved these changes

2025-01-05 06:53 UTC, Nevoss requested changes

2025-01-05 06:53 UTC, Nevoss commented on modules/global-classes/global-classes-rest-api.php
> +		return Response_Builder::make( $classes->get_items()->all() )
```suggestion
		return Response_Builder::make( (object) $classes->get_items()->all() )
```

2025-01-05 06:53 UTC, Nevoss commented on modules/global-classes/global-classes-rest-api.php
>  		$class = $request->get_params();
Get whitelist

2025-01-05 11:07 UTC, Nevoss requested changes

2025-01-05 11:07 UTC, Nevoss commented on modules/global-classes/global-classes-rest-api.php
> +		] )->all();
```suggestion
		$value = Collection::make( $request->get_params() )
			->only( [ 'label', 'variants' ] )
			->merge( [
				'type' => 'class',
				'id' => $id,
			] )
			->all();;
```

2025-01-05 11:07 UTC, Nevoss commented on modules/global-classes/global-classes-rest-api.php
> +		] )->all();
```suggestion
		$class =Collection::make( $request->get_params() )
			->only( [ 'label' ] )
			->merge( [
				'variants' => $request->get_param( 'variants' ) ?? [],
				'type' => 'class',
			] )
			->all();
```

2025-01-05 11:07 UTC, Nevoss commented on tests/phpunit/elementor/modules/global-classes/test-global-classes-rest-api.php
> +use function ElementorDeps\DI\value;
?

2025-01-06 07:28 UTC, Nevoss approved these changes, later dismissed

2025-01-06 12:18 UTC, IshayMaya approved these changes

2025-01-06 12:18 UTC, merged