Ajax Manager
elementor/elementor pull request #3102
Opened 2018-01-07 10:21 UTC by matipojo

2018-01-07 16:20 UTC, KingYes requested changes

2018-01-07 16:20 UTC, KingYes commented on assets/dev/js/editor/components/saver/manager.js
> +					elementor.settings.page.model.set( 'post_status', options.status );
tab tab

2018-01-07 16:20 UTC, KingYes commented on assets/dev/js/editor/elements/models/element.js
> +		return elementor.ajax.addRequest( 'render_widget', {
send + via ajax-manager

2018-01-07 16:20 UTC, KingYes commented on assets/dev/js/editor/utils/ajax.js
> +		var	deferred,
tab

2018-01-07 16:20 UTC, KingYes commented on core/settings/page/manager.php
> +use Elementor\Plugin;
remove

2018-01-08 10:54 UTC, matipojo commented on assets/dev/js/editor/elements/models/element.js
> +		return elementor.ajax.addRequest( 'render_widget', {
done

2018-01-14 13:15 UTC, closed without merging