Feature/documents
elementor/elementor pull request #3306
Opened 2018-01-24 17:31 UTC by matipojo

2018-01-24 22:36 UTC, ramiy commented on core/documents-manager.php
> +			throw new \Exception( 'Access Denied' );
See: https://github.com/pojome/elementor/pull/3282

Use: `throw new \Exception( 'Access denied.' );`

and update the phpDocs to: `@throw \Exception If current user don't have permissions to edit the post or the post is not using Elementor.`

2018-01-25 11:57 UTC, KingYes requested changes

2018-01-25 11:57 UTC, KingYes commented on core/documents-manager.php
> +			if ( ! $doc_type ) {
remove

2018-01-25 11:57 UTC, KingYes commented on core/settings/page/manager.php
> +			if ( is_preview() || Plugin::$instance->preview->is_preview_mode() ) {
doc support?

2018-01-25 11:57 UTC, KingYes commented on core/settings/page/manager.php
> +		$post_id = get_the_ID();
doc support?

2018-01-28 14:39 UTC, ramiy approved these changes

2018-01-28 14:47 UTC, KingYes commented on core/documents-manager.php
> +			// Translators: %s = document type name.
/* tra

2018-01-28 14:47 UTC, KingYes commented on core/documents-manager.php
> +			$post_data['post_title'] = __( 'Elementor', '' ) . ' ' . ucfirst( $type );
remove type

2018-01-28 15:19 UTC, merged