Adding a general hook 'elementor/frontend/before_render' to element-base
elementor/elementor pull request #5025
Opened 2018-07-11 06:30 UTC by M4Gd

Handy hook for applying new attributes to the main wrapper for multiple elements with one single hook.

2018-07-11 06:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pojome/elementor?pullRequest=5025) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pojome/elementor?pullRequest=5025) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pojome/elementor?pullRequest=5025) it.</sub>

2018-07-12 16:53 UTC, KingYes requested changes

2018-07-12 16:53 UTC, KingYes commented on includes/base/element-base.php
> +		do_action( "elementor/frontend/before_render", $this );
Replace `"` => `'`.

2018-07-12 16:53 UTC, KingYes commented on includes/base/element-base.php
> +		 * @since 2.1.0
Change `@since 2.1.0` to `@since 2.2.0`

2018-07-14 05:31 UTC, M4Gd commented on includes/base/element-base.php
> +		 * @since 2.1.0
Sure!

2018-07-14 18:30 UTC, KingYes commented
Thanks

2018-07-14 18:30 UTC, KingYes approved these changes

2018-07-14 18:31 UTC, merged

2018-07-21 11:53 UTC, M4Gd commented
@KingYes Could you please add these changes in next upcoming update of Elementor? We prepared an update regarding these changes for our product and currently waiting for the changes to be available on new release of Elementor. Could you kindly instruct me on this matter?

2018-07-26 14:23 UTC, M4Gd commented
Thanks for your response! Nevermind, we will find a solution on our own.