Testing
elementor/elementor pull request #5177
Opened 2018-07-23 13:28 UTC by OmriBar-Zik

2018-08-06 13:47 UTC, KingYes requested changes

2018-08-06 13:47 UTC, KingYes commented on tests/phpunit/manager.php
> +	public static $instance = null;
private

2018-08-06 13:47 UTC, KingYes commented on tests/bootstrap.php
> +global $argv;
Try use with Bootstrap class

2018-08-06 13:47 UTC, KingYes commented on tests/phpunit/elementor/includes/base/test-controls-stack.php
> +	public function test_Should_add_control() {
spell

2018-08-06 13:47 UTC, KingYes commented on tests/phpunit/elementor/includes/template-library/test-manager-general.php
> +		$this->assertWPError( self::$manager->register_source( 'pop' ), 'source_class_name_not_exists' );
change `pop`

2018-08-06 13:47 UTC, KingYes commented on tests/phpunit/elementor/includes/template-library/test-manager-general.php
> +		$this->assertFalse( self::$manager->unregister_source( 0 ) );
change `0`.

2018-08-06 13:47 UTC, KingYes commented on tests/phpunit/elementor/includes/template-library/test-manager-general.php
> +	public function mockGetTemplate() {
rename & move & protected

2018-08-06 13:47 UTC, KingYes commented on tests/phpunit/elementor/includes/template-library/test-manager-general.php
> +		self::$manager->register_source( 'Elementor\TemplateLibrary\Source_Remote' );
why register?

2018-08-06 13:47 UTC, KingYes commented on tests/phpunit/elementor/includes/template-library/test-manager-general.php
> +		self::$manager->register_source( 'Elementor\TemplateLibrary\Source_Remote' );
why register?

2018-08-06 13:47 UTC, KingYes commented on tests/phpunit/elementor/includes/template-library/test-manager-general.php
> +	public function test_should_return_library_data_send_this_parameters() {
remove

2018-08-06 13:47 UTC, KingYes commented on tests/phpunit/elementor/includes/template-library/test-manager-general.php
> +		$this->assertWPError(
`$fake_post_id = '123';`

2018-08-06 13:47 UTC, KingYes commented on tests/phpunit/elementor/includes/template-library/test-manager-general.php
> +		$templates = [
line

2018-08-06 13:47 UTC, KingYes commented on tests/phpunit/elementor/includes/template-library/test-manager-general.php
> +			'templates' => [
replace false to WP_Error

2018-08-06 13:47 UTC, KingYes commented on tests/phpunit/elementor/includes/template-library/test-manager-general.php
> +	/*    public function () {
cleanup

2018-08-06 13:47 UTC, KingYes commented on tests/phpunit/elementor/includes/template-library/test-manager-local.php
> +<?php /** @noinspection PhpParamsInspection */
?

2018-08-06 13:47 UTC, KingYes commented on tests/phpunit/elementor/includes/template-library/test-manager-local.php
> +require_once 'test-manager-general.php';
remove

2018-08-06 13:47 UTC, KingYes commented on tests/phpunit/elementor/includes/template-library/test-manager-local.php
> +		$this->assertTrue( self::$manager->register_source( 'Elementor\TemplateLibrary\Source_Local' ) );
add condition ensuring is exist.

2018-08-06 13:47 UTC, KingYes commented on tests/phpunit/elementor/includes/template-library/test-manager-local.php
> +	public function test_should_return_true_from_unregister_source() {
swap

2018-08-06 13:47 UTC, KingYes commented on tests/phpunit/elementor/includes/template-library/test-manager-local.php
> +		self::$manager->register_source( 'Elementor\TemplateLibrary\Source_Local' );
remove this line

2018-08-06 13:47 UTC, KingYes commented on tests/phpunit/elementor/includes/template-library/test-manager-local.php
> +		$post_id = $this->factory()->create_and_get_default_Post()->ID;
upper?

2018-08-06 13:47 UTC, KingYes commented on tests/phpunit/elementor/includes/template-library/test-manager-remot.php
> +	public function test_should_return_data_from_get_template_data() {
?

2018-08-06 13:47 UTC, KingYes commented on tests/phpunit/elementor/includes/template-library/test-manager-remot.php
> +	public function test_should_delete_template() {
?

2018-08-06 14:06 UTC, OmriBar-Zik commented on tests/phpunit/manager.php
> +	public static $instance = null;
done

2018-08-06 14:07 UTC, OmriBar-Zik commented on tests/phpunit/elementor/includes/base/test-controls-stack.php
> +	public function test_Should_add_control() {
done

2018-08-07 07:12 UTC, KingYes requested changes

2018-08-07 07:12 UTC, KingYes commented on tests/phpunit/elementor/includes/template-library/test-manager-general.php
> +	public function mockGetTemplate() {
rename

2018-08-07 07:12 UTC, KingYes commented on includes/template-library/sources/remote.php
> +
remove line

2018-08-07 07:12 UTC, KingYes commented on includes/template-library/sources/remote.php
> +	public function register_data() { }
space?

2018-08-07 07:12 UTC, KingYes commented on includes/template-library/sources/remote.php
> +		return new \WP_Error( 'invalid_request', 'cannot save template from remote source' );
from => to

2018-08-07 07:12 UTC, KingYes commented on tests/phpunit/elementor/includes/template-library/test-manager-remot.php
> +				'template_id' => '777',
id?

2018-08-07 07:12 UTC, KingYes commented on tests/phpunit/elementor/includes/template-library/test-manager-remote.php
> +	public function test_should_return_WP_Error_from_save_template() {
lower

2018-08-07 08:59 UTC, KingYes requested changes

2018-08-07 08:59 UTC, KingYes commented on tests/phpunit/elementor/includes/template-library/test-manager-general.php
> +		$this->assertWPError( self::$manager->register_source( 'pop' ), 'source_class_name_not_exists' );
?

2018-08-07 08:59 UTC, KingYes commented on tests/phpunit/elementor/includes/template-library/test-manager-local.php
> +require_once 'test-manager-general.php';
?

2018-08-07 08:59 UTC, KingYes commented on tests/phpunit/elementor/includes/template-library/test-manager-remote.php
> +			'post_id' => '777',
?

2018-08-07 08:59 UTC, KingYes commented on tests/phpunit/elementor/includes/template-library/test-manager-remote.php
> +					'template_id' => '777',
?

2018-08-15 11:17 UTC, closed without merging