Embedding base library module in admin
elementor/elementor pull request #5446
Opened 2018-08-16 07:05 UTC by kobizz

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/pojome/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2018-08-16 15:08 UTC, KingYes requested changes

2018-08-16 15:08 UTC, KingYes commented on core/admin/admin.php
> +		wp_register_style(
Try embed WP font

2018-08-16 15:08 UTC, KingYes commented on core/admin/admin.php
> +		add_action( 'current_screen', function () {
space

2018-08-16 15:08 UTC, KingYes commented on core/admin/admin.php
> +	private function print_library_layout_template() {
public

2018-08-17 14:39 UTC, arielk commented
@kobizz please remove the Google Font loading and sed it again.

2018-08-19 13:42 UTC, KingYes approved these changes

2018-08-19 13:42 UTC, merged