Feature/app
elementor/elementor pull request #5672
Opened 2018-09-05 12:25 UTC by kobizz

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/pojome/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2018-09-20 09:52 UTC, KingYes requested changes

2018-09-20 11:01 UTC, KingYes requested changes

2018-09-20 11:01 UTC, KingYes commented on includes/user.php
> +		/** @var \Elementor\Core\Common\Modules\Ajax\Module $ajax */
use param

2018-10-03 08:12 UTC, kobizz commented on core/admin/admin.php
> +			[],
Unnecessary

2018-10-03 09:56 UTC, kobizz commented on includes/base/controls-stack.php
> +		return self::get_items( $this->get_stack()['controls'], $control_id );
This method has already been deprecated

2018-10-03 13:22 UTC, merged