E2E tests with cypress
elementor/elementor pull request #5899
Opened 2018-10-11 13:53 UTC by OmriBar-Zik

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/pojome/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] CI related changes
- [ ] Documentation content changes
- [x] Other... Please describe: e2e tests

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2018-10-14 16:10 UTC, KingYes requested changes

2018-10-14 16:10 UTC, KingYes commented on .circleci/config.yml
> +      - schedule:
fix indent

2018-10-14 16:10 UTC, KingYes commented on .circleci/config.yml
> +  e2e:
Run only in PRs

2018-10-14 16:10 UTC, KingYes commented on .circleci/config.yml
> +            rm -fr elementor
-rf

2018-10-14 16:10 UTC, KingYes commented on .circleci/config.yml
> +          name: Setup Wordpress
capelcase

2018-10-14 16:10 UTC, KingYes commented on .circleci/config.yml
> +defaults: &e2e_default
try multiple files

2018-10-14 16:10 UTC, KingYes commented on bin/install-wordpress.sh
> +docker-compose $DOCKER_COMPOSE_FILE_OPTIONS run --rm -u 33 $CLI config set AUTOSAVE_INTERVAL 2 --add --type=constant >/dev/null
try as filter

2018-10-14 16:10 UTC, KingYes commented on cypress.json
> +  "projectId": "uta8ca"
remove

2018-10-14 16:10 UTC, KingYes commented on package.json
> +  "name": "elementor",
tabs plz!

2018-10-14 16:10 UTC, KingYes commented on tests/e2e/integration/auto-save.spec.js
> +var setPanelSelectedElement = function( elementor, category, name ) {
es6

2018-10-15 13:42 UTC, OmriBarZik commented on .circleci/config.yml
> +defaults: &e2e_default
there is no solution

2018-11-01 15:59 UTC, merged