Upgrades: Fix - Upgrade Widget Image to support `caption=attachment` …
elementor/elementor pull request #6012
Opened 2018-10-29 09:52 UTC by matipojo

…(Fix #6005)

2018-10-29 09:57 UTC, bainternet commented
Missing every widget that inherits image widget, eg: post-thumbnail, site-logo...

2018-10-29 13:45 UTC, KingYes requested changes

2018-10-29 13:45 UTC, KingYes commented on includes/upgrades.php
> +			OR `meta_value` LIKE \'%"widgetType":"woocommerce-category-image"%\'
?

2018-11-01 15:58 UTC, KingYes approved these changes

2018-11-01 16:12 UTC, merged