Release/2.4.0
elementor/elementor pull request #6144
Opened 2018-11-13 08:39 UTC by kobizz

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/pojome/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2018-11-13 14:50 UTC, kobizz commented on core/admin/admin.php
> +			'elementor-admin-modules',
Put in footer and add deps

2018-12-05 12:39 UTC, KingYes requested changes

2018-12-05 13:08 UTC, KingYes requested changes

2018-12-05 13:08 UTC, KingYes commented on .grunt-config/webpack.js
> +	'modules': path.resolve( __dirname, '../assets/dev/js/modules/modules.js' ),
one module per endpoint.

2018-12-06 12:04 UTC, merged