frontend - fix: add rocket-loader param to elementor-frontend script tag.
elementor/elementor pull request #7313
Opened 2019-03-05 08:59 UTC by nuritsha

2019-03-05 16:44 UTC, matipojo commented on includes/frontend.php
> +
\Elementor\Core\Base\App::print_config
```
final protected function print_config() {
		$name = $this->get_name();

		echo '<script data-cfasync="false">' . "\n";
		echo 'var elementor' . ucfirst( $name ) . 'Config = ' . wp_json_encode( $this->get_settings() + $this->get_components_config() ) . ";\n";
		echo "</script>\n";
	}
```

2019-03-05 17:54 UTC, bainternet commented
Still missing elementorFrontendConfig

2019-03-06 08:01 UTC, bainternet commented
here also:
https://github.com/elementor/elementor/blob/fe5eb3949a9ea8b72e84616468614fc1a77e9262/includes/editor.php#L712-L724

2019-03-07 10:09 UTC, bainternet commented on includes/frontend.php
> +		if ( 'elementor-frontend' === $handler ) {
if ( isset( $_REQUEST['elementor-preview'] ) || ( isset( $_REQUEST['action'] ) && 'elementor' === $_REQUEST['action'] ) ) {

2019-03-07 11:29 UTC, matipojo commented on includes/frontend.php
> +		if ( 'elementor-frontend' === $handler ) {
Plugin::instance()->preview->is_preview_mode();

2019-03-07 11:32 UTC, matipojo requested changes

2019-03-07 11:32 UTC, matipojo commented on includes/frontend.php
> +		if ( isset( $_REQUEST['elementor-preview'] ) || ( isset( $_REQUEST['action'] ) && 'elementor' === $_REQUEST['action'] ) ) {
Plugin::elementor()->preview->is_preview_mode()

2019-03-07 11:32 UTC, matipojo commented on includes/utils.php
> +	public static function elementor_print_js_config( $js_var, $config, $already_jason = false ) {
already_jason => already_json

2019-03-07 12:05 UTC, nuritsha commented on includes/utils.php
> +	public static function elementor_print_js_config( $js_var, $config, $already_jason = false ) {
ho! sure

2019-03-07 12:09 UTC, nuritsha commented on includes/frontend.php
> +		if ( isset( $_REQUEST['elementor-preview'] ) || ( isset( $_REQUEST['action'] ) && 'elementor' === $_REQUEST['action'] ) ) {
like so?
```		
if ( Plugin::instance()->preview->is_preview_mode() || ( isset( $_REQUEST['action'] ) && 'elementor' === $_REQUEST['action'] ) ) {
			return str_replace( '<script', '<script data-cfasync="false"', $tag );
		}

		return $tag;
```

2019-03-11 14:33 UTC, merged