Tweak: Beta-Tester newsletter dialog trigger.
elementor/elementor pull request #8286
Opened 2019-06-10 13:58 UTC by nuritsha

2019-06-11 14:13 UTC, kobizz requested changes

2019-06-11 14:13 UTC, kobizz commented on assets/dev/js/admin/beta-tester/beta-tester.js
> +	getDefaultSettings() {}
Remove all the empty methods

2019-06-11 14:13 UTC, kobizz commented on core/admin/admin.php
> +		if ( empty( $beta_tester_user_meta ) && ( 'elementor_page_elementor-tools' === $current_screen->id ) ) {
Just `!`

2019-06-17 16:09 UTC, kobizz commented on assets/dev/js/admin/beta-tester/beta-tester.js
> +		elements.$beta_tester_first_to_know = jQuery( selectors.beta_tester_first_to_know );
Usually all our `js` variables are camelCase

2019-06-18 06:47 UTC, nuritsha commented on assets/dev/js/admin/beta-tester/beta-tester.js
> +	getDefaultSettings() {}
done

2019-06-18 06:47 UTC, nuritsha commented on core/admin/admin.php
> +		if ( empty( $beta_tester_user_meta ) && ( 'elementor_page_elementor-tools' === $current_screen->id ) ) {
done

2019-06-18 06:50 UTC, nuritsha commented on assets/dev/js/admin/beta-tester/beta-tester.js
> +		elements.$beta_tester_first_to_know = jQuery( selectors.beta_tester_first_to_know );
done

2019-06-18 18:00 UTC, merged