Fix/document type page
elementor/elementor pull request #8659
Opened 2019-07-23 12:17 UTC by iNewLegend

2019-07-28 10:06 UTC, matipojo requested changes

2019-07-28 10:06 UTC, matipojo commented on core/upgrade/upgrades.php
> +			$data = Plugin::$instance->db->iterate_data( $data, function ( $element ) {
Remove spaces here and below.

2019-07-28 10:06 UTC, matipojo commented on core/upgrade/upgrades.php
> +	public static function _v_2_6_7_remove_old_usage_data() {
Move to tracking branch.

2019-07-30 09:58 UTC, matipojo requested changes
See the comments.

2019-07-31 10:35 UTC, matipojo approved these changes

2019-08-04 15:05 UTC, KingYes requested changes

2019-08-04 15:05 UTC, KingYes commented on core/upgrade/upgrades.php
> +	}
Add call to `wp_cache_flush()`.

2019-08-05 10:08 UTC, merged