Feature/background vimeo video (Github #1903)
elementor/elementor pull request #8868
Opened 2019-08-20 10:10 UTC by udidol

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2019-08-20 10:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/elementor/elementor?pullRequest=8868) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/elementor/elementor?pullRequest=8868) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/elementor/elementor?pullRequest=8868) it.</sub>

2019-08-20 15:45 UTC, kobizz requested changes

2019-08-20 15:45 UTC, kobizz commented on assets/dev/js/frontend/handlers/section.js
> +		if ( 0 !== startTime ) {
`if ( startTime )`

2019-08-20 15:45 UTC, kobizz commented on assets/dev/js/frontend/handlers/section.js
> +		this.player.getDuration().then( ( duration ) => {
Do all this logic in one `timeupdate` listener

2019-08-20 15:45 UTC, kobizz commented on assets/dev/js/frontend/handlers/section.js
> +		if ( videoLink.includes( 'vimeo.com' ) ) {
Check the logic

2019-08-20 15:45 UTC, kobizz commented on assets/dev/js/frontend/utils/vimeo.js
> +export default class VimeoModule extends elementorModules.ViewModule {
Create a base api importer

2019-08-21 07:07 UTC, udidol commented on assets/dev/js/frontend/handlers/section.js
> +		if ( videoLink.includes( 'vimeo.com' ) ) {
It works

2019-08-21 11:00 UTC, kobizz requested changes

2019-08-21 11:00 UTC, kobizz commented on assets/dev/js/frontend/handlers/section/background-video.js
> +			aspectRatioSetting = $video ? $video.outerWidth() + ':' + $video.outerHeight() : '16:9';
Remove this check, and instead check it in the event attachment

2019-08-21 11:00 UTC, kobizz commented on assets/dev/js/frontend/handlers/section/background-video.js
> +			this.isVimeoVideo = true;
Change it to `this.videoType`

2019-08-22 10:55 UTC, kobizz requested changes

2019-08-22 10:55 UTC, kobizz commented on assets/dev/js/frontend/handlers/section/background-video.js
> +		this.handleVimeoStartEndTimes( elementSettings, startTime );
Don't send this parameter

2019-08-22 10:55 UTC, kobizz commented on assets/dev/js/frontend/handlers/section/background-video.js
> +		// If an end time is defined, handle ending the video
Move this comment to the right place

2019-08-22 11:10 UTC, kobizz approved these changes

2019-08-22 13:24 UTC, closed without merging