Tweak: implemented virtual list render in Icons Library
elementor/elementor pull request #8897
Opened 2019-08-25 10:24 UTC by bainternet

boost Icons library performance in 6000%

2019-08-25 10:51 UTC, danielkatz approved these changes
Looking great.
Maybe better let React worry about subscribing and unsubscribing to the scroll event?

2019-08-25 10:52 UTC, bainternet commented
@danielkatz 

meaning?

2019-08-25 10:55 UTC, danielkatz commented
Is it possible to use `onScroll={someScrollHandler}` instead on manually adding and removing 'scroll' event listener with (add|remove)EventListener?

2019-08-25 10:57 UTC, bainternet commented
Oh that, well it's out of context and on a higher level wrapper parent

2019-08-27 14:18 UTC, KingYes requested changes

2019-08-27 14:18 UTC, KingYes commented on assets/dev/js/editor/components/icons-manager/components/icon-list.js
> +		if ( ! this.state.itemSize.width ) {
reverse logic

2019-08-27 14:18 UTC, KingYes commented on assets/dev/js/editor/components/icons-manager/components/icon-list.js
> +					width: testElement.offsetWidth + 20,
use variable for padding size

2019-08-27 14:18 UTC, KingYes commented on assets/dev/js/editor/components/icons-manager/components/icon-manager.js
> +	scrollViewRef = React.createRef();
import react

2019-08-27 14:32 UTC, KingYes approved these changes

2019-08-27 14:32 UTC, merged