Divider widget tweaks
elementor/elementor pull request #8976
Opened 2019-09-03 15:37 UTC by joshmarom

2019-09-03 15:42 UTC, matipojo requested changes

2019-09-03 15:42 UTC, matipojo commented on includes/widgets/divider.php
> +					'label' => _x( 'Trees 2', 'shapes', 'elementor' ),
Move after "Trees".

2019-09-04 07:35 UTC, matipojo submitted a review, later dismissed

2019-09-04 15:49 UTC, bainternet approved these changes

2019-09-04 16:08 UTC, KingYes approved these changes

2019-09-04 16:09 UTC, merged