added helper method to utils.php for checking empty values including '0'
elementor/elementor pull request #9189
Opened 2019-09-25 13:58 UTC by udidol

And implemented this method to fix affected core widgets: image, image box, progress bar, star rating, icon box and alert

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2019-09-25 15:15 UTC, matipojo submitted a review, later dismissed

2019-10-02 13:43 UTC, kobizz requested changes

2019-10-02 13:43 UTC, kobizz commented on includes/utils.php
> +	public static function control_is_empty( $control_value ) {
The method's name should be more generic

2019-10-03 11:10 UTC, kobizz approved these changes

2019-10-03 11:22 UTC, merged