Added: Icon control inline skin
elementor/elementor pull request #9306
Opened 2019-10-10 09:55 UTC by udidol

## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2019-10-10 15:18 UTC, kobizz requested changes

2019-10-10 15:35 UTC, udidol commented on assets/dev/js/editor/controls/icons.js
> +		ui.inputs = '[type="radio"]';
radioInputs?

2019-10-27 15:53 UTC, kobizz requested changes

2019-10-27 15:53 UTC, kobizz commented on assets/dev/js/editor/controls/icons.js
> +		if ( 'inline' === skin ) {
`else`

2019-10-30 14:34 UTC, kobizz approved these changes

2019-10-30 15:34 UTC, merged