Fix : Shapes SVG include PHP Parse Error elementor#9693
elementor/elementor pull request #9694
Opened 2019-11-26 17:15 UTC by MarieComet

## PR Checklist

- [ x] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [x ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

* This PR propose a fix for the issue about PHP Parse Error explained here https://github.com/elementor/elementor/issues/9693

## Test instructions
This PR can be tested by following these steps:

* Add a custom SVG shape, the SVG file must begin with <?xml version="1.0" encoding="UTF-8"?>
For example :
`<?xml version="1.0" encoding="UTF-8"?> <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 111.859 500 42.943"><path d="M.366 156.606h498.56v-45.71L.366 156.606z" fill="#bada55"></path></svg>`

## Quality assurance

- [x ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

2019-11-26 17:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/elementor/elementor?pullRequest=9694) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/elementor/elementor?pullRequest=9694) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/elementor/elementor?pullRequest=9694) it.</sub>

2019-11-30 22:41 UTC, bainternet commented on includes/elements/section.php
>  		?>
Looks good but we need an extra check if the file actually exists something like 
```suggestion
		$shape_path = Shapes::get_shape_path( $settings[ $base_setting_key ], $negative );
		if ( ! file_exists( $shape_path ) ) {
			return;
		}
		?>
```

2019-11-30 22:42 UTC, bainternet commented on includes/elements/section.php
> +			<?php echo file_get_contents( Shapes::get_shape_path( $settings[ $base_setting_key ], ! empty( $settings[ $base_setting_key . '_negative' ] ) ) ); ?>
and then this can be done like this:
```suggestion
			<?php echo file_get_contents( $shape_path ); ?>
```

2019-11-30 22:44 UTC, bainternet requested changes
Thanks for the PR, 
can you please correct the requested changes.

2019-12-01 15:23 UTC, MarieComet commented
Thanks for the review @bainternet 
New PR with requested changes : https://github.com/elementor/elementor/pull/9734

2019-12-01 15:57 UTC, bainternet commented
closed in favor of #9734

2019-12-01 15:57 UTC, closed without merging