Deprecate methods prefixed with underscore (_) + replace with unprefixed methods
elementor/elementor pull request #9897
Opened 2019-12-16 14:52 UTC by udidol

Documentation has to be updated as well!
All mentions of the prefixed methods such as `_register_controls()` in the documentation should be changed to the unprefixed version (such as `register_controls()`.

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [X] Other... Please describe: **It is a refactor but the API does change**

## Summary

This PR can be summarized in the following changelog entry:

* Replaced control-related methods `_register_controls()`, `_get_initial_config()`, `_content_template()`, `_init()`, with unprefixed versions (e.g. `register_controls()`, `get_initial_config`, etc.)

## Description
An explanation of what is done in this PR

* Replaced control-related methods `_register_controls()`, `_get_initial_config()`, `_content_template()`, `_init()`, with unprefixed versions (e.g. `register_controls()`, `get_initial_config`, etc.).
* Replaced all of these methods' uses across the Elementor Core plugin

## Test instructions
This PR can be tested by following these steps:

* General Sanity tests, general testing of controls.

## Quality assurance

- [X] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

2019-12-18 16:12 UTC, kobizz requested changes

2019-12-18 16:12 UTC, kobizz commented on core/dynamic-tags/base-tag.php.rej
> +
Removed this file

2019-12-18 16:12 UTC, kobizz commented on includes/base/controls-stack.php
> +		$this->content_template();
Add a check if the old method exists

2019-12-18 16:12 UTC, kobizz commented on includes/base/controls-stack.php
> +	 * @deprecated 2.9.0 Implement `get_initial_config()` instead
Use "use" instead of "implement". Same for all occurrences

2019-12-18 16:12 UTC, kobizz commented on includes/base/controls-stack.php
> +			$this->_register_controls();
```suggestion
			$this->register_controls();
```
Move it to version 3.0.0

2019-12-18 16:12 UTC, kobizz commented on includes/base/controls-stack.php
> +		}
This check shouldn't be here

2019-12-18 16:12 UTC, kobizz commented on includes/base/controls-stack.php
> +			$this->init( $data );
Here you have to do the check

2019-12-18 16:12 UTC, kobizz commented on includes/base/controls-stack.php.rej
> + 		$this->register_controls();
Remove this file

2019-12-18 16:12 UTC, kobizz commented on includes/base/element-base.php
> +	protected function get_initial_config() {
Change `since` everywhere

2019-12-19 10:20 UTC, kobizz requested changes

2019-12-19 10:20 UTC, kobizz commented on includes/base/controls-stack.php
> +		if ( method_exists( $this, '_content_template' ) ) {
Add "TODO" note

2019-12-19 10:20 UTC, kobizz commented on includes/controls/base.php
> +	 * @since 2.9.0
Reverse the change

2019-12-19 10:20 UTC, kobizz commented on includes/controls/base.php
> +				<?php
Reverse

2019-12-19 10:20 UTC, kobizz commented on includes/controls/code.php
> +	 * @since 2.9.0
Reverse in all controls

2019-12-19 13:35 UTC, kobizz approved these changes

2019-12-23 13:39 UTC, merged

2020-03-22 13:52 UTC, eatbuildplay commented
This is confusing to me as a first time widget builder, I tried using the unprefixed register_controls() and it doesn't work, so I'm using _register_controls() which does work and I checked the Elementor core widgets, they are also using _register_controls().

2020-03-22 15:39 UTC, udidol commented
> This is confusing to me as a first time widget builder, I tried using the unprefixed register_controls() and it doesn't work, so I'm using _register_controls() which does work and I checked the Elementor core widgets, they are also using _register_controls().

Hi @eatbuildplay,
Some of the code in this PR was later modified. `_register_controls()` will be staying prefixed for now. We will issue a blog post in [our developers blog](https://developers.elementor.com/blog/) that will address this in due time.

For more info on building widgets, consult with our developer documentation: [https://developers.elementor.com/creating-a-new-widget/](https://developers.elementor.com/creating-a-new-widget/)