Adds featured_image URL to frontend config (for Pinterest Share Button issue)
elementor/elementor pull request #9905
Opened 2019-12-17 12:43 UTC by udidol

## Summary
Adds featured_image URL to frontend config (for Pinterest Share button issue - PT 240).
This issue is in Elementor Pro, but this addition to the Core is needed as part of the solution.

In order to control which image appears in a Pinterest share (Pin), Pinterest has a GET parameter (`media`) in which the image URL should be passed:
`https://www.pinterest.com/pin/create/button/?url={url}&media={featured image URL}`.

Until now we didn't pass this `media` parameter at all. The post/page's featured image URL was not available to us on any frontend object

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Description
An explanation of what is done in this PR

* Adds the current post/page's featured image URL (full) to Elementor's config JS object.

## Quality assurance

- [X] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

2019-12-17 15:43 UTC, matipojo submitted a review, later dismissed

2019-12-18 16:02 UTC, kobizz requested changes

2019-12-18 16:02 UTC, kobizz commented on includes/frontend.php
> +				'featured_image' => get_the_post_thumbnail_url(),
```suggestion
				'featuredImage' => get_the_post_thumbnail_url(),
```

2019-12-19 10:08 UTC, kobizz approved these changes

2019-12-19 13:29 UTC, kobizz approved these changes

2019-12-19 13:41 UTC, merged