Add Custom Attributes section in core version with pro promotion
elementor/elementor pull request #9917
Opened 2019-12-18 11:29 UTC by udidol

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [X] Other... Please describe: Adds Pro teaser for Attributes in the Advanced tab of all elements

## Description
An explanation of what is done in this PR

* Adds an Attributes section in the Advanced tab for all elements with a Pro teaser

## Test instructions
This PR can be tested by following these steps:

* Click on any and all elements (widget, column, section, page), go to the Advanced tab, and see if there is an Attributes controls section with a Pro teaser.

## Quality assurance

- [X] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

2019-12-18 13:01 UTC, matipojo requested changes

2019-12-18 13:01 UTC, matipojo commented on includes/managers/controls.php
> +	 * Add custom Attributes controls.
```suggestion
	 * Add custom attributes controls.
```

2019-12-18 13:01 UTC, matipojo commented on includes/managers/controls.php
> +	 * @since 1.0.0
Remove
```suggestion
	 * @since 2.8.3
```

2019-12-18 16:00 UTC, kobizz requested changes

2019-12-18 16:00 UTC, kobizz commented on includes/managers/controls.php
> +				'raw' => '<div class="elementor-nerd-box">' .
Make a general method that retrieves the template and use it for both custom-css and custom attributes

2019-12-19 10:03 UTC, kobizz requested changes

2019-12-19 10:03 UTC, kobizz commented on includes/managers/controls.php
> +	public function get_teaser_template( $texts ) {
Use buffering

2019-12-19 13:27 UTC, kobizz approved these changes

2019-12-19 13:38 UTC, merged