User Data: redesign "recalc" button and change label to "Recalculate"
elementor/elementor pull request #9922
Opened 2019-12-18 16:11 UTC by udidol

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe: Redesign of button in Elementor system reports

## Description
An explanation of what is done in this PR

* Redesign the "Recalculate" button in the system usage report table and relabel it "Recalculate" instead of "Recalc"

2019-12-18 16:16 UTC, matipojo submitted a review, later dismissed

2019-12-19 10:01 UTC, kobizz requested changes

2019-12-19 10:01 UTC, kobizz commented on assets/dev/scss/admin/_system_info.scss
> +		background-color: #a4afb7;
Use variable

2019-12-19 10:01 UTC, kobizz commented on assets/dev/scss/admin/_system_info.scss
> +	#elementor-usage-recalc {
Take it out of scope

2019-12-19 13:24 UTC, kobizz approved these changes

2019-12-19 13:36 UTC, merged