LightBox Update
elementor/elementor pull request #9978
Opened 2019-12-23 12:08 UTC by joshmarom

2019-12-25 11:49 UTC, kobizz requested changes

2019-12-25 11:49 UTC, kobizz commented on assets/dev/js/frontend/utils/lightbox/lightbox.js
> +					iconExpand: 'jicon-fullscreen',
Use `elementor-` class prefix wherever possible

2019-12-25 11:49 UTC, kobizz commented on assets/dev/js/frontend/utils/lightbox/lightbox.js
> +		var self = this,
Use internal arrow functions instead of using `self`.

2019-12-25 11:49 UTC, kobizz commented on assets/dev/js/frontend/utils/lightbox/lightbox.js
> +			$iconExpand = $( '<i>', { class: slideshowClasses.iconExpand } ).append( '<span>', '<span>' ),
Use either closing tag or `jQuery( '<span>' )`

2019-12-25 11:49 UTC, kobizz commented on assets/dev/js/frontend/utils/lightbox/lightbox.js
> +	getSlideshoHeader: function() {
```suggestion
	getSlideshowHeader: function() {
```

2019-12-25 11:49 UTC, kobizz commented on assets/dev/js/frontend/utils/lightbox/lightbox.js
> +			if ( screenfull.isFullscreen ) {
Move the method content into an external method. Same for the entire file

2019-12-25 11:49 UTC, kobizz commented on assets/dev/js/frontend/utils/lightbox/lightbox.js
> +			$shareLinks = $( '<ul><li>Share on Facebook</li><li>Share on Facebook</li></ul>' ),
Lopp through an object of data to build various share links

2019-12-25 11:49 UTC, kobizz commented on assets/dev/js/frontend/utils/lightbox/lightbox.js
> +		const classes = this.getSettings( 'classes' ),
What is it?

2019-12-25 11:49 UTC, kobizz commented on assets/dev/js/frontend/utils/lightbox/lightbox.js
> +		$container.on( 'mouseenter mouseover mousedown mousemove keyup keypress swipe tap vmousedown vmouseover vmousemove', function() {
1. 'mouseover' and 'mouseenter' are included in 'mousemove' event
2. 'keyup' is included in 'keypress' event
3. 'swipe', 'tap', 'vmousedown', 'vmouseover' and 'vmousemove' events are not exists

2019-12-25 11:49 UTC, kobizz commented on assets/dev/js/frontend/utils/lightbox/lightbox.js
> +			titleText = $activeSlide.find( '.elementor-lightbox-image' ).data( 'title' ),
Export the find result to a variable to avoid duplicate `find` call

2019-12-25 11:49 UTC, kobizz commented on assets/dev/js/frontend/utils/lightbox/lightbox.js
> +		$description.empty().text( descriptionText );
Remove the `empty` call

2019-12-25 11:49 UTC, kobizz commented on assets/dev/js/frontend/utils/lightbox/lightbox.js
> +				description: jQuery( this ).data( 'elementor-lightbox-description' ),
Export `jQuery( this )` into a variable

2019-12-25 11:49 UTC, kobizz commented on assets/dev/scss/frontend/_global.scss
> +}
?

2019-12-31 16:32 UTC, kobizz requested changes

2019-12-31 16:32 UTC, kobizz commented on assets/dev/js/frontend/utils/lightbox/lightbox.js
> +			elements.$iconExpand.on( 'click', this.toggleFullscreen );
Does it work?

2019-12-31 16:32 UTC, kobizz commented on assets/dev/js/frontend/utils/lightbox/lightbox.js
> +		}
It's better to use if-else in this case

2019-12-31 16:32 UTC, kobizz commented on assets/dev/js/frontend/utils/lightbox/lightbox.js
> +		swiper.zoom.enable();
Do you need to enable zoom in every activation?

2019-12-31 16:32 UTC, kobizz commented on assets/dev/js/frontend/utils/lightbox/lightbox.js
> +		if ( ! $container.hasClass( classes.slideshow.shareMode ) ) {
It would be better to split it into two different methods

2019-12-31 16:32 UTC, kobizz commented on assets/dev/js/frontend/utils/lightbox/lightbox.js
> -
Revert this

2019-12-31 16:32 UTC, kobizz commented on assets/dev/js/frontend/utils/lightbox/lightbox.js
>  	},
Revert this

2019-12-31 16:57 UTC, joshmarom commented on assets/dev/js/frontend/utils/lightbox/lightbox.js
> +			elements.$iconExpand.on( 'click', this.toggleFullscreen );
Why not?

2020-01-13 12:52 UTC, kobizz requested changes

2020-01-13 12:52 UTC, kobizz commented on assets/dev/js/frontend/utils/lightbox/lightbox.js
> +			facebook: 'Share on facebook',
Add translations

2020-01-13 12:52 UTC, kobizz commented on assets/dev/js/frontend/utils/lightbox/lightbox.js
> +			if ( socialNetworks.hasOwnProperty( network ) ) {
Instead of that, use `jQuery.each`

2020-01-13 12:52 UTC, kobizz commented on assets/dev/js/frontend/utils/lightbox/lightbox.js
> +		} else if ( videoUrl ) {
Omit `if ( videoUrl )` or alternatively handle the case it doesn't exist

2020-01-13 12:52 UTC, kobizz commented on assets/dev/js/frontend/utils/lightbox/lightbox.js
> +			$linkList.append( $( '<a>', { href: itemUrl, download: '' } ).text( 'Download Image' ).prepend( $( '<i>', { class: 'eicon-file-download' } ) ) );
Translation

2020-01-13 12:52 UTC, kobizz commented on assets/dev/js/frontend/utils/lightbox/lightbox.js
> +			$linkList.append( $( '<a>', { href: hash, download: '' } ).text( 'Hash' ).prepend( $( '<i>', { class: 'eicon-file-download' } ) ) );
?

2020-01-13 12:52 UTC, kobizz commented on assets/dev/js/frontend/utils/lightbox/lightbox.js
> +				$slideImage[ 0 ].ondragstart = () => {
$slideImage.on( 'dragstart', () => false )

2020-01-13 12:52 UTC, kobizz commented on assets/dev/scss/global/_dialog.scss
> +			position: sticky;
It's not supported in ie

2020-01-13 13:03 UTC, joshmarom commented on assets/dev/scss/global/_dialog.scss
> +			position: sticky;
So are custom properties...

2020-01-14 07:56 UTC, closed without merging

2020-01-14 09:05 UTC, kobizz commented on core/settings/general/model.php
> +								'description' => __( 'Description', 'elementor-pro' ),
Fix text domain

2020-01-14 09:05 UTC, kobizz commented on core/settings/general/model.php
> +								'description' => __( 'Description', 'elementor-pro' ),
Fix text domain