Feature/history per document
elementor/elementor pull request #9979
Opened 2019-12-23 12:54 UTC by iNewLegend

2019-12-31 13:32 UTC, matipojo requested changes

2019-12-31 13:52 UTC, matipojo requested changes

2019-12-31 13:52 UTC, matipojo commented on assets/dev/js/modules/modules.js
> +export default window.elementorModules = elementorModules;
Why?

2019-12-31 13:52 UTC, matipojo commented on modules/history/assets/js/panel-page.js
> +	documentId: null,
It's used?

2019-12-31 13:52 UTC, matipojo commented on modules/history/assets/js/revisions/panel-tab.js
> +				self.document.revisions.setEditorData( data.elements );
remove all `self` from file

2019-12-31 13:52 UTC, matipojo commented on modules/history/assets/js/revisions/panel-tab.js
> +		$e.run( 'document/save/set-is-modified', { status: this.isRevisionApplied } );
Revert

2019-12-31 13:52 UTC, matipojo commented on modules/history/assets/js/revisions/panel-tab.js
> +		$e.run( 'document/save/set-is-modified', { status: true } );
Revert

2019-12-31 13:52 UTC, matipojo commented on modules/history/assets/js/revisions/panel-tab.js
> +			$e.run( 'document/save/save', {
Revert

2019-12-31 13:52 UTC, matipojo commented on tests/qunit/core/editor/document/elements/commands/delete.spec.js
> +				$e.run( 'document/save/set-is-modified', { status: false } );
Revert

2019-12-31 13:52 UTC, matipojo commented on tests/qunit/core/editor/document/elements/commands/empty.spec.js
> +			$e.run( 'document/save/set-is-modified', { status: false } );
Revert

2019-12-31 13:52 UTC, matipojo commented on tests/qunit/core/editor/document/elements/commands/paste-style.spec.js
> +				$e.run( 'document/save/set-is-modified', { status: false } );
Revert

2019-12-31 13:52 UTC, matipojo commented on tests/qunit/core/editor/document/elements/commands/paste.spec.js
> +				$e.run( 'document/save/set-is-modified', { status: false } );
Revert

2019-12-31 13:52 UTC, matipojo commented on tests/qunit/core/editor/document/elements/commands/reset-style.spec.js
> +				$e.run( 'document/save/set-is-modified', { status: false } );
Revert

2019-12-31 13:52 UTC, matipojo commented on tests/qunit/core/editor/document/history/component.spec.js
> +			$e.run( 'document/save/set-is-modified', { status: false } );
Revert

2019-12-31 13:52 UTC, matipojo commented on tests/qunit/core/editor/document/manager.js
> +import ElementsHelper from './helper';
Rename `spec.js`

2020-01-02 14:11 UTC, iNewLegend commented on assets/dev/js/editor/components/settings/page/manager.js
> +				force: true,
Old page/manager:
```javascript
		template: function() {
			elementor.saver.saveAutoSave( {
				onSuccess: function() {
					elementor.reloadPreview();

					elementor.once( 'preview:loaded', function() {
						$e.route( 'panel/page-settings/settings' );
					} );
				},
			} );
		},
```
Old saver/manager:
```javascript
	doAutoSave: function() {
		var editorMode = elementor.channels.dataEditMode.request( 'activeMode' );

		// Avoid auto save for Revisions Preview changes.
		if ( 'edit' !== editorMode ) {
			return;
		}

		this.saveAutoSave();
	},

	saveAutoSave: function( options ) {
		if ( ! this.isEditorChanged() ) {
			return;
		}

		options = _.extend( {
			status: 'autosave',
		}, options );

		this.saveEditor( options );
	},
```

new auto save command:
```javascript
import Base from './base/base';

export class Auto extends Base {
	apply( args ) {
		const { force = false, options = {} } = args;

		if ( ! force && 'edit' !== elementor.channels.dataEditMode.request( 'activeMode' ) ) {
			return;
		}

		this.save( options );
	}

	save( options ) {
		if ( this.component.isEditorChanged() ) {
			// TODO: Move to es6.
			options = _.extend( {
				status: 'autosave',
			}, options );

			$e.run( 'document/save/save', options );
		}
	}
}

export default Auto;
```

2020-01-02 14:17 UTC, iNewLegend commented on assets/dev/js/editor/editor-base.js
> -/* global ElementorConfig */
ES6 editor base merged.

2020-01-02 14:17 UTC, iNewLegend commented on assets/dev/js/editor/editor-base.js
> +import Environment from 'elementor-common/utils/environment';
ES6 editor base merged.

2020-01-02 14:45 UTC, iNewLegend commented on assets/dev/js/modules/modules.js
> +export default window.elementorModules = elementorModules;
Reverted.

2020-01-05 12:39 UTC, matipojo submitted a review, later dismissed

2020-01-06 14:28 UTC, kobizz requested changes

2020-01-06 14:28 UTC, kobizz commented on assets/dev/js/editor/document/save/commands/discard.js
> +			success: function() {
Use arrow function

2020-01-06 14:28 UTC, kobizz commented on assets/dev/js/editor/document/save/commands/pending.js
> +		// TODO: Move to es6.
Do it

2020-01-06 14:28 UTC, kobizz commented on assets/dev/js/editor/document/save/commands/publish.js
> +		// TODO: Move to es6.
Do it

2020-01-06 14:28 UTC, kobizz commented on assets/dev/js/editor/document/save/commands/update.js
> +		// TODO: Move to es6.
Do it

2020-01-06 14:28 UTC, kobizz commented on assets/dev/js/editor/document/save/component.js
> +		// TODO: Move to es6.
Do it

2020-01-08 09:34 UTC, kobizz approved these changes

2020-01-09 12:22 UTC, merged